### ISSUE TITLE
How to start a script with parameters?

### ISSUE THREAD

**Issue by gzoller** [just-containers/s6-overlay#102]
I have a base Docker containing a small program (portster) I want to run on start-up.  I'm using S6 overlay for this and have create a script: /etc/services.d/portster/run (and finish).

So this works well by itself.  I can derive trivial Dockers from this base image and so long as I don't define an ENDPOINT or CMD my portster program launches neatly without any assistance.

Now I want to use this base image to derive a new Docker holding a Java application.  When run this application needs to accept parameters from the "docker run" command line (to be consumed as args in my Java code).  I have a shell script that will launch my Java code (sets variables, classpath, etc.)

How can I configure S6 overlay to launch my Java app, accepting parameters, and still retain the core behavior of auto-launching/managing portster I initially needed (without the new Java  Docker having to know about or manage portster)?

**Comment by sameersbn** [comment]
@gzoller I had a similar requirement, I ended up creating an wrapper for the `/init` script with the following content

```bash
#!/bin/bash
if [ "${1:0:1}" = '-' ]; then
  export EXTRA_OPTIONS="$@"
  set --
fi
exec /init "$@"
```

The script exports a variable named `EXTRA_OPTIONS` with all user specified command line options, removes all the args from the command line and launches the `/init` script of `s6-overlay`

Now in your services `run` script you can use the `EXTRA_OPTIONS` variable. eg.

```bash
#!/usr/bin/with-contenv bash
set -e

exec /usr/bin/mydaemon  ${EXTRA_OPTIONS:+"$EXTRA_OPTIONS"}
```

P.S. I am not aware if s6-overlay has any built-in option for this.

**Comment by gzoller** [comment]
I may have discovered something...  If you pass other commands to /init on the command line they *seem* to go right through to execution.  So as long as my derived Dockers always set an ENDPOINT [/init, whatever] then it may work.  (At least it worked in the application I tried.)  I'll have a look at the wrapper script idea too, just in case I'm misusing /init in this way.

I don't mind much if derived dockers have to follow a convention of running /init, because that's pretty generic.  I just don't want them having to know about or start a bunch of specific services.

**Comment by sameersbn** [comment]
@gzoller that is true. any command specified to `/init` will get executed in addition to the services you may have configured. This is mostly useful for debugging, for example you can launch `bash` and debug stuff. Another neat feature of s6 is that it will reap zombie processes created by commands launched in this manner.

Note that when the command exits, the container exits as well.

**Comment by jprjr** [comment]
@gzoller yep - that's one of the features of the `s6-overlay`, it helps for those some reasons @sameersbn mentioned. The overall idea is, even with the `s6-overlay` setup (so downloaded and `ENTRYPOINT` configured), your images should still generally behave the same as the default images, up until you start adding services.

@gzoller I'd also recommend just using an environment variable to store your arguments and referencing it in your `run` script. So the user would run something like:

`docker run -e MY_DAEMON_ARGS="-f /some/file -p -i ..." myimage`

Then in your run script:

```
#!/usr/bin/with-contenv sh

exec /usr/bin/my-daemon $MY_DAEMON_ARGS
```

@sameersbn's wrapper script is a pretty good idea, though!

**Comment by glerchundi** [comment]
@gzoller I'm with @jprjr, use environment variables to customize your daemon behaviour, IMO, it's the most configurable way of handling parameters. I usually do and it work pretty well for all kind of situations.

**Comment by glerchundi** [comment]
@gzoller can we close this?

**Comment by gzoller** [comment]
Yes please.  Responses were very helpful :-)
