### ISSUE TITLE
s6-overlay modified for alpine linux

### ISSUE THREAD

**Issue by giminni** [just-containers/s6-overlay#108]
Hey John, 

first of all thx to all contributors for this great package.

I am using alpine linux for a minimalistic approach, and
I saw you are a contributor for alpine linux either.

I got s6-overlay working as a trimmed down package for alpine linux
using their s6 package provided by Laurent Bercot.
```
apk -U add --allow-untrusted --repository ${ALPINE_EDGE_REPO}  s6 execline s6-portable-utils 
```

- there is a misalignment between /usr/bin/execlineb and /bin/execlineb
- some execline scripts has absolute path I changed it removing the prefix for several ones.
- also bang paths must be aligned to /bin/execlineb
- I built a new overlay package using the files below without the embedded s6

Question can you build a s6-overlay for alpine linux repository "s6-overlay" with dependencies listed above?

```
root # tree s6-overlay-amd64-v1.16.0.1-mod.tar.gz
.
|-- etc
|   |-- cont-finish.d
|   |-- cont-init.d
|   |-- fix-attrs.d
|   |-- s6
|   |   |-- init
|   |   |   |-- env
|   |   |   |   `-- PATH
|   |   |   |-- env-stage2
|   |   |   |-- init-stage1
|   |   |   |-- init-stage2
|   |   |   |-- init-stage2-fixattrs.txt
|   |   |   |-- init-stage2-redirfd
|   |   |   `-- init-stage3
|   |   |-- init-catchall
|   |   |   |-- init-stage1
|   |   |   `-- init-stage2
|   |   |-- init-no-catchall
|   |   |   |-- init-stage1
|   |   |   `-- init-stage2
|   |   `-- services
|   |       |-- s6-fdholderd
|   |       |   |-- down
|   |       |   |-- notification-fd
|   |       |   |-- rules
|   |       |   |   `-- uid
|   |       |   |       |-- 0
|   |       |   |       |   |-- allow
|   |       |   |       |   `-- env
|   |       |   |       |       |-- S6_FDHOLDER_GETDUMP
|   |       |   |       |       |-- S6_FDHOLDER_LIST
|   |       |   |       |       |-- S6_FDHOLDER_RETRIEVE_REGEX
|   |       |   |       |       |-- S6_FDHOLDER_SETDUMP
|   |       |   |       |       `-- S6_FDHOLDER_STORE_REGEX
|   |       |   |       `-- default
|   |       |   |           |-- allow
|   |       |   |           `-- env
|   |       |   |               `-- S6_FDHOLDER_LIST
|   |       |   |-- run
|   |       |   `-- supervise
|   |       |-- .s6-svscan
|   |       |   |-- crash
|   |       |   `-- finish
|   |       `-- s6-svscan-log
|   |           `-- run
|   `-- services.d
|-- init
`-- usr
    `-- bin
        |-- fix-attrs
        |-- logutil-newfifo
        |-- logutil-service
        |-- logutil-service-main
        |-- printcontenv
        |-- with-contenv
        `-- with-retries

24 directories, 32 files
```

**Comment by giminni** [comment]
After testing a while I encountered another glitch:

- I use s6-applyuidgid from s6 edge repo not the one shipped with s6-overlay

after starting a docker box with s6-log I got s6-applyuidgid: GID not set.

Looking inside the config directory for logging I found the problem in /usr/bin/logutil-service-main
apparently s6-applyuidgid -U ... cannot be executed properly.
My hack was to remove -U and insert -u 65534 -g 65534 (alpine's nobody user). Feel free to generalize this for the world.

**Comment by smebberson** [comment]
@giminni, checkout this GitHub repository which has a whole suite of images dedicated to Alpine Linux and, s6-overlay https://github.com/smebberson/docker-alpine

In particular check out https://github.com/smebberson/docker-alpine/blob/master/alpine-base/Dockerfile, which demonstrates how we mix Alpine Linux with s6-overlay.

**Comment by giminni** [comment]
@smebberson, thx for pointing me to your bundle of alpine containers. 

My point was another, there are s6, execline and other packages inside the s6 alpine package repository from Laurent, John & Christian. 

I thought why not to use only the delta from s6-overlay and get the base images from repository?

The result is a smaller Dockerfile without ADD, curl and so on, only
apk -U add --allow-untrusted --repository ${ALPINE_EDGE_REPO} s6 execline s6-portable-utils

and maybe s6-overlay

```
execline-dev 	2.1.4.5-r0 			Laurent Bercot
execline 	2.1.4.5-r0	 			Laurent Bercot
execline-doc 	2.1.4.5-r0 			Laurent Bercot
s6-rc-doc 	0.0.2.0-r0 				Laurent Bercot
s6-rc 	0.0.2.0-r0 					Laurent Bercot
s6-rc-dev 	0.0.2.0-r0				Laurent Bercot
s6 	2.2.4.0-r0 						Laurent Bercot
s6-dev 	2.2.4.0-r0 					Laurent Bercot
s6-doc 	2.2.4.0-r0 					Laurent Bercot
s6-networking 	2.1.0.4-r0 			John Regan
s6-networking-dev 	2.1.0.4-r0 		John Regan
s6-dns-dev 	2.0.0.7-r0 	URL 		John Regan
s6-dns 	2.0.0.7-r0 					John Regan
s6-linux-utils-dev 	2.0.2.3-r0 		Christian Kampka
s6-linux-utils 	2.0.2.3-r0 			Christian Kampka
s6-portable-utils 	2.0.5.3-r0 		John Regan
s6-portable-utils-dev 	2.0.5.3-r0 	John Regan
```

**Comment by jprjr** [comment]
That's actually a pretty good idea. I know a couple other distros have s6 available, we could produce some variant of the s6-overlay that strictly contains the scripts - I imagine it'd be useful for people using distros with a packaged s6.

I'll see about adding some kind of 'scripts-only' tarball to releases.

**Comment by jprjr** [comment]
Hi @giminni - I put out a [new release](https://github.com/just-containers/s6-overlay/releases/tag/v1.16.0.2) that has a "nobin" variant of the tarball, that doesn't have any of the pre-compiled s6 packages. This should be useful for people making docker images with s6 packages in the repos. If this works, go ahead and close the issue!

**Comment by giminni** [comment]
Hey John,

thx for your prompt action.

I reviewed your 'nobin' tarball, and discovered a path misalignment between Laurent's s6 images on alpine linux repo (s6 & execline) and yours.

Please read my 1st and 2nd note regarding the difference.

**Comment by glerchundi** [comment]
@giminni  can you check last `nobin` release? Concretely `v1.17.0.0`.

**Comment by skarnet** [comment]
Yes, I moved all the binaries to `/bin` in the latest Alpine packaging. The plan was to provide s6+s6-rc as an alternative to OpenRC in Alpine 3.4, so the binaries needed to be in the root filesystem. (I'm working for a paying customer atm, so the rest of the plan has been delayed, but the move is still a good move.)

If you can wait until Alpine 3.3 is officially released (it should happen any day now), then you'll be able to use it as a baseline and settle on `/bin`.

**Comment by giminni** [comment]
well, I tested the newest v17.0.0 nobin tarball and there are some inconsistencies:

right now we have in the alpine packages repo the s6-portable-utils package (2.0.5.3-r0) from John
pointing to /usr/bin/s6-....
the latest package has artefacts pointing to /bin/s6-... (see below)

IMHO a new s6-portable-utils package must be created, and
BTW to guarantee proper redirection symlinks must be added

```
root # grep -r "/bin/s6" *
etc/s6/init/init-stage1:/bin/if { /bin/s6-mkdir -pm 0755 -- /var/run/s6/container_environment }
etc/s6/init/init-stage1:/bin/if { /bin/s6-dumpenv -- /var/run/s6/container_environment }       
etc/s6/init/init-stage1:  /bin/s6-rmrf ${envdir}                                               
etc/s6/init/init-stage1:/bin/if { /bin/s6-hiercopy /etc/s6/init/env /var/run/s6/env-stage1 }   
etc/s6/init/init-stage1:/bin/if { /bin/s6-mkdir -pm 0755 -- /var/run/s6/env-stage2 }           
etc/s6/init/init-stage1:/bin/if { /bin/s6-mkdir -pm 0755 -- /var/run/s6/env-stage3 }           
etc/s6/init/init-stage1:/bin/s6-envdir /var/run/s6/env-stage1                                  
usr/bin/with-contenv:/bin/s6-envdir -fn -- /var/run/s6/container_environment             
```

**Comment by skarnet** [comment]
Um, the s6-portable-utils package should not point to anything in s6. It doesn't depend on it.

I didn't make a new s6-portable-utils package because it does not matter if s6-portable-utils binaries are in `/usr/bin`. Alpine doesn't, and won't, use s6-portable-utils binaries in boot scripts.

Ultimately *it should not matter* where binaries are. That's what PATH is for! Instead of hardcoding absolute paths (that may change, because FHS is fickle) and having symlinks, the overlay should just set PATH to include `/usr/bin:/bin` and use PATH resolution for every executed program. It's much simpler and resilient to changes.

**Comment by glerchundi** [comment]
@skarnet yep, done. @giminni try if this finally works or not: v1.17.0.1.

**Comment by giminni** [comment]
I tested the new tarball and I don't know if I have another issue, fact is
I get ...

```
[cont-init.d] executing container initialization scripts...                    
[cont-init.d] 00-cont_init: executing...                                       
/var/run/s6/etc/cont-init.d/00-cont_init: exec: line 4: s6-setuidgid: not found
[cont-init.d] 00-cont_init: exited 2.                                          
                                                                               
!!!!!                                                                          
 init-stage2 failed.                                                           
!!!!!                                                                          
```
This issue comes from my call in 00-cont_init

```
exec s6-setuidgid daemon /usr/local/bin/cont_init.sh
```

**Comment by glerchundi** [comment]
What does this command output? `docker run --entrypoint=/bin/sh yourimage which s6-setuidgid`

**Comment by giminni** [comment]
```
/bin/sh: can't open 'which'
```

**Comment by glerchundi** [comment]
`docker run --entrypoint="/bin/sh" yourimage -c "/usr/bin/which s6-setuidgid"`

**Comment by giminni** [comment]
/sbin/s6-setuidgid

**Comment by glerchundi** [comment]
@skarnet do you know why `s6` didn't include `s6-setuidgid` in the alpine package? https://pkgs.alpinelinux.org/contents?pkgname=s6&arch=x86_64&repo=main

It seems like some binaries are missing, concretely these: `/libexec/s6lockd-helper`, `/sbin/{s6-applyuidgid,s6-setuidgid}`

@giminni wait for those binaries to be available in the alpine packages or whatever workaround they propose and then tell us something again.

**Comment by giminni** [comment]
Not shure if something is missing...

https://pkgs.alpinelinux.org/contents?filename=s6-%25uid%25&path=&pkgname=&repo=all&arch=x86_64

**Comment by glerchundi** [comment]
@skarnet, forgot it. It seems like alpine package content listing doesn't support paging. Sorry about that. So the problem should be with your PATH @giminni...

**Comment by skarnet** [comment]
I guess `/sbin` should be added to the default PATH in init-stage1.

**Comment by giminni** [comment]
@skarnet: +1

It works now!
I made an own temporary s6-overlay version.

BTW this is my report:

*1) "s6-applyuidgid not found"
/usr/sbin and /sbin to PATH in init-stage1
```
#!/bin/execlineb -S0                                                           
                                                                               
##                                                                             
## we add /usr/bin:/bin to PATH at least for the very first init-stage1 steps, 
## this was motivated due to this issue:                                       
## - https://github.com/just-containers/s6-overlay/issues/108                  
## although this change we'll keep how stages envs are handled, see below.     
##                                                                             
                                                                               
/bin/export PATH /usr/sbin:/usr/bin:/sbin:/bin                                           
/bin/import PATH                                                               
...                                               
```

than I got another error:

*2)s6-applyuidgid: fatal: GID not set
this happens at /usr/bin/logutil-service-main
I guess alpine nobody user is not recognized I resolved it with a quick hack, 
please adapt to the world release
```
...                                                                                     
# execute s6-log and drop root rights in favor of nobody                             
s6-envuidgid -D 32768:32768 nobody                                                   
#s6-applyuidgid -U              
s6-applyuidgid -u 65534 -g 65534
...
```

at least I discovered an unrelated file, please expand .gitignore

*3) /etc/leapsecs.dat

@glerchundi : please build a new one and let me test it again. Thx.

**Comment by glerchundi** [comment]
@skarnet unless i'm missing something `/sbin` is loaded in [`here`](https://github.com/just-containers/s6-overlay/blob/master/builder/overlay-rootfs/etc/s6/init/init-stage1#L46-L48). Before going to stage2. Now I have a doubt with this, if s6-envdir is used to load an env which is already available in the current execution context, how does it behave? Does it replace the current one?

**Comment by glerchundi** [comment]
> *1) "s6-applyuidgid not found"
> /usr/sbin and /sbin to PATH in init-stage1

These are the binaries used before proceeding to clean the current environments and loading the new ones from the stage1's env folder:

`/usr/bin/s6-mkdir`: https://pkgs.alpinelinux.org/contents?filename=%25s6-mkdir%25&path=&pkgname=all&repo=main&arch=x86_64
`/usr/bin/s6-dumpenv`: https://pkgs.alpinelinux.org/contents?filename=%25s6-dumpenv%25&path=&pkgname=all&repo=main&arch=x86_64
`/bin/{elglob,forx,importas}`
`/usr/bin/s6-rmrf`: https://pkgs.alpinelinux.org/contents?filename=%25s6-rmrf%25&path=&pkgname=all&repo=main&arch=x86_64
`/usr/bin/s6-hiercopy`: https://pkgs.alpinelinux.org/contents?filename=%25s6-hiercopy%25&path=&pkgname=all&repo=main&arch=x86_64
`/usr/bin/s6-mkdir`: https://pkgs.alpinelinux.org/contents?filename=%25s6-mkdir%25&path=&pkgname=all&repo=main&arch=x86_64

> *2)s6-applyuidgid: fatal: GID not set
> this happens at /usr/bin/logutil-service-main
> I guess alpine nobody user is not recognized I resolved it with a quick hack, 
> please adapt to the world release

https://github.com/just-containers/s6-overlay/issues/97#issuecomment-161263789

> *3) /etc/leapsecs.dat

This is also needed if someone want TAI precise timing.

I would like to understand what is going on before doing anything else.

**Comment by giminni** [comment]
I had to add also /usr/sbin to PATH for recognizing all the daemons in /usr/sbin too

**Comment by glerchundi** [comment]
I missed one thing with this all, I was dumping every env (including PATH) after overriding it, that was causing the last issue you mentioned.

In order to keep backward compatibility I preserve the current PATH if it exist, create if it doesn't. With the same values as Docker uses when it runs a container without providing it.

v1.17.0.2 is on the road, PTAL and close this whenever you can.

**Comment by giminni** [comment]
Throwing error: s6-applyuidgid: fatal: GID not set
(See my item #2 above

**Comment by glerchundi** [comment]
this is because latest release's `s6-envuidgid` binary doesn't properly set GID if `-D` is used, see https://github.com/just-containers/s6-overlay/issues/97#issuecomment-161263789

**Comment by giminni** [comment]
... I understand

**Comment by skarnet** [comment]
Ah yes, sorry - I've been busy with other things. I'll get to it ASAP.

**Comment by glerchundi** [comment]
@giminni #121 should solve your issues. Take and go ahead with `v1.17.1.0` and tell us if it works for you.

**Comment by glerchundi** [comment]
Just to let you know that previous release has a bug, use `v1.17.1.1` instead.

**Comment by glerchundi** [comment]
@giminni, reopen if you feel this wasn't completely solved.
