### ISSUE TITLE
S6_LOGGING=1

### ISSUE THREAD

**Issue by hurricanehrndz** [just-containers/s6-overlay#115]
Whenever  S6_LOGGING is set to 1 in my container, I get the following error:
```s6-chown: fatal: GID not set```

**Comment by glerchundi** [comment]
Which version? Probably this is happening just in the latest release due to this [`issue`](https://github.com/just-containers/s6-overlay/issues/97#issuecomment-161263789). Try another version and tell us if it fixes or not.

**Comment by hurricanehrndz** [comment]
Thank you, I will test and report when I get a chance.

**Comment by glerchundi** [comment]
@hurricanehrndz please check latest release, should solve this.

**Comment by hurricanehrndz** [comment]
Yes it does.
