### ISSUE TITLE
RFI: fix-attrs files with user defined variables?

### ISSUE THREAD

**Issue by giminni** [just-containers/s6-overlay#119]
Is it feasible to pass user defined variables to the fix-attr files?

Does it makes sense?

```
/etc/fix-attrs.d/02-mysql-log-dirs:
```
```
#!/usr/bin/with-contenv sh

${OBJ1} ${FLAG1} ${BE_USER1},${UID1}:${GID1} ${PERM_FILE1} ${PERM_DIR1}
${OBJ2} ${FLAG2} ${BE_USER2},${UID2}:${GID2} ${PERM_FILE2} ${PERM_DIR2}
${OBJ3} ${FLAG3} ${BE_USER3},${UID3}:${GID3} ${PERM_FILE3} ${PERM_DIR3}
...
```

**Comment by glerchundi** [comment]
The idea with `fix-attrs` was to fix perms with previously known volumes. I don't think this is worth it. Although you can achieve that behaviour easily using a `cont-init` script:

`/etc/cont-init.d/02-mysql-log-dirs`:
```
#!/usr/bin/with-contenv sh

file=$(mktemp)
echo ${OBJ1} ${FLAG1} ${BE_USER1},${UID1}:${GID1} ${PERM_FILE1} ${PERM_DIR1} >> ${file}
echo ${OBJ2} ${FLAG2} ${BE_USER2},${UID2}:${GID2} ${PERM_FILE2} ${PERM_DIR2} >> ${file}
echo ${OBJ3} ${FLAG3} ${BE_USER3},${UID3}:${GID3} ${PERM_FILE3} ${PERM_DIR3} >> ${file}
cat ${file} | fix-attrs
```

**Comment by joeblackwaslike** [comment]
I don't personally do this, but this is a great way to do it using a heredoc for readability. this would generate an actual file each time, which could be what you're looking for or not. 

cheers

```bash
# /etc/cont-init.d/02-mysql-log-dirs
cat <<-EOF > /etc/fix-attrs.d/02-mysql-log-dirs
	${OBJ1} ${FLAG1} ${BE_USER1},${UID1}:${GID1} ${PERM_FILE1} ${PERM_DIR1}
	${OBJ2} ${FLAG2} ${BE_USER2},${UID2}:${GID2} ${PERM_FILE2} ${PERM_DIR2}
	${OBJ3} ${FLAG3} ${BE_USER3},${UID3}:${GID3} ${PERM_FILE3} ${PERM_DIR3}
EOF
```

**Comment by glerchundi** [comment]
@joeblackwaslike that is not gonna work. `fix-attrs.d` is executed before `cont-init.d` scripts.

**Comment by glerchundi** [comment]
Closing this as it requires a lot of messy stuff to be implemented in the init which IMHO is not worth it. Moreover, there exist a workaround.
