### ISSUE TITLE
Run some code after a service has started

### ISSUE THREAD

**Issue by smebberson** [just-containers/s6-overlay#120]
I need some advice. Using all the goodness in s6-overlay, how would one elegantly run some code after a service has started?

I'm setting up an InfluxDB container. After the InfluxDB service has started, if some environment variables are present, I want to create a user using the InfluxDB HTTP service.

Where should I put this code, and how should I make it run?

This is how I have it structured at present: https://github.com/smebberson/docker-alpine/blob/alpine-influxdb/alpine-influxdb/root/etc/services.d/influxdb/run. I'm not sure starting the `create-user` script in the background, before I start the InfluxDB service is the way to go.

The code within the `create-user` script itself could be better. Checking for a HTTP 204 status is the recommending way to determine if InfluxDB is ready for HTTP requests, https://github.com/influxdb/influxdb/issues/4595.

Thanks in advance for any advice.

**Comment by glerchundi** [comment]
@smebberson there is no a oneshot concept in our overlay, at least for now. Probably, the best way to achieve this would be to use `s6-rc` and incorporate it in a major release.

But anyway, you can get it working in a different ways:
* Create a `cont-init.d` script using `background {}` as mentioned here: https://github.com/just-containers/s6-overlay/issues/86.
* Create a `services.d` service like it was an oneshot service to do your initialization tasks and then unregister it from `s6` or do a noop operation like `tail -f /dev/null` or `s6-pause -th`.

Always using `svwait` to wait until your concrete service is up and then `with-retries` with `curl` or whatever to achieve the readiness.

**Comment by smebberson** [comment]
@glerchundi, thanks for your advice. There are a few good options to tidy up the code.

**Comment by dev-mraj** [comment]
How to unregister it from s6 so the script can't rerestart after exit. and don't restart unless container restarted.
