### ISSUE TITLE
errors in centos 7

### ISSUE THREAD

**Issue by pubyun** [just-containers/s6-overlay#124]
1. overwite /bin symlink and all old files in /bin are missing, and we shall add "h" option to tar

RUN tar hxzf /tmp/s6-overlay-amd64.tar.gz -C / \
    && rm /tmp/s6-overlay-amd64.tar.gz

2. too many levels of symbolic links: /init

lrwxrwxrwx   1 root  root     7 Dec 17 22:39 bin -> usr/bin

/usr/bin/execlineb symlink to itself, so symlink loop now.

**Comment by glerchundi** [comment]
Can you explain a little bit more your use case and give some examples?

**Comment by glerchundi** [comment]
@pubyun #125 is this the same issue?

**Comment by ploef** [comment]
These issues seem related. The error message of issue #125 is gone...this one occurs.

**Comment by pubyun** [comment]
@glerchundi same issue

**Comment by glerchundi** [comment]
@ploef I consider this as solved because if `-h` is not used and if we re-create `/bin` references with `s6-update-symlinks` all works as expected.

**Comment by pubyun** [comment]
s6-update-symlinks only solved first issue.

/usr/bin/execlineb symlink to /bin/execlineb, and /bin/execlineb symlink to /usr/bin/execlineb.

#sudo docker run -ti  c7 /bin/bash                                                                
too many levels of symbolic links
Error response from daemon: Cannot start container 287493655ac059f29a7ef19ca326f05020c51beb37374b58fd8fdc090b4d8caf: [8] System error: too many levels of symbolic links
