### ISSUE TITLE
System error: exec: "/bin/sh": stat /bin/sh: no such file or directory

### ISSUE THREAD

**Issue by ploef** [just-containers/s6-overlay#125]
Hi,

If I use the latest versions (after 1.14.x) an error occures:

System error: exec: "/bin/sh": stat /bin/sh: no such file or directory

*Everything seems to work fine with the older version.*

Best regards,
Peter

**Comment by glerchundi** [comment]
Can you explain a little bit more your use case and give some examples?

**Comment by ploef** [comment]
Hi,

Thanks for the quick response!

As an example you could use this simple Dockerfile:

FROM centos:centos7
ADD https://github.com/just-containers/s6-overlay/releases/download/v1.17.1.1/s6-overlay-amd64.tar.gz /tmp/
RUN tar xzf /tmp/s6-overlay-amd64.tar.gz -C /
RUN apt-get update 

If you build this file I get following output:


Step 0 : FROM centos:centos7
 ---> ce20c473cd8a
Step 1 : ADD https://github.com/just-containers/s6-overlay/releases/download/v1.17.1.1/s6-overlay-amd64.tar.gz /tmp/
Downloading [==================================================>] 1.438 MB/1.438 MB
 ---> 319a895ce016
Removing intermediate container eee8c9887111
Step 2 : RUN tar xzf /tmp/s6-overlay-amd64.tar.gz -C /
 ---> Running in 06b4257d6a07
 ---> 9b50df7da82f
Removing intermediate container 06b4257d6a07
Step 3 : RUN apt-get update
 ---> Running in af74c15be142
[8] System error: exec: "/bin/sh": stat /bin/sh: no such file or directory

**Comment by glerchundi** [comment]
@ploef centos with apt-get? That would be awesome :P

**Comment by ploef** [comment]
Hmmmm, in an attempt to make the example as simple as possible I combined your example with my code. :-)

This is better...same error:

FROM centos:centos7
ADD https://github.com/just-containers/s6-overlay/releases/download/v1.17.1.1/s6-overlay-amd64.tar.gz /tmp/
RUN tar xzf /tmp/s6-overlay-amd64.tar.gz -C /
RUN yum clean all && yum -y update

**Comment by glerchundi** [comment]
Add an extra option to decompress, `tar hxzf /tmp/s6-overlay-amd64.tar.gz -C /` and tell me if it works

**Comment by glerchundi** [comment]
The problem is that centos symlinks /bin to /usr/bin. To bypass this problem you can do this:

```
FROM centos:centos7
ADD https://github.com/just-containers/s6-overlay/releases/download/v1.17.1.1/s6-overlay-amd64.tar.gz /tmp/
RUN tar xzf /tmp/s6-overlay-amd64.tar.gz -C / && \
    mv /bin /bin-s6 && \
    /bin-s6/s6-update-symlinks /bin /bin-s6 /usr/bin 
RUN yum clean all && yum -y update
```

Use it until we found a better approach.

**Comment by ploef** [comment]
Hi,
Could you please reopen this issue?
Unfortunately this does not work. If you create an image like that, I get this error:

*Cannot start container 704e111faea9b0316b20dcaef3c42d485024e37445b8660caf800d9d2ffd9076: [8] System error: too many levels of symbolic links*

This is the Dockerfile:

FROM centos:centos7
# Add the s6 overlay.
ENV S6_VERSION v1.17.1.1
ADD https://github.com/just-containers/s6-overlay/releases/download/$S6_VERSION/s6-overlay-amd64.tar.gz /tmp/
RUN tar xzf /tmp/s6-overlay-amd64.tar.gz -C / && \
    mv /bin /bin-s6 && \
    /bin-s6/s6-update-symlinks /bin /bin-s6 /usr/bin

ENTRYPOINT ["/init"]

**Comment by zanhsieh** [comment]
+1. i got the same issue, too.

**Comment by jprjr** [comment]
@ploef @zanhsieh what about the workaround from the README? https://github.com/just-containers/s6-overlay#bin-and-sbin-are-symlinks

This is what I do on CentOS

**Comment by jprjr** [comment]
@ploef @zanhsieh @glerchundi  I found the cause of the "too many levels of symbolic links" problem:

https://github.com/just-containers/s6-overlay/commit/704c86aff57702a1767cc718d8775c7b7095fe23

The s6-overlay tarball contains a symlink: `/usr/bin/execlineb -> /bin/execlineb`

So if you extract the tarball and run `s6-update-symlinks`, you wind up with a circular symlink:

```
/bin/execlineb -> /usr/bin/execlineb
/usr/bin/execlineb -> /bin/execlineb
```

So another workaround is to use something like:

```
FROM centos:centos7
ENV S6_VERSION v1.17.1.1
ADD https://github.com/just-containers/s6-overlay/releases/download/$S6_VERSION/s6-overlay-amd64.tar.gz /tmp/
RUN tar xzf /tmp/s6-overlay-amd64.tar.gz -C / && \
mv /bin /bin-s6 && \
rm /usr/bin/execlineb && \
/bin-s6/s6-update-symlinks /bin /bin-s6 /usr/bin

ENTRYPOINT ["/init"]
```

**Comment by zanhsieh** [comment]
I will give it a try later on.

**Comment by 1dal** [comment]
Actually same problem with Debian:stretch-slim. Workarounds above not working to me, ends with error: 

```bash
tar: ./sbin: Not found in archive
tar: Exiting with failure status due to previous errors

``` 

In my case working this solution with **rsync**: 

```bash
RUN wget https://keybase.io/justcontainers/key.asc --no-check-certificate -O /tmp/s6-overlay-key.asc \
    && wget https://github.com/just-containers/s6-overlay/releases/download/${S6_OVERLAY_VERSION}/s6-overlay-amd64.tar.gz --no-check-certificate -O /tmp/s6-overlay-amd64.tar.gz \
    && wget https://github.com/just-containers/s6-overlay/releases/download/${S6_OVERLAY_VERSION}/s6-overlay-amd64.tar.gz.sig --no-check-certificate -O /tmp/s6-overlay-amd64.tar.gz.sig \
    && gpg --import /tmp/s6-overlay-key.asc \
    && gpg --verify /tmp/s6-overlay-amd64.tar.gz.sig /tmp/s6-overlay-amd64.tar.gz \
    && mkdir /tmp/s6 \
    && tar xzf /tmp/s6-overlay-amd64.tar.gz -C /tmp/s6 \
    && rsync -r --progress --ignore-existing /tmp/s6/ / \
    && ln -s /bin/execlineb /usr/bin/execlineb
    && rm -f /tmp/s6-overlay-key.asc \
    && rm -f /tmp/s6-overlay-amd64.tar.gz \
    && rm -f /tmp/s6-overlay-amd64.tar.gz.sig
```

**Comment by fredleger** [comment]
@1dal : just got a simpler one fro debian:stretch-slim and no need of rsync

```
FROM debian:stretch-slim

ADD https://github.com/just-containers/s6-overlay/releases/download/v1.19.1.1/s6-overlay-amd64.tar.gz /tmp/
RUN tar xzf /tmp/s6-overlay-amd64.tar.gz -C / --exclude="./bin" && \
    tar xzf /tmp/s6-overlay-amd64.tar.gz -C /usr ./bin
RUN ls -als /bin
```

This is the same approach as stated in the documentation execpt that the current overlays version s d'ont include any /sbin directory so it might be removed.

**Comment by frekele** [comment]
It was exactly the problem I was having after doing the Debian 8 (Jessie) upgrde for the Debian 9 (Stretch).

I could use rsync as well as @1dal said, but I see no need to install another package.
We do not need to delete /sbin for this case, only /bin in the s6-overlay 1.19.1.1 version.

My Dockerfile: https://github.com/frekele/docker-debian/blob/master/Dockerfile

Thank you @fredleger.

**Comment by 1dal** [comment]
@fredleger Your solution is better, thank you! I was too lazy read tar man :-)

**Comment by 1dal** [comment]
Small update: 

Debian 9.1 no longer uses symlinks to /bin. 
My Dockerfile now looks like this: 
```Dockerfile

    FROM debian:stretch-slim
    ENV S6_OVERLAY_VERSION=v1.20.0.0
     
    RUN .... \ 
        curl -L -o /tmp/s6-overlay-key.asc https://keybase.io/justcontainers/key.asc \
        && curl -L -o /tmp/s6-overlay-amd64.tar.gz https://github.com/just-containers/s6-overlay/releases/download/${S6_OVERLAY_VERSION}/s6-overlay-amd64.tar.gz  \
        && curl -L -o /tmp/s6-overlay-amd64.tar.gz.sig https://github.com/just-containers/s6-overlay/releases/download/${S6_OVERLAY_VERSION}/s6-overlay-amd64.tar.gz.sig \
        && gpg --import /tmp/s6-overlay-key.asc \
        && gpg --verify /tmp/s6-overlay-amd64.tar.gz.sig /tmp/s6-overlay-amd64.tar.gz \
        && tar xvfz /tmp/s6-overlay-amd64.tar.gz -C / ;
```

**Comment by frekele** [comment]
Debian 9.0 used symlinks /bin, but after update debian 9.1 it no longer more uses symlinks in /bin.

**Comment by frekele** [comment]
Debian 9.0 used symlinks /bin, but after update debian 9.1 it no longer more uses symlinks in /bin.

https://github.com/frekele/docker-debian/commit/3eb1b9c8836a2369a9ec58760d696316629ae21e
