### ISSUE TITLE
With centos 7: [8] System error: too many levels of symbolic links

### ISSUE THREAD

**Issue by ploef** [just-containers/s6-overlay#126]
Hi,

Creating a new issue for the closed issue #124. The original error seems to be solved, but resulting in a new error when running the image:

*[8] System error: too many levels of symbolic links*

Could you please look in to this?

Regards,
Peter

**Comment by glerchundi** [comment]
```
FROM centos:centos7
ADD https://github.com/just-containers/s6-overlay/releases/download/v1.17.1.1/s6-overlay-amd64.tar.gz /tmp/
RUN tar xzf /tmp/s6-overlay-amd64.tar.gz -C / && \
    mv /bin /bin-s6 && \
    rm /usr/bin/execlineb && \
    /bin-s6/s6-update-symlinks /bin /bin-s6 /usr/bin && \
    ln -s /bin/execlineb /usr/bin/execlineb
RUN yum clean all && yum -y update
ENTRYPOINT [ "/init" ]
```

**Comment by glerchundi** [comment]
@ploef did you tested it? it worked on my machine....

**Comment by pubyun** [comment]
same issue of /sbin which symlink to /usr/sbin

ADD https://github.com/just-containers/s6-overlay/releases/download/v1.17.1.1/s6-overlay-amd64.tar.gz /tmp/
RUN tar xzf /tmp/s6-overlay-amd64.tar.gz -C / \
    && mv /bin /bin-s6 \
    && rm /usr/bin/execlineb \
    && /bin-s6/s6-update-symlinks /bin /bin-s6 /usr/bin \
    && ln -s /bin/execlineb /usr/bin/execlineb \
    && mv /sbin /sbin-s6 \
    && /bin-s6/s6-update-symlinks /sbin /sbin-s6 /usr/sbin

**Comment by glerchundi** [comment]
I'm going to close this as it seems resolved with the following `Dockerfile`:
```
FROM centos:centos7

# Decompress overlay, and fix /bin & /sbin symlinks
ADD https://github.com/just-containers/s6-overlay/releases/download/v1.17.1.1/s6-overlay-amd64.tar.gz /tmp/
RUN tar xzf /tmp/s6-overlay-amd64.tar.gz -C / && \
  mv /bin /bin-s6 && \
  rm /usr/bin/execlineb && \
  /bin-s6/s6-update-symlinks /bin /bin-s6 /usr/bin && \
  ln -s /bin/execlineb /usr/bin/execlineb && \
  mv /sbin /sbin-s6 && \
  /bin-s6/s6-update-symlinks /sbin /sbin-s6 /usr/sbin
RUN yum clean all && yum -y update

ENTRYPOINT [ "/init" ]
```
