### ISSUE TITLE
use environmental variables passed to docker in cont-init.d and services.d files?

### ISSUE THREAD

**Issue by cboettig** [just-containers/s6-overlay#128]
I am attempting to refer to environmental variables that are passed to my container at run time using the `-e ENVVAR=value` from `docker run`.  My `/etc/cont-init.d` directory just contains a bash script that refers to these, e.g. `$ENVVAR`, and I can see s6 is running the script successfully but the script is not getting the values passed to the container.  Is there a way around this?

**Comment by smebberson** [comment]
Have you tried the following shebang in your bash script?

```
#!/usr/bin/with-contenv bash
echo $ENVVAR
```

**Comment by cboettig** [comment]
Thanks, and sorry I missed that in the documentation! (https://github.com/just-containers/s6-overlay#container-environment)

**Comment by sakoht** [comment]
It's unclear to me what _exactly_ goes into the `docker run` command, or into the dockerfile, or how exactly I modify the entrypoint to get those env vars.

Could you clarify?

(I'm passing-through AWS* so that tools can access AWS.)
