### ISSUE TITLE
core file dump

### ISSUE THREAD

**Issue by drankinn** [just-containers/s6-overlay#129]
I'm trying to track down or disable the creating of a mysterious core file in my volume.
running  "docker run --rm -it -v /tmp/app:/app --workdir /app justcontainers/base-alpine ash"
and then exiting creates a binary file named core in the mounted volume.  I assume it's some sort of core dump or something.   
How can I prevent it from polluting my volume?

**Comment by glerchundi** [comment]
Which overlay version are you using? Our custom base images? If so, which image tag? Provide a complete example so that we'll be able to reproduce it.

**Comment by drankinn** [comment]
please try the docker command in my initial post.  I think it's using a 1.16 something version.   I have also been able to reproduce it with the latest 1.17.1.1 in a custom alpine:latest base image.

**Comment by glerchundi** [comment]
I didn't get any core dump on my machine:

```
22:45:27 $> ls -l app
ls: app: No such file or directory

22:45:31 $> docker run --rm -it -v `pwd`/app:/app --workdir /app justcontainers/base-alpine ash
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
/app # exit
ash exited 0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

22:45:50 $> ls -la app/
total 0
drwxr-xr-x   2 glerchundi  staff    68 Jan 11 22:45 .
drwxr-xr-x+ 85 glerchundi  staff  2890 Jan 11 22:45 ..
```

Are you `ulimit`ing or doing something more that the mentioned statement?

**Comment by drankinn** [comment]
I don't think so.  when I run ulimit it says unlimited.  
I'm running docker 1.9.1:
> docker info
Containers: 1
Images: 547
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 549
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.0-22-generic
Operating System: Ubuntu 15.10
CPUs: 8
Total Memory: 15.6 GiB
Name: dev-workstation-1502
ID: C5GA:KUAE:MJOM:L7SI:6WSU:WG5D:SPDO:BBH6:U3GQ:OHZZ:VZRI:TC5J
Username: ****
Registry: https://index.docker.io/v1/
Labels:
 provider=generic


Is there a way I can see what is generating that file?

**Comment by glerchundi** [comment]
I cannot tell you anything until I get a non-working environment. I seems to work well on my machine...

**Comment by smerrill** [comment]
@drankinn If you are on a Linux host, you may be able to run `file $CORE_FILE`, as below.

```
$ file core.18299
core.18299: ELF 64-bit LSB core file x86-64, version 1 (SYSV), SVR4-style, from 's6-pause -th'
```

**Comment by glerchundi** [comment]
@drankinn did you solve this?

**Comment by drankinn** [comment]
no, I can confirm that I'm still seeing the same problem.  @smerrill  I am getting the exact same output as you posted.  something with the s6-pause  command

**Comment by glerchundi** [comment]
@drankinn can you follow the steps specified in this [issue](https://github.com/just-containers/s6-overlay/issues/85) in order to get a strace output? It would be really helpful.

**Comment by drankinn** [comment]
@glerchundi  I tried to build and run that container, but the url for the strace seems to be invalid.  can you provide another?  thanks.

**Comment by glerchundi** [comment]
@drankinn replace the lines regarding to strace with `RUN apt-get update && apt-get install -y strace`, and of course use the latest overlay ;)

**Comment by drankinn** [comment]
Here's the docker file I used
[Dockerfile.txt](https://github.com/just-containers/s6-overlay/files/157183/Dockerfile.txt)

and after running 

`docker run -v `pwd`/logs:/logs --workdir=/logs -ti asdf ash`

Here's what I see

strace: ptrace(PTRACE_TRACEME, ...): Operation not permitted
+++ exited with 1 +++

**Comment by drankinn** [comment]
seems like strace didn't work?

**Comment by glerchundi** [comment]
Try this:

```
FROM justcontainers/base-alpine
	
# strace
RUN apk add --update libcap strace
RUN setcap cap_sys_ptrace=eip /usr/bin/strace

# replace 's6-pause' with 'strace s6-pause'
RUN sed -i 's/s6-pause/redirfd -w 2 \/logs\/s6-pause-strace.log strace -v s6-pause/g' /etc/s6/init/init-stage2

ENTRYPOINT [ "/init" ]
```

**Comment by glerchundi** [comment]
If this doesn't work probably interfering process flow (ptracing) is not permitted in containers by your host machine...

**Comment by smerrill** [comment]
You could probably add `--cap-add SYS_PTRACE` to the `docker run` command for the container in order to allow strace to work.

**Comment by drankinn** [comment]
$ docker build -t asdf .
Sending build context to Docker daemon 4.608 kB
Step 1 : FROM justcontainers/base-alpine
 ---> 5c5b62f45ad9
Step 2 : RUN apk add --update libcap strace
 ---> Using cache
 ---> e34133bc173f
Step 3 : RUN setcap cap_sys_ptrace=eip /usr/bin/strace
 ---> Running in cf295d2bae35
Failed to set capabilities on file `/usr/bin/strace' (Invalid argument)
usage: setcap [-q] [-v] (-r|-|<caps>) <filename> [ ... (-r|-|<capsN>) <filenameN> ]

 Note <filename> must be a regular (non-symlink) file.
The command '/bin/sh -c setcap cap_sys_ptrace=eip /usr/bin/strace' returned a non-zero code: 1


still no luck :(

**Comment by glerchundi** [comment]
umm, it worked on my machine....
anyway, remove setcap and just use `-cap-add SYS_PTRACE` like @smerrill pointed:

`docker run --cap-add SYS_PTRACE -v `pwd`/logs:/logs -ti asdf exit 0`

Lets see if this works.

**Comment by skarnet** [comment]
@drankinn : there was a bug in earlier versions of `s6-pause` that caused it to potentially crash with a SIGSEGV, which would cause a core dump. It was fixed on 2015-11-10 (commit 2078ad6352b4149a4ca1388f4557affd56ac6901 of s6-portable-utils). Please make sure you're using a recent version of s6-overlay.

**Comment by drankinn** [comment]
ok, so turns out I had to add --privileged to the run command for strace to work.

Here's the log output:
`execve("/bin/s6-pause", ["s6-pause", "-th"], ["PATH=/usr/bin:/usr/sbin:/bin:/sb"..., "?=0"]) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
+++ killed by SIGSEGV (core dumped) +++
`

**Comment by drankinn** [comment]
one additional bit.  the core dump only appears if I set a --workdir to a mounted volume location

**Comment by skarnet** [comment]
@drankinn : it really looks like you are experiencing the old `s6-pause` crash. Please update to an overlay that provides the latest git of s6-portable-utils and try again.
@glerchundi : do you need me to release a numbered version of s6-portable-utils ?

**Comment by glerchundi** [comment]
wow, i was pretty sure it was already included in the overlay! but its not :\

I though it was that bug but discarded after looking at the version (s)he's using.

@skarnet follow your versioning flow, I prepared the build system to use sha1 sums to build things or versions whenever I need them.

@drankinn thanks for reporting!

PD.: Already released a new version, 1.17.2.0, can you test if this is working for you?

**Comment by glerchundi** [comment]
@drankinn?

**Comment by drankinn** [comment]
ok, sorry for the delay.  I have tested the latest version, 1.17.2.0, and can confirm that the bug is fixed!

Thank yo so much
