### ISSUE TITLE
Permissions for service management

### ISSUE THREAD

**Issue by smebberson** [just-containers/s6-overlay#130]
What permissions are required for service management? We're discussing something over in https://github.com/smebberson/docker-alpine/pull/13 regarding how we can have one service up another service when the time is ready.

Further down in the comments, you'll see a screenshot which highlights the problem.

What is best practice to have one service up another service, when neither service is running as root (but s6 is)?

**Comment by glerchundi** [comment]
@smebberson, as stated in the Laurent's documentation (http://skarnet.org/software/s6/s6-svc.html):

> s6-svc writes control commands into the servicedir/supervise/control FIFO. A s6-supervise process running on servicedir will be listening to this FIFO, and will read and interpret those commands.

If you have write permissions on that file, you'll be able to manage it. I guess. Did you tried it?

**Comment by matthewvalimaki** [comment]
@glerchundi I tested and it does seem to work.

I created a new group called `s6`. Then did `chown -R root:s6 /var/run/s6/services/consul/` and added user `consul` to group `s6`. Then I tried `s6-svc -h /var/run/s6/services/consul/` and got `s6-svc: fatal: unable to control /var/run/s6/services/consul/: Permission denied`. Then I did `chmod g+w /var/run/s6/services/consul/supervise/*` and tried `s6-svc` again and it worked.

I wonder if the group write permission should be there by default?

**Comment by matthewvalimaki** [comment]
> I wonder if the group write permission should be there by default?

Answering to myself here: I do believe so. Problem is that if we want to use group to command services we'd need to `chmod  /var/run/s6/services/consul/supervise/*` somehow after the files are created in that folder. That does not sound right.

**Comment by glerchundi** [comment]
hei @matthewvalimaki,

I made a little test and it seems to work. Although i'll deny that I said this.... :). The idea is to precreate the supervision fifo with the required perms before making it into the image (`mkfifo rootfs/etc/services.d/test/supervise/control`).

```
$> tree
.
├── Dockerfile
├── README.md
└── rootfs
    ├── etc
    │   ├── fix-attrs.d
    │   │   └── 01-test
    │   └── services.d
    │       └── test
    │           ├── log
    │           │   └── run
    │           ├── run
    │           └── supervise
    │               └── control
    └── var
        └── log
            └── test
```

```
$> ls -l rootfs/etc/services.d/test/supervise/control
prw-rw----  1 glerchundi  staff  0 Feb  9 17:04 rootfs/etc/services.d/test/supervise/control
```

```
$> cat rootfs/etc/services.d/test/run
#!/bin/execlineb -P
trap
{
  term
  {
    foreground { s6-echo term received! }
    import -u ! kill ${!}
  }
}
loopwhilex -o 0
s6-sleep -m 1000
s6-echo tic
```

And the test go here:
```
$> docker run -ti test sh
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-test: applying... 
[fix-attrs.d] 01-test: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
/ # cat /var/log/test/current 
2016-02-09 16:55:44.935472500  tic
[...]
2016-02-09 16:55:51.943751500  tic
/ # su operator
/ $ s6-svc -t /var/run/s6/services/test
/ $ cat /var/log/test/current
2016-02-09 16:55:44.935472500  tic
[...]
2016-02-09 16:56:29.931678500  term received!
2016-02-09 16:56:29.994355500  tic
/ $
```

Obviously, this is a bull-shit and probably not forward compatible. If Laurent decides to modify the `s6` codebase and now asserts if `supervise/control` doesn't exist before proceeding...you know what would happen.

So, yes it works, but use at your own risk.

**Comment by glerchundi** [comment]
@smebberson @matthewvalimaki did you find this useful? can we close this?

**Comment by matthewvalimaki** [comment]
@glerchundi I can live with your proposal :) I would recommend adding a note of this to the readme.

**Comment by glerchundi** [comment]
i'm going to close this then :)
