### ISSUE TITLE
zombie process is not reaped

### ISSUE THREAD

**Issue by nigelgbanks** [just-containers/s6-overlay#135]
Hello I'm not sure if this should be logged against **s6** or here (or potentially I'm doing something wrong).

Basically I'm trying to build a container that uses **karaf**, and in the process of it starting, **java** gets abandoned by some parent process, at which point it's adopted by **init** (process 1). So far so good, but it never gets reaped by init.

```
Mem: 829908K used, 1220032K free, 456K shrd, 49596K buff, 371716K cached
CPU:   0% usr  49% sys   0% nic  50% idle   0% io   0% irq   0% sirq
Load average: 1.00 0.80 0.46 2/190 812
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
  773     1 root     Z        0   0%   0  49% [java]
....
```

Manually sending SIGCHLD to process 1 doesn't seem to have an affect either.

```bash
kill -s SIGCHLD 1
```

**Comment by glerchundi** [comment]
Although it can be something related to `s6-overlay` can you ask in the supervision list? Or just ping @skarnet if he can just give us a clue of what's going on there.

**Comment by skarnet** [comment]
Does `s6-svscanctl -z /var/run/s6/services` remove the zombie? If it does not, it's probably a kernel issue - which I suspect it is, because a zombie taking 49% of CPU isn't normal at all.

 This is not the first time I'm seeing this symptom of a zombie getting stuck and using all the CPU. It's very strange and likely a namespace-related kernel bug (PID namespaces, which are used to implement containers, are visibly not a mature technology yet).

**Comment by nigelgbanks** [comment]
```s6-svscanctl -z /var/run/s6/services``` does not remove the zombie, I'm running **Ubuntu 14.04** as  the host OS with **3.13.0-77-generic kernel**, and **Docker 1.10.3**. I'm going to close this ticket, and try with a different host OS, or see if I can make a minimal reproducible issues to create an issue for the Linux Kernel or Docker folks.

**Comment by nigelgbanks** [comment]
For others who may come across this, here is a potential lead as to the Kernel issue (AUFS specific):

https://github.com/docker/docker/issues/18180
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1533043

**Comment by skarnet** [comment]
Thanks for confirming it's a kernel problem. :) Did you manage to get your system working in the end?

**Comment by nigelgbanks** [comment]
Yup changing the kernel did fix it for me.
