### ISSUE TITLE
Service Start > Bad Lock File > Stays Running

### ISSUE THREAD

**Issue by bryanlatten** [just-containers/s6-overlay#140]
```
[services.d] starting services
[services.d] done.
Wed Mar 16 15:58:19 2016 (221): Fatal Error Unable to create lock file: Bad file descriptor (9)
Wed Mar 16 15:58:19 2016 (221): Fatal Error Unable to create lock file: Bad file descriptor (9)
Wed Mar 16 15:58:20 2016 (228): Fatal Error Unable to create lock file: Bad file descriptor (9)
Wed Mar 16 15:58:21 2016 (235): Fatal Error Unable to create lock file: Bad file descriptor (9)
Wed Mar 16 15:58:22 2016 (242): Fatal Error Unable to create lock file: Bad file descriptor (9)
```

I have a service definition that refuses to start, but the S6 supervisor is not running the `finish` script or terminating. I'm probably doing something backwards in my service definition, but it should at least take down the services instead staying up.

**Comment by glerchundi** [comment]
can you extend your information with your Dockerfile + assets? Which version are u using?

**Comment by bryanlatten** [comment]
@glerchundi I dug a bit deeper, there was a supervised master thread staying alive with dead children. my apologies for the noise!
