### ISSUE TITLE
Changing SIGTERM --> Other process signal

### ISSUE THREAD

**Issue by bryanlatten** [just-containers/s6-overlay#141]
@skarnet as per http://blog.tutum.co/2015/05/20/s6-made-easy-with-the-s6-overlay/, in the "Using signals besides TERM" section, there is the workaround for catching/changing the SIGTERM into another signal. For example, I'm currently leveraging both nginx (SIGQUIT) and apache (SIGWINCH), and have to do the tiny hack for both. Are there plans to make this into a feature? 

Sidenote: `really` enjoying S6

**Comment by glerchundi** [comment]
@bryanlatten can [this](https://github.com/just-containers/s6-overlay/issues/41#issuecomment-99366363) work for you?

**Comment by bryanlatten** [comment]
that was it - any issues running as a child process of `trap` (as root)?

```
root       173  0.0  0.0    192     4 ?        Ss   20:34   0:00  \_ trap -x  term   foreground    nginx    -s    quit      echo   [sigterm-nginx]   graceful   shutdown   complete
www-data   175  0.0  0.7  82168  7748 ?        S    20:34   0:00      \_ nginx: master process nginx -g daemon off;
```

**Comment by skarnet** [comment]
The only issue is that using `s6-svc -k` or `s6-svc -p` will not work, because you can't trap SIGKILL or SIGSTOP, so `trap` cannot forward those to its child process. Apart from that, everything should work transparently.

**Comment by bryanlatten** [comment]
sounds reasonable. thanks again, @skarnet!

**Comment by grosser** [comment]
@bryanlatten could you share your full setup please, I'm trying the same but it does not seem to work :/

```
#!/usr/bin/execlineb -P
# always take down nginx gracefully so it does not drop requests
# via https://github.com/just-containers/s6-overlay/issues/141
trap
{
  term
  {
    foreground {
      nginx -s quit -c /app/nginx/nginx.conf
    }
    import -u ! kill ${!}
  }
}
nginx -g "daemon off;" -c /app/nginx/nginx.conf

```

**Comment by bryanlatten** [comment]
Not doing much special: 

https://github.com/behance/docker-nginx/blob/master/container/root/etc/services-available/nginx/run
