### ISSUE TITLE
Can I use "#!/usr/bin/env sh" in init scripts?

### ISSUE THREAD

**Issue by PavelPrischepa** [just-containers/s6-overlay#143]
Can I use "#!/usr/bin/env sh" instead of "#!/usr/bin/with-contenv sh" in init scripts?

**Comment by jprjr** [comment]
@PavelPrischepa you can, but scripts are started with a completely blank environment. If you use `#!/usr/bin/env sh` as your shebang line, none of the Docker container's environment variables will be visible. Depending on your use case, this might be fine.

Using `#!/usr/bin/with-contenv sh` will import the container's environment variables.

**Comment by PavelPrischepa** [comment]
Ok, thank you!
