### ISSUE TITLE
script in fix-attrs.d run too slow

### ISSUE THREAD

**Issue by Ara4Sh** [just-containers/s6-overlay#146]
Hello 
I have a simple permission fix script with only one line in fix-attrs.d 

```
/var/www/owncloud true apache 0644 0755
```

problem starts when I run the container it almost take a minute to fix permissions and that is too slow 

why this proccess takes long time ?

**Comment by glerchundi** [comment]
hi @Ara4Sh, sorry for the delay.

Which version are you using? I made some changes in this #121 PR which should improve its performance a little bit. Although, in case you didn't know, fix-attrs is entirely written in execline scripting language which is, of course, much less performant than any native code.

Don't expect any improvement in this area until we evaluate the possibility to create a custom ad-hoc fix-attrs binary which does exactly the same as the script.

Feel free to create a new issue asking for a feature request.

**Comment by Ara4Sh** [comment]
Thank you very much 
Im using v1.17.2.0 is there any thing that we can help to improve the process ? is there any contributing documentation ?

**Comment by glerchundi** [comment]
@Ara4Sh I missed this comment completely, as this is a project maintained in our spare time I wasn't able to follow this properly.

In the next weeks(?) we're going to prototype a new version of `s6-overlay` using `s6-rc` which would ease everything a little bit so maybe this would be a good time to discuss how to proceed with this performance problem too.

Thanks for your patience & contributing goodwill.

**Comment by snakevil** [comment]
Why not using the following commands?

```bash
chown -hR $user:$group $dir
chmod -R $fmode $dir
find $dir -type d -exec chmod $dmode {} \;
```

**Comment by jprjr** [comment]
Closing, if fix-attrs.d is too slow you should probably just use the combination of chown/chmod/find in the above comment.
