### ISSUE TITLE
Add build for ARM to automated builds

### ISSUE THREAD

**Issue by bofm** [just-containers/s6-overlay#152]
It would be great to be able to grab a built release for armhf platform from releases.

**Comment by jprjr** [comment]
@bofm - take a look at [release v1.18.1.0](https://github.com/just-containers/s6-overlay/releases/tag/v1.18.1.0) - this has a new armhf build a file. Try it out and let me know if it works out for you :)

**Comment by glerchundi** [comment]
@jprjr great work! this should be fixed now as `armhf` releases are included in the release process.
