### ISSUE TITLE
v1.17.3.0 doesn't include /bin/*

### ISSUE THREAD

**Issue by snout1979** [just-containers/s6-overlay#154]
The necessary S6 binaries are not included in the latest release, the archive contains just the scripts from /etc and /usr/bin

**Comment by jprjr** [comment]
Sorry about that - I think when I was bumping versions earlier I did a few steps out-of-order. Just pushed v1.18.0.0 which should fix it

**Comment by jprjr** [comment]
@snout1979 v1.18.0.0 looks correct, I've gone and and deleted release v1.17.3.0 - feel free to close this issue.
