### ISSUE TITLE
please clarify your license

### ISSUE THREAD

**Issue by williamh** [just-containers/s6-overlay#157]
I am looking at packaging this for Gentoo Linux. However, looking through your repository, I am unable to tell how you are licensing it. Can you please clarify?
Thanks much.

**Comment by jprjr** [comment]
@glerchundi @skarnet thoughts? I'd be OK with with a more permissive license, like the ISC license.

**Comment by glerchundi** [comment]
I feel very comfortable with ISC, so it's ok for me.

**Comment by glerchundi** [comment]
done in #162.
