### ISSUE TITLE
un-bundling s6, s6-portable-utils, skalibs etc.

### ISSUE THREAD

**Issue by williamh** [just-containers/s6-overlay#159]
In Gentoo Linux, we already have separate packages for s6, s6-portable-utils, skalibs, etc. I would like to know how to install your overlay so that it uses our packages for these utilities, and where to look to make sure I set the dependencies correctly so that it uses the correct versions of these packages.
Do you mind giving me suggestions for how to do this?

Thanks for your time,

William

**Comment by glerchundi** [comment]
@williamh take a look to this issue: #108. `-nobin` releases uses you host binaries instead of bundling them in the overlay.
