### ISSUE TITLE
Add build for i386 to automated builds

### ISSUE THREAD

**Issue by dquintela** [just-containers/s6-overlay#164]
Hello, I've seen arm has been included recently #152 . Can i386 be included also ?

**Comment by glerchundi** [comment]
@dquintela of course, PR are also welcome ;)

**Comment by pharazon** [comment]
I'd need this, too. Tried to compile it but skaware has too many x64 dependencies, so it was too much was and I reverted to use other more straight forward tools.

**Comment by jprjr** [comment]
We now have an x86 build as of the latest release: https://github.com/just-containers/s6-overlay/releases/tag/v1.19.1.1
