### ISSUE TITLE
just-containers/alpine-base contradicts recommended 'ADD' over 'RUN' directives

### ISSUE THREAD

**Issue by devproco** [just-containers/s6-overlay#175]
From [just-containers/s6-overlay/readme.md](https://github.com/just-containers/s6-overlay/blob/master/README.md#usage):

``` md
Right now, we recommend using Docker's `ADD` directive instead of running `wget` or `curl` in a `RUN` directive - Docker is able to handle the https URL when you use `ADD`, whereas your base image might not be able to use https, or might not even have `wget` or `curl` installed at all.
```

From [just-containers/base-alpine/Dockerfile](https://github.com/just-containers/base-alpine/blob/master/Dockerfile#L11):

``` dockerfile
# s6 overlay
RUN apk add --no-cache wget \
 && wget https://github.com/just-containers/s6-overlay/releases/download/v1.18.1.3/s6-overlay-amd64.tar.gz --no-check-certificate -O /tmp/s6-overlay.tar.gz \
 && tar xvfz /tmp/s6-overlay.tar.gz -C / \
 && rm -f /tmp/s6-overlay.tar.gz \
 && apk del wget
```

**Comment by JonathanSerafini** [comment]
Just my 2c... 
Although technically true ( i.e. the docs say so ), i'd go so far as to say that in practice the wget route with versioned uris is superior. ADD seems to re-download the asset on each build ( although it wont invalidate cache if the file doesn't change ) whereas with wget the entire step will be cached thus ensuring the asset doesnt download needlessly.
