### ISSUE TITLE
Question about retry strategy

### ISSUE THREAD

**Issue by oilbeater** [just-containers/s6-overlay#177]
Hi, I noticed that s6 will restart service if the service failed quickly. But I am not sure if there is some restart delay or backoff strategy. Where can I find some docs and examples to set the retry strategy

**Comment by robinroestenburg** [comment]
See the s6-supervise documentation (http://skarnet.org/software/s6/s6-supervise.html):

> There is a minimum 1-second delay between two ./run spawns, to avoid busylooping if ./run exits too quickly.
