### ISSUE TITLE
Is it possible to start services in order and await their order

### ISSUE THREAD

**Issue by u6f6o** [just-containers/s6-overlay#178]
Hi, 

I hope you don't mind my direct approach but I am not sure which channel is favoured for questions regarding s6-overlay. 

Lately I used s6-overlay to create a little [docker image](https://github.com/u6f6o/docker-openvpn-pia/) to startup openvpn with pia and as a next step I'd like to use iptables to guarantee all communication with the outside world happens through vpn. 

In order to do so, I'd like to know if it is possible to start services in a particular order (e.g. 01-iptables, 02-openvpn) and await the other services successful startup signal before starting up a new one? 

Thx in advance, 
u6f6o

**Comment by u6f6o** [comment]
So I read about fd-notification but I do not understand how I can signal that a service is finally in it's desired state? As the service should run in foreground mode, I cannot really check if the service is up and announce it's state? 

Would be nice if somebody could re-direct me to a wiki-page etc.

**Comment by michaellopez** [comment]
@u6f6o I think this issue might be what you want https://github.com/just-containers/s6-overlay/issues/123 but unfortunately its a bit stale...
