### ISSUE TITLE
Creating folder pre or during fix-attr.d

### ISSUE THREAD

**Issue by KalleDK** [just-containers/s6-overlay#181]
This issue is related to https://github.com/just-containers/s6-overlay/issues/90

I have the same trouble. I have a path ex /data where there has to be some folders and files with the right permissions.

```
/data/onething
/data/onething/flaf.conf
/data/other
/data/other/stuff.json
```

I mount the onething and other folder either from the host or some volumes. This makes sure these two folders exists and that their permisisons are correct. But i still have problems with the files (and other subfolders). cont-init.d runs after fix-attr.d, so if i create them via cont-init.d - i also have to set their permissions there, this i find counter intuitive. So first time cont-init.d provides the permissions and next time the image is run, fix-attr.d provides them. 

I would love fix-attr.d to be able to create empty files and folders if they do not exists yet.

That way I know they exists when cont-init.d arrives, and I can still populate the files there, without thinking about ownership

( The program i use require those files to exists and wont create them itself, therefore I create them via cont-init.d, they also differ in content provided via environment variables)

**Comment by bhuisgen** [comment]
Yes, I need it too as when you create a named volume (mount bind from host), docker doesn't populate the content of the directory from the image. This is not the case with nameless volume. So I'm forced to create subdirectories and set the right permissions from a cont-init.d script. I would appreciate to have a new option to the fix-attrs.d file to create the required directories into the volume.

**Comment by skarnet** [comment]
I realize it's very late and my comment won't even answer your needs, but I've only started working on this two months ago and the new 3.0.0.0 version will hopefully solve all the previous maintenance issues.

Is it possible for you guys to set the proper ownerships and permissions to your files from outside the container, in your Docker setup or Dockerfile? Our point of view is that files without proper ownerships are security issues waiting to happen, and would rather not have to fix things from *inside* the container (which doesn't work with USER containers anyway); we're trying to deprecate `fix-attrs`.
