### ISSUE TITLE
cont-init.d fails with exit code 1, but container exits with code 0

### ISSUE THREAD

**Issue by HadesArchitect** [just-containers/s6-overlay#183]
When cont-init.d script quits with error (exit code 1), the whole container still quits with exit code 0. Is it an issue or have I misunderstood configuration?

Example:

```
service         | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
service          | [s6-init] ensuring user provided files have correct perms...exited 0.
service          | [fix-attrs.d] applying ownership & permissions fixes...
service          | [fix-attrs.d] done.
service          | [cont-init.d] executing container initialization scripts...
service          | [cont-init.d] init: executing...

ERROR HAPPENS

service          | [cont-init.d] init: exited 1.
service          | [cont-finish.d] executing container finish scripts...
service          | [cont-finish.d] done.
service          | [s6-finish] syncing disks.
service          | [s6-finish] sending all processes the TERM signal.
service          | [s6-finish] sending all processes the KILL signal and exiting.
service exited with code 0
```

Version: v1.18.1.5
Env. Variable: S6_BEHAVIOUR_IF_STAGE2_FAILS=2

**Comment by jrgensen** [comment]
This should be fixed by PR #186

**Comment by HadesArchitect** [comment]
Great! 

Should I close the issue now or wait till PR merged?

**Comment by eXistenZNL** [comment]
Still an issue, it seems

**Comment by HadesArchitect** [comment]
@eXistenZNL Wow, 4 years later? The fix (?) was merged already. Which version do you use?

**Comment by eXistenZNL** [comment]
@HadesArchitect I am running version v1.22.1.0, released on march 21, 2019 :) However I will give it a spin with version v2.1.0.2, to see if the problem still exists in v2. If not, I am more than happy to simply upgrade to version 2, and let you decide if you want to backport fixes from v2 to v1 :)

**Comment by eXistenZNL** [comment]
@HadesArchitect the results are in: this was totally my fault for not setting the right S6_BEHAVIOUR_IF_STAGE2_FAILS environment variable... so please ignore my ramblings about this still being broken :+1:
