### ISSUE TITLE
Envs in fix-attrs.d files

### ISSUE THREAD

**Issue by eratolekov** [just-containers/s6-overlay#188]
Hi glerchundi

Thanks for s6-overlay ;)

Is there possibility to use environment variables in fix-attrs.d files?

**Comment by GraemeF** [comment]
Would be great to be able to disable what fix-attrs.d does without having to make a new image...

**Comment by jprjr** [comment]
I'll just be honest, I'm not going to change this. Feel free to open a PR if this is needed.
