### ISSUE TITLE
Pipeline block args with quotes? 

### ISSUE THREAD

**Issue by bryanlatten** [just-containers/s6-overlay#191]
@skarnet trying to get `pipeline` to connect a handful of text processors together, but I cannot seem to understand the [docs](http://skarnet.org/software/execline/el_semicolon.html) on how to format blocks with quote arguments. Is there a clean way to escape the quotes? I've tried a number of different ways, but I always end up breaking the `sed` or having an unterminated block

Simplified statement in question:
```pipeline { producer } sed -u 's,\"$,,'```

**Comment by skarnet** [comment]
Single quotes are not special characters to execline. Use double quotes, or no quotes at all.
 `pipeline { producer } sed -u "s,\"$,,"`

**Comment by bryanlatten** [comment]
Easy enough! Thanks!
