### ISSUE TITLE
Finish script has only a few seconds to execute

### ISSUE THREAD

**Issue by AmazingDonut** [just-containers/s6-overlay#196]
The scripts in `/etc/services.d/myservice/finish` have only a few seconds to execute. If a finish script takes longer, it gets killed.

Perhaps it wasn't immediately clear from the documentation, but the `S6_KILL_FINISH_MAXTIME ` setting only applies to finalization scripts contained in `/etc/cont-finish.d`.

This poses a limitation that no complex operations can be performed in a finish script for a particular service. The workaround is to use a finalization script; however, it doesn't cover the use case for services being restarted inside a container. I also feel that when using multiple services, it is cleaner to have dedicated finish scripts for each of them.

**Comment by trapexit** [comment]
You need to use `timeout-finish` file in your service directory.

http://skarnet.org/software/s6/servicedir.html

**Comment by AmazingDonut** [comment]
Thank you for pointing it out! Closing the issue.
