### ISSUE TITLE
WORKDIR support for services ?

### ISSUE THREAD

**Issue by guillaume-perreal** [just-containers/s6-overlay#198]
It seems the WORKDIR command from Dockerfile is ignored for services, which is probably to be expected, given how s6-supervise works.

However, when building base images, it could be useful that some services were run in the starting working directory defined by derived images instead of an hard-coded one, e.g. running `npm start`, `grunt watch`, and so on.

I am thinking about trying the following solution, but as I'm no execlineb expert I suppose it could be improved.

Create the following files:

/usr/bin/save-contwd:

    #!/usr/bin/execlineb 
    elgetpositionals
    getcwd S6_CONT_WORKDIR
    emptyenv -P
    $@

/usr/bin/with-contwd:

    #!/usr/bin/execlineb 
    elgetpositionals
    import S6_CONT_WORKDIR
    cd $S6_CONT_WORKDIR
    emptyenv -P
    $@

Then, use this in the docker file:

    CMD ["/usr/bin/save-contwd", "/init"]

And in the run script:

    #!/usr/bin/execlineb -P
    with-contenv
    with-contwd
    run-my-service

Any advice ?

**Comment by jprjr** [comment]
When we save the container environment, we save the `WORKDIR` as `CWD`, so all that really needs to be done in a service script is to cd to `$CWD`:

```
#!/usr/bin/execlineb -P

with-contenv
importas -ui CWD CWD

cd $CWD
run-your-service
```
