### ISSUE TITLE
Check the S6 version

### ISSUE THREAD

**Issue by bryanlatten** [just-containers/s6-overlay#203]
I can quickly see there is an S6 release of 2.4.0.0 here: https://github.com/skarnet/s6/releases,
But there does not seem to be any variable to correlates the base S6 version inside this package. 

Is there a way to figure out what version of S6 is being used/built?

**Comment by jprjr** [comment]
I suppose I could add some text to the GitHub release page with a listing of each package.

Basically, releases of s6-overlay have a corresponding release over at the [just-containers/skaware](https://github.com/just-containers/skaware/releases) project - you basically drop the last number of an s6-overlay release to get the just-containers/skaware release.

So our current release, v1.19.1.0 uses [v1.19.1](https://github.com/just-containers/skaware/releases/tag/v1.19.1) of just-containers/skaware. The releases page for just-containers/skaware lists the versions of included packages.

**Comment by bryanlatten** [comment]
Perfect, thank you!
