### ISSUE TITLE
Running command as normal user with s6?

### ISSUE THREAD

**Issue by bborysenko** [just-containers/s6-overlay#207]
Hello,

What is the best way to run command under the s6 supervisor as normal user? 

I have tried `s6-setuidgid`, but since `$HOME` is not changed it fails in some cases. For example:

```
/usr/src/app # s6-setuidgid owox git config --global user.name docker
warning: unable to access '/root/.gitconfig': Permission denied
warning: unable to access '/root/.config/git/config': Permission denied
error: could not lock config file /root/.gitconfig: Permission denied
```

**Comment by eratolekov** [comment]
Hi

I'm using

```
#!/usr/bin/with-contenv sh

exec s6-setuidgid user /path/to/script.sh
```
/path/to/script.sh:
```
#! /bin/bash -e

HOME=~user
export HOME
...
```

**Comment by jprjr** [comment]
That's something to generally be aware of - by default most environment variables are removed, and a lot of apps expect variables like `HOME` to be available.

I've thought about writing a short script that sets things like HOME. In the meantime, here's an example of running a shell with CMD as not-root:

```Dockerfile
CMD ["/usr/bin/execlineb", "-P", "-c", "emptyenv export HOME /home/user s6-setuidgid user /bin/bash"]
```
