### ISSUE TITLE
Environment variables over 4096 bytes are trimmed

### ISSUE THREAD

**Issue by JamesBarwell** [just-containers/s6-overlay#212]
Hi, after upgrading from an older version of s6-overlay, I ran into this issue where environment variables were being silently trimmed to 4096 bytes. I found this comment at the end of #46

> Yes, there's a 4096 byte limit for variables loaded via s6-envdir. This is intentional: most legitimate uses of the environment never transmit large quantities of data. You can put the data in a temporary file, put the name of the file in an environment variable, and make your application get its data from the file.

My use case is that I want to pass a TLS certificate chain (6071 bytes) via the environment variable. What I've ended up doing is running a pre-init process before s6-overlay init, to write the environment variable to a file, then in my cont-init script (that s6 runs and that uses `with-contenv`), I have to read the file back out and export the variable.

main init for docker container. s6-overlay init has been renamed init2
```
echo "$SSL_CERT" > /tmp/SSL_CERT
/init2
```

script inside cont-init.d
```
#!/usr/bin/with-contenv sh

SSL_CERT_PATH=/tmp/SSL_CERT
if [ ! -f "$SSL_CERT_PATH" ]; then
    echo "error: could not find SSL_CERT at $SSL_CERT_PATH"
    exit 1
fi

export SSL_CERT=$(cat $SSL_CERT_PATH)

# stuff using the environment variables goes here...
```

I haven't seen any discussion of why the 4096 byte limit was put in place or what the intention of limiting it is. I'm hoping that my use-case above might help to show that there are legitimate reasons to pass large environment variables through. The above has got me around the problem but I can't really understand why it is desirable for it to work this way.

Cheers.

**Comment by holycheater** [comment]
Hit same problem trying to get SSL certs to env. AFAIK linux kernel has limit on env variable size for processes. Some extra limit out of nowhere is not necessary here.

**Comment by jprjr** [comment]
Release v2.0.0.0 no longer trims variables.
