### ISSUE TITLE
Example for how to log services that don't log to stdout/stderr

### ISSUE THREAD

**Issue by mikehaertl** [just-containers/s6-overlay#214]
I try to capture logs for postfix with this overlay. As it seems, postfix can not be configured to log to `stdout` and `stderr` but insists on syslog.

I guess postfix is not the only daemon that behaves like this and wonder how this can be solved with the s6 overlay. So having an example in the documentation would surely help.

**Comment by mikehaertl** [comment]
I'm not sure, but I think, this here should help me:

https://github.com/skarnet/s6/tree/master/examples/syslogd-linux

Unfortunately I could not make it work. It's probably because there's no `/dev/log` inside the container. And I don't know how to create such a file. There are some error messages being logged:

```
@4000000059e482920361e9d4 fdmove: fatal: unable to move fd 3 to fd 1: Bad file descriptor
```

 Due to cryptic execlineb (which misses a good tutorial) I also fail to debug what could be wrong.

To be honest I feel a bit lost and almost regret having chosen s6-overlay. At first glimpse the docs looked fine and extensive. But after a closer look everything is extremely idiosyncratic and you have to spend ages to get the hang of it.

I also start to wonder if this project is really maintained anymore. Any help really much appreciated.

**Comment by mikehaertl** [comment]
Even at the risk of talking to myself, here's what I've tried so far.

Following the link above and trying to fix the issue I've undone the changes in this commit: https://github.com/skarnet/s6/commit/df194e5564f5b32aaf0e107b97095a1dd5bdbe35.

So my setup now looks like this. In the directory `/etc/services.d/syslog-linux` I have the following files:

**run**

```
#!/usr/bin/execlineb -P
fdmove -c 2 1
exec -c
s6-envuidgid nobody
s6-notifywhenup -f
s6-ipcserver -U -1 -- /dev/log
fdmove -c 1 2
ucspilogd IPCREMOTEEUID IPCREMOTEEGID
```

**log/run**

As there's no user syslog I've used root for `s6-setuidgid`.

```
#!/usr/bin/execlineb -P
s6-setuidgid root
s6-envdir -f env
importas -Cs LOGSCRIPT LOGSCRIPT
exec -c
s6-log $LOGSCRIPT

# Change env/LOGSCRIPT to alter s6-log's behaviour
```

**log/env/LOGSCRIPT**

```
- +^[0-9]+:\s[0-9]+:\serror\. t /logs/syslogd/error
- +^[0-9]+:\s[0-9]+:\sauthpriv\. t /logs/syslogd/auth
- +^[0-9]+:\s[0-9]+:\suser\. t /logs/syslogd/user
- +^[0-9]+:\s[0-9]+:\smessages\. t /logs/syslogd/messages
- +^[0-9]+:\s[0-9]+:\sdaemon\. t /logs/syslogd/daemon
f t /logs/syslogd/misc
```

Still, all i get in `/logs/misc/current` is:

```
@4000000059e48b4f1e84d014 s6-ipcserver-socketbinder: fatal: unable to exec s6-applyuidgid: No such file or directory
```

**Comment by robinroestenburg** [comment]
@mikehaertl I just run syslogd as a s6 service as follows:

**syslogd/run**
```
#!/usr/bin/execlineb -P
fdmove -c 2 1
/sbin/syslogd -n -O -
```

**syslogd/log/run**
```
#!/usr/bin/execlineb -PW
s6-setuidgid XYZ
emptyenv

# Redirect everything on stdout to the fifo.
redirfd -w 1 /var/run/company-name/syslogd-log-fifo
s6-format-filter "%s"
```

All output from syslogd is written to the log fifo. The following service listens redirects the output from the fifo to a log directory:

**syslogd-logs/run**
```
#!/usr/bin/execlineb -PW
s6-setuidgid XYZ
emptyenv

# Redirect stdin from fifo to stdout of service.
redirfd -rnb 0 /var/run/company-name/syslogd-log-fifo
s6-format-filter "[syslogd] %s"
```

**syslogd-logs/log/run**
```
#!/usr/bin/execlineb -PW

# Import log configuration.
s6-envdir /var/run/s6/container_environment
importas -is S6_LOGGING_SCRIPT S6_LOGGING_SCRIPT

s6-setuidgid XYZ
emptyenv

s6-log -bp -- ${S6_LOGGING_SCRIPT} /var/log/syslogd
```

And finally postfix:

**postfix/run**
```
#!/usr/bin/execlineb -P
fdmove -c 2 1
/usr/lib/postfix/master -d
```

**Comment by mikehaertl** [comment]
Finally I'm a step further. As you see in #215 I had installed an outdated version. Now I'm at 1.12.0.0 and the original syslogd-linux script doesn't create any errors anymore.

Unfortunately it still doesn't log anything. There are no messages from postfix.I've also tried with `logger -p daemon.notice "bla bla"` but the log files stay empty now.

So it's 2 steps forward 1 step back.

**Comment by mikehaertl** [comment]
Ok, I gave up on the above and tried something else: Using busybox' syslogd. This time it worked and i finally get logging output.

Here's what I have:

**services.d/syslogd/run**

```
#!/bin/sh

# Run syslogd and let it log to stdout
exec /sbin/syslogd -n -S -O -
```

**services.d/syslogd/log/run**

```
#!/bin/sh

export S6_LOGGING_SCRIPT="n20 s1000000"
exec logutil-service /logs/postfix
```

Now I finally get log output, even if timestamp is now duplicated:

```
2017-10-16 11:52:36.689966500  Oct 16 11:52:36 syslogd started: BusyBox v1.26.2
2017-10-16 11:52:38.471264500  Oct 16 11:52:38 postfix/master[456]: daemon started -- version 3.1.4, configuration /etc/postfix
```

I've tried to set another `S6_LOGGING_SCRIPT` by adding a `export S6_LOGGING_SCRIPT="n20 s1000000"` to the `log/run` script above. Of course this didn't work.

For now I can live with that - but if someone comes up with a yet better approach or knows how I can get rid of the duplicate timestamps let me know.

I still think, that something like this should be added to the docs.

**Comment by mikehaertl** [comment]
@robinroestenburg Sorry, just seen your comment. Your solution looks a bit more complex than mine. You use 2 services to deal with syslog. Is this really neccessary? Or what's the advantage of that?

Also did you manage to get rid of the duplicate timestamps in the log file?

**Comment by robinroestenburg** [comment]
@mikehaertl yes, the fifo can be omitted; your setup is ok. I can probably get rid of it :)

You should be able to get rid of the duplicate timestamps by using that `S6_LOGGING_SCRIPT`. I am not sure if/how this works with the logutil-service, as I am using s6-log directly.

That being said, I do have duplicate timestamps for syslogd. I did not want to bother with another `S6_LOGGING_SCRIPT` variable. All my other services use the `T` option.

**Comment by mikehaertl** [comment]
@robinroestenburg It mostly works now. Apart from one nasty thing: It seems that longer log messages are somehow cut off. Here's an example (names and ip's anonymized):

```
2017-10-18 10:52:19.579047500  Oct 18 08:52:19 postfix/smtpd[949]: NOQUEUE: reject: RCPT from mail.example.com[xx.xx.xxx.xxx]: 450 4.2.0 <demo@example.de>: Recipient address rejected: Greylisted for 300 seconds; from=<mh@example.de> to=<demo@example.de> proto=ESMTP helo=<mail.exa
```

Do you also have this problem? Or maybe any idea what could cause this?

**Comment by mikehaertl** [comment]
Ok, this seems to be a bug with busybox syslogd: https://bugs.launchpad.net/ubuntu/+source/busybox/+bug/1040900

 The weird thing is that it should alreday be fixed in the version I use (1.26.2) - but it isn't. I've verified though, by letting syslogd log to a file (without any s6-log involved) and sending long log messages with `logger`. They are still cut off at about 250 characters. Oh my...

**Comment by robinroestenburg** [comment]
No I don't have that problem. You could try the following to debug:
* stop syslogd service
* start it manually and check if output is truncated
If that output is not truncated then the problem is probably somewhere in the `logutil-service` you are using?

Also, I see you are starting syslogd with `-S` option - which says `Smaller output` in the help. That should not truncate your messages, but might be good to check anyway ;-)

**Comment by robinroestenburg** [comment]
@mikehaertl never mind my previous comment, didn't see your latest comment.

**Comment by mikehaertl** [comment]
@robinroestenburg Hmm, weird that you don't have this issue. Can you maybe try to send a longer syslog message? Here's a test string with some length markers. If you issue this inside the container you should see the message being logged. For me it's cut off around `... 23456 220 23456 230`

```
logger  234567 10 234567 20 234567 30 234567 40 234567 50 234567 60 234567 70 234567 80 234567 90 23456 100 23456 110 23456 120 23456 130 23456 140 23456 150 23456 160 23456 170 23456 180 23456 190 23456 200 23456 210 23456 220 23456 230 23456 240 23456 250 23456 260 23456 270 23456 280
```

**Comment by robinroestenburg** [comment]
@mikehaertl hmm you are right... it is cut off:

```
2017-10-18 09:45:51.747010500  [syslogd] Oct 18 09:45:51 4897bd01dbc9 user.notice root: 234567 10 234567 20 234567 30 234567 40 234567 50 234567 60 234567 70 234567 80 234567 90 23456 100 23456 110 23456 120 23456 130 23456 140 23456 150 23456 160 23456 170 23456 180 23456 190 23456 200 23456 210 23456 220 23456 230
```

**Comment by mikehaertl** [comment]
Ok, as I see it this is a compile time config variable. They've fixed it in the Ubuntu packace but not in alpine.

This brings me back to my original idea to use s6 tools to emulate a syslogd. 

@skarnet Do you maybe have an idea what could have been wrong in my setup?  See my comments above: https://github.com/just-containers/s6-overlay/issues/214#issuecomment-336849787 and https://github.com/just-containers/s6-overlay/issues/214#issuecomment-336857848

**Comment by skarnet** [comment]
Is your container Alpine-based by any chance? it's a known issue with the syslog emulation scripts provided with s6 - they don't work with the musl libc. (Technical details: they listen to `/dev/log` as SOCK_STREAM but musl's `syslog()` only supports SOCK_DGRAM.)

If it's the case, the simplest solution for now is to install [socklog](http://smarden.org/socklog/). Then your `syslogd-linux/run` script can just become `fdmove -c 2 1 fdclose 0 socklog`, and you can use s6-log as your backend, i.e. your `syslogd-linux/log/run` script remains unchanged.

I need to update and modernize the documentation on logging with s6, but stuff with more priority keeps popping up. Sorry about that.

**Comment by mikehaertl** [comment]
> Is your container Alpine-based by any chance?

@skarnet Correct. I've tried socklog and it works, thanks!

Final problem: I still have duplicate timestamp information in the logs now. If you see an easy trick to get rid if this (i.e. how to make socklock ommit the timestamp) please let me know.

```
2017-10-19 08:31:41.535720500  mail.info: Oct 19 06:31:41 postfix/master[963]: daemon started -- version 3.1.4, configuration /etc/postfix
```

**Comment by skarnet** [comment]
The second timestamp is added by the syslog() function itself, there's not much we can do about it.
The first timestamp is added by s6-log. If you want to remove it, look for a `T` character in the logging script at some point before your logging directory. The `T` instruction tells s6-log to add an ISO8601 timestamp; remove that instruction and you won't get the timestamp.
If there's no `T` in your `S6_LOGGING_SCRIPT`, then it may be hardcoded in `syslogd-linux/log/run` or something. Look for it and remove it.

**Comment by mikehaertl** [comment]
I've seen the `S6_LOGGING_SCRIPT` var, but changing this would also affect all other log services. I found no way to only change it for one specific service.

In fact I was hoping to remove the second timestamp with some nifty regex somehow. As we deal with simple text streams I thought, something like this should be easy with s6, no?

**Comment by skarnet** [comment]
Filtering data is always harder than adding data; and s6's focus is process supervision, not text stream manipulation, so it doesn't offer much in the way of filters. You could probably interpose a simple sed script removing syslog's timestamp, but it's still more complex and brittle than telling s6-log not to add its own timestamp.

I would remove `T` from `S6_LOGGING_SCRIPT` and manually add it back to the `log/run` scripts of your other services if you want the timestamp.

**Comment by mikehaertl** [comment]
> You could probably interpose a simple sed script removing syslog's timestamp

That's still the solution I'd prefer (mainly because s6-log's timestamp is correct, while socklog's is off by 1 hour). But no idea how to achieve this. When I read about s6 and how it's based on stdout/stderr I was actually expecting that all kind of filtering etc. would be easy. Just like connecting some shell commands with a pipe.

So I'm surprised to hear that this is very complex.

**Comment by skarnet** [comment]
Oh, it is easy enough. I only mean that adding a filter to your pipeline is more complex, and results in a less efficient pipeline, than not doing it. :-)

To filter out syslog()'s timestamp: in your `log/run` script, add the following line just before the `s6-log` invocation:
`pipeline { filter }` (the spaces are important!)
replacing `filter` with the command you'd use to filter out the timestamp, such as: `sed s/timestamp_regex//`, or an awk script, or whatever you want.

**Comment by mikehaertl** [comment]
Sorry, I still have issues. It seems the command accepted in `pipeline { }` must be escaped somehow:

```
#!/bin/execlineb -P

pipeline { /usr/bin/cut -d' ' -f 1-4,8- }
logutil-service /logs/syslog
```

```
cut: ': No such file or directory
```

**Comment by skarnet** [comment]
execline does not use (or need) simple quotes. Use `-d" "`.

**Comment by mikehaertl** [comment]
Ok, great it finally works now, thanks.

@jprjr Maybe worth adding a section to the README about all this? Here's my final setup:

**/etc/services.d/socklog/run/**

```
#!/bin/execlineb -PW
fdmove -c 2 1 fdclose 0 socklog
```

**/etc/services.d/socklog/log/run**

```
#!/bin/execlineb -P
pipeline { /usr/bin/cut -d" " -f 1-4,8- }
logutil-service /logs/syslog
```

**Comment by mikehaertl** [comment]
@skarnet Sorry, I was wrong: It does not work. I seems to process only one single line through `cut`:

```
2017-10-31 11:54:18.590917500  listening on /dev/log, starting.
```

Then it continues and logs duplicate timestamps as before:

```
2017-10-31 11:56:26.341622500  mail.info: Oct 31 10:54:18 v2.10.3 starting (args: -x /etc/opendkim/opendkim.conf)
2017-10-31 11:56:26.341643500  mail.info: Oct 31 10:54:18 v2.2.27 (c0f36b0) starting up for imap, lmtp, sieve
```

The weird part is, that the first few log messages are logged with a 2 min delay (note the different timestamps).

All this is probably because I don't call `s6-log` directly but `logutil-service` instead. I start to wonder if it really was a good idea to use s6-overlay for my little project :).

**Comment by skarnet** [comment]
Sigh. Indeed, my solution assumed that the output of `cut` would be piped directly into `s6-log`. I don't know how to do it with `logutil-service`, maybe @jprjr or @glerchundi would. But really, you don't need `logutil-service` to log socklog's output. Just use `s6-log T n20 s1000000 /logs/syslog` and you should be set. Or maybe just `logutil-service-main /logs/syslog` works - it should.

 s6-overlay is practical, but like every integrated solution and abstraction, it shows its limits when you're trying to do something it hasn't planned for. That's why I always consider it best to still know how the underlying tools work - so you can assemble them together the way you want if the upper layer glue isn't fitting your needs.

**Comment by mikehaertl** [comment]
Ok, thanks for your patience. But yet again, things don't play out well. I've found, that `cut` is the wrong tool here as I wrongly assumed a fixed position for the date, which is simply not the case. So I want to use `sed`.

Now for some reason a regex that works just fine outside of s6 does not work when used in the `log/run` script. For testing I've stripped it down:

```
#!/bin/execlineb -P
pipeline { /bin/sed "s/ [A-Z][a-z]\{2\} / /" }
s6-log T n20 s1000000 /logs/syslog
```

This should remove any ` Jan `, ` Feb `, ... from the log string. It works fine on the command line (`tail logs/syslog/current | sed "s/ [A-Z][a-z]\{2\} / /"`) but in the log script it does nothing. The string is logged unchanged.

So anything I'm missing here again? Maybe `[` or something are again not allowed inside execlineb? Or is there a problem with escape sequences like `\{`? If so, I'm really close to giving up because if this is the case the script becomes basically unmaintanable in the future. No one will ever want to touch this again to not break this fragile thing.

**Comment by skarnet** [comment]
This has nothing to do with s6. This is about how the `execlineb` script parser, documented [here](https://skarnet.org/software/execline/execlineb.html), works.
execlineb's quoting is simple and logical, it's not fragile at all, but precisely in order to be simple and logical, it sometimes deviates from the shell's syntax, which is ad-hoc and laden with special cases.
Here, your issue is that execlineb can escape *any* character with `\`, so if you want a literal backslash in the argument to sed, you need to duplicate it in an execline script. So your `\{` and `\}` should be written `\\{` and `\\}` respectively. And unless I'm missing something, there's no reason it shouldn't work if you make that small change.

You may want to ask "but then why can't I just use a shell?" and the answer is: *you can*. You can write run scripts in any language you want, including a shell. However, in your precise case, I do not recommend it, because shells cannot create a pipeline and exec into one of the branches of the pipeline. If you wrote something like
```sh
#!/bin/sh
/bin/sed "s/ [A-Z][a-z]\{2\} / /" | exec s6-log T n20 s1000000 /logs/syslog
```
the "exec" would be ignored, and you would find yourself with a shell process with both a sed child and a s6-log child. Which means at shutdown time, s6 would send signals to the shell, not to the s6-log process, which is not what you want; it would essentially be impossible to correctly shut down your syslogd service (and that would be true with any supervision suite or service manager, not just s6). By contrast, execline allows you to create a pipeline and have your process *execute into* s6-log, which is exactly what you need here.

So, I'm sorry if things feel complex to you, but it's not gratuitous, and all your difficulties come from a lack of practice with the tools. You would likely run into similar trouble with any tool you're not familiar with, and it is the unfortunate state of Unix that the tools everyone is familiar with (shell scripting in the present case) are lacking in subtle but significant ways.

**Comment by jprjr** [comment]
I've gone ahead and created an "add-on" module, `socklog-overlay` https://github.com/just-containers/socklog-overlay

It's basically a pre-configured instance of `socklog` + `s6-log` that *should* work on any distribution.

I don't want to add it into mainline `s6-overlay`, since I feel it's somewhat outside the scope of the `s6-overlay` to provide syslog functionality (and for all I know, somebody's already made their own `socklog` server that I could be stomping on).

Most sysadmins need to configure logging for their specific use-case. The `socklog-overlay` isn't particularly configurable, but it at least provides a starting point - anybody can modify the `run` scripts for their use-case.

I'll update the main README to point to `socklog-overlay`

**Comment by mikehaertl** [comment]
@skarnet Ok, it finally works now (phew). Here's my final `log/run` script:

```
#!/bin/execlineb -P

# Strip socklog's additional timestamp
# Note: execlineb requires \ to be escaped as \\ and strings to be surrounded by " not '
pipeline { /bin/sed "s/[A-Z][a-z][a-z] \\+[1-3]\\?[0-9] [0-2][0-9]:[0-5][0-9]:[0-5][0-9] //" }
s6-log T n20 s1000000 /logs/syslog
```

A final and very personal (and OT) note about my experience with s6 as a beginner:

> This is about how the execlineb script parser, documented here, works.

Believe me, I really tried hard to learn about all the s6 tooling.

You should know that all I wanted was a quick and painless solution to run multiple processes in a container for a little mail server side project of mine. What looked like a perfect fit at first glance turned out to become not so easy after a while. After some problems (don't remember which) I first spent a whole evening wading through a mass of man pages and other documentation on your site. Most of it made sense, but I remember often missing useful real life examples (e.g. Logging scripts with `s6-log` - it sounds powerful but some real world examples would help tremendously what they are for)

I soon found out that I should probably learn some execlineb. How hard could it be? I already understood the basic principle (a command always executes into the next command).  But on the page you linked (which already is the most introductory I assume?) right in the beginning you are attacked by sentences like:

> Pushing the current stack frame. If none of the -p, -P, -S or -s options is set: execlineb pushes the current positional parameters, i.e. environment variables that start with #, 0, 1, ..., 9. To get the previous values back, use emptyenv -P.

Uuuh, OK?? At that point I knew that it would require again a lot of time in absolute concentration and reading every sentence at least twice to get the meaning. And there where dozens more pages for execlineb ahead! And no "Getting started" or something that would start with a simple example and take you by the hand. 

So I finally gave up  frustratetly and felt stupid. :) Again: This is just my personal view.

**Comment by skarnet** [comment]
Yes, I'm aware that the documentation needs improvement. Unfortunately, there are so many projects that I want to prioritize over making a rewriting pass at existing docs :-/
 Thanks for your return of experience, it really helps identifying what the pain points are in the documentation and where the focus should be when I finally get to improving it.

**Comment by trinitronx** [comment]
> Pushing the current stack frame. If none of the -p, -P, -S or -s options is set: execlineb pushes the current positional parameters, i.e. environment variables that start with #, 0, 1, ..., 9. To get the previous values back, use emptyenv -P.

This one was a bit confusing to me too.  Seems simple in principle when you understand how C function calls, or other programming languages work by pushing local variables onto the stack frame.

Could use maybe a couple images (or ASCII art) to show what happens.  The other part in the docs has some extra clarifying info: [Pushing and popping the environment][1].

[1]: https://skarnet.org/software/execline/el_pushenv.html
