### ISSUE TITLE
Update README to point to the latest version

### ISSUE THREAD

**Issue by mikehaertl** [just-containers/s6-overlay#215]
I've followed the README to install s6-overlay on an image. Unfortunately the instructions there contain a link to an outdated version:

```
ADD https://github.com/just-containers/s6-overlay/releases/download/v1.11.0.1/s6-overlay-amd64.tar.gz /tmp/
RUN tar xzf /tmp/s6-overlay-amd64.tar.gz -C /
```

This lead to lot of headaches some examples I found did not work (See #214). I spent quite some time until I discovered this.

So an updated README would be nice.

**Comment by jprjr** [comment]
Done and done!
