### ISSUE TITLE
s6-overlay overrides workdir

### ISSUE THREAD

**Issue by JonathanSerafini** [just-containers/s6-overlay#219]
Today I updated from _v1.19.1.1_ to _v1.21.1.0_ and am running to the case where the CMD isn't being run within the WORKDIR defined in the Dockerfile. Instead, I seem to find myself within /run/s6/services/docker-cmd.

```
root@0a7b268ccd90:/run/s6/services/docker-cmd# find .
.
./run
./event
./supervise
./supervise/control
./supervise/status
./supervise/lock
./down
./cmd
./finish
```

**Comment by jprjr** [comment]
Pushed up tag v1.21.1.1, which should fix that - the working directory is saved early in the init, and restored when running the CMD

**Comment by JonathanSerafini** [comment]
Thank you kindly !
