### ISSUE TITLE
Name based chown in fix-attrs.d does not work

### ISSUE THREAD

**Issue by mikehaertl** [just-containers/s6-overlay#220]
I have to come back to #97 as the solution there does not seem to work for me.

I don't know why this is, but I can not use user or group names but always need to specify the numeric id.

```
/var/mail/domains true vmail:root,102:0 0755 0755
```

The hardcoded uid makes it extremely error prone. It's very easy that the uid changes during the lifetime of a project. For example a new package that you install could add another user. You always have to remember to go over all files in `fix-attrs.d` afterwards and fix the numeric user and group ids.

**Comment by jprjr** [comment]
Can you come up with some dockerfile that demonstrates this behavior?

I just made:

```Dockerfile
FROM busybox

ADD https://github.com/just-containers/s6-overlay/releases/download/v1.21.4.0/s6-overlay-amd64.tar.gz /tmp/
RUN tar xzf /tmp/s6-overlay-amd64.tar.gz -C /

RUN adduser -S -H vmail

RUN mkdir -p /var/mail/domains

COPY root /

ENTRYPOINT ["/init"]
```

And my file in `root/etc/fix-attrs.d/mail`:

```
/var/mail/domains true vmail:root 0755 0755
```

Finally:

```bash
john@lxle-virt ~/tmp $ docker build -t test .
Sending build context to Docker daemon  17.41kB
Step 1/7 : FROM busybox
 ---> f6e427c148a7
Step 2/7 : ADD https://github.com/just-containers/s6-overlay/releases/download/v1.21.4.0/s6-overlay-amd64.tar.gz /tmp/
Downloading [==================================================>]  1.699MB/1.699MB
 ---> d30d58ed1b3b
Step 3/7 : RUN tar xzf /tmp/s6-overlay-amd64.tar.gz -C /
 ---> Running in 7a6b1ceac15e
tar: skipping unsafe symlink to '/bin/execlineb' in archive, set EXTRACT_UNSAFE_SYMLINKS=1 to extract
Removing intermediate container 7a6b1ceac15e
 ---> 0c51480ab5e0
Step 4/7 : RUN adduser -S -H vmail
 ---> Running in 3ad90b6f1b88
Removing intermediate container 3ad90b6f1b88
 ---> 82e81f8c7c1d
Step 5/7 : RUN mkdir -p /var/mail/domains
 ---> Running in 634a60f39574
Removing intermediate container 634a60f39574
 ---> 91a9167b0579
Step 6/7 : COPY root /
 ---> 22fda20f3b0c
Step 7/7 : ENTRYPOINT ["/init"]
 ---> Running in fc0e2aaff6a4
Removing intermediate container fc0e2aaff6a4
 ---> e5d022f768e8
Successfully built e5d022f768e8
Successfully tagged test:latest
john@lxle-virt ~/tmp $ docker run --rm -ti test ls -lh /var/mail
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] mail: applying... 
[fix-attrs.d] mail: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
total 4
drwxr-xr-x    1 vmail    root        4.0K Mar 14 15:45 domains
[cmd] ls exited 0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

Everything seems to be working correctly.

**Comment by mikehaertl** [comment]
It's a long time since I reported this. I tried to reproduce my problem locally but couldn't. This is quite weird because I remember that this issue gave me some big headaches. I think it always complained about "could not find user" or something if I didn't supply a numeric uid/gid. In the end I created a `cont-init.d/00-fix-permissions` script and never looked back.

Actually I still wonder, what's the advantage of using `fix-attrs.d`. With a custom script I can use regular `chown` commands that are well-known and work reliably for me. Whereas with `fix-attrs.d` I'd have to learn a new syntax - which always left me with an uncertain feeling ("will this really always do what I want?").

**Comment by jprjr** [comment]
Yeah, I think the main use-case for `fix-attrs.d` is if you're making an *extremely* minimal image, without coreutils/busybox, or even `/bin/sh`. `s6-chown` doesn't have a recursive option, so in those use-cases using `fix-attrs.d` is useful.

For most other cases, though - you have GNU coreutils or busybox anyway. I regularly fix permissions in `cont-init.d` as well, to be honest - I usually need to make sure whatever directory tree exists because it may be a volume with nothing in it, and `fix-attrs.d` doesn't support making directories.

**Comment by mikehaertl** [comment]
Makes sense, thanks.

I think you can then close this issue.
