### ISSUE TITLE
Alpine: "s6-test: fatal: parse error at argument 0"

### ISSUE THREAD

**Issue by ppmathis** [just-containers/s6-overlay#222]
Running Alpine 3.6 containers with the S6 overlay prints an error (*s6-test: fatal: parse error at argument 0*) when **CMD** is either being specified within the Dockerfile or as a command line argument when executing **docker run**:

```
FROM alpine:3.6

ENV S6_OVERLAY_VERSION=v1.21.2.1

RUN apk add --no-cache ca-certificates wget \
	&& wget -O /tmp/s6-overlay.tar.gz https://github.com/just-containers/s6-overlay/releases/download/${S6_OVERLAY_VERSION}/s6-overlay-amd64.tar.gz \
	&& tar xzf /tmp/s6-overlay.tar.gz -C / \
	&& rm -f /tmp/s6-overlay.tar.gz \
	&& apk --no-cache del ca-certificates wget

ENTRYPOINT ["/init"]
CMD ["/bin/sh"]
```

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
s6-test: fatal: parse error at argument 0
/ # 
```

This issue only occurs with **v1.21.2.1**, the old release **v1.21.2.0** does not have that issue. I assume this bug was introduced with either 0f7a212ada723d687fdedbf0672b20e1bad91aae or 8983527b975101519c7454e02f5f41d5522dc7ca, as not specifying any command does not print that error message.

**EDIT:** I did some further testing and this seems to occur with Debian images as well. Am I using s6-overlay wrong in some kind of way or is this a generic bug? Running *Docker version 17.10.0-ce, build f4ffd2511c* on my host system.

**Comment by frenck** [comment]
Confirmed. I have the same issue.

**Comment by bborysenko** [comment]
The same issue for me, but with v1.21.2.0 I get this error:

```
docker run --rm -it  nginx-php-fpm:1.13-7.1 sh
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
sh: can't access tty; job control turned off
/ #
```

**Comment by jjlorenzo** [comment]
this https://github.com/just-containers/s6-overlay/pull/224 fix in my case, I'm still new to s6 so probably I miss something
