### ISSUE TITLE
No such file or directory sh

### ISSUE THREAD

**Issue by nskforward** [just-containers/s6-overlay#226]
**Created "run" file:**
`#!/usr/bin/with-contenv sh`
`exec nginx;`

**When I start container I see the following errors:**

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
: No such file or directory sh
: No such file or directory sh

**Using of full path (/bin/sh) does not help**

**Full Dockerfile:**

FROM nskforward/php:7.2.1
ENV S6_OVERLAY_RELEASE v1.21.2.2
RUN apk add --no-cache nginx && \
	ln -sf /dev/stdout /var/log/nginx/access.log && \
	ln -sf /dev/stderr /var/log/nginx/error.log
RUN curl -sL -o /tmp/s6-overlay-amd64.tar.gz https://github.com/just-containers/s6-overlay/releases/download/${S6_OVERLAY_RELEASE}/s6-overlay-amd64.tar.gz && \
    tar zxf /tmp/s6-overlay-amd64.tar.gz -C / && \
	rm -f /tmp/s6-overlay-amd64.tar.gz
ADD s6 /etc/services.d
COPY nginx.conf /etc/nginx/nginx.conf
COPY index.php /app/index.php
ENTRYPOINT ["/init"]
CMD [];
EXPOSE 80 443

**Comment by xmik** [comment]
This may happen due to this: https://github.com/just-containers/s6-overlay#bin-and-sbin-are-symlinks . `/bin/sh` was deleted while installing s6-overlay.

**Comment by jprjr** [comment]
@xmik is exactly right - you'll have to do the 2-step extraction to keep from deleting /bin
