### ISSUE TITLE
How to automatically add app/service name to stdout/stderr logs?

### ISSUE THREAD

**Issue by Labutin** [just-containers/s6-overlay#228]
How to automatically add app/service name to stdout/stderr logs?

**Comment by jprjr** [comment]
That's really a pretty open-ended question with a lot of possible solutions. Here's one way to do it in your run script:

```bash
#!/bin/sh
set -eo pipefail

fdmove -c 2 1 \
/usr/bin/some-service | awk '{print "[some-service] " $0}'
```

That will use awk to prepend all lines of output with `[some-service] `

**Comment by fensoft** [comment]
i've added `-W interactive` to awk to avoid stdout caching
