### ISSUE TITLE
s6-svc -k doesn't kill child procs like it should??

### ISSUE THREAD

**Issue by danshumaker** [just-containers/s6-overlay#229]
Hi,
In trying to simulate a kill or fail of my supervised app I'm running
```
s6-svc -k /var/run/s6/services/pal_dpub
```
within the docker container.   I monitor what's going on via two while loops in bash
```
while(true); do s6-svstat /var/run/s6/services/pal_dpub; sleep 1; done
```
and 
```
while(true); do ps -eaf; sleep 1; done
```

While those two loops are running I can watch what the svc -k command does.  And what it does is kill the parent process and not the running app child that I care about.

For example:  ps output
```
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 Feb16 ?        00:00:00 s6-svscan -t0 /var/run/s6/services
root        32     1  0 Feb16 ?        00:00:00 s6-supervise s6-fdholderd
root       265     1  0 Feb16 ?        00:00:00 s6-supervise pal_dpub/log
root       266     1  0 Feb16 ?        00:00:00 s6-supervise pal_dpub
nobody     270   265  0 Feb16 ?        00:00:00 s6-log -bp -- n20 s10000000 /var/log/services/pal_dpub
root       303     0  0 Feb16 pts/0    00:00:01 bash
root       339     0  0 Feb16 pts/1    00:00:01 bash
root      3531   266  0 Feb16 ?        00:00:00 sh ./run
root      3533  3531  0 Feb16 ?        00:00:00 node src/app.js --redis-host=pal_redis --publisher-port=7070
root     11803   339  0 00:04 pts/1    00:00:00 ps -eaf
```

What happens is that proc 3531 gets killed but 3533 sticks around.  Then as expected, s6-overlay detects the process (3531) is down and tries to restart it, but then, as you can imagine, the app (3533) still has the port locked (in this case 7070) and the newly started app fails and says the resource is busy.

So, do I have my run script wrong?  Do I have my kill command wrong (of the 25 options listed here: http://skarnet.org/software/s6/s6-svc.html )?  What am I missing, because I know this can't be the expected behavior to only kill parents and not child procs.  Or maybe that assumption is wrong too?

 My run script is:
```
#!/usr/bin/with-contenv sh
cd /usr/src/pal
node src/app.js --redis-host=pal_redis --publisher-port=$PAL_DRUPAL_PUB_PORT
```

Should I be using execlineb or something?  Thanks for any help, examples, documentation etc.

I thought about punting the s6-overlay and just moving to let docker's CMD proc management take over (using https://docs.docker.com/engine/reference/builder/#healthcheck  and https://docs.docker.com/engine/reference/commandline/run/#restart-policies-restart ), but I really don't want to have restart a container because of the flightyness of the running procs within the container because I plan to have several monitors connected to the runing containers and a restart of the container will break/disconnect those monitors.

Thanks again.

**Comment by jprjr** [comment]
Since you're not `exec`-ing into node, it's running as a child process of your run script. So the KILL signal gets sent to "./run", but it's not propagated to any children processes (and as far as I know, `SIGKILL` is never propagated - `sh` would have to catch it and propagate it, but it cant since you can't catch and react to `SIGKILL`

Try this as your run script:

```bash
#!/usr/bin/with-contenv sh
cd /usr/src/pal
exec node src/app.js --redis-host=pal_redis --publisher-port=$PAL_DRUPAL_PUB_PORT
```

**Comment by danshumaker** [comment]
Many thanks @jprjr That did the trick.  Sorry for the delay in response.

**Comment by sadwxqezc** [comment]
That works! Thanks very much!
