### ISSUE TITLE
Interactive process issues

### ISSUE THREAD

**Issue by p3lim** [just-containers/s6-overlay#230]
Hey, I'm trying to run [WeeChat](https://weechat.org/) under Alpine and s6-overlay, and I'm having issues where if I attach to the container it only flashes the WeeChat UI.

> You can even run interactive programs under the s6 supervisor!

I assumed with that in the readme for this project that this should be possible.

My Dockerfile:
```Dockerfile
FROM p3lim/alpine:3.7 # this is just alpine + s6-overlay and creates a user "abc"
RUN apk add --no-cache weechat
COPY root/ / # this adds the service.d directory
```

And the service:
```bash
#!/usr/bin/with-contenv bash
exec s6-setuidgid abc /usr/bin/weechat
```

If I build that image and run it, then attach to it (`docker attach weechat`) it just flashes the UI repeatedly.

**Comment by jprjr** [comment]
Weechat is expecting to be connected to a terminal, when you run as a service it won't be connected to one.

I'd run weechat as a `CMD` instead, like:

```
FROM p3lim/alpine:3.7
RUN apk add --no-cache weechat

ENV HOME /config
WORKDIR /config

CMD ["/usr/bin/with-contenv","s6-setuidgid","abc","/usr/bin/weechat"]
```

**Comment by jprjr** [comment]
I did figure out a way to run weechat as a service, but using `docker attach` doesn't work very well - you have to hit `ctrl-L` once attached to force weechat to redraw the screen, and it doesn't detect when you resize your terminal window (you have to hit `ctrl-L` again).

Here is how you can do it, though:


```Dockerfile
FROM p3lim/alpine:3.7
RUN apk add --no-cache weechat

COPY root /
```

Then have a cont-init.d file to save the stdout and stderr file descriptors (`root/etc/cont-init.d/999-save-fds`):

```
#!/usr/bin/execlineb

if { s6-svc -u -wU /var/run/s6/services/s6-fdholderd }
if { s6-fdholder-store -d 1 /var/run/s6/fdholderd-socket init-stdout }

s6-fdholder-store -d 2 /var/run/s6/fdholderd-socket init-stderr
```

Then in the run script:

```
#!/usr/bin/with-contenv /usr/bin/execlineb

backtick -n HOME { homeof abc }
importas HOME HOME

cd $HOME

s6-fdholder-retrieve -t 5000 /var/run/s6/fdholderd-socket init-stdout
fdmove -c 0 1
s6-fdholder-retrieve -t 5000 /var/run/s6/fdholderd-socket init-stderr
fdmove -c 0 2
s6-setuidgid abc
/usr/bin/weechat
```

You don't have to use execlineb as your run script, you can also use bash. You just need to make sure everything is chained into one big command:

```bash

exec \
s6-fdholder-retrieve -t 5000 /var/run/s6/fdholderd-socket init-stdout \
fdmove -c 0 1 \
s6-fdholder-retrieve -t 5000 /var/run/s6/fdholderd-socket init-stderr \
fdmove -c 0 2 \
s6-setuidgid abc \
/usr/bin/weechat
```

I'd probably just go with using it as your CMD though, it's a lot simpler and still gets to run under the s6 supervisor.

**Comment by p3lim** [comment]
Much obliged, I went with the first solution as attaching is the whole point of the container, having odd behavior is not something I'd enjoy much.
On the plus side, everything in `/etc/cont.init.d` still runs with that example 👍
