### ISSUE TITLE
logutil-newfifo hangs on s6-uniquename command

### ISSUE THREAD

**Issue by robinroestenburg** [just-containers/s6-overlay#234]
I have a cont-init.d script that creates a new log fifo using the `logutil-newfifo` script. This script uses the `s6-uniquename` command.

When I start the container, it hangs on the `s6-uniquename` command - that is consuming 100% CPU. 

Running the `s6-uniquename` command in the container also hangs.

Anyone have this problem before?

I am running Alpine 3.6.2 on RHEL btw.

**Comment by robinroestenburg** [comment]
Running `strace -c -f -p <id>` tells me it is spending all the time in `getrandom` function.

Running `strace -T -e "stat" -s 2048 -p <id>` shows the following log:
![screen shot 2018-05-07 at 14 25 10](https://user-images.githubusercontent.com/693266/39701723-8825dfac-5202-11e8-983d-4f979f68db88.png)

I will investigate further - probably a specific issue for this environment.

**Comment by jprjr** [comment]
Which version of RHEL?

On May 7, 2018 8:26:13 AM EDT, Robin Roestenburg <notifications@github.com> wrote:
>Running `strace -c -f -p <id>` tells me it is spending all the time in
>`getrandom` function.
>
>Running `strace -T -e "stat" -s 2048 -p <id>` shows the following log:
>![screen shot 2018-05-07 at 14 25
>10](https://user-images.githubusercontent.com/693266/39701723-8825dfac-5202-11e8-983d-4f979f68db88.png)
>
>I will investigate further - probably a specific issue for this
>environment.
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/just-containers/s6-overlay/issues/234#issuecomment-387048636

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by robinroestenburg** [comment]
CentOS 7.0 actually.

I found the problem: the kernel of the docker hosts was outdated. It did not support the `getrandom` system call. This was added in kernel 3.17, I am not sure in which kernel patch it was added though. It was running `3.10.0-514.26.2.el7-x86-64`, upgrading to `3.10.0-693.21.1.el7.x86_64` fixed it.
