### ISSUE TITLE
s6-envuidgid : not droping privilege

### ISSUE THREAD

**Issue by mikafouenski** [just-containers/s6-overlay#235]
Hello,

The program `s6-envuidgid` doesn't drop privilege to desired user.

Step to reproduce:
```
$ docker run --rm -it quay.io/justcontainers/base-alpine sh
$ adduser -HD test
$ s6-envuidgid test id
uid=0(root) gid=0(root) groups=0(root) .....
```
When the command `id` is executed you see root user !

**Comment by mikafouenski** [comment]
Oh ok, didn't see it that way. I'm going for the combo. 
Thanks. :+1:

**Comment by XodgvmXwaCdfTN6Q4DJdsm4a** [comment]
Can someone dumb this down a little bit more? I am trying to start a service/program/app as root on port 443 and then drop/change to a limited user. For the life of me I am not getting it to work. I can be root or USER just not dropping/changing like I would like.

Thanks,
Michael

**Comment by skarnet** [comment]
You need support from your web server itself in order to do that. You should start the service as root, and tailor your web server's configuration or command-line options to drop root privileges to a normal user.

**Comment by XodgvmXwaCdfTN6Q4DJdsm4a** [comment]
> drop root privileges to a normal user

That is what I don't understand. I have tried s6-envuidguid s6-appyuidguid s6-setuidguid.
my app is configured for the port. When I try and drop privileges to a normal user the app does not have access to the privileged port.

**Comment by XodgvmXwaCdfTN6Q4DJdsm4a** [comment]
/etc/s6-overlay/s6-rc.d/svc-sonarr/run 
#!/usr/bin/with-contenv bash
# shellcheck shell=bash

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 80" \
        cd /app/sonarr/bin s6-envuidgid abc /app/sonarr/bin/Sonarr \
        -nobrowser -data=/config

`ps axu
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0    192     8 ?        Ss   Feb07   0:00 /package/admin/s6/command/s6-svscan -d4 -- /run/service
root        15  0.0  0.0    196     8 ?        S    Feb07   0:00 s6-supervise s6-linux-init-shutdownd
root        17  0.0  0.0    184     0 ?        Ss   Feb07   0:00 /package/admin/s6-linux-init/command/s6-linux-init-shutdownd -
root        37  0.0  0.0    196     8 ?        S    Feb07   0:00 s6-supervise s6rc-oneshot-runner
root        38  0.0  0.0    196     8 ?        S    Feb07   0:00 s6-supervise s6rc-fdholder
root        39  0.0  0.0    196     8 ?        S    Feb07   0:00 s6-supervise svc-sonarr
root        47  0.0  0.0    172     0 ?        Ss   Feb07   0:00 /package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s
root       143  1.0  1.1 2619156 187440 ?      Ssl  Feb07  16:17 /app/sonarr/bin/Sonarr -nobrowser -data=/config
root      9406  0.0  0.0   2652  1776 pts/0    Ss   00:33   0:00 bash`

but it runs as ROOT

**Comment by nekopsykose** [comment]
`s6-envuidgid abc` doesn't drop perms to `abc`, you want `s6-setuidgid` for what you are trying to express there.

(it probably won't work for other reasons, but that is a start)

**Comment by jprjr** [comment]
The order matters here.

When you use the s6 apps to change to a normal user - you're doing that *before* starting the app.

So now the app is running as a normal user - tries to open a privileged port - and fails.

You have to open the port as root - then change user. This usually requires support in the application using the port.

There are some apps that allow you to use an already-opened port, so you could use s6-tcpserver4-socketbinder to open the port, then s6-setuidgid to drop privileges, then run the app. But it requires support from the app.

I usually just run apps on some non-privileged port, and run some kind of proxy in front like nginx, haproxy, etc.
