### ISSUE TITLE
s6-overlay keeps restarting perl application fhem

### ISSUE THREAD

**Issue by trasba** [just-containers/s6-overlay#241]
Hi,

I have an odd behavior in my docker container. I want to start an application (fhem) with s6.
In the end the application is started and running but in the logfile I see that every second there is a second instance of the application trying to start. It can't because the ports are already in use and this goes on all the time.
Here is my code /etc/services.d/fhem/run:

```
#!/usr/bin/with-contenv bash

cd /opt/fhem || exit

exec \
        s6-setuidgid <user> perl /opt/fhem/fhem.pl /opt/fhem/fhem.cfg
```

What I see is that there is a process perl... that was not startet from s6-supervise and s6-supervise is the one constantly trying to start the second perl session.
However if I build my image without the fhem/run file no perl session is startet. So I believe this to be connected with each other.
From the PPID it seems as if s6-svscan started the first perl session. Any suggestions on how I could find out what the issue is?
```
root@f3b8dc750bab:/# ps axjf
 PPID   PID  PGID   SID TTY      TPGID STAT   UID   TIME COMMAND
    0   197   197   197 pts/0     2171 Ss       0   0:00 /bin/bash
  197  2171  2171   197 pts/0     2171 R+       0   0:00  \_ ps axjf
    0     1     1     1 ?           -1 Ss       0   0:00 s6-svscan -t0 /var/run/s6/services
    1    33     1     1 ?           -1 S        0   0:00 s6-supervise s6-fdholderd
    1   249     1     1 ?           -1 S        0   0:01 s6-supervise fhem
  249  2169  2169  2169 ?           -1 Rs       0   0:00  \_ perl /opt/fhem/fhem.pl /opt/fhem/fhem.cfg
    1   267   252   252 ?           -1 S     1000   0:01 perl /opt/fhem/fhem.pl /opt/fhem/fhem.cfg
```
PS: I have another application/docker image where this setup runs smoothly. I have this issue only with fhem.
Thanks for your time.

**Comment by amannocci** [comment]
Hello @trasba,
Can you try to run the same script without the `exec` part of the command ?
```bash
#!/usr/bin/with-contenv bash
cd /opt/fhem || exit
s6-setuidgid <user> perl /opt/fhem/fhem.pl /opt/fhem/fhem.cfg
```

Just to see what the script do usually in normal condition.

**Comment by trasba** [comment]
> Hello @trasba,
> Can you try to run the same script without the `exec` part of the command ?
> 
> ```shell
> #!/usr/bin/with-contenv bash
> cd /opt/fhem || exit
> s6-setuidgid <user> perl /opt/fhem/fhem.pl /opt/fhem/fhem.cfg
> ```
> 
> Just to see what the script do usually in normal condition.

Hi @amannocci,
thanks for your suggestion. I tried it and the result was the same.
However your reply reminded me of this issue and I investigated a little further.
I believe my issue is a duplicate of issue #147. It seems as if the process returns immediately so S6 thinks it exited and re-spawns it.

I modified the fhem config to create a pid file. I created a short script that starts fhem and checks for the pid file, if the pid file is missing it exits. And finally I made S6 start this script not fhem directly.

Find the code below:

/opt/fhem/fhem.cfg: (added)
`attr global pidfilename /opt/fhem/fhem.pid`

/opt/fhem/runfhem.sh: (new file)
```
#! /usr/bin/env bash
# Runs FHEM in foreground for s6-overlay

set -eu

pidfile="/opt/fhem/fhem.pid"
cd /opt/fhem
command=perl

# Launch daemon
$command fhem.pl fhem.cfg
sleep 2

# Loop while the pidfile and the process exist
while [ -f $pidfile ] ; do
    sleep 0.5
done
exit 1000 # exit unexpected
```

/var/run/s6/services/fhem/run: (modified)
```
#!/usr/bin/with-contenv bash

cd /opt/fhem || exit

exec \
        s6-setuidgid abc /opt/fhem/runfhem.sh
```
Note: abc is the user in my case.

For me this issue is solved and I'll close it. I hope we can help someone else with this.
