### ISSUE TITLE
Service not-started at start (using service.d/X/down) does not log to stdout once started

### ISSUE THREAD

**Issue by sgtsquiggs** [just-containers/s6-overlay#247]
Hi,

I've got a service I'm starting conditionally w/ `s6-svc -u /run/s6/services/myservice` but it does not seem to log to stdout (so docker gathers it) when I do this. If I remove `/etc/services.d/myservice/down` and let it start w/ CMD it logs to stdout fine.

Is this intended behavior? I have S6_LOGGING=0.

**Comment by jprjr** [comment]
It should be going to stdout, which is what happens in my small demo:

## Dockerfile:

```Dockerfile
FROM alpine:3.7

ADD https://github.com/just-containers/s6-overlay/releases/download/v1.21.8.0/s6-overlay-amd64.tar.gz /tmp/
RUN tar xzf /tmp/s6-overlay-amd64.tar.gz -C /

COPY root /
ENTRYPOINT ["/init"]
```

## Contents of the copied-in "root" folder:
```
jprjr s6-test $ tree root
root
└── etc
    └── services.d
        └── some-service
            ├── down
            └── run

3 directories, 2 files
```

## And the `run` file:

```
#!/bin/sh

echo "Hey there"
sleep 10
```

I ran:

```
docker build -t test . 2>/dev/null # make sure I'm not seeing stderr, just stdout
docker run --rm test
```

Then, in another shell:

```
docker exec -ti $(docker ps -q) s6-svc -u /var/run/s6/services/some-service
```

And I saw the text "Hey there" start repeating in my terminal running Docker.
