### ISSUE TITLE
Errors with su-exec $UID:$GID

### ISSUE THREAD

**Issue by LM1LC3N7** [just-containers/s6-overlay#251]
Hello,

I am using [this Dockerfile](https://github.com/Wonderfall/docker-rtorrent-flood) to start a container with rtorrent.
And I can't understand why, but there an error generated when `s6-svscan` is started.

This command is used to start `s6-svscan` with user rights ([source](https://github.com/Wonderfall/docker-rtorrent-flood/blob/master/rootfs/usr/local/bin/run.sh)):
```bash
exec su-exec $UID:$GID /bin/s6-svscan /etc/s6.d
```

The error generated is:
```bash
Error loading shared library libs6.so.2.7: Permission denied (needed by /bin/s6-svscan)
Error loading shared library libskarnet.so.2.6: Permission denied (needed by /bin/s6-svscan)
Error relocating /bin/s6-svscan: strerr_diesys: symbol not found
Error relocating /bin/s6-svscan: selfpipe_init: symbol not found
Error relocating /bin/s6-svscan: tain_add: symbol not found
Error relocating /bin/s6-svscan: tain_less: symbol not found
Error relocating /bin/s6-svscan: fd_read: symbol not found
Error relocating /bin/s6-svscan: strerr_warn: symbol not found
Error relocating /bin/s6-svscan: fd_close: symbol not found
Error relocating /bin/s6-svscan: iopause_stamp: symbol not found
Error relocating /bin/s6-svscan: tain_addsec: symbol not found
Error relocating /bin/s6-svscan: tain_now: symbol not found
Error relocating /bin/s6-svscan: child_spawn0: symbol not found
Error relocating /bin/s6-svscan: s6_supervise_lock: symbol not found
Error relocating /bin/s6-svscan: strerr_warnsys: symbol not found
Error relocating /bin/s6-svscan: pipe_internal: symbol not found
Error relocating /bin/s6-svscan: waitpid_nointr: symbol not found
Error relocating /bin/s6-svscan: selfpipe_read: symbol not found
Error relocating /bin/s6-svscan: sig_name: symbol not found
Error relocating /bin/s6-svscan: selfpipe_trapset: symbol not found
Error relocating /bin/s6-svscan: tain_from_millisecs: symbol not found
Error relocating /bin/s6-svscan: strerr_die: symbol not found
Error relocating /bin/s6-svscan: xpathexec_run: symbol not found
Error relocating /bin/s6-svscan: subgetopt_r: symbol not found
Error relocating /bin/s6-svscan: uint320_scan_base: symbol not found
Error relocating /bin/s6-svscan: skasigaction: symbol not found
Error relocating /bin/s6-svscan: fd_move: symbol not found
Error relocating /bin/s6-svscan: selfpipe_finish: symbol not found
Error relocating /bin/s6-svscan: sanitize_read: symbol not found
Error relocating /bin/s6-svscan: dir_close: symbol not found
Error relocating /bin/s6-svscan: STAMP: symbol not found
Error relocating /bin/s6-svscan: PROG: symbol not found
Error relocating /bin/s6-svscan: tain_infinite_relative: symbol not found
Error relocating /bin/s6-svscan: SKASIG_IGN: symbol not found
```

If I change the startup command to `exec /bin/s6-svscan /etc/s6.d`, `s6-svscan` is started with `root` and everything is working.
But I don't want that rtorrent and node running as `root`.

My question is: should `s6-svscan` run as root in order to properly work, or is there any workaround for my problem?

**Comment by jprjr** [comment]
Where in your Dockerfile are you pulling in the `s6-overlay` project? All our binaries are built statically, are you using your distro's package?

**Comment by LM1LC3N7** [comment]
Thank you for answering.

I don't know `s6-*` for a long time, I discovered it in that Dockerfile. It seems that there is no `s6-overlay` in it (Dockerfile extract):

```bash
 && apk add \
    ca-certificates \
    curl \
    ncurses \
    libressl \
    gzip \
    zip \
    zlib \
    s6 \
    su-exec \
```

Should I replace `s6` to `s6-overlay` in this Dockerfile?

**Comment by jprjr** [comment]
This git repo (`s6-overlay`) is a collection of scripts, pre-compiled binaries, etc for use in any distro. It includes `s6`, as well as some other packages from skarnet.org. As far as I know, `s6-overlay` isn't packaged by any distros, you'll need to read the README.md in this repo to get an idea of how to use `s6-overlay`

I think your question is more about `s6` in general, or some kind of possible bug in Alpine's packaging of `s6`. For what it's worth, I just tried building your Docker image and running, I didn't get any errors about loading libraries.

Generally-speaking, I do run `s6-svscan` as root, and change my user in the individual `run` files.

**Comment by LM1LC3N7** [comment]
> This git repo (`s6-overlay`) is a collection of scripts, pre-compiled binaries, etc for use in any distro. It includes `s6`, as well as some other packages from skarnet.org. As far as I know, `s6-overlay` isn't packaged by any distros, you'll need to read the README.md in this repo to get an idea of how to use `s6-overlay`

Good to know, thanks.

> For what it's worth, I just tried building your Docker image and running, I didn't get any errors about loading libraries.

Thanks to try it, so it must be my docker / docker host configuration (there were some hardening).

> Generally-speaking, I do run `s6-svscan` as root, and change my user in the individual `run` files.

You mean to use something like `su-exec` or `sh -c "command" myuser`?

**Comment by jprjr** [comment]
>> Generally-speaking, I do run `s6-svscan` as root, and change my user in the individual `run` files.

> You mean to use something like `su-exec` or `sh -c "command" myuser`?

Yeah, `su-exec`, `s6-setuidgid`, etc. I don't think `sh -c "command" myuser` would change the user.
