### ISSUE TITLE
Logging to /dev/stdout and to file at the same time.

### ISSUE THREAD

**Issue by markmadlangbayan** [just-containers/s6-overlay#252]
Hello,

Is it possible to log to /dev/stdout and the same time to a file in /var/log directory?  I tried to redirect all longs to /dev/stdout, and I can actually see the logs as output in docker, but not in a file.  Then I read the documentation, and used the logutil-service by creating a file called log/run.  Now it redirected all outputs from screen to the file in /var/log/*/current file.  

I'd like to set it up where I see the outputs on screen, and also in file.

Thanks,
Mark

**Comment by markmadlangbayan** [comment]
Thank you for the detailed response, it worked!

**Comment by felipecrs** [comment]
Any plans to add an option, or environment variable, to allow logutil-service to abstract this configuration?

**Comment by skarnet** [comment]
`S6_LOGGING_SCRIPT`?

**Comment by felipecrs** [comment]
Got it. Now I understand, to retain the behavior described above, I suppose I would have to set:

```
S6_LOGGING_SCRIPT="T 1 n20 s1000000 T"
```

Is this correct?

**Comment by felipecrs** [comment]
Thanks a lot!
