### ISSUE TITLE
Define name collision

### ISSUE THREAD

**Issue by sabrehagen** [just-containers/s6-overlay#255]
When the user has a binary named `define` in their path, it will be executed [here](https://github.com/just-containers/s6-overlay/blob/44b39577dceaa7c77108078f07b20537ceae8c4b/builder/overlay-rootfs/etc/s6/init/init-stage1#L10) instead of `execlineb`'s `define`, causing container startup to fail.

**Comment by jprjr** [comment]
What package is presenting this conflict? I don't know if anything that has a binary named `define`.

A while ago we stopped using the execline `import` command and switched to `importas`, since `import` conflicts with ImageMagick's `import`. I'm not sure if it's worth searching out every possible conflict.

**Comment by sabrehagen** [comment]
No need to search out every possible conflict - all you need is one. Having [this binary](https://github.com/Rican7/define) on the system before installing s6-overlay causes the issue.

**Comment by jprjr** [comment]
The only way I can think to fix this is to use absolute paths everywhere, which we intentionally avoid (save for the very initial `/etc/init` script, where we redefine `PATH` if it doesn't exist).

I would recommend just renaming that other `define` to something else, or keeping it out of the system-wide `PATH` and redefining `PATH` in your `run` scripts for app/services that need it.

**Comment by sabrehagen** [comment]
Considering this is the only use of `define` in the codebase, is there an
alternate non-`define` approach that can be used here to void this issue?

**Comment by jprjr** [comment]
I *think* we could replace the text `${DO_NOT_KEEP_ENV}` with `s6-test ${S6_KEEP_ENV} -eq 0` and possibly remove that define, I haven't tested it.

If somebody implements, tests, and issues a pull request I'll accept it.
