### ISSUE TITLE
Porting S6-overlay to Power (ppc64le)

### ISSUE THREAD

**Issue by sandipmgiri** [just-containers/s6-overlay#257]
We are planning to port S6-overlay code on Power (ppc64le) architecture. 

Just wanted to check if there is any general guidance on how to approach this, how complex this might be and looks like it has been ported on arm architecture , is there any documents which can be used as reference ?

As per our initial analysis looks like we need to port the below dependencies :
1.	MUSL_CROSS_MAKE        
2.	PROOT                
3.	QEMU                 
4.	BUSYBOX_CHROOT       
5.	TRAVIS_TOOLS             
6.	aktau/github-releases                 

Any pointers will help to proceed further. Thanks!

**Comment by jprjr** [comment]
Off the top of my head, you shouldn't need to do anything with qemu, proot, travis-tools, and github-releases. Those are all used by the host.

So the general process would be:

* Add the ppc64le target to the list of targets in musl-cross-make. Musl already supports that, so it should be easy.
* Create a busybox chroot for ppc64le
* Update the skaware builder to use the new ppc64le cross-compiler and chroot, plus the right qemu-user binaries from qemu.
* Add ppc64le to the list of targets in s6-overlay, socklog, socklog-overlay

**Comment by sandipmgiri** [comment]
@jprjr thanks for the quick response and inputs! I am still trying to understand how things are structured here, so some of these questions may be a bit basic, but - if I am interpreting this correctly, it seems that the above steps suggest that I should attempt to run this on an x86 host and cross compile for ppc64le? Or am I missing something here?

Basically, at this point in time,  my intension is to build s6-overlay (and any dependencies) directly on Power hardware and it seems that that in turn will require me to build all the dependent packages(qemu, proot, travis-tools, musl-cross-make, busybox-chroot and github-releases) on ppc64le first. Could you please confirm if that understanding is correct and makes sense?

Thank you and looking forward to your guidance!!

**Comment by jprjr** [comment]
> it seems that the above steps suggest that I should attempt to run this on an x86 host and cross compile for ppc64le? Or am I missing something here?

That's exactly right - we run everything on x86 and cross-compile, even x86 is technically a cross-compile (since we're running on a glibc host but want to target a musl libc host).

> Basically, at this point in time, my intension is to build s6-overlay (and any dependencies) directly on Power hardware and it seems that that in turn will require me to build all the dependent packages(qemu, proot, travis-tools, musl-cross-make, busybox-chroot and github-releases) on ppc64le first. Could you please confirm if that understanding is correct and makes sense?

So if you want to build directly on Power hardware, and also run on power hardware (a straightforward compile), you could just compile the `skaware` dependencies directly.

The busybox-chroot + qemu + proot is for compiling the `skaware` packages, `skalibs` needs to run tests as part of its `configure` script, so we use qemu, proot, and the busybox chroot to get through that step. Travis-tools and github-release is just for our automated builds and releases, you don't need those to actually produce the s6-overlay tarballs.

**Comment by jprjr** [comment]
Just put out a new release that includes ppc64le: https://github.com/just-containers/s6-overlay/releases/tag/v1.22.1.0

**Comment by sandipmgiri** [comment]
@jprjr Thanks a lot for providing ppc64le tar in the latest release. We have tested s6-overlay-ppc64le.tar.gz on ppc64le using steps https://github.com/just-containers/s6-overlay/#quickstart and it’s working fine. Please let us know if you want to verify the tar by running additional tests/use-cases on ppc64le.
