### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by HowardLander** [just-containers/s6-overlay#258]
Not sure if this is the right place to ask this question: please let me know if there is a more appropriate forum... In any case, I have a docker that uses the tigervncserver. The way you start this is to execute the command "vncserver", but vncserver is actually (after a couple of links) a perl script that starts the actual process which is Xtigervnc. So the vncserver script exits as soon as it starts Xtigervnc.  Is there a way to use the s6-overlay code in this situation?

Thanks much
Howard

**Comment by jprjr** [comment]
I think vncserver has an option to stay in the foreground (-fg), have you tried that?

On March 22, 2019 1:56:30 PM EDT, Howard Lander <notifications@github.com> wrote:
>Not sure if this is the right place to ask this question: please let me
>know if there is a more appropriate forum... In any case, I have a
>docker that uses the tigervncserver. The way you start this is to
>execute the command "vncserver", but vncserver is actually (after a
>couple of links) a perl script that starts the actual process which is
>Xtigervnc. So the vncserver script exits as soon as it starts
>Xtigervnc.  Is there a way to use the s6-overlay code in this
>situation?
>
>Thanks much
>Howard
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/just-containers/s6-overlay/issues/258

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
