### ISSUE TITLE
change in UID/GID and fix-attrs.d

### ISSUE THREAD

**Issue by devster31** [just-containers/s6-overlay#259]
This is a question related to #68.
Is there a best practice on how to deal with users which change UIDs and GIDs in the context of `fix-attrs.d` scripts?
An easy example are users running daemons interacting with mounted files and folders, for which I may wish to specify environment variables for the UIDs and GIDs. I would then run `usermod` and `groupmod` in a `cont-init.d` script to fix , and drop down to them with `s6-setuidgid` in a service script. `cont-init.d`, however, runs after `fix-attrs.d`.
The current way to do it seems to run `chown` in the `cont-init.d` script which also changes UID/GID.
An alternative solution would be to switch execution order (or give the option to), but I'm not able to judge the implications for existing users.

**Comment by jprjr** [comment]
Yeah, this seems to come up pretty often and I'm not sure what the true best fix is.

I think `fix-attrs.d` works great for a few, simple cases. The main benefit is allowing chown operations without relying on the host container's binaries. Even for some of our internal scripts though, I've had to switch to just calling `fix-attrs` from within a `cont-init.d` script. For example: https://github.com/just-containers/socklog-overlay/blob/45fe7f6971661a5635d6bb365cbfed2d751415b5/overlay-rootfs/etc/cont-init.d/%7E-socklog#L36

I'd probably just stick with `chown` in your `cont-init.d` script.

**Comment by devster31** [comment]
Thank you for the reply.
I'll keep using `chown` or the `pipeline` example you linked.
