### ISSUE TITLE
How to pull latest release with dockerfile?

### ISSUE THREAD

**Issue by Nottt** [just-containers/s6-overlay#260]
Sorry if this has been asked before, I couldn't find it.

Right now I have a Dockerfile with this:

```
ADD https://github.com/just-containers/s6-overlay/releases/download/v1.21.1.1/s6-overlay-amd64.tar.gz /tmp/
```

Is there a way to always download the latest release? That way I'd never have to worry about manually updating the URL.

It could be done by having a folder in the repository, with files named like `latest-amd64`. You just overwrite the file after a new release but keep the filename and sync it. The Dockerfile entry could be something like this:

`ADD https://github.com/Nottt/s6-overlay/raw/master/latest/latest-amd64.tar.gz /tmp/
`

Thanks!

**Comment by smebberson** [comment]
@Nottt - Is this a good idea? What if they release a new version which breaks your code?

**Comment by Nottt** [comment]
That'd be easy to fix, just revert to a specific release URL.

But I believe it shouldn't happen a lot, and would make sure we are updated
in case of a security fix, improvements, etc.

**Comment by 8ear** [comment]
@Nottt check this out:
```ADD https://github.com/just-containers/s6-overlay/releases/latest/download/s6-overlay-amd64.tar.gz /tmp/```
