### ISSUE TITLE
About s6-svc

### ISSUE THREAD

**Issue by heyconnor** [just-containers/s6-overlay#263]
I can't quite understand s6-svc. What is it for? Which program should it work with? I start a docker, and I try "s6-svc -d /var/run/s6/services/xxxx" in the container, but nothing happens.

**Comment by jprjr** [comment]
Can you share an example Dockerfile? It should bring the service down.

`s6-svc` is used to send commands to `s6-supervise`, and `s6-supervise` is what actually tries to kill the monitored process. `s6-svc` is used to (effectively) send signals to monitored processes, like sending a `SIGTERM`, `SIGINT`, etc.

**Comment by heyconnor** [comment]
Thanks for your reply.

This is the Dockerfile:
FROM ubuntu:bionic
MAINTAINER csk0411@gmail.com

ADD https://github.com/just-containers/s6-overlay/releases/download/v1.17.2.0/s6-overlay-amd64.tar.gz \
    https://github.com/eveybcd/BitcoinDiamond/releases/download/v1.3.0/bitcoindiamond-1.3.0-x86_64-linux-gnu.tar.gz /tmp/
#COPY s6-overlay-amd64.tar.gz \
#     bitcoindiamond-1.3.0-x86_64-linux-gnu.tar.gz /tmp/

RUN tar xzf /tmp/s6-overlay-amd64.tar.gz -C / && \
    cd /tmp && tar xvf bitcoindiamond*.tar.gz && cp -r /tmp/bitcoindiamond*/bin/* /usr/local/bin && \
    rm -rf /usr/share/man/* /usr/share/groff/* /usr/share/info/* /var/cache/man/* /tmp/* /var/lib/apt/lists/*

EXPOSE 16101 16102 16103

ENTRYPOINT ["/init"]
VOLUME ["/data"]
ADD rootfs /

I also added a link in the last email, there is init and service scripts here. https://github.com/heyconnor/bcd_private_testnet

And I must correct an error of last email.
If I don't put "s6-svc -d /var/run/s6/services/node-xxx" at the end of service scripts, it would fail when I run with "docker run -it image", but succeed when running  with "docker run -it -d image".
If I put "s6-svc -d /var/run/s6/services/node-xxx" at the end of service scripts, either is ok.
It failed because there was already a service running.
I don't know what happened. Does s6 start the service and then stop it and start it again when running with "docker run -it -d image"?



csk0411@126.com
 
From: John Regan
Date: 2019-04-23 00:11
To: just-containers/s6-overlay
CC: connor; Author
Subject: Re: [just-containers/s6-overlay] About s6-svc (#263)
Can you share an example Dockerfile? It should bring the service down.
s6-svc is used to send commands to s6-supervise, and s6-supervise is what actually tries to kill the monitored process. s6-svc is used to (effectively) send signals to monitored processes, like sending a SIGTERM, SIGINT, etc.

**Comment by heyconnor** [comment]
Thanks for your reply.
This is the [Dockerfile](https://github.com/heyconnor/bcd_private_testnet).

**Comment by jprjr** [comment]
So I'm not familiar with bitcoindiamd, but I saw lines like this in your `run` files:

`/usr/local/bin/bitcoindiamondd -daemon`

I'm guessing that `-daemon` flag makes the program double-fork and run in the background, which you don't want to do. Services under `service.d` should not fork.
