### ISSUE TITLE
Start and stop services in a specific order

### ISSUE THREAD

**Issue by Nottt** [just-containers/s6-overlay#265]
Is there a way to start and stop services in a specific order (e.g start mysql before starting nginx)?

I have a `run` file for each service in `/services.d`, should I just put everything in a single `run` file and let bash handle this by doing the first thing to be started first, etc or is there a better way?

**Comment by jprjr** [comment]
Yes - I don't have a great example but you should be able to do this with the readiness notification in s6, and `s6-svwait`, see https://skarnet.org/software/s6/notifywhenup.html and https://skarnet.org/software/s6/s6-svwait.html
