### ISSUE TITLE
Preserving exit code from terminated process

### ISSUE THREAD

**Issue by ahmetb** [just-containers/s6-overlay#270]
(Apologies if this shouldn't be asked here, I'm happy to move to stackoverflow.com if needed.)

I've looked at the readme but couldn't find how to preserve the status code from terminated processes while the init process itself terminates.

I have this structure:

```
└── services
    ├── service1
    │   ├── finish
    │   └── run
    └── service2
        ├── finish
        └── run
```

and in `finish` script I do

```sh
#!/usr/bin/env sh
echo >&2 "service1 exited. code=${1}"
exec s6-svscanctl -t /var/run/s6/services
```

when a service crashes, the container exits with status=0 which doesn't indicate a failure.

I'm trying to figure out a way of preserving the status code, or at least exit from the /init process with a non-zero exit code when a subprocess fails.

**Comment by jprjr** [comment]
If you write something into `/var/run/s6/env-stage3/S6_STAGE2_EXITED` you can control what code `/init` exits with.
