### ISSUE TITLE
Should I use the arm or armhf version for arm32v7?

### ISSUE THREAD

**Issue by rfgamaral** [just-containers/s6-overlay#271]
I'm trying to fix some architecture issues on [this docker image](https://github.com/rfgamaral/docker-gphotos-uploader) and I'm confused with version of S6 should I use for my `arm32v7:alpine` based image.

I believe this image will be picked by most versions of the Raspberry Pi but the README states:

> * `s6-overlay-armhf.tar.gz` - includes binaries for 32-bit ARM (hard-float) platforms, ie, **Raspberry Pi**

I just want to make sure I pick the right architecture for my `arm32v7:alpine` based image. So, which one should I go with, `s6-overlay-armhf.tar.gz` or `s6-overlay-arm.tar.gz`?

**Comment by jprjr** [comment]
I honestly don't know, my recommendation is to experiment and see which works.
