### ISSUE TITLE
/etc/cont-init-post.d after /etc/services.d ?

### ISSUE THREAD

**Issue by lukasmrtvy** [just-containers/s6-overlay#273]
Is possible to somehow run a script after /etc/services.d part of stage ?
I need to use CLI of running service to set some properties, that are not possible to set with config file nor env variables and service must be running.

Something like:
1. /etc/cont-init.d
2. /etc/services.d
3. /etc/cont-init-post.d

Of course I can do `docker exec -it container command-cli foobar`

Thanks

**Comment by lukasmrtvy** [comment]
duplicate: https://github.com/just-containers/s6-overlay/issues/120

**Comment by jprjr** [comment]
What about using [`s6-notifyoncheck`](https://skarnet.org/software/s6/s6-notifyoncheck.html) in your `run` script?

Make a folder called `data` and put in a script called `check`

In you run script, call `s6-notifyoncheck` towards the beginning.

The check script will be periodically called. Whenever your service is up and you get to set your properties, the check script should exit 0.

This also allows for notifying other, dependent services that you're ready.
