### ISSUE TITLE
/etc is group writable in tar file

### ISSUE THREAD

**Issue by grmblfrz** [just-containers/s6-overlay#274]
I think /etc should have mode 755 (currently 775) in the tar file. I had problems with opendkim because in alpine linux group 0 has more than one user and /etc belongs to group 0 and is group writable if the s6-overlay tar is installed. I've worked around this now by using --no-same-permissions when extracting, but I think it could save others from hassle if the default permissions are changed (the same goes for /usr/bin).

**Comment by jprjr** [comment]
Fixed in `v2.0.0.1`
