### ISSUE TITLE
Logging for a subprocess

### ISSUE THREAD

**Issue by tblazina** [just-containers/s6-overlay#276]
I have a question pertaining to how to enable logging for a process which is being spawned by a process that is launched during `init`.

I am running [this docker image](https://hub.docker.com/r/rocker/rstudio/dockerfile) which uses a `/etc/services.d/rstudio/run` service that runs `exec /usr/lib/rstudio-server/bin/rserver --server-daemonize 0` which in turn starts an instance of a rstudio server instance. 

However, when you start an instance of Rstudio it launches another process (e.g. `/usr/lib/rstudio-server/bin/rsession -u tim --launcher-token 1E182A64`), which I am wondering how to get logs from. 
 
I haven't been able to figure out how to get the things from `stdout` or `stderr` from the Rstudio instance out so that I can see logs using `docker logs`.  Any help is appreciated!

**Comment by jprjr** [comment]
If the process is being launched by `rserver` I'd reach out to them and see what kind of logging options they may have.

That said you could do something like, move `rsession` to `rsession-bin`, and replace the original `rsession` with a wrapper script that calls `rsession-bin` but with stdout/stderr redirected.

Something like:

```bash
#!/bin/sh 

exec /usr/lib/rstudio-server/bin/rsession-binary "$@" >/somewhere/to/log 2>&1
```

But the way better option is to find a way for `rsession` to just inherit the stdout/stderr handles of the `rserver` process.
