### ISSUE TITLE
Does a command exist to check all services? 

### ISSUE THREAD

**Issue by shadycuz** [just-containers/s6-overlay#280]
I know I can check a single service, and somtimes I will run s6-ps to see all of them, but I'm looking for a simple one-liner that I can use to check all my user services are up. For context this is for a kubernetes probe that will restart the container if it does not return a 0 exit code.

**Comment by jprjr** [comment]
I believe [`s6-svwait`](https://skarnet.org/software/s6/s6-svwait.html) could do that, something like:

```#!/bin/execlineb

cd /var/run/s6/services
s6-svwait -t 5000 -U svc1 svc2 svc3 ... etc
```

Using `-U` means each and every service will need a readiness notification setup.
