### ISSUE TITLE
I Wrote a New Introduction

### ISSUE THREAD

**Issue by PythonLinks** [just-containers/s6-overlay#282]
I wrote some new introductory documentation.    The idea is to give a high level introduction to S6.   Did I get it right? Should I change anything? Would you accept a pull request?

S6 makes it possible to run multiple heterogeneous processes inside of a single container.  Usually Docker recommends that each container only runs one process.  But  what if you want to build containers that support multiple processes?  S6 makes it possible!

Why is this difficult?  Well Docker has a certain structure, and one has to respect that structure.  So for those new to Docker let us start by defining the Docker environment. 

## Docker Environment. 

Docker assumes that there is a process pid #1, on startup that process is created, and when that process  dies, the whole container terminates.  

Docker also assumes that you can send the TERM signal to process #1, and that process is killed and the container is terminated. 
 
So running multiple processes in that kind of environment takes a moments thought. 

## S6 Environment
So how does S6 handle a container with multiple processes?  

S6 is the container’s process #1.  It manages the other processes. 

S6 supports a list of heterogenous processes.   

Each process gets its own process manager, its own process directory, its own startup script (think entryoint) and its own shut down script. 
 On startup, S6 starts one manager for each process , and the manager manages the processes in that group.  It starts them up.  If they fail, it either restarts them, or shuts down the whole container.  When a SIG is sent, it forwards the SIG to its processes. 

Container processes such as NGINX themselves may have further sub-processes. 

On startup, S6 calls the managers for each process , and they execute the startup scripts.  For Docker self, there would be just one startup script.  For S6 there is one startup script per process .   

On shutdown, S6 process #1 notifies the  process managers, and the managers shut down the processes before exiting themselves. 

What happens when a process dies?   Well if it is a main process for the container, Docker expects it to terminate the container, so that corrective action can be taken.  If it is a minor process, then it could be restarted.  

S6 supports these options by having finish scripts  When a process dies, it calls the finish script.  The finish script can terminate the whole container, or it can do nothing, and then the run script is called again to restart the process. 
 
Containers also have to deal with signals.  Docker assumes that a TERM signal kills the process #1, and that terminates the Docker container.  With multiple processes, one runs the risk of having zombie processes remaining on the system.  That would be like a horror movie. 

S6 kills zombies.   When a TERM signal is received by the S6 process # 1, it propagates that TERM signal to all of the process group managers, who forward it to all of their sub-processes.  

S6 also makes it easy to convert all of the file system user and group ids to match those of the person running the container.  That way it is easy to bind docker container volumes to host operating system volumes, and not get read and write permission errors. 

After starting each process its privileges are dropped, so that there are no running root processes. 

How can S6 do all of this magic?  Well it has to start as root,  then the permissions are changed, and then the privileges are dropped, so it is all still quite secure. 

How do you control individual processes?  You can optionally pass environment variables to the tree of processes.   S6 also has its own environment variables.   And you can pass signals to individual processes.  

The only thing you can’t do, is to pass the command line arguments to the individual startup scripts. (is that correct?)

Okay, now that you have the high level picture, we invite you to read about the details of how to make all of this work.

**Comment by jprjr** [comment]
Some of this is getting into like, "how do UNIX-like operating systems work". Plus some of this isn't really correct, like:

> After starting each process its privileges are dropped, so that there are no running root processes.

Each supervised process needs to drop its own privileges, we don't do anything to auto-drop privileges.
