### ISSUE TITLE
error while loading env variables running usr/bin/with-contenv

### ISSUE THREAD

**Issue by aarushig14** [just-containers/s6-overlay#285]
I have written a shell script as follows 

`#!/usr/bin/with-contenv sh
source /usr/bin/with-contenv
echo $JAVA_HOME`

But when executed sh command it shows the following error:

`ifelse: fatal: unterminated if block
exec: usage: exec [ -c ] [ -l ] [ -a argv0 ] prog...
s6-envdir: usage: s6-envdir [ -I | -i ] [ -n ] [ -f ] [ -c nullchar ] dir prog...
exec: usage: exec [ -c ] [ -l ] [ -a argv0 ] prog... `

I am new to this. Please explain what went wrong here.

**Comment by jprjr** [comment]
Try this instead:

```
#!/usr/bin/with-contenv /bin/sh

echo $JAVA_HOME
```

`#!/usr/bin/with-contenv /bin/sh` needs to be on its own line.

There's no need to call `source` in your script, that first line took care of bringing in the environment variables.
