### ISSUE TITLE
Simple script to shadow specific overlay services run dir with s6-svc

### ISSUE THREAD

**Issue by debosvi** [just-containers/s6-overlay#289]
Is it possible to add a script (like others utils) acting as a proxy to use s6-svc for up and down?
Now it is mandatory to use complete service dir path using s6-svc.
thanks for next work.

**Comment by debosvi** [comment]
could be useful also to add a command 'list' to enumerate all predisposed running services.

**Comment by jprjr** [comment]
You could always cd to /var/run/s6/services first then start using s6-svc.

I'm not sure how useful having wrapper scripts would be for things like listing services. What's a use case for that?
