### ISSUE TITLE
foreground s6-pause does'nt work

### ISSUE THREAD

**Issue by debosvi** [just-containers/s6-overlay#290]
Hi all,

I am running docker s6overlay based image.
I want to use PM2 npm package to run my backend component.
But the s6-pause, required to wait down control, does  not wait for signals.
Am I wrong in my run script?

Here is my run script:

```
#!/usr/bin/with-contenv sh
s6-setuidgid www-data
cd /var/apps/backend
pm2 start index.js --name tsix-backend
foreground { s6-pause }
pm2 stop tsix-backend
```

**Comment by debosvi** [comment]
totally out of sense
i tried to convert with all exelineb style but faced that I did'nt find how to go forward after s6-pause resumes.

```
#!/usr/bin/with-contenv execlineb
if { s6-echo start }
foreground { pm2 start /var/apps/backend/index.js --name tsix-backend }
if { s6-echo wait }
foreground { s6-pause }
if { s6-echo stop }
pm2 stop tsix-backend
```

**Comment by jprjr** [comment]
I believe `pm2 start` forks and detaches which you don't want.

PM2 actually has a separate binary meant for running in Docker, this will probably do what you want:

```
#!/usr/bin/with-contenv /bin/execlineb
execlinecd /var/apps/backend
s6-setuidgid www-data
pm2-runtime --name tsix-backend index.js
```
