### ISSUE TITLE
Add support for s390x (IBM z/Arch)

### ISSUE THREAD

**Issue by crazy-max** [just-containers/s6-overlay#296]
Hi,

It would be nice to bring support for s390x platform like you have done for ppc64le (IBM Power). Thanks!

**Comment by skarnet** [comment]
With v3.0.0.0 out, supporting a new architecture is only a matter of building a musl cross-toolchain for that architecture. I will try to build a s390x toolchain.

**Comment by crazy-max** [comment]
This is supported with my [alpine-s6 docker image](https://github.com/crazy-max/docker-alpine-s6/blob/master/Dockerfile) with 2.2.0.3 but will refactor a bit for 3.0.0.0 and also use a proper toolchain to avoid using QEMU.

**Comment by skarnet** [comment]
The build system has been greatly simplified; you won't need qemu or anything with 3.0.0.0, you will just need a proper toolchain and `make`. And since by default the build system fetches toolchains from my site, I need to make one available there for every supported architecture 😅

**Comment by crazy-max** [comment]
Roh wonderful!

**Comment by skarnet** [comment]
I added a s390x target in the latest git, with a toolchain that targets z196 or higher (similar to what Alpine does). Please tell me if it works for you.

**Comment by crazy-max** [comment]
d480b99f58be995e6d0c2e59d00bc2856b2ae0d2 lgtm thx.

```
#22 0.091 + make 'VERSION=3.0.0.0' 'OUTPUT=/out' 'ARCH=s390x-linux-musl'
#22 0.100 exec mkdir -p /out/sources
#22 0.101 cd /out/sources && wget https://skarnet.org/toolchains/cross/s390x-linux-musl_z196-11.2.0.tar.xz
#22 0.222 Connecting to skarnet.org (95.142.172.232:443)
#22 0.366 saving to 's390x-linux-musl_z196-11.2.0.tar.xz'
#22 0.392 s390x-linux-musl_z19   0% |                                |  8192  1:17:49 ETA
#22 1.397 s390x-linux-musl_z19  18% |*****                           | 6760k  0:00:09 ETA
#22 2.411 s390x-linux-musl_z19  32% |**********                      | 11.9M  0:00:06 ETA
#22 3.404 s390x-linux-musl_z19  44% |**************                  | 16.3M  0:00:04 ETA
...
```

```
$ docker run --rm -it --entrypoint s6-ps alpine-s6:local
WARNING: The requested image's platform (linux/s390x) does not match the detected host platform (linux/amd64) and no specific platform was requested
USER  PID  TTY    STAT  START     COMMAND
root    1  pts/0  Rsl+  15:31:51  /usr/bin/qemu-s390x /usr/bin/s6-ps
```

**Comment by skarnet** [comment]
Not that I know of, but booting an s6-overlay container with `/init` as the entrypoint and `s6-ps` as CMD should show very quickly if anything's wrong. ;-)
