### ISSUE TITLE
s6-supervise Error on Ubuntu And CentOS

### ISSUE THREAD

**Issue by HiColinn** [just-containers/s6-overlay#297]
Hi,I like s6,But recently I use it,will error😣And all image will have this error msg if use s6.
I also test in Ubuntu,it is same error info.
***
| Key            | Value                                     |
| -------------- | ----------------------------------------- |
| CentOS version | CentOS Linux release 8.1.1911 (Core)      |
| docker Verison | Docker version 19.03.10, build 9424aeaee9 |
| s6-overlay Version |latest |
***
![0](https://user-images.githubusercontent.com/65964332/83346393-83aab200-a34e-11ea-8e43-cf4c6bb9ac06.gif)

**Comment by HiColinn** [comment]
I also tried to add some run arg,but  is is uesless:
![01](https://user-images.githubusercontent.com/65964332/83346505-8e197b80-a34f-11ea-9334-01e844cf42f3.gif)

**Comment by jprjr** [comment]
You shouldn't be running `s6-svscan` interactively like that, that's all handled by the init system.

What are you trying to do exactly? If you launch one of those containers and run something like `ps` you should see `s6-svscan` running.

**Comment by HiColinn** [comment]
> You shouldn't be running `s6-svscan` interactively like that, that's all handled by the init system.
> 
> What are you trying to do exactly? If you launch one of those containers and run something like `ps` you should see `s6-svscan` running.


I am learning s6 now，I am just don't kuow why it will print all those error message,so ,I should ignore those err msg?
