### ISSUE TITLE
Conditional start of the user services and cont-init.d/ scripts

### ISSUE THREAD

**Issue by githubsaritasa** [just-containers/s6-overlay#300]
HI,

Environment:
* S6_OVERLAY_VERSION=v2.0.0.1
* Docker Image: Centos 7
* Docker version 19.03.11, build 42e35e61f3
* Host OS: Fedora 31, Kernel: 5.6.18-200.fc31.x86_64

### Issue

My container runs several services, but I want to run them conditionally on the value of ENV **XCOMMAND**

**/etc/services.d/uwsgi/run**

```bash
#!/usr/bin/with-contenv bash

source /etc/profile.d/utils.sh

function start() {
  header "Start UWSGI svc"
  uwsgi /etc/uwsgi.ini
}

[ -z "$XCOMMAND" ]  && start
```

However when I run the following command

```bash
XCOMMAND=run_migrations ENVIRONMENT=development docker run -p 8000:80 \                                         
-e AWS_ACCESS_KEY_ID \
-e AWS_SECRET_ACCESS_KEY \
-e AWS_DEFAULT_REGION \
-e ENVIRONMENT \
-e XCOMMAND \
--name test -it magid/backend:v1.0.0 /bin/bash && \
docker rm test || docker rm test
```

I get the following output

```bash
[services.d] starting services
[services.d] done.
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[root@06256dd599e6 app]# [s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
test
```

And never get to **/bin/bash**

Am I missing something? I just started with **s6-overlay** for the first time. 

Pls put me in the correct direction.

**Comment by Axent96** [comment]
I have the same problem on v2.1.0.0:
`[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.`

Docker version 19.03.6-ce, build 369ce74
Docker Image: Alpine 3.2 (php:7.4.11-fpm-alpine3.12)
Host OS: centos rhel fedora (Linux 4.14.193-149.317.amzn2.x86_64 x86_64)

**Comment by jprjr** [comment]
I would re-architect this.

If you have a conditional script, it should be its own script the `cont-init.d` script and use an environment variable to run or not, and not part of the service run script.
