### ISSUE TITLE
Why does the release contain replacement binary for base image / Linux distro’s?

### ISSUE THREAD

**Issue by thy143** [just-containers/s6-overlay#301]
Hi, sorry this is not a issue per say however I unsure where to ask this.  I seeing a far few images using S6-overlay and it seems a to fit a use case I have. 

After exploring the release files, I noticed you seem to be providing replacement binary files for common ultilities (eg cd, exec, export etc…). I am wondering why you are replacing common binary files usually provided by you base image / distro?

**Comment by jprjr** [comment]
`cd`, `exec`, `export`, etc are actually shell built-ins. When you run `cd` in an sh script, it's not actually running `/usr/bin/cd`, it's calling a built-in shell function to change the directory.

`execline` has no concept of a shell built-in (it's not a shell), so it takes a different approach by using binaries.
