### ISSUE TITLE
standard_init_linux.go:211: exec user process caused "no such file or directory"

### ISSUE THREAD

**Issue by djnotes** [just-containers/s6-overlay#302]
I am trying to build an Apache container with php-fpm. So, I will need two services httpd and fpm. That's why I approached s6-overlay. The problem is this utility seems to overwrite essential files as mentioned in the [docs](https://github.com/just-containers/s6-overlay#bin-and-sbin-are-symlinks). I followed the two-step extraction workaround, but still it seems that the overwrite issue remains.    
Here's my Dockerfile: 

```
# FROM nginx:1.19-alpine
FROM httpd:2.4-alpine


RUN apk update 

RUN apk add nano php-fpm

COPY . /usr/local/apache2/htdocs

WORKDIR /usr/local/apache2/htdocs


ADD https://github.com/just-containers/s6-overlay/releases/download/v2.0.0.1/s6-overlay-amd64.tar.gz /tmp/
RUN tar xzf /tmp/s6-overlay-amd64.tar.gz -C / --exclude="./bin" && \
    tar xzf /tmp/s6-overlay-amd64.tar.gz -C /usr ./bin


RUN sed -i 's@^Listen = 127.0.0.1:9000@Listen = /var/run/fpm.sock@' /etc/php7/php-fpm.d/www.conf

# #Enable fcgi module
RUN sed -i 's@^#LoadModule proxy_module modules/mod_proxy.so@LoadModule proxy_module modules/mod_proxy.so@' /usr/local/apache2/conf/httpd.conf
RUN sed -i 's@^#LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so@LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so@' /usr/local/apache2/conf/httpd.conf


COPY run-apache /etc/services.d/httpd/run

COPY run-fpm    /etc/services.d/fpm/run


COPY ./httpd.conf /usr/local/apache2/conf/httpd.conf



ENTRYPOINT ["/init"]

```

Content of run-apache:
```
#!/bin/ash
httpd-foreground
```

Content of run-fpm:
```
#!/bin/ash
php-fpm7 -F
```
After building it with "docker build -t webapp .", I run it with:  

```
docker run --rm -p 8000:80 webapp  
```
I get this error: 
```
standard_init_linux.go:211: exec user process caused "no such file or directory"
```

**Comment by markus-seidl** [comment]
I have the same problem, the file "/etc/s6/init-stage1" is missing for me.

**Comment by jprjr** [comment]
The 2-step extraction method is meant for distros that symlink /bin into /usr/bin

Do the single-step version and it should work.

-John

On August 2, 2020 3:15:21 AM EDT, Markus Seidl <notifications@github.com> wrote:
>I have the same problem, the file "/etc/s6/init-stage1" is missing for
>me.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/just-containers/s6-overlay/issues/302#issuecomment-667638839

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by shinebayar-g** [comment]
As @jprjr  suggested, this worked.

```
FROM debian
ADD https://github.com/just-containers/s6-overlay/releases/download/v2.0.0.1/s6-overlay-amd64.tar.gz /tmp/
RUN gunzip -c /tmp/s6-overlay-amd64.tar.gz | tar -xf - -C /
```
