### ISSUE TITLE
Is it possible to redirect services log to container log?

### ISSUE THREAD

**Issue by shinebayar-g** [just-containers/s6-overlay#304]
Is it possible to redirect services log to container log? I mean I want to show background services log by running `docker logs ..`
Because I have fluentd agent that's streaming log to elasticsearch and I'd like to grab services log too. Right now it looks like `exec logutil-service /var/log/myapp` is saving logs to a file.

Edit: Well it's not really useful unless different service logs have different prefix for their logs like

[service1] log log log 
[service2] log log log

as I mentioned [here](https://github.com/just-containers/s6-overlay/issues/70#issuecomment-686859205).

**Comment by jprjr** [comment]
If you use `logutil-service` your logs will get saved to files, I usually mount a volume for my logs and have something on my host machines pick them up from there. Alternatively, just don't use `logutil-service` and let them go to standard out.

If you want to prefix you can just use sed. Example:

`Dockerfile`:

```Dockerfile
FROM ubuntu:20.04
ADD https://github.com/just-containers/s6-overlay/releases/download/v2.0.0.1/s6-overlay-amd64.tar.gz /tmp/
RUN tar xzf /tmp/s6-overlay-amd64.tar.gz -C / --exclude='./bin' && tar xzf /tmp/s6-overlay-amd64.tar.gz -C /usr ./bin

COPY rootfs /
ENTRYPOINT ["/init"]
```

Folder structure of the `rootfs` folder from the `COPY` line:

```
rootfs/
├── etc
│   └── services.d
│       └── service1
│           ├── log
│           │   └── run
│           └── run
└── usr
    └── bin
        └── service1
```

`rootfs/usr/bin/service1`:

```bash
#!/bin/sh

while true ; do
    printf "some message on stdout\n"
    printf "some message on stderr\n" 1>&2
    sleep 5
done

```

`rootfs/etc/services.d/service1/run`:

```
#!/bin/execlineb

fdmove -c 2 1 # redirect stderr into stdout
/usr/bin/service1
```

`rootfs/etc/services.d/service1/log/run`:

```
#!/bin/execlineb

sed "s/^/[service1] /"
```

All lines from `/usr/bin/service1` will have a a `[service1] ` prefix

**Comment by shinebayar-g** [comment]
Thanks for the thorough details. Following your example, it didn't print anything to docker logs?


> I usually mount a volume for my logs and have something on my host machines pick them up from there

However I think I'm kinda settling on this approach.

**Comment by jprjr** [comment]
So `sed` can have pretty different behavior depending on what distro you're using. I believe GNU `sed` buffers output which would explain why it takes time for output to appear.

Try using the `--unbuffered` switch.
