### ISSUE TITLE
bash: /init: /bin/execlineb: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by 8ear** [just-containers/s6-overlay#307]
Hi together,

I added s6 in my dockerfile with the following commands:
```
ADD https://github.com/just-containers/s6-overlay/releases/download/v2.1.0.0/s6-overlay-amd64.tar.gz /tmp/
RUN set -eu \
    ;tar xzf /tmp/s6-overlay-amd64.tar.gz -C / --exclude='./bin' \
    ;tar xzf /tmp/s6-overlay-amd64.tar.gz -C /usr ./bin \
    ;
COPY --chown=thehive:thehive application.conf /etc/thehive/
#COPY s6/permissions /etc/fix-attrs.d/00-thehive-set-permissions
COPY s6/thehive/prepare /etc/cont-init.d/00-thehive-prepare
COPY s6/thehive/run /etc/services.d/thehive/run
ENTRYPOINT ["/init"]
CMD ["thehive"]
```

If I start now the container with:
``docker run --rm -ti mycontainer/container``
OR
I go into the container with bash:
```
docker run --rm -ti --entrypoint "" mycontainer/container bash
/init
```

I will get always the following error:
*``bash: /init: /bin/execlineb: bad interpreter: No such file or directory``*

System:
Docker version 19.03.13, build 4484c46d9d
Host: Ubuntu 20.04

What can I do now?

**Comment by jprjr** [comment]
what's the base distro?

**Comment by 8ear** [comment]
Ubuntu 20.04 on the host image is Debian buster

**Comment by jprjr** [comment]
The default instructions were updated some time ago to accommodate Ubuntu and CentOS replacing `/bin` with a symlink to `/usr/bin` - but debian buster still keeps `/bin` around as an actual directory.

If you just do `tar xzf /tmp/s6-overlay-amd64.tar.gz -C /` you should be good to go.

**Comment by jprjr** [comment]
The latest release has a new self-extracting option that just does the right thing based on whether `/bin` is a symlink or not. https://github.com/just-containers/s6-overlay/releases/tag/v2.1.0.2
