### ISSUE TITLE
s6-overlay now packaged in Alpine

### ISSUE THREAD

**Issue by dermotbradley** [just-containers/s6-overlay#308]
Hi

FYI I'm the Alpine package maintainer for justc-envdir, s6-overlay, and s6-overlay-preinit.

For now the packages are only in the "Edge" version but as I recently moved the packages from the "testing" section to "community" section this means that whenever the next Alpine release, 3.13.0, comes out (probably December) they will be part of that too.

**Comment by jprjr** [comment]
Awesome!! Thank you so much

**Comment by NicolasCARPi** [comment]
This is great. Thanks for your efforts @dermotbradley :)
