### ISSUE TITLE
build script is failing on v2.1.0.2

### ISSUE THREAD

**Issue by overratedpro** [just-containers/s6-overlay#310]
I'm sorry to report the [build script](https://github.com/just-containers/s6-overlay/blob/39f59a769f2ba6a148c2b0bfeef413a1a72bb256/Dockerfile#L18) is broken in the latest release (v2.1.0.2), with an unmet dependency:

```
tar (child): xz: Cannot exec: No such file or directory
```

**Comment by jprjr** [comment]
Fixed in latest commit
