### ISSUE TITLE
Option to delay cont-finish-d until all services.d are finished, killed, etc.

### ISSUE THREAD

**Issue by ShahimEssaid** [just-containers/s6-overlay#313]
I'm new to s6-overlay but I think I noticed that there is no way to delay the running of cont-finish.d scripts until all the services have finished, are killed, etc. Is that correct? I think it would be useful to have an option to customize this behavior.

I did notice that the cont-init stage does not overlap with the services stage (i.e. nothing in the later starts to run before the former if completely finished) but this is not the case for the services stage and the cont-finish stage. These latter two stages seem to overlap but there might be situations where this is not desirable. 

In my case I have a container in a docker compose setup that sort of manages the other containers in different ways and it does this through services. What I'm trying to accomplish is for this "managing" container to run the cont-finish.d scripts only after all the "managing services" in this container are completely finished one way or another before any of the cont-finish.d script run. I can hack that in the cont-finish scripts but it would be so much easier and more reliable if I can specify this once at the s6-overlay stages level.

**Comment by ShahimEssaid** [comment]
Any suggestions for the best approach for how to delay the running of a cont-finish script until ALL the services are completely done (i.e. exited/killed && finished/finish timed out, etc.) as a workaround for the above issue?

**Comment by jprjr** [comment]
I think `s6-svwait -D /var/run/s6/services/*` is the best option.

`cont-finish.d` scripts run after the term signal has been sent. I would rather waiting on services to be down be completed within a cont-init.d script than change the behavior of s6.

Like I'll just be honest, I think I'm the only person still working on this and my free time is pretty limited, and it seems like no matter what I do people have issues. If there's a solution that works inside of a cont-finish.d script, I'm going to say go with that solution.
