### ISSUE TITLE
Unable to launch

### ISSUE THREAD

**Issue by tcm0116** [just-containers/s6-overlay#314]
I'm developing a Home Assistant addon that utilizes the s6 overlay. When running on my local machine for development, it would great. However, I'm running into an issue when I run the addon on a RaspberryPi. When attempting to start the addon, the following messages are generated in the logs:
```
/bin/importas: line 3: syntax error: unexpected word (expecting ")")
/init: export: line 12: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin: bad variable name
```
Any ideas as to what could be causing this?

**Comment by jprjr** [comment]
Can you produce a small Dockerfile that reproduces the error?

**Comment by tcm0116** [comment]
I was able to determine that it was being caused by using the incorrect architecture for the s6-overlay image in my Dockerfile.
