### ISSUE TITLE
s6-overlay-preinit fails to start if /var does not exist

### ISSUE THREAD

**Issue by vroad** [just-containers/s6-overlay#321]
s6 overlay version is v2.2.0.0

```
s6-overlay-preinit: fatal: unable to mkdir /var/run: No such file or directory
```

After adding /var to the image s6 runs successfully.

I built base docker image with nix-build, and added s6-overlay using Dockerfile, because s6 does not seem to be available in nixpkgs. The image built with nix-build lacks /var directory.
I'm not sure where the source of the script is, but can this be fixed easily by just adding -p to mkdir option?

**Comment by jprjr** [comment]
Good catch, we've always assumed /var exists. I just updated `s6-overlay-preinit` to try making `/var`, it's in the latest release `v2.2.0.1`
