### ISSUE TITLE
Remove /etc/leapsecs.dat

### ISSUE THREAD

**Issue by skarnet** [just-containers/s6-overlay#323]
Hey @jprjr,

s6-overlay still provides the `/etc/leapsecs.dat` file, as `builder/overlay-rootfs/etc/leapsecs.dat`, and chmods it in `builder/build-latest` as well.
It's been several major versions of skalibs since this file is no longer necessary 😄 skalibs now hardcodes its leap second table; the rationale is that skalibs releases occur way more frequently than leap second additions.

To avoid confusion and trim the unneeded, could you remove this file? Thanks!

**Comment by jprjr** [comment]
No problem!
