### ISSUE TITLE
Fix the Quickstart example for machines that do not have IPV6 enabled

### ISSUE THREAD

**Issue by HowardLander** [just-containers/s6-overlay#326]
When running the quickstart example docker file I got the following error:

nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)

Turns out this is because my machine is not configured for IPV6.  Luckily it was a fairly simple fix: I changed

RUN apt-get update && \
    apt-get install -y nginx && \
    echo "daemon off;" >> /etc/nginx/nginx.conf

to 

RUN apt-get update && \
    apt-get install -y nginx && \
    sed -i -e "s/listen \[/#listen \[/g" /etc/nginx/sites-available/default && \
    echo "daemon off;" >> /etc/nginx/nginx.conf

Howard

**Comment by HowardLander** [comment]
Maybe you want to add both to the README with a note to use the second one if you see the error?  Not sure ...

**Comment by jprjr** [comment]
This seems like a really niche error
