### ISSUE TITLE
What is the recommended method of starting services that are down by default with docker run command?

### ISSUE THREAD

**Issue by kuba-lilz** [just-containers/s6-overlay#327]
Say inside docker container I want to have a few services that are down by default - they have `down` file included in their services directories.
What is the recommended method of starting these services with `docker run` command?

Running e.g. 
`docker run -d my_container /bin/bash -c "s6-svc -u /var/run/s6/services/first && s6-svc -u /var/run/s6/services/second"`
doesn't work because once `s6-svc` finishes starting services, docker quits the container - from docker's perspective all work container was asked to perform was already done.

My current workaround is to have a wrapper script e.g:
```bash
s6-svc -u /var/run/s6/services/first
s6-svc -u /var/run/s6/services/second
# some waiting code here
# ...
```
and call container like this:
`docker run -d my_container /bin/bash /app/wrapper_script.sh`

Note that this script has to be blocking - hence comment about waiting code after calls to `s6-svc` - or else container exits after script finished processing.
Is there a better method of handling this problem that I don't see?

**Comment by jprjr** [comment]
Well, if having a wrapper script that unconditionally starts the services works, I'd question why they're down by default.

If the service is down by default, but should be started conditionally at runtime, I would use a script in `cont-init.d` that checks for an environment variable and removes the `down` file, like:

``#!/bin/sh

if [ -n "$MY_VAR" ] ; then
  rm /var/run/s6/etc/services.d/first/down
fi
```

Then run your docker container like:

`docker run -e MY_VAR=1 -d my_container`

If `MY_VAR` is defined, the service runs.

**Comment by kuba-lilz** [comment]
> Well, if having a wrapper script that unconditionally starts the services works, I'd question why they're down by default.

Perhaps I didn't phrase it well, I want these services to be down by default.

> If the service is down by default, but should be started conditionally at runtime, I would use a script in cont-init.d that checks for an environment variable and removes the down file

Oh, that is... a lot nicer than what I cooked up. Should have thought of this myself! Thank you!
