### ISSUE TITLE
Request for help: The USER keyword in docker file is not quite doing what I want.

### ISSUE THREAD

**Issue by HowardLander** [just-containers/s6-overlay#328]
Hi all

I've got a fairly complex docker file that uses the s6-overlay.  The problem I have is the following:  I don't want the docker to have any processes running as root so I tried the USER keyword and in fact I can get s6-svscan and s6-supervise programs to run as the specified user.  So far so good.  But one of the container init steps has to, among other tasks, create a local user inside of the container and it can't do that unless it's running as root.  I think what I really want (and I could be convinced I'm wrong) is for the container init scripts to be run as root and the rest of the init (including starting s6-svscan and s6-supervise and the run files) to run as the specified user.  Does that sound like a reasonable idea? Is there a way to do that? Or is there a better way to accomplish what I am trying to do?

I would be grateful for any suggestions
Howard

**Comment by jprjr** [comment]
Well my first question is, what are you trying to do? Like, why are you trying to create a user when the container starts, instead of creating it while building the image? Plus, I assume your plan is to run things as that user, but only root can change users.

I would probably just start the container as root and ensure service scripts drop privileges as appropriate, personally.

The only work-around is to write a binary with the `SUID` bit set to force it to run as root. Emphasis on binary, the kernel will ignore the `SUID` bit if it's set on a script. There's work-arounds to "compile" shell scripts into binaries.

But if the user can just be created when the image is built, instead of when the container is run, that would be way simpler.

**Comment by jprjr** [comment]
One small tip, depending on the use here - I've had cases where I want to run something via `CMD` as Not Root (it was an interactive app). So if the goal of `USER` was more around running `CMD` as not root, you can use something like this:

```Dockerfile

ENTRYPOINT ["/init", "/usr/bin/execlineb", "-S0", "-c", "emptyenv export HOME /home/someuser s6-setuidgid someuser $@" ]
CMD ["/bin/sh"]
```

Depending on the app you may need to add some more environment variables, though typically `HOME` is good enough. That will make `CMD` run as `someuser`, the user can still specify their own commands, they'll all run as whichever user you specify with `s6-setuidgid (username)`

**Comment by HowardLander** [comment]
HI John:

Thanks so much for the replies.

The user can be different every time the docker is started.  The only way I know how to create a user while building the image requires you to specify the user name at build time and I don't want a separate docker image for every possible user.  If there is a way around this restriction I would love to know it.

More specifics about what I am trying to do: we are building a docker that includes Guacamole, Guacd, VNC and XFCE to create a virtual desktop inside an image. This is being done for various data security reasons. This docker is run inside of a platform where the user has already logged in, so the user name is known at start time. The running image is started as root inside a kubernetes cluster.  It uses a container init script to create the required user (we pass the user name from the platform) and set up the VNC environment.  There are a number of additional processes that are started by run scripts: these do successfully use s6-setuidgid to run as the newly created user.  The issue is that several of the s6 programs (s6-svscan and s6-supervise) continue to run as root and our system admins would prefer they didn't. So I tried the USER variable, but of course now the s6 startup cannot create the required user.

I hope that gives a clearer picture of what I am trying to accomplish

Thanks again for any input/suggestions.  I'll read your previous replies more carefully to see if what I need is already there.

Howard

**Comment by jprjr** [comment]
Your fundamental issue here is even after you create the user, you won't have a great way to start processes as that new user. s6-setuidgid, for example, requires root.

This is definitely getting way outside the scope of `s6-overlay` and more into solution architecture. Off the top of my head there's a few ways to accomplish this, but `s6-overlay` isn't really involved. Plus I'll be honest, I'm not comfortable providing this much "outside the scope of this repo" support on another project, I hope you understand.
