### ISSUE TITLE
[Question] Extension of the files in the cont.init.d

### ISSUE THREAD

**Issue by MiguelNdeCarvalho** [just-containers/s6-overlay#332]
Hey,

First of all thanks for creating `s6-overlay`, I have an question, in the documentation you never put an extension in the init scripts, but I am using `super-lint` github actions to lint the code and it doesn't detect my current scripts as scripts because it doesn't have the extension. Can I add it? Will it be an issue?

Thanks,
MiguelNdeCarvalho

**Comment by joeflateau** [comment]
@MiguelNdeCarvalho what happens when you rename the files and run your container? That will give you your answer

**Comment by MiguelNdeCarvalho** [comment]
> @MiguelNdeCarvalho what happens when you rename the files and run your container? That will give you your answer

Hey,

It run just fine, but I was advised by some people not to do that. That's why I asked that in here, so the people who are developing it can help me answering this.

Thanks,
MiguelNdeCarvalho

**Comment by skarnet** [comment]
`/etc/cont-init.d` doesn't care about your file names or file extensions, it only wants the files to be executable.
Rename your files to your heart's content. ;-)

**Comment by MiguelNdeCarvalho** [comment]
Thanks!
