### ISSUE TITLE
Documentation for stage-3 does not reflect that actual order of events 

### ISSUE THREAD

**Issue by nigelgbanks** [just-containers/s6-overlay#333]
According to the README [here](https://github.com/just-containers/s6-overlay/blame/51467be3d14568e821d018fbb6ffeaf79479ef80/README.md#L130-L136).

> 3. **stage 3**: This is the shutdown stage. It will:
    1. Send a TERM signal to all supervised services.
    2. Run any finalization scripts contained in `/etc/cont-finish.d` - this is done while services may still be shutting down.
    3. Wait on all services to finish (up to `S6_SERVICES_GRACETIME` milliseconds (default `3000`)).
    4. Send all processes a `TERM` signal.
    5. Sleep `S6_KILL_GRACETIME` milliseconds (default `3000`)
    6. Send all processes a `KILL` signal.
    
Step 3.1 does not occur in the script [init-stage3](https://github.com/just-containers/s6-overlay/blob/51467be3d14568e821d018fbb6ffeaf79479ef80/builder/overlay-rootfs/etc/s6/init/init-stage3) the first TERM signal is sent in step 3.4, which means `S6_SERVICES_GRACETIME` is waiting for nothing, and will always exit with the message `s6-svwait: fatal: timed out` regardless of the value given.

**Comment by nigelgbanks** [comment]
This only seems to happen when doing a `docker run` that is not detached. Then using `CTRL-C` to stop. Oddly enough if one uses `docker kill --signal INT` then this does not occur. Not sure what the difference is here.

**Comment by skarnet** [comment]
Sorry for the delay in answering.

This is a known issue that was difficult to fix with the previous version of s6-overlay.
s6-overlay-3.0.0.0 is out now, and it should solve the problem.
