### ISSUE TITLE
Source tarfile has only some scripts executable and only some dirs in overlay-rootfs

### ISSUE THREAD

**Issue by dermotbradley** [just-containers/s6-overlay#334]
I'm using Release's Source Code tarfile, rather than the nobin tarfile, when creating Alpine packages of s6-overlay.

Whilst looking into an issue raised in #329 I realised that some of the execlineb scripts in the Source Code tarfile have execute permission but others do not. Likwise there are some directories missing from inside the overlay-rootfs directory but others do exist.

I realise I could/should probably use the nobin tarfile as a basis for packaging - from memory I did use it in the past but switched to the Source Code tarfile as it was easier to work with (as its a versioned directory).

No sure if this is something you'd want to fix with the Source Code tarfile.

**Comment by skarnet** [comment]
Now that 3.0.0.0 is out, can I close this? ;-)
