### ISSUE TITLE
php-fpm doesn't write logs in log file

### ISSUE THREAD

**Issue by DoobleD** [just-containers/s6-overlay#340]
Not really an issue but rather likely me not understanding s6-overlay well enough. I apologize if this is not the right place for a usage question but I couldn't find any other place to ask.

I use s6-overlay with php-fpm. I have the following in `/etc/services.d/php-fpm/run`:

```
#!/usr/bin/execlineb -P

/usr/sbin/php-fpm7.4 -c /etc/php/7.4/fpm -F
```

The `-F` option tells php-fpm to start in the foreground. Works like a charm! However in that mode logs are not written in the usual php-fpm log file (`/var/log/php7.4-fpm.log`), but to stdout instead it seems. I run all of this in docker and php-fpm logs just show in the container logs, instead of showing in `/var/log/php7.4-fpm.log`.

I tried using simple redirections but that doesn't work. I've read the [logging documentation](https://github.com/just-containers/s6-overlay#logging) and I created `/etc/services.d/php-fpm/log/run` with:

```
#!/usr/bin/execlineb -P

logutil-service /data/log/s6/php-fpm
```

But that just creates empty current/lock/state/@... files in `/data/log/s6/php-fpm`.

Any idea how I could have php-fpm logs be written in `/var/log/php7.4-fpm.log`?

**Comment by DoobleD** [comment]
Seems execlineb doesn't support the usual redirection syntax. This works:

```
#!/usr/bin/execlineb -P

redirfd -a 1 /var/log/php7.4-fpm.log
redirfd -a 2 /var/log/php7.4-fpm.log

/usr/sbin/php-fpm7.4 -c /etc/php/7.4/fpm -F
```

Not sure this is recommended though. Any opinion on that?

**Comment by DoobleD** [comment]
My first solution doesn't use s6-log. To fix this I changed the run file with:

```
#!/usr/bin/execlineb -P

fdmove -c 2 1
/usr/sbin/php-fpm7.4 -c /etc/php/7.4/fpm -F
```

Along with this in php-fpm.conf:

`error_log = /proc/self/fd/2
`

It works, but I'm not sure to get why honestly.

**Comment by regnerisch** [comment]
I had the same problem. I also set `slowlog` to `/proc/self/fd/2` and I got some information but it seems that stdout is only getting the first line:

```
[test] [2021-05-28T08:34:48.638049324Z] [28-May-2021 08:34:48] WARNING: [pool www] child 306, script '/app/public/index.php' (request: "GET /index.php") executing too slow (3.974271 sec), logging
```
But I want to get all informations. I would expect information why / what is taking so long to process. 

Maybe someone can help me with this - if it is related to s6 overlay.

Thanks in advance.

**Comment by skarnet** [comment]
If you're using `error_log = /proc/self/fd/2` and then redirecting stderr to stdout and using `s6-log` or `logutil-service` to log stdout to an automatically rotated directory, you're doing the right thing; normally, both your stdout and your error_log should be available in your log directory.
If php-fpm has trouble writing to its stdout past the first line, I'm afraid it's unrelated to s6-overlay.
