### ISSUE TITLE
examples directory to help beginners

### ISSUE THREAD

**Issue by caljnj** [just-containers/s6-overlay#341]
Hi 

Beginner with s6-overlay and i had a real struggle getting it working. 
I read 90% of the s6 documentation and all of the readme here, and various blogs that i could find.
I tried to get it working by creating the directories and copying them into the docker container but this failed. and i wasted a lot of time. 

What helped was luckily finding this post here which gave a worked example of how to set it up: 

https://github.com/just-containers/s6-overlay/issues/291#issuecomment-612206952

Can we add a directory for examples/samples to this repo?

I'm happy to help out writing beginner-directed documentation. Though i'm not that skilled myself to be honest...

**Comment by skarnet** [comment]
Sorry for the delay in answering.

We'll try to gather common service examples in the future.
