### ISSUE TITLE
`s6-overlay/builder/overlay-rootfs/init` export command

### ISSUE THREAD

**Issue by danhalligan** [just-containers/s6-overlay#342]
The `/init` script is as follows:

```
#!/bin/execlineb -S0

##
## load default PATH (the same that Docker includes if not provided) if it doesn't exist,
## then go ahead with stage1.
## this was motivated due to this issue:
## - https://github.com/just-containers/s6-overlay/issues/108
##


/bin/importas -D /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin PATH PATH
export PATH ${PATH}
/etc/s6/init/init-stage1 $@
```

I'm fairly sure the export line should instead read:

```
export PATH="${PATH}"
```

Firstly, the `=` is necessary for assignment, and I think the quotes should be there for safety.

I maybe completely wrong because I only have a very vague understanding of what is going on here, so please ignore if this is not obviously an issue.

**Comment by skarnet** [comment]
execline is not a shell, its syntax is fairly different. ;-)
