### ISSUE TITLE
`s6-setuidgid` complains `FATAL ERROR: config file error: config file permission denied`

### ISSUE THREAD

**Issue by Deathlok666** [just-containers/s6-overlay#343]
Base image is equipped with `s6-overlay`, `ENTRYPOINT` is set to `["/init"]`.
Service start script, which is `/etc/service.d/some-service/run`, with content as follows:
```bash
#!/usr/bin/with-contenv bash
exec s6-setuidgid abc service-start-command
```
Base image's `Dockerfile` and container composition scheme is larged inspired by [linuxserver.io/docker-baseimage-alpine](https://github.com/linuxserver/docker-baseimage-alpine/blob/master/Dockerfile). The user above `abc` is created to be mapped with the UID and GID.
The `docker run` command uses environment variable `PUID` and `PGID` for user mapping, not the `-u` option provided by Docker.
The documentation on the s6 official site about `s6-setuidgid` is quite short, also as a newbie, I'm not familiar with the s6 suite. Just a big fan of `linuxserver.io` and I am astonished by how their containers are well organized with the power of `s6-overlay`, and I decided to give it a go myself. Unfortunately I ran into this problem that I cannot solve it myself.
Anyway, thanks in advance :)

**Comment by skarnet** [comment]
Sorry for the delay in answering.
If you're running your service as user `abc`, then your config file must be readable by user `abc`. Chances are it's only readable for root or something. `chmod 0644` your config file.

**Comment by skarnet** [comment]
No, I mean the config file that is read by your `some-service` daemon that is run as user `abc`, and that causes your `Permission denied` error. But I may be wrong and misinterpreting your problem. If you have a solution that works for you, don't waste any time on this. Or please paste the exact error message you're getting.
Note that `s6-applyuidgid -u $(id -u abc) -g $(id -g abc) ...` is exactly equivalent to `s6-setuidgid abc`, so it's really a question of *when* you're running the command, not *how* you write it. :-)

**Comment by Deathlok666** [comment]
> No, I mean the config file that is read by your `some-service` daemon that is run as user `abc`, and that causes your `Permission denied` error. But I may be wrong and misinterpreting your problem. If you have a solution that works for you, don't waste any time on this. Or please paste the exact error message you're getting. Note that `s6-applyuidgid -u $(id -u abc) -g $(id -g abc) ...` is exactly equivalent to `s6-setuidgid abc`, so it's really a question of _when_ you're running the command, not _how_ you write it. :-)

Weird... I cannot reproduce the problem I met before now. `s6-setuidguid` works fine now. Consider this issue solved :). I will close the issue later on. By the way, I wonder whether there is a way to control the service start sequence (or in other way `service dependency`)? Currently I use `sleep <number-of-seconds>` to delay service startup in order to get some sort of sequence. I would like to know if s6 has such features that I don't know about. Or do you have better suggestions on how to implement this? Maybe it is a bit off-topic, but thanks in advance :)

**Comment by skarnet** [comment]
With s6-overlay v3, which is now out (source only for now, but it's easy to build), you can make it so your services are started by [s6-rc](https://skarnet.org/software/s6-rc/), which allows you to declare dependencies between services - this is how you can control the start sequence and make sure that *B* does not start before *A* is ready.

The [syntax](https://skarnet.org/software/s6-rc/s6-rc-compile.html#source), however, takes some getting used to, so do not rush into this without ample amount of dedication, time and coffee. ;-)

**Comment by Deathlok666** [comment]
Understood. Thanks for the time and effort you put on this amazing project! I will close the issue now.
