### ISSUE TITLE
Healthcheck for service

### ISSUE THREAD

**Issue by scion4581** [just-containers/s6-overlay#345]
Hello!
I could not find any useful information about how I can create healthcheck call for crond is still running
How to get a list of running services?
How to get info per service?

And one more, supposing I create services while building a docker image and after start container, I decided to remove some service - what is the best way to do this?

Thanks

**Comment by scion4581** [comment]
Finally I found something s6-svstat /var/run/s6/services/cron

**Comment by dazz** [comment]
@scion4581 for your second question the answer is here: https://github.com/just-containers/s6-overlay/issues/595
