### ISSUE TITLE
Have s6-log notify on a fd when its ready so services can wait before starting up

### ISSUE THREAD

**Issue by KomailKanjee** [just-containers/s6-overlay#349]
Presently, services and their respective logging services are launched in parallel. In the following scenarios it will be beneficial for services to wait for the logging service to be fully up aka ready:

1. Error in `S6_LOGGING_SCRIPT` or any other issue preventing `s6-log` from launching
2. Log setup is not near instantaneous when setup for log service takes some time.

In above situation some stderr (when redirected to stdout) and stdout output is not logged to the appropriate log file(s) and goes to stdout/stderr.

`s6-log` already has the option `-d` which can take in a file descriptor to notify on the `notification-fd` file in the service-directory can be used to let `s6-supervise` what file descriptor to monitor.

I have some ideas around implementing this but wanted to validate the issue before implementing it in a PR form.

**Comment by skarnet** [comment]
Rejoice! The v3 version of s6-overlay is almost ready, and it comes with a way to declare dependencies between services ([s6-rc](https://skarnet.org/software/s6-rc/)) so the startup sequence is properly ordered.

**Comment by skarnet** [comment]
v3.0.0.0 is out, and you can now run your services under s6-rc , which honors readiness.
Please reopen if it's not working for you.
