### ISSUE TITLE
Fails to build / run on Ubuntu Server

### ISSUE THREAD

**Issue by a-h-abid** [just-containers/s6-overlay#355]
I'm having trouble running the s6-overlay via Docker on Ubuntu Server 20.04. I can run it fine on my Windows WSL2, but weirdly I can neither build nor run the image on Ubuntu, it shows some errors. Tried to run various ways, none worked.

**Dockerfile**
```Dockerfile
FROM debian:bullseye-slim

USER root

# S6 Overlay Setup Configuration
ADD https://github.com/just-containers/s6-overlay/releases/download/v2.2.0.3/s6-overlay-aarch64-installer /tmp/s6-overlay-installer

RUN chmod +x /tmp/s6-overlay-installer && /tmp/s6-overlay-installer /

STOPSIGNAL SIGTERM

ENTRYPOINT ["/init"]

CMD []
```

It builds fine on my WSL2, but when try to build on Ubuntu, throws the below error:

```bash
abid@abid-srv:~/s6-test$ sudo docker build -t s6-test:latest .
Sending build context to Docker daemon  2.048kB
Step 1/7 : FROM debian:bullseye-slim
bullseye-slim: Pulling from library/debian
f8416d8bac72: Already exists
Digest: sha256:e3ed4be20c22a1358020358331d177aa2860632f25b21681d79204ace20455a6
Status: Downloaded newer image for debian:bullseye-slim
 ---> 7beb0248fd81
Step 2/7 : USER root
 ---> Running in 0070167483d2
Removing intermediate container 0070167483d2
 ---> 11d02a9cdfd8
Step 3/7 : ADD https://github.com/just-containers/s6-overlay/releases/download/v2.2.0.3/s6-overlay-aarch64-installer /tmp/s6-overlay-installer
Downloading [==================================================>]  6.245MB/6.245MB

 ---> e0f0ba058f45
Step 4/7 : RUN chmod +x /tmp/s6-overlay-installer && /tmp/s6-overlay-installer /
 ---> Running in da5d783c72e4
/bin/sh: 1: /tmp/s6-overlay-installer: Exec format error
The command '/bin/sh -c chmod +x /tmp/s6-overlay-installer && /tmp/s6-overlay-installer /' returned a non-zero code: 126
```

Since I was able to build & run on WSL2, I pushed the image to [docker hub](https://hub.docker.com/r/ahabid/s6-overlay-test) & tried to run on Ubuntu using the image. It throws the below error:

```sh
abid@abid-srv:~$ sudo docker run --rm -it ahabid/s6-overlay-test:latest
standard_init_linux.go:228: exec user process caused: exec format error

abid@abid-srv:~$ sudo docker run --rm -it --entrypoint="" ahabid/s6-overlay-test:latest bash -c "/init"
/init: line 11: /bin/importas: cannot execute binary file: Exec format error
/init: line 12: export: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin': not a valid identifier
/etc/s6/init/init-stage1: line 26: syntax error near unexpected token `}'
/etc/s6/init/init-stage1: line 26: `}'
```

This is really unexpected from docker, as my expectation was that if an image runs, it will run everywhere.

Would be great if any solution is available. I built this nginx+phpfpm setup with S6-overlay and now I cannot run this on platform where I need the most.

**Comment by skarnet** [comment]
`abid@abid-srv:~$ sudo docker run --rm -it --entrypoint="" ahabid/s6-overlay-test:latest bash -c "/init"`

There's your problem. You're trying to get `/init` run by bash, but it's not a shell script.
Try `sudo docker run --rm -it --entrypoint="" ahabid/s6-overlay-test:latest /init` instead.

**Comment by a-h-abid** [comment]
@skarnet nah ... same result...

![image](https://user-images.githubusercontent.com/2020773/132231148-3aacbef4-141a-4004-b1f7-274394f6c057.png)

**Comment by skarnet** [comment]
That's not the same error at all, now we know that `/init` itself cannot be executed, which points to a problem in the format of `/bin/execlineb`. And given the exec format error from `/tmp/s6-overlay-installer`, I suspect a bad binary build. @jprjr, can you take it from here?

**Comment by jprjr** [comment]
Well, I noticed you're pulling the `aarch64` installer in your Dockerfile, but the image you pushed to Dockerhub is listed as `amd64`

Are you pulling down the right installer for your architecture?

**Comment by a-h-abid** [comment]
> Well, I noticed you're pulling the `aarch64` installer in your Dockerfile, but the image you pushed to Dockerhub is listed as `amd64`
> 
> Are you pulling down the right installer for your architecture?

You are right. Didn't noticed that I was downloading from `aarch64`. Should be `amd64`.

```
ADD https://github.com/just-containers/s6-overlay/releases/download/v2.2.0.3/s6-overlay-amd64-installer /tmp/s6-overlay-installer
```

Now it builds & runs...

![image](https://user-images.githubusercontent.com/2020773/132237900-9267cdcd-6534-4ea5-8772-7fe0400013fb.png)

Thanks @jprjr
