### ISSUE TITLE
s6-overlay package missing in alpine 3.15

### ISSUE THREAD

**Issue by ksurl** [just-containers/s6-overlay#360]
When updating my Dockerfile to use alpine 3.15, it fails to build since s6-overlay is not found when trying to install with `apk add s6-overlay`. it is there in 3.14. Will it be added later? or is there a technical reason?

previous to using the package repo version, I had used the readme method of wget/curl to grab the install script from github and run it. This became problematic when I started using multi arch builds with buildx. Kind of messy to add extra detection logic so I figure the easy way was to use the built in package repo.

**Comment by GreyXor** [comment]
https://gitlab.alpinelinux.org/alpine/aports/-/issues/12547#note_170154

**Comment by ksurl** [comment]
yep, that's how I did it before finding it was already in alpine package repo. I guess if I need to update alpine, I'll go back to that way. 

seems like dependency issue with newer alpine packages. maybe it will be resolved with the new version being developed. thanks.

**Comment by dermotbradley** [comment]
@ksurl Hi, former Alpine s6-overlay maintainer here.

Unfortunately, as mentioned in the link @GreyXor provided, I decided a little over months ago to move the Alpine package to unmaintained status.

I took this decision as fundamentally s6-overlay did not work **correctly** with recent versions of the other s6 utilities (which are separately packaged for Alpine) and, as s6-overlay development appeared to have slowed, there was no sign of this problem being addressed.

I would like see the Alpine s6-overlay package reintroduced for Alpine in the future but this really depends on s6-overlay itself being "fixed" to work with recent s6. It is hard to be a package maintainer (including dealing with any issues raised by users) when the underlying software is not actively in development.

I was actually talking with @skarnet (the s6 author) yesterday, shortly before I saw this issue, about s6-overlay's "reawakening" in the past week #358. Hopefully this can lead to an Alpine s6-overlay package again becoming feasible.

**Comment by skarnet** [comment]
Yes, the point of writing a new version of s6-overlay is to clear all the pending issues that are too difficult to fix with the current version - including the difficulty of packaging it for Alpine. :-)
As soon as it is ready, a new package will be available.
