### ISSUE TITLE
Turn off timestamps (T) in logutil-service

### ISSUE THREAD

**Issue by erikvanzijst** [just-containers/s6-overlay#361]
When using `logutil-service`, it always starts `s6-log` with "T" in the logging script.

In program being logged however already emits accurate timestamps for each line and so I'd like to turn off the redundant timestamps inserted by `s6-log`.

Is there a way to do this with `logutil-service`, or is it [hardwired behavior](https://github.com/just-containers/s6-overlay/blob/master/builder/overlay-rootfs/usr/bin/logutil-service-main#L4)?

**Comment by skarnet** [comment]
If it's the case for all your services: you can change the behaviour via the `S6_LOGGING_SCRIPT` variable when starting the container.
Try `S6_LOGGING_SCRIPT="n20 s1000000"`.

If you want to customize behaviour depending on the service, then you need to use `s6-log` directly, without the `logutil-service` wrapper.

**Comment by erikvanzijst** [comment]
Ah yeah that works perfectly, thanks!
