### ISSUE TITLE
[Question] Manually executing service?

### ISSUE THREAD

**Issue by zsQ8ymRSY8B4owpdCvTRdkz8rQUK** [just-containers/s6-overlay#365]
If I make a service in services.d it automatically runs the script.

How do I instead manually invoke the script and not have it auto-run on container startup?

My use case is I have a cronjob on my host machine that I want to periodically execute a maintenance script in my s6-overlayed docker container.

I need the script to run with pid1 to get proper docker logs.

**Comment by skarnet** [comment]
Add a `down` file in your service directory, so the service won't run on startup. When you want to run the service, use `s6-svc -o` on the service directory: this will execute your `run` script once.

**Comment by zsQ8ymRSY8B4owpdCvTRdkz8rQUK** [comment]
```
root@016ba71e0161:/app# s6-svc -o /etc/services.d/yt-subsync
s6-svc: fatal: unable to control /etc/services.d/yt-subsync: supervisor not listening
```

I've searched documentation and it says svc-supervisor shouldn't be run manually. How do I get it to supervise my service?

Also, am I able to run the service as a specific user? I get permission errors if I try to invoke s6-svc as non-root.

**Comment by skarnet** [comment]
Please have a little patience, I'm working on getting s6-overlay v3 out as soon as possible. Any problem you're currently experiencing should go away with the new version.

**Comment by zsQ8ymRSY8B4owpdCvTRdkz8rQUK** [comment]
No problem. Thanks for the great work.

**Comment by skarnet** [comment]
Now that s6-overlay v3 is out, can I close this?
(I'm preparing the next release and trying to close as many issues as possible.)

Note that even in v3, the service directories in `/etc/services.d` aren't the live ones, so it's normal that `s6-svc` fails. In v3, the live service directories are accessible via `/run/service`, so `s6-svc -o /run/service/yt-subsync` should accomplish what you want.

**Comment by skarnet** [comment]
Closing this, please reopen if your problem isn't solved.
