### ISSUE TITLE
release v3.0.0.0 missing download link

### ISSUE THREAD

**Issue by AdamEscamilla** [just-containers/s6-overlay#367]
my scripts pull latest realease using download link but latest release seems to be missing

**Comment by GreyXor** [comment]
Hi @AdamEscamilla 
it lacks an automated release process : https://github.com/just-containers/s6-overlay/issues/358#issuecomment-1016552954

For the moment you have to build it yourself, as seen here : https://github.com/just-containers/s6-overlay#building-the-overlay-yourself

**Comment by skarnet** [comment]
Yup, waiting for @jprjr to set up the CI/CD so pre-built tarballs can be found on github. It may take a few days, please build from source for now 😅

**Comment by AdamEscamilla** [comment]
np, just seen its a major upgrade :) looking forward to 3.x, thanks guys
