### ISSUE TITLE
socklog overlay support for 3.0.0.0?

### ISSUE THREAD

**Issue by crazy-max** [just-containers/s6-overlay#368]
It looks like [socklog](https://github.com/just-containers/socklog) is [not currently included](https://github.com/just-containers/s6-overlay/blob/master/conf/versions) in the build system.

FWIW I use socklog to receive syslog messages for Docker containers on stdout. This is useful for a seamless integration with docker logs. Some examples:
* pure-ftpd (ftp): https://github.com/crazy-max/docker-pure-ftpd/blob/master/rootfs/etc/socklog.rules/pure-ftpd
* postfix (mail): https://github.com/anonaddy/docker/blob/master/rootfs/etc/socklog.rules/mail

Is it planned to be supported or is there a way to build it myself without patches with the current build system?

Thanks!

**Comment by skarnet** [comment]
There is a [s6-socklog](https://skarnet.org/software/s6/s6-socklog.html) program, part of the s6 package, included in the overlay now.

With v3.0.0.0, everything is integrated in the s6-overlay package; the other packages from just-containers are all obsoleted, save for `s6-overlay-helpers` which gather the remaining s6-overlay-specific binary utilities.

**Comment by crazy-max** [comment]
Perfect thanks!
