### ISSUE TITLE
unreachable download links

### ISSUE THREAD

**Issue by C4F3Z1N** [just-containers/s6-overlay#373]
the release/download links mentioned in lines [#46](https://github.com/just-containers/s6-overlay/blob/beb21d9d724b816bd05cffe66b9683036f6c7d8b/README.md?plain=1#L46) and [#48](https://github.com/just-containers/s6-overlay/blob/beb21d9d724b816bd05cffe66b9683036f6c7d8b/README.md?plain=1#L48) are unreachable 😥

**Comment by skarnet** [comment]
They'll be coming when the CI is in place, just a little more patience 😉

**Comment by jprjr** [comment]
Solved as of release 3.0.0.0-1
