### ISSUE TITLE
$HOME is still set as `/root` after dropping privileges.

### ISSUE THREAD

**Issue by lemniskett** [just-containers/s6-overlay#374]
Hi, I have a user named `odoo` in the container with its home located in `/opt/odoo`, but apparently dropping privilege with `s6-setuidgid` doesn't change the user home directory, below is the output of `id`, `env | grep HOME`, and `cat /etc/passwd | grep odoo` executed by the service.

![Screenshot from 2022-01-22 15-12-08](https://user-images.githubusercontent.com/43294321/150630582-c728075a-1bac-4c9c-96dd-c6f8d35fdef9.png)

**Comment by skarnet** [comment]
Dropping privileges isn't the same thing as logging in. You shouldn't expect HOME, or any other user-related environment variables, to be set after using `s6-setuidgid`. If you want to *log in* as a user, not just *drop privileges* to a user, use `su -l`.

**Comment by lemniskett** [comment]
Thanks! I'll just export the needed variables instead.
