### ISSUE TITLE
fatal with S6_KEEP_ENV

### ISSUE THREAD

**Issue by GreyXor** [just-containers/s6-overlay#377]
Hi, I would like to take advantage of the S6_KEEP_ENV configuration variable to have access to my environment variables but I get a fatal error

Dockerfile to reproduce error
```Dockerfile
FROM alpine

ENV S6_KEEP_ENV=1

RUN apk add --no-cache curl && \
    S6_OVERLAY_VERSION=3.0.0.0-1 && \
    curl -sSL "https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch-${S6_OVERLAY_VERSION}.tar.xz" | tar -xJf - -C / && \
    curl -sSL "https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-x86_64-${S6_OVERLAY_VERSION}.tar.xz" | tar -xJf - -C /

ENTRYPOINT ["/init"]

```
Error :
`s6-rc-compile: fatal: unable to opendir /etc/cont-profile.d//s6-overlay/s6-rc.d: No such file or directory`

without `S6_KEEP_ENV` I can have the normal behavior

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
```

https://github.com/just-containers/s6-overlay/issues/358

**Comment by skarnet** [comment]
Do you have a `S6_RUNTIME_PROFILE` environment variable in your host environment? If so, please try after unsetting it.

**Comment by GreyXor** [comment]
Neither host or guest have `S6_RUNTIME_PROFILE` setted

**Comment by skarnet** [comment]
Confirmed, it's a bug, going to fix it. Thanks.

**Comment by skarnet** [comment]
Should be fixed in the latest git head, if you can build from source please tell me if it works for you. Otherwise, we'll try and do another release towards the end of this week, with all the early bugs fixed.

**Comment by GreyXor** [comment]
It works ✅. Thanks
