### ISSUE TITLE
unable to ttyname stdout and exit

### ISSUE THREAD

**Issue by pubyun** [just-containers/s6-overlay#381]
$ sudo docker run --rm=true -ti  docker.example.com/pubyun/debian /bin/sh                                                                                                              <<<
s6-linux-init: warning: unable to ttyname stdout: No such file or directory
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

$ cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)

**Comment by skarnet** [comment]
Is the `/proc` filesystem mounted in your container by Docker? That is a prerequisite for using `-it` with s6-overlay.

**Comment by pubyun** [comment]
thanks.

it runs ok without -it option

then how can mounted /proc? it still exit with same error:

sudo docker run --rm=true -v /proc/:/host/proc/:ro -ti  docker.pubyun.com/pubyun/debian /bin/zsh                                                                                     <<<
s6-linux-init: warning: unable to ttyname stdout: No such file or directory
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by skarnet** [comment]
Don't mount it read-only, that will probably work better 😄

**Comment by pubyun** [comment]
same message without read-only

sudo docker run --rm=true -v /proc/:/host/proc/ -ti  docker.pubyun.com/pubyun/debian /bin/zsh
s6-linux-init: warning: unable to ttyname stdout: No such file or directory
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by skarnet** [comment]
Can you get a shell in the container (use `s6-pause` as your CMD in order to avoid exiting immediately, then run `docker exec -it container_name sh`) and tell me what `ls -l /proc/1/fd` says?

**Comment by pubyun** [comment]
# ls -l /proc/1/fd
total 0
lr-x------ 1 root root 64 Jan 26 14:40 0 -> /dev/null
l-wx------ 1 root root 64 Jan 26 14:40 1 -> 'pipe:[754047288]'
l-wx------ 1 root root 64 Jan 26 14:40 2 -> 'pipe:[754047289]'
l-wx------ 1 root root 64 Jan 26 14:40 3 -> /run/service/.s6-svscan/lock
lr-x------ 1 root root 64 Jan 26 14:40 5 -> /run/service/.s6-svscan/control
l-wx------ 1 root root 64 Jan 26 14:40 6 -> /run/service/.s6-svscan/control
lrwx------ 1 root root 64 Jan 26 14:40 7 -> 'anon_inode:[signalfd]'

**Comment by skarnet** [comment]
My bad, wrong testing command, sorry.
Please try `ls -l /proc/1/fd` in a pid 1 shell, obtained via your `docker run -it` invocation with your `-v` mounting option, but also with `--entrypoint=/bin/sh`.

**Comment by pubyun** [comment]
docker run --entrypoint=/bin/sh --rm=true -v /proc/:/host/proc/ -ti  docker.pubyun.com/pubyun/debian
# ls -l /proc/1/fd
total 0
lrwx------ 1 root root 64 Jan 27 22:45 0 -> /8
lrwx------ 1 root root 64 Jan 27 22:45 1 -> /8
lrwx------ 1 root root 64 Jan 27 22:45 10 -> /dev/tty
lrwx------ 1 root root 64 Jan 27 22:45 2 -> /8

**Comment by skarnet** [comment]
Thanks! There's your problem: the symlinks in `/proc/$pid/fd` are incorrect. `/8` makes no sense; it should be something like `/dev/pts/8` instead.
I'm not sure what causes it; it could be a misconfiguration either in the kernel (`/proc` or `/dev/pts` options), or, more likely, in the way Docker mounts the pseudo-filesystems.
Please check that your container setup mounts `/dev` and `/dev/pts` at start time,  and compare with working containers (any minimal container, e.g. `FROM busybox` or `FROM alpine`, will do) where `/proc/1/fd/1` should be a symlink to `/dev/pts/something`.

I am sorry you encountered that issue - unfortunately, that's not a problem we're able to fix because it's not caused by s6-overlay.

**Comment by jprjr** [comment]
I think the reason for that `/8` symlink not making sense may be due to manually mounting `/proc`. Docker should just create the correct `/proc` and `/dev` filesystem. Looking at the `debian:11` image, `/dev` and `/proc` are just empty directories.

I suspect the error is in the build process somewhere. I tried pulling `docker.pubyun.com/pubyun/debian:latest` to try and recreate, but it's using an older version of `s6-overlay`.

Please provide a `Dockerfile` that demonstrates the issue.

**Comment by pubyun** [comment]
`FROM debian:stable

ARG S6_OVERLAY_VERSION=3.0.0.2
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -y \
    && apt-get install -y openssh-server vim xz-utils \
    && apt-get clean

ADD https://mirrors.pubyun.com/bitcomm/s6-overlay-noarch-${S6_OVERLAY_VERSION}.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-noarch-${S6_OVERLAY_VERSION}.tar.xz
ADD https://mirrors.pubyun.com/bitcomm/s6-overlay-x86_64-${S6_OVERLAY_VERSION}.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-x86_64-${S6_OVERLAY_VERSION}.tar.xz

ENTRYPOINT ["/init"]
`

**Comment by skarnet** [comment]
It works for me with this exact Dockerfile.
```
$ docker run -it test1 /bin/sh
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
# ls -l /proc/1/fd/1
lrwx------ 1 root root 64 Feb  1 15:45 /proc/1/fd/1 -> /dev/pts/0
```

**Comment by jprjr** [comment]
Same. I had to fix the posted Dockerfile (it was missing some newline escapes).

But with this Dockerfile:

```Dockerfile
FROM debian:stable

ARG S6_OVERLAY_VERSION=3.0.0.2
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -y \
&& apt-get install -y openssh-server vim xz-utils \
&& apt-get clean

ADD https://mirrors.pubyun.com/bitcomm/s6-overlay-noarch-${S6_OVERLAY_VERSION}.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-noarch-${S6_OVERLAY_VERSION}.tar.xz
ADD https://mirrors.pubyun.com/bitcomm/s6-overlay-x86_64-${S6_OVERLAY_VERSION}.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-x86_64-${S6_OVERLAY_VERSION}.tar.xz

ENTRYPOINT ["/init"]
```

I can launch and get to a command prompt:

```
$ $ docker run --rm=true -it test /bin/sh
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
# 
```

**Comment by pubyun** [comment]
we run docker-1.13.1 on centos 7.9, it failed.  it works ok on centos 8. 
```

docker-1.13.1-208.git7d71120.el7_9.x86_64

# uname -a
Linux install.bitcomm.cn 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 10
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 66aedde759f33c190954815fb765eedc1d782dd9 (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
Kernel Version: 3.10.0-1160.53.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 4
Total Memory: 7.638 GiB
Name: install.bitcomm.cn
ID: DMZT:ZNOU:MYPR:KL7E:QVSA:ONEG:FDD7:IISK:33XZ:6TZ2:4ZRO:VQSN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: docker.io (secure)

```

**Comment by skarnet** [comment]
Then it's probably a CentOS 7.9 bug, which they fixed. Glad it's working for you now.
