### ISSUE TITLE
Workdir modified

### ISSUE THREAD

**Issue by Kyos** [just-containers/s6-overlay#385]
Hi, 

I've switched to the 3x version of s6-overlay and I found a strange behavior regarding docker workdir and I'd like to have your opinion (I can't tell if it's a bug or a new behavior but I haven't found anything on the documentation and other issues).

To reproduce I used this minimal dockerfile :  

```
FROM debian:bullseye

RUN apt-get update && apt-get install xz-utils && mkdir /app

ADD https://github.com/just-containers/s6-overlay/releases/download/v3.0.0.1/s6-overlay-noarch-3.0.0.1.tar.xz /tmp
RUN ls /tmp/ && tar -C / -Jxpf /tmp/s6-overlay-noarch-3.0.0.1.tar.xz
ADD https://github.com/just-containers/s6-overlay/releases/download/v3.0.0.1/s6-overlay-x86_64-3.0.0.1.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-x86_64-3.0.0.1.tar.xz

WORKDIR /app
```

You can simply build it using : 

`docker build --rm -t test:test .`

When I simply launch this image using : 

```
docker run -ti --rm --entrypoint="/init" test:test bash
```

I can see that I am no longer in /app but in /

Is this an expected behavior with the new version to reset the docker workdir ?

Thanks by advance :)

**Comment by skarnet** [comment]
I'm not sure how Docker implements WORKDIR, but if it's just the cwd of pid 1, then yes, the new version puts you into `/` when it boots.
I'll find a workaround so that WORKDIR is honored, thanks for the report.

**Comment by skarnet** [comment]
@Kyos If you can build from source, can you try the latest version and tell me if it works for you?

**Comment by Kyos** [comment]
@skarnet I just did and it works like a charm.

Thank you very much for the fix !

**Comment by skarnet** [comment]
Awesome, thanks. We'll include the fix in the next version.
