### ISSUE TITLE
I/O in `cont-init.d` scripts

### ISSUE THREAD

**Issue by shriphani** [just-containers/s6-overlay#391]
Hi everyone, 

Thank you very much work your work on this project. I am trying to set up a one-time executing script for use with s6. I put this script in `/etc/cont-init.d/script`. The script is executable and the init / bootstrap process shows that it is being executed with exit code 0. However, there are lines in the scripts that redirect output to files. I see the target files being created but empty.

The contents of `/etc/cont-init.d/script`

```
#!/bin/sh
WORKDIR=/script-job-dir
PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LANG=C.UTF-8
GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568
PYTHON_VERSION=3.8.12
PYTHON_PIP_VERSION=21.2.4
PYTHON_SETUPTOOLS_VERSION=57.5.0
PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/3cb8888cc2869620f57d5d2da64da38f516078c7/public/get-pip.py
PYTHON_GET_PIP_SHA256=c518250e91a70d7b20cceb15272209a4ded2a0c263ae5776f129e0d9b5674309
echo script-running > /script.log
cd $WORKDIR
/bin/sh -c python hello_world.py
```

I can see the path `/script.log` just fine (result from the line `echo script-running > /script.log` but it is empty. What am I missing?

Also if it helps, I am running s6 as the init for a firecracker vm but IMO there should be no difference to the docker setup since everything else seems to be ok.

**Comment by shriphani** [comment]
Ok I managed to fix it - turns out I don't have `/proc` so I added this line to my script:

`mount -t proc proc /proc`

And the final script was:

```
#!/bin/sh -e
mount -t proc proc /proc
WORKDIR=/script-job-dir
PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LANG=C.UTF-8
GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568
PYTHON_VERSION=3.8.12
PYTHON_PIP_VERSION=21.2.4
PYTHON_SETUPTOOLS_VERSION=57.5.0
PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/3cb8888cc2869620f57d5d2da64da38f516078c7/public/get-pip.py
PYTHON_GET_PIP_SHA256=c518250e91a70d7b20cceb15272209a4ded2a0c263ae5776f129e0d9b5674309
echo script-running > /script.log
cd $WORKDIR
/bin/sh -c python hello_world.py
```

Do you have a collection of best practices such as what to mount where etc for init scripts? Might be helpful in case things dont work out.

**Comment by skarnet** [comment]
There is a pretty important difference between a VM setup and a container setup. In a container, the container manager sets up a lot of things for you beforehand, such as pre-mounting `/dev` and `/proc`. In a VM, you have to do everything from scratch like on real metal.

s6-overlay is really meant for containers and is tailored to that use case. If you want to run a VM with s6 as your init, you may want to read on the details of [s6-linux-init](https://skarnet.org/software/s6-linux-init/) and install it yourself instead, so you have complete free reign on what is running on your VM.

**Comment by shriphani** [comment]
Thank you very much - we're going to pursue this route you suggested. I really appreciate the help.
