### ISSUE TITLE
/package/admin/s6-overlay-3.0.0.2/etc/s6-rc/scripts/cont-init: errors starting programs

### ISSUE THREAD

**Issue by markster101** [just-containers/s6-overlay#393]
Running Debian with S6-overlay and using /etc/cont-init.d directory to start cron.

Example -> 10-cron
#!/usr/bin/with-contenv sh
/etc/init.d/cron start

I am getting the following errors 

s6-rc: info: service legacy-cont-init: starting
"cont-init: info: /etc/cont-init.d/10-cron exited 127

This used to work in older version. Am I doing it wrong? 
Please suggest the fix.

**Comment by skarnet** [comment]
It is a mistake to import the PATH variable from the host container, even with `with-contenv`; previous versions of s6-overlay accepted it, but we fixed that in v3 by removing PATH from the list of imported environment variables.

The default PATH in your services is `/command:/usr/bin:/bin`; if you need other directories there, set an appropriate PATH in every service.
You can also change the default PATH by modifying the `/etc/s6-overlay/config/global_path` in version 3.0.0.2, or via the `S6_GLOBAL_PATH` environment variable in version 3.1.0.0 which will be released soon (or in the s6-overlay git head).

**Comment by markster101** [comment]
Thank you for clarification. I specified PATH for each program and it works as intended. 
It would be good to mention this in release notes. 

—mark

**Comment by skarnet** [comment]
Will do.
