### ISSUE TITLE
Add /usr/local/bin to default PATH

### ISSUE THREAD

**Issue by mwgamble** [just-containers/s6-overlay#395]
I think it would be immensely helpful if `/usr/local/bin` was added to the default `PATH`, rather than expecting users to manually include it. It's common for language package managers such as `pip` and `npm` to install binaries in there, and I'm sure users have come to expect that it's just always included out of the box.

Either that, or there should be a way to merge custom `PATH` additions with the default `PATH`, so that you don't have to manually re-specify the default `PATH` just to prepend a folder to it.

**Comment by skarnet** [comment]
The 3.0.0.2 way to merge custom PATH additions to the default PATH is the `/etc/s6-overlay/config/global_path` file.
This has been reported by several users as inconvenient, so in 3.1.0.0 it will change and you will be able to specify the global path in the `S6_GLOBAL_PATH` variable, that you can change in your Dockerfile.

**Comment by mwgamble** [comment]
That feels like a canned response to my issue. Sorry if I didn't make this clear, but I'm aware of both `/etc/s6-overlay/config/global_path` and `S6_GLOBAL_PATH`.

I'm asking if an alteration can be made to the defaults. If that isn't palatable, I'm also wondering if it's possible for a "better" approach to custom `PATH` additions to be implemented that involves combining the default `PATH` with the custom additions, rather than the current system that only supports full replacement.

**Comment by skarnet** [comment]
Sorry for misinterpreting your request.

The optimal default global path being distribution- and image-specific, no, we don't plan on changing it soon. You need `/usr/local/bin`, but other images don't; some people will need `/opt/jre/bin`, others will not, etc. Adding extra directories to the default global path is a slippery slope which will only end in a bloated PATH for everyone. It's much saner to let users explicitly specify the global path they need.

You don't have to re-specify the default path in `S6_GLOBAL_PATH` or `/etc/s6-overlay/config/global_path`, you can just list the path directories you need. Unless there's a bug in the [existing merge](https://github.com/just-containers/s6-overlay/blob/master/layout/rootfs-overlay/init#L9), s6-overlay will automatically add `/command`, `/usr/bin` and `/bin` to the PATH if these directories aren't already there.

I will make it clearer in the `S6_GLOBAL_PATH` documentation - which I wanted to keep concise, but better be accurate than concise.

**Comment by mwgamble** [comment]
I wasn't aware of the merge functionality, so it would definitely be good to have that documented. It's a critical component of how the "global path" functionality will be used.

To be fair to my request, I think `/usr/local/bin` is quite different from just any other possible directory that could be added to `PATH`. It's in `PATH` by default in just about every single user's personal machine, and by default in just about every production Linux environment you can find. It was included by default in v2 of s6-overlay too.

However I respect your decision and appreciate your consideration :pray: Thank you for your time.

**Comment by felipecrs** [comment]
There would be also `/sbin`, `/usr/sbin`, `/usr/local/sbin` as well. If these 4 gets added, the default PATH would be at least equal to a minimum base image like Alpine:

```console
❯ docker run --rm alpine sh -c 'echo $PATH'
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

**Comment by felipecrs** [comment]
But I do think it would be nice if there was an option like:

```console
S6_USE_PATH_IN_GLOBAL_PATH=1
```

Which would simply restore the previous behavior of S6 Overlay v2, i.e. it will leverage the `PATH` environment variable.

**Comment by mwgamble** [comment]
> There would be also /sbin, /usr/sbin, /usr/local/sbin as well.

On most modern systems, `/sbin`, and `/usr/sbin` are symlinks to `/usr/bin`.

For that matter, so is `/bin`.

So I guess there is still an argument that the defaults should be updated, given most users will be using debian-based images where these symlinks are in place.

**Comment by skarnet** [comment]
Okay, @felipecrs convinced me in another issue - `S6_GLOBAL_PATH` is unnecessary, we can simply use the value of `PATH`, as defined in the Dockerfile, for the global path. (It will still be modified to make sure it contains at least `/command`, `/usr/bin` and `/bin`.)

Closing this; please reopen if things still aren't working for you when 3.1.0.0 comes out - or earlier if you build s6-overlay from the latest source.
