### ISSUE TITLE
read only file system

### ISSUE THREAD

**Issue by guoard** [just-containers/s6-overlay#397]
I have a docker file with `ENV S6_READ_ONLY_ROOT=1`

but when i try to run it by this command `docker container run --read-only --tmpfs /run -p 8000:8000 <image-name>` 
or this one `docker container run --read-only -p 8000:8000 <image-name>`

I get this error:
```bash
/package/admin/s6-overlay/libexec/preinit: info: read-only root
/package/admin/s6-overlay/libexec/preinit: info: writable /run. Remounting exec just in case.
s6-mount: fatal: unable to mount tmpfs on /run: Operation not permitted
/package/admin/s6-overlay-3.0.0.2/libexec/stage0: 80: exec: /run/s6/basedir/bin/init: Permission denied
```
But it works perfectly without a read-only file system

If you had such a problem, it would be great if you share your experience

**Comment by skarnet** [comment]
Your Docker setup is pre-mounting `/run` as a tmpfs, which is a good thing, but it is pre-mounting it with the `noexec` option, which is a common configuration mistake but prevents s6-overlay from working.
You need to find where your setup pre-mounts `/run`, and make sure it doesn't mount it noexec. Something like `--mount type=tmpfs,dst=/run,exec` should do the trick.

**Comment by guoard** [comment]
I could run s6-overlay in a read-only file system **without** `ENV S6_READ_ONLY_ROOT=1` but it also need `/tmp` directory as tmpfs
my command: `docker container run -p 8000:80 --read-only --tmpfs /run:exec --tmpfs /tmp <image-name>`

when run **with** `ENV S6_READ_ONLY_ROOT=1` it also works but gives me this warning before starting:
```
/package/admin/s6-overlay/libexec/preinit: info: read-only root      
/package/admin/s6-overlay/libexec/preinit: info: writable /run. Remounting exec just in case.
s6-mount: fatal: unable to mount tmpfs on /run: Operation not permitted
s6-rc: info: service task: starting                                                                                                                                                                                
s6-rc: info: service cron: starting                                                                      
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service task successfully started
s6-rc: info: service cron successfully started
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service nginx successfully started
...
```

**Comment by skarnet** [comment]
- The `/tmp` filesystem isn't used anywhere by s6-overlay, but lots of software assume it's there. It's probably your services that need `/tmp`; in any case it's a good idea to have it as a tmpfs (with `01777` rights).
- The s6-mount error is normal since by default Docker does not give the `CAP_SYS_ADMIN` capability to containers; that is why it's better to pre-mount `/run` exec yourself, because by default s6-overlay cannot do it for you. (It can if you tell Docker to start the container with `CAP_SYS_ADMIN`, but it's easier and more secure just to pre-mount `/run`.) I will change the error message so that it's less intimidating.

**Comment by guoard** [comment]
unfortunately, docker does not have `exec` option for `tmpfs` in docker swarm in the other word you can't remove `noexec` from this command: `--mount type=tmpfs`

more detail in this [issue](https://github.com/moby/moby/issues/32131)

so I think it's impossible to use it with docker swarm!

**Comment by skarnet** [comment]
:-(
But seeing as how long it has taken for us to release a new version of s6-overlay, I can't really blame Docker for being slow on fixing that bug...

Until Docker Swarm is fixed, the workaround is to give the `CAP_SYS_ADMIN` capability to your container, and s6-overlay will then be able to remount `/run` exec for you. It shouldn't be a security issue if you have proper privilege separation in your services.

**Comment by NicolasCARPi** [comment]
Issue to follow for mounting with exec and docker-compose: https://github.com/compose-spec/compose-spec/issues/176

**Comment by skarnet** [comment]
There isn't much more we can do on our side, so I'm closing this issue.

**Comment by k3a** [comment]
Why is executable permission necessary in /run mount? It sounds like a bad design to me. IMO, executable code should be read-only and writable paths should be noexec for better security. All other containers which I have deployed can be deployed this secure way. Except s6-based ones. :(

**Comment by skarnet** [comment]
It is unfortunately a pretty common misconception that having `/run` executable is a security concern, but the reality is that it is not an issue at all - no more than having your `$HOME` executable. W^X is only helpful when privilege boundaries can be crossed, which is not the case at all for `/run`. `/run` belongs to root and only root, and is only writable by root; if you can write to it, you are already root on the system, and there's nothing an executable can do that an attacker couldn't already have done.

Now please go teach your distribution, or the people who mount your containers, that having a noexec `/run` doesn't do *anything at all* for security, and that cargo culting is harmful.
