### ISSUE TITLE
S6-overlay 3.0.0.2: oneshot service ran as execlineb even when the shebang is bash

### ISSUE THREAD

**Issue by edgd1er** [just-containers/s6-overlay#400]
I'm trying to use oneshot service to replace cont-init script.
Even if the shebang is bash, the script is ran as the shebang was an execlineb. only the first line run executed whatever is the first line

Is it a misusage from me ? is the a way to execute sereval commands in a oneshot service ?

I placed the hereunder script in /etc/s6-overlay/s6-rd.d/my-init/up
an empty file is in /etc/s6-overlay/s6-rc.d/user/contents.d/my-init

```
#!/command/with-contenv bash

foreground     # an unquoted string, evaluated to: foreground
{              # A single opening brace, not included in the argv
  /etc/s6-overlay/s6-rc.d/my-init/05-changer-uid-gid.sh
  s6-echo "Starting 05-changer-uid-gid.sh"
  echo "starting 20-start.sh"
  /etc/s6-overlay/s6-rc.d/my-init/20-start.sh
}
``` 

# Please provide a small Dockerfile that demonstrates your issue.

Dockerfile
```
FROM debian:bullseye-slim

ENV S6_ARCH=x86_64
ENV S6_OVERLAY_VERSION=3.0.0.2
ENV S6_GLOBAL_PATH=/command:/usr/bin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin:/bin

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
#hadolint ignore=DL3008
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends ca-certificates tar curl procps xz-utils vim
RUN curl -sSL https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch-${S6_OVERLAY_VERSION}.tar.xz | tar -Jxpf - -C /  \
    && curl -sSL https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-${S6_ARCH}-${S6_OVERLAY_VERSION}.tar.xz | tar -Jxpf - -C /  \
    #Optional restore /usr/bin symlinks.
    && curl -sSL https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-symlinks-noarch-${S6_OVERLAY_VERSION}.tar.xz | tar -Jxpf - -C / \
    && curl -sSL https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-symlinks-arch-${S6_OVERLAY_VERSION}.tar.xz | tar -Jxpf - -C / \
    && mv /init /s6-init \
    && echo "Buidling a bug demo" \
    && rm -rf /var/cache/apt/archives /var/lib/apt/lists/*
COPY s6/debian-root /


ENV S6_LOGGING 0
ENV S6_KEEP_ENV 1
ENV S6_BEHAVIOUR_IF_STAGE2_FAILS 2

ENV PATH /opt/pihole:${PATH}

SHELL ["/bin/bash", "-c"]
ENTRYPOINT [ "/s6-init" ]
```

Container output: first line (script) is executed. no other lines are processed: 2 echo, 1 script

```
Attaching to docker-pi-hole-pihole-1
docker-pi-hole-pihole-1  | s6-rc: info: service s6rc-oneshot-runner: starting
docker-pi-hole-pihole-1  | s6-rc: info: service s6rc-oneshot-runner successfully started
docker-pi-hole-pihole-1  | s6-rc: info: service fix-attrs: starting
docker-pi-hole-pihole-1  | s6-rc: info: service my-init: starting
docker-pi-hole-pihole-1  | + modifyUser www-data
docker-pi-hole-pihole-1  | + declare username=www-data newId=
docker-pi-hole-pihole-1  | + [[ -z www-data ]]
docker-pi-hole-pihole-1  | + [[ -z '' ]]
docker-pi-hole-pihole-1  | + return
docker-pi-hole-pihole-1  | + modifyGroup www-data
docker-pi-hole-pihole-1  | + declare groupname=www-data newId=
docker-pi-hole-pihole-1  | + [[ -z www-data ]]
docker-pi-hole-pihole-1  | + [[ -z '' ]]
docker-pi-hole-pihole-1  | + return
docker-pi-hole-pihole-1  | + modifyUser pihole
docker-pi-hole-pihole-1  | + declare username=pihole newId=
docker-pi-hole-pihole-1  | + [[ -z pihole ]]
docker-pi-hole-pihole-1  | + [[ -z '' ]]
docker-pi-hole-pihole-1  | + return
docker-pi-hole-pihole-1  | + modifyGroup pihole
docker-pi-hole-pihole-1  | + declare groupname=pihole newId=
docker-pi-hole-pihole-1  | + [[ -z pihole ]]
docker-pi-hole-pihole-1  | + [[ -z '' ]]
docker-pi-hole-pihole-1  | + return
docker-pi-hole-pihole-1  | fix-attrs: info: applying /etc/fix-attrs.d/01-resolver-resolv
docker-pi-hole-pihole-1  | s6-rc: info: service my-init successfully started
docker-pi-hole-pihole-1  | fix-attrs: warning: fix-attrs is deprecated, please fix volume permissions in your container manager instead
docker-pi-hole-pihole-1  | s6-rc: info: service fix-attrs successfully started
docker-pi-hole-pihole-1  | s6-rc: info: service legacy-cont-init: starting
docker-pi-hole-pihole-1  | s6-rc: info: service legacy-cont-init successfully started
docker-pi-hole-pihole-1  | s6-rc: info: service legacy-services: starting
docker-pi-hole-pihole-1  | s6-rc: info: service legacy-services successfully started
```

**Comment by edgd1er** [comment]
Thanks for the confirmation and the suggestion. I'll stop searching for a solution using oneshot service.

What are the advantages to use oneshot service knowing the up script has to be a oneline command compared to cont-init.d that can run scripts ?
setup/prepare phases are infrequently a oneline command.

**Comment by skarnet** [comment]
The fact that oneshot services need an indirection should not stop you from using them.
The way s6-rc encodes oneshots makes it that the `up` script itself has to be a single command line, but it does not mean that your whole service has to fit in the `up` script. As I wrote above, you can write your oneshot *wherever you want*, as an executable, with the shebang you want, and then simply call that executable in the `up` file. It has always been the intended usage of `up` (and `down`) scripts; the fact that s6-rc does not enforce a place to store your scripts is not a drawback, it's added freedom.

s6-rc services are superior to `/etc/cont-init.d` and `/etc/services.d` ones because they can have dependencies - you can define a dependency graph between services, and services always start in the proper order, even if you have oneshots depending on longruns or vice-versa. Also, independent services are started in parallel, so s6-rc is *fast*.
In comparison, `/etc/cont-init.d` is a lexicographically sorted list of oneshots, running sequentially, and `/etc/services.d` is a set of longruns that are always started after all the oneshots in cont-init.d. The legacy methods are slower and less flexible.

**Comment by skarnet** [comment]
Closing this.

**Comment by Venator-Fox** [comment]
Thanks for clarification on this, @skarnet. Is there a way to wait for a script (ie, `/etc/s6-overlay/script/my-init-up` as you mentioned above) ran by `up` to finish running, prior to running other s6-rc longruns?  (ie. if a longrun depends on output of that oneshot)

**Comment by skarnet** [comment]
Yes: declare a dependency from the longrun to the oneshot. Then the longrun will only be started after the oneshot script has successfully exited.

`touch /etc/s6-overlay/my-longrun/dependencies.d/my-init`
