### ISSUE TITLE
The `arm` variant is missing in the release assets

### ISSUE THREAD

**Issue by felipecrs** [just-containers/s6-overlay#401]
https://github.com/just-containers/s6-overlay/releases/tag/v3.0.0.2

v2 releases used to include it.

**Comment by skarnet** [comment]
There is an `arm`, an `armhf`, an `i486` and an `i686` flavor of the arch-specific tarball. I'm not sure what you're asking for here?

**Comment by felipecrs** [comment]
For comparison, these are the ones from v2:

`arm`: https://github.com/just-containers/s6-overlay/releases/download/v2.2.0.3/s6-overlay-arm.tar.gz
`x86`/`i386`: https://github.com/just-containers/s6-overlay/releases/download/v2.2.0.3/s6-overlay-x86.tar.gz

**Comment by felipecrs** [comment]
Refs https://github.com/just-containers/s6-overlay/issues/164

**Comment by skarnet** [comment]
Yes, `arm` (as in genericv7a) is missing, we'll fix this. @jprjr is it on my side or mine?
That said, unless you have a *very* old 32-bit ARM machine, I doubt it's the one you need. `armhf` is probably it. And if your ARM processor is 64-bit, `aarch64` is the one you want.

As for x86, the `i686` image is very probably what you are looking for. Yes, the names have changed; since everything else has changed as well, I don't think it's a big deal.

**Comment by felipecrs** [comment]
Thank you for the answer, but it's not about which machine I have. I'm working on https://github.com/hassio-addons/addon-base/pull/176 which, when/if integrated, will be delivered to the following list of architectures:

https://developers.home-assistant.io/docs/add-ons/configuration/#:~:text=A%20list%20of%20supported%20architectures%3A%20armhf%2C%20armv7%2C%20aarch64%2C%20amd64%2C%20i386.

> armhf, armv7, aarch64, amd64, i386

It lists specifically `i386` (instead of `i486` or `i686`), so I believe real `i386` machines are meant to be supported. But of course I can propose for the maintainers to use S6's `i486` in their `i386` archtecture target and see what they think. I'll do that.

**Comment by skarnet** [comment]
When people say `i386`, what they really mean is "32-bit x86". It does not mean "386 SX with no instructions at all from later versions of the chip such as the i486".
I am one of the very few people who run Linux on an i486 today. It still works, but it's not easy.
I doubt there is anyone running Linux on a pure i386 today. And there is *certainly* **nobody** running Docker on one.
I guarantee you that `i486` is the lowest possible standard, and that `i686` would be best for a huge majority of people.

**Comment by felipecrs** [comment]
Thanks a lot for the rationale. It makes total sense.

I will just change the title of this issue since the only missing thing is the `arm` variant.

**Comment by crazy-max** [comment]
@felipecrs Maybe this (not stripped) one could work for you in the meantime: https://github.com/crazy-max/docker-alpine-s6/releases/tag/3.0.0.2-r0

**Comment by felipecrs** [comment]
Hey @crazy-max, thanks a lot for letting me know about your project. I replied in https://github.com/hassio-addons/addon-base/pull/176#issuecomment-1039484875.

**Comment by jprjr** [comment]
@skarnet - figured it out, Make uses a confusing order for `findstring` - it's `$(findstring searchterm,text)`, I think the Makefile is performing `$(findstring text,searchterm)`.

The GNU docs label it `$(findstring find,in)`, which is pretty confusing IMO.

Swapping the order fixes it, pushing it up now.

**Comment by skarnet** [comment]
Gah! sorry about that. You could just have told me it wasn't a problem with the CI, I would have done the searching ^^'

**Comment by jprjr** [comment]
It's no problem, I've been swamped the past... oh my goodness, 9 days now? Jeez. Once I'm looking, figure I'll try and solve it!

I see the new release is published, closing issue

**Comment by jprjr** [comment]
Oh wow - I didn't notice I based on the latest master, that release shouldn't have been made. I deleted it, I'll rebase

**Comment by jprjr** [comment]
I've created a new release that's just 3.0.0.2 + the CI fix: https://github.com/just-containers/s6-overlay/releases/tag/v3.0.0.2-2

**Comment by felipecrs** [comment]
Thank you very much!
