### ISSUE TITLE
Alpine `coreutils` messes up with some S6 Overlay binaries

### ISSUE THREAD

**Issue by felipecrs** [just-containers/s6-overlay#403]
```dockerfile
FROM alpine:3.15

ADD https://github.com/just-containers/s6-overlay/releases/download/v2.2.0.3/s6-overlay-amd64.tar.gz /tmp
RUN tar -C / -zxpf /tmp/s6-overlay-amd64.tar.gz

RUN stat /bin/s6-applyuidgid

RUN apk add --no-cache --virtual .build-deps coreutils \
        # Doing something with coreutils, like installing Python from src
        && apk del --no-cache --purge .build-deps

RUN stat /bin/s6-applyuidgid
```

Ends up with:

```
stat: can't stat '/bin/s6-applyuidgid': No such file or directory
```

I know I'm not using the latest version, but the latest version has some breaking changes that I'm still not ready to adopt like `/bin` -> `/usr/bin`.

**Comment by skarnet** [comment]
We're not providing support for version 2 anymore.
Please upgrade to version 3; nothing should break if you're not doing anything unsupported, like relying on absolute FHS paths.

**Comment by felipecrs** [comment]
Ok. Thank you. I added as a caveat of https://github.com/just-containers/s6-overlay/issues/403#issuecomment-1034320847. As it's about a base image used by many and unknown other images, it's possible that one could have made this mistake. But anyway, what we can do is to push a major bump in the version number and make sure this is in the release notes.
