### ISSUE TITLE
Should not "symlink" packages also include symlinks from `/bin/*` to `/usr/bin/*`?

### ISSUE THREAD

**Issue by felipecrs** [just-containers/s6-overlay#404]
In order to provide backwards compatibility with S6 Overlay v2.

Refs https://github.com/just-containers/s6-overlay/issues/403

**Comment by skarnet** [comment]
The fact that binaries such as `s6-applyuidgid` lived in `/bin` in previous versions was an implementation detail; you were never supposed to call those binaries with a full PATH. Instead, you were supposed to assume that they're accessible via the PATH environment variable, and just call them by their name without specifying a full path: `s6-applyuidgid`.

If you follow these guidelines and remove your absolute calls, everything will work for you in the latest version.

**Comment by felipecrs** [comment]
Alright. I agree.
