### ISSUE TITLE
S6_GLOBAL_PATH: no effect

### ISSUE THREAD

**Issue by edgd1er** [just-containers/s6-overlay#407]
According to the README:
```
S6_GLOBAL_PATH (default = /command:/usr/bin:/bin): this is the default PATH that all the services in the container, including the CMD, will have. Set this variable if you have a lot of services that depend on binaries stored in another directory, e.g. /usr/sbin. Note that /command, /usr/bin and /bin will always be added to that path if they're not already in the one you provide.
```

Having set the S6_GLOBAL_PATH:
`docker-pi-hole-pihole-1  | declare -x S6_GLOBAL_PATH="/command:/usr/bin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin:/bin"
d`
PATH var and global_path file are not changed:
```
docker-pi-hole-pihole-1  | + echo /command:/usr/bin:/bin      # <= echo $PATH
docker-pi-hole-pihole-1  | + cat /etc/s6-overlay/config/global_path
docker-pi-hole-pihole-1  | /command:/usr/bin:/bin
``` 

As a result, /usr/local/bin/ command  are not found:
```
docker-pi-hole-pihole-1  | + pihole -v
docker-pi-hole-pihole-1  | /etc/s6-overlay/scripts/20-start.sh: line 41: pihole: command not found
```

S6_GLOBAL_PATH is defined at build time in the dockerfile.

a temporary fix is to overwrite the global_path file: `echo "${S6_GLOBAL_PATH}" > /etc/s6-overlay/config/global_path`

**Comment by edgd1er** [comment]
Thank you for the feed back. as there is a workaround,  I guess there is no rush to fix it :). thank you for your work.

**Comment by crazy-max** [comment]
@edgd1er In the meantime you can do this: https://github.com/crazy-max/docker-alpine-s6/blob/00fe18989aabd61021671db6d0aafff3af0b6236/Dockerfile#L220

**Comment by edgd1er** [comment]
@crazy-max , thanks for the input. 
I chose to write global_path based on the ARG value:
```
 echo "${S6_GLOBAL_PATH}" > /etc/s6-overlay/config/global_path
```

**Comment by skarnet** [comment]
For your information: I removed `S6_GLOBAL_PATH` because it's actually unnecessary. The current source version now just uses `PATH` as the initial global path - this makes it simpler if you are performing several operations in your Dockerfile that need a specific PATH. Sorry for the change, I think it's for the best. These are the risks of living on the bleeding edge. ;-)

Closing this.

**Comment by skarnet** [comment]
What do you think the following `addpath` invocations do exactly? 😜

**Comment by crazy-max** [comment]
> What do you think the following `addpath` invocations do exactly? 😜

Ah my bad :sweat_smile:
