### ISSUE TITLE
Permissions on container_environment need public read and execute

### ISSUE THREAD

**Issue by bfren** [just-containers/s6-overlay#409]
# Summary

Under v2 it was possible to run `/usr/bin/with-contenv` as a user other than root, because `/run/s6/container_environment` permissions were 0755.  However under v3 `/run/s6/container_environment` permissions are 0700.

# Detail

This was possible with v2.x.x.x:

```bash
# == run ==
s6-setuidgid www init.sh

# == init.sh ==
#!/usr/bin/with-contenv sh
# do something with container environment loaded
```

However with v3.x.x.x the same script causes an error:

```bash
# == run ==
s6-setuidgid www init.sh

# == init.sh ==
#!/command/with-contenv sh
# do something with container environment loaded
```

Script `init.sh` fails with:

```
justc-envdir: fatal: unable to justc_envdir: Permission denied
```

This is because 

```bash
# under v2
$ ls -al /run/s6/container_environment
drwx--xr-x    2 root     root          4096 Feb 11 14:11 .
drwxr-xr-x    5 root     root          4096 Feb 11 14:11 ..

# under v3
$ ls -al /run/s6/container_environment
drwx------    2 root     root          4096 Feb 11 14:11 .
drwxr-xr-x    5 root     root          4096 Feb 11 14:11 ..
```

# Suggested fix

```
chmod +xr /run/s6/container_environment
```

**Comment by skarnet** [comment]
Good catch, thanks! Fixed in git; the fix will propagate to the released tarball when we release a next version (as soon as possible, but there's a lot to do).
