### ISSUE TITLE
Unexpected timeout behaviour on oneshot

### ISSUE THREAD

**Issue by bfren** [just-containers/s6-overlay#411]
# Summary

The oneshot timeout appears to be set to 5s, when it should be indefinite:

> An optional regular file named timeout-up. This file, if it exists, must contain an integer, which is the maximum number of milliseconds s6-rc will wait for successful completion of the service start; if starting the service takes longer than this value, s6-rc will declare the transition a failure. If the file does not exist, or contains 0, no timeout is defined and s6-rc will wait indefinitely for the service to start.
> https://www.skarnet.org/software/s6-rc/s6-rc-compile.html

# Dockerfile

```Dockerfile
FROM alpine
ARG S6_OVERLAY_VERSION=3.0.0.2

ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch-${S6_OVERLAY_VERSION}.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-noarch-${S6_OVERLAY_VERSION}.tar.xz
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-x86_64-${S6_OVERLAY_VERSION}.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-x86_64-${S6_OVERLAY_VERSION}.tar.xz

# make long running oneshot
RUN mkdir -p /etc/s6-overlay/s6-rc.d/long && \
    echo "oneshot" > /etc/s6-overlay/s6-rc.d/long/type && \
    echo "foreground { if { sleep 4 } echo 'awake' }" > /etc/s6-overlay/s6-rc.d/long/up
#RUN echo "0" > /etc/s6-overlay/s6-rc.d/long/timeout-up

# make dependency
RUN mkdir -p /etc/s6-overlay/s6-rc.d/next && \
    echo "longrun" > /etc/s6-overlay/s6-rc.d/next/type && \
    echo "#!/bin/sh" > /etc/s6-overlay/s6-rc.d/next/run && \
    echo "while true ; do sleep 1 && uptime ; done" >> /etc/s6-overlay/s6-rc.d/next/run && \
    echo "long" > /etc/s6-overlay/s6-rc.d/next/dependencies

# create bundle
RUN mkdir -p /etc/s6-overlay/s6-rc.d/user/contents.d && \
    touch /etc/s6-overlay/s6-rc.d/user/contents.d/long && \
    touch /etc/s6-overlay/s6-rc.d/user/contents.d/next

ENTRYPOINT ["/init"]
```

# Results

The above works fine because the oneshot sleeps for 4s and the timeout is 5s.  However, increase this to 6s and I get the following:

```
s6-rc: fatal: timed out
s6-sudoc: fatal: unable to get exit status from server: Operation timed out
'awake'
```

According to the documentation (quoted above) without a timeout-up file S6 will wait 'indefinitely'.  However, adding a timeout-up file (either with 0 or a long value like 10000) doesn't work either.

Is this something to do with `S6_CMD_WAIT_FOR_SERVICES_MAXTIME` - i.e. is that being used instead of the time defined in `timeout-up`?  It feels like it because if I add `ENV S6_CMD_WAIT_FOR_SERVICES_MAXTIME=10000` to the Dockerfile, everything works fine.

**Comment by skarnet** [comment]
There are two timeouts: a global one and a service-local one. Things fail when either of them is reached.

- `timeout-up` is local to the service. If the service fails to get ready in the given amount of time, it will error out.
- `S6_CMD_WAIT_FOR_SERVICES_MAXTIME` is the global timeout. If the whole set of services takes more than the given amount of time to be ready, it will report an error.

Increasing `S6_CMD_WAIT_FOR_SERVICES_MAXTIME`, or setting it to 0, is the correct maneuver.
I will make it clearer in the documentation.

**Comment by bfren** [comment]
Thanks - the issue remains though, in my example above adding `timeout-up` with a value of 10000 doesn't work, I still get the `s6-rc: fatal: timed out` error.

**Comment by skarnet** [comment]
s6-overlay uses a different default from the underlying s6-rc mechanism: the default for `S6_CMD_WAIT_FOR_SERVICES_MAXTIME` is 5000, for historical reasons - more things would break if we didn't set it.
Defining `S6_CMD_WAIT_FOR_SERVICES_MAXTIME` to 0, to get the global timeout out of the way, and handling your individual timeouts in `timeout-up` files sounds like what you want.

**Comment by bfren** [comment]
Thanks so much - works a treat!
