### ISSUE TITLE
Bash script not run on up  (oneshot)

### ISSUE THREAD

**Issue by bugsyb** [just-containers/s6-overlay#415]
Hi All,

Many thanks for s6-overlay - great project.

The issue being faced is that bash script put /app/first-run.sh is not being run.
Structure of files is /etc/s6-overlay/s6-rc.d/firstboot/:
type:
`oneshot`
up:
`exec bash -c '/app/first-run.sh'`
The /app/first-run.sh script:
`
I did experiment with content of up starting with shebang #!/bin/bash  and calling the script - same effect - it didn't work.

#!/bin/bash -e
source /etc/profile
set -e
date >> /root/.date.log
`
Script is executable and for whatever reason is not run at all.

How can I troubleshoot it? Did go through documentation but didn't find any clues.

Release v3.0.0.2

**Comment by skarnet** [comment]
Just put `/app/first-run.sh` in your `up` file.

**Comment by bugsyb** [comment]
Thank you very much! It worked. I did try earlier putting directly path to script, but must have had a typo.

Thanks again.
