### ISSUE TITLE
The state of logging

### ISSUE THREAD

**Issue by smebberson** [just-containers/s6-overlay#42]
I had a good read through #13, but I couldn't really find the answer I was looking for.

I've used my own Alpine Linux base image, added s6-overlay and used https://github.com/just-containers/nginx-loadbalancer as an example to configure logging (the s6-overlay 'way' I guess). I have my logs going into /var/log/nginx-access-log/current and /var/log/nginx-error-log/current.

But I have some questions. How do I get this to hit `stdout`, rather than, or concurrently hitting the file as it does now? Also, what is the benefit to setting up the logging as per the nginx-loadbalancer example? I must admit, it was a lot of work to get the logging setup.

Most Docker images out there when run, by default, logging hits `stdout`. In our case, not just s6 logging, but the main process logging too. Many nginx containers do something like:

```
RUN ln -sf /dev/stdout /var/log/nginx/access.log && \
    ln -sf /dev/stderr /var/log/nginx/error.log
```

which is nice and simple (of course, maybe not what everyone would want). There isn't a lot of documentation on the s6-overlay preferred logging at the moment, so I'm a little confused.

**Comment by glerchundi** [comment]
> https://github.com/just-containers/nginx-loadbalancer as an example to configure logging (the s6-overlay 'way' I guess)

yes :-)

> But I have some questions. How do I get this to hit stdout, rather than, or concurrently hitting the file as it does now? Also, what is the benefit to setting up the logging as per the nginx-loadbalancer example? I must admit, it was a lot of work to get the logging setup.

Take it with a grain of salt, it's not finished yet! This is another interesting reading about how @skarnet understands logging: http://skarnet.org/software/s6/s6-log.html (section 'why another logging...).

But being short, I want to achieve the following:
* don't mix different kind of logs into the same place. Because I want to forward them tagged to another centralised log management server.
* i want to have log rotator as a first citizen inside the container, `s6-log` already provides that (although it's not implemented yet...)
* just log to stdout supervision level logs, startup and finish.

**Comment by smebberson** [comment]
@glerchundi, thanks for getting back to me. So there is no real way to achieve it at this point? Is there something in https://github.com/just-containers/nginx-loadbalancer/blob/master/rootfs/etc/services.d/nginx-access-log/run that I can piggy back to output to stdout too (using `s6-echo` or something)?

**Comment by dreamcat4** [comment]
On Thu, Apr 23, 2015 at 7:52 AM, Gorka Lerchundi Osa <
notifications@github.com> wrote:

>
>    - just log to stdout supervision level logs, startup and finish.
>
> i want to have log rotator as a first citizen inside the container, s6-log
> already provides that (although it's not implemented yet...)
>

It would also be nice to see a log rotated docker logging plugin.

**Comment by glerchundi** [comment]
> @glerchundi, thanks for getting back to me. So there is no real way to achieve it at this point? Is there something in https://github.com/just-containers/nginx-loadbalancer/blob/master/rootfs/etc/services.d/nginx-access-log/run that I can piggy back to output to stdout too (using s6-echo or something)?

although I would encourage you not to do that, it can be achieved by:
* remove `/etc/cont-init.d/00-initialize-log-fds`
* remove `/etc/services.d/nginx-access-log` & `/etc/services.d/nginx-error-log`
* change [these](https://github.com/just-containers/nginx-loadbalancer/blob/master/rootfs/etc/nginx/nginx.conf.tmpl#L6) [lines](https://github.com/just-containers/nginx-loadbalancer/blob/master/rootfs/etc/nginx/nginx.conf.tmpl#L27), and point to `/dev/stdout`

done.

**Comment by glerchundi** [comment]
> It would also be nice to see a log rotated docker logging plugin.

yes it would be nice but that probably doesn't solve merging/syslog problem, that's why I really like having switching (through fifos and `s6-fdholderd`) & logrotation mechanisms inside the container.

**Comment by jprjr** [comment]
@glerchundi I would *love* to hear about your logstash setup - do you keep logs at a volume, and have another container accessing the logs?

**Comment by glerchundi** [comment]
That's it.

**Comment by glerchundi** [comment]
@jprjr I didn't make it a reality yet but this is my idea:
* CoreOS
* Each machine running CoreOS will have a persistent storage in which containers will place its logrotated logs.
* Use kubernetes to make packages of containers using pods like:
  * nginx-loadbalancer
  * logstash-forwarder

So that every container would have a logstash-forwarder alongside it.

**Comment by glerchundi** [comment]
@smebberson could I close this?

**Comment by smebberson** [comment]
Yep. Thanks for getting back to me on it too. I haven't tried it yet, but will shortly.
