### ISSUE TITLE
Migration Guide

### ISSUE THREAD

**Issue by alexyao2015** [just-containers/s6-overlay#420]
Given the massive changes with v3, I thought it would be nice to create a simple TLDR to help with the migration from v2 to v3. Maybe this would be better to PR this to a document somewhere. Please let me know.

Most people will encounter this:

- Installation now requires extracting two `xz` files, one specific to the architecture and one for all architectures.
- PATH now only contains `/command:/usr/bin:/bin` and can be adjusted by modifying `S6_GLOBAL_PATH`.
- Usage of `#!/usr/bin/with-contenv` should be changed to `#!/command/with-contenv`
- Usage of `s6-svscanctl -t /var/run/s6/services` should be changed to `/run/s6/basedir/bin/halt`
- All scripts are now required to be executable to be ran
- There is now a timeout for init scripts (which are a service now), adjustable using `S6_CMD_WAIT_FOR_SERVICES_MAXTIME`. This can be disabled by setting to 0 for the old behavior.

Some people may encounter this:

- Services are now copied to `/run/service/myservice` so usage of `/var/run/s6/services/myservice` should be changed.
- S6 executables are located in `/command` now and in the PATH so any direct usage of `/bin/s6-mycmd` should be changed to use the executable in PATH
- Socklog has been replaced by `syslogd-overlay`. This can also be invoked using `s6-socklog` directly.
- S6 files have been moved from `/var/run` to `/run`, but a symlink has been added to maintain compatibility.

**Comment by skarnet** [comment]
I will take this into account for the next version of the `README.md`. Thanks.

**Comment by skarnet** [comment]
Migration guide added, closing this. More items can always be added to the guide later. ;-)

**Comment by alexyao2015** [comment]
I got one more thing to add to the guide. 

- Init scripts now have a `PWD` of a temp directory and not the `WORKDIR`. Scripts using a relative path to the `WORKDIR` should be updated to use an absolute path.
