### ISSUE TITLE
Passing arguments to `/init` to a service while still dropping privilegies with `s6-setuidgid`

### ISSUE THREAD

**Issue by fakuivan** [just-containers/s6-overlay#422]
I'm migrating an image from using the `USER` directive to `s6-setuidgid`, in the process I would like to retain the functionality of being able to pass arguments to the main service. Is there a way to accomplish this without using environment variables? I'm thinking I could use `[ "/init", "s6-setuidgid", "myuser:myuser", "myapp" ]` but that seems a little it could cause other issues.

**Comment by skarnet** [comment]
You should be able to do that, but rather than modifying the ENTRYPOINT, it sounds like you really want to use a CMD.

**Comment by fakuivan** [comment]
To my knowledge `CMD` is overwritten by whatever arguments you pass docker after the image name. I'm using `ENTRYPOINT` since it will allow the user to pass arguments to config behaviour of the container further. Also, should I signal `/init` and `s6-setuidgid` to stop parsing arguments with `--`? As in `[ "/init", "--", "s6-setuidgid", "myuser:myuser", "--", "myapp" ]`.

**Comment by skarnet** [comment]
Don't use `--`, s6-overlay won't understand it.
`[ "/init", "s6-setuidgid", "myuser:myuser", "myapp" ]` is the correct syntax.
