### ISSUE TITLE
not working after upgrading from v2 to v3

### ISSUE THREAD

**Issue by mybigman** [just-containers/s6-overlay#423]
What was working in v2 is not in v3 :/

logs

```
cont-init: info: running /etc/cont-init.d/02-nginx-user.sh
/etc/cont-init.d/02-nginx-user.sh: line 11: groupmod: command not found
/etc/cont-init.d/02-nginx-user.sh: line 13: usermod: command not found
cont-init: info: /etc/cont-init.d/02-nginx-user.sh exited 127
```

/etc/cont-init.d/02-nginx-user.sh

```
#!/command/with-contenv bash

PUID=${PUID:-1000}
PGID=${PGID:-1000}

NUID=$(id -u nginx)
NGID=$(id -g nginx)

if [[ $PUID != $NUID || $PGID != $NGID ]]; then

  groupmod -o -g "$PGID" nginx

  usermod -o -u "$PUID" nginx

fi
```

**Comment by skarnet** [comment]
`/usr/sbin` is not in the default global path. For now, please specify the PATH you need in your services, or in `/etc/s6-overlay/config/global-path`, but that file will be obsoleted in the next version (3.1.0.0). Instead, the global path will be inherited by the PATH environment variable declared in your Dockerfile.
