### ISSUE TITLE
Log CMD to both stdout/stderr and file

### ISSUE THREAD

**Issue by felipecrs** [just-containers/s6-overlay#425]
I found https://github.com/just-containers/s6-overlay/issues/252, but it does not mention `CMD`, and I think I have a compelling use case:

Kubernetes by default is configured to check for the contents of `/dev/termination-log` to properly fill the _Termination Message_ attribute of a Pod when it fails. It can be configured to some other place by changing `terminationMessagePath` ([ref](https://kubernetes.io/docs/tasks/debug-application-cluster/determine-reason-pod-failure/#customizing-the-termination-message)).

So, it would be desired to keep both the logs in stdout/stderr, but also copy the output of CMD to `/dev/termination-log`.

Is there any tip on how this can be achieved?

**Comment by skarnet** [comment]
Duplicating log channels, unfortunately, always require an additional process.

Make sure your image has the `tee` binary available, then change your CMD to
`pipeline -w tee /dev/log-termination "" oldCMD`
This will launch a `tee` process in the background that duplicates your old CMD's output to `/dev/log-termination`.

**Comment by felipecrs** [comment]
I guess I can put this in the ENTRYPOINT, like:

```
ENTRYPOINT ["/init", "pipeline", "-w", "tee", "/dev/termination-log", ""]
CMD ["jenkins-agent"]
```

Right?

**Comment by skarnet** [comment]
No! Doing this will 1. make all the messages from the supervision tree and the container init go through the `tee` process, and 2. will prevent clean shutdowns because `tee` will be killed while the supervision tree still depends on it. Do not mess with the `ENTRYPOINT`.

**Comment by felipecrs** [comment]
Hm... I don't understand why. If my understanding is correct, docker always concatenates both `ENTRYPOINT` and `CMD` and executes them as a whole.

This would mean that:

```dockerfile
ENTRYPOINT ["/init", "pipeline", "-w", "tee", "/dev/termination-log", ""]
CMD ["jenkins-agent"]
```

Or

```dockerfile
ENTRYPOINT ["/init"]
CMD ["pipeline", "-w", "tee", "/dev/termination-log", "", "jenkins-agent"]
```

Ends up with the same command line for starting the container.

**Comment by felipecrs** [comment]
For my very own example, I'm lucky that the `CMD` by default logs to one file. That way I can simply copy the logs from that file to `/dev/termination-log` during `cont-finish.d`:

```bash
# Copy jenkins-agent logs to /dev/termination-log so that K8s can set the
# termination message.
if [[ -d "${AGENT_WORKDIR}/remoting/logs" ]]; then
    echo "Flushing termination log..." >&2
    find "${AGENT_WORKDIR}/remoting/logs" \
        -type f -name 'remoting.log.*' -and -not -name 'remoting.log.*.lck' \
        -exec cat {} ";" | tee /dev/termination-log >/dev/null
fi
```

That, however, is not perfect. If user forgets to set an environment variable, `jenkins-agent` will fail without even creating logs (although its stdout/stderr still indicates the issue of missing something).

And, again, it's a solution only applicable to my very own use case.

**Comment by felipecrs** [comment]
> In theory you could, but in practice this will badly break things if you try starting a container without a CMD. I suppose it's okay if you know you're always going to run a CMD. As a general rule, it's better to avoid messing with the ENTRYPOINT ;-)

Oh okay, now I understand. If I run without a CMD. But that will never be the case in my situation, so I think it's ok. Thank you!

**Comment by felipecrs** [comment]
Out of curiosity, `/init` could accept a flag like `--pre-cmd { pre-command }` which would instruct s6-overlay to concatenating pre-command with `CMD` before executing `CMD`.

In that case, it would be smart enough not to run `CMD` in case `CMD` is not set.

I would use it like below:

```dockerfile
# Dropping privileges for CMD
ENTRYPOINT ["/init", "--pre-cmd", "s6-setuidgid", "jenkins", ""]
```

```dockerfile
# Redirecting stdout to /dev/termination-log and dropping privileges for CMD
ENTRYPOINT ["/init", "--pre-cmd", "pipeline", "-w", "tee", "/dev/termination-log", "", "s6-setuidgid", "jenkins", ""]
```

**Comment by skarnet** [comment]
Well, `/init` simply cannot tell the difference between what's in the ENTRYPOINT and what's the CMD. You just need to make sure that the command line that results from the concatenation of those two things ends up being something consistent, and the `pipeline` command (documented [here](https://skarnet.org/software/execline/pipeline.html), it's a part of the execline package) needs to have a nonempty _prog2_ command line in order to work, so if you have no CMD after it, it fails with an error message, that's all. No `--pre-cmd` hack is needed, the complete command line just needs to make sense.

To also redirect stderr to `/dev/termination-log`, you can add more stuff to the CMD: `pipeline -w tee /dev/termination-log "" fdmove -c 2 1 jenkins-agent`
[`fdmove`](https://skarnet.org/software/execline/fdmove.html) is another execline command that performs a file descriptor redirection.

**Comment by felipecrs** [comment]
> Well, /init simply cannot tell the difference between what's in the ENTRYPOINT and what's the CMD. You just need to make sure that the command line that results from the concatenation of those two things ends up being something consistent, and the pipeline command (documented [here](https://skarnet.org/software/execline/pipeline.html), it's a part of the execline package) needs to have a nonempty prog2 command line in order to work, so if you have no CMD after it, it fails with an error message, that's all. No --pre-cmd hack is needed, the complete command line just needs to make sense.

Which can be handled with:

```bash
#!/bin/sh

if [ $# -gt 0 ]; then
  exec /init \
    pipeline -w tee /dev/termination-log "" \
    fdmove -c 2 1 \
    s6-setuidgid jenkins \
    "$@"
else
  exec /init
fi
```

```dockerfile
ENTRYPOINT ["/entrypoint.sh"] # instead of /init
CMD ["jenkins-agent"]
```

As I'm using `exec` in `entrypoint.sh`, `/init` would still be kept as PID 1. Right?

> To also redirect stderr to `/dev/termination-log`, you can add more stuff to the CMD: `pipeline -w tee /dev/termination-log "" fdmove -c 2 1 jenkins-agent`
> [`fdmove`](https://skarnet.org/software/execline/fdmove.html) is another execline command that performs a file descriptor redirection.

Thank you so much!!!

**Comment by skarnet** [comment]
Yes, your `entrypoint.sh` script would work. But be careful if someday you're using a CMD that is not supposed to run as user `jenkins`. 😄

**Comment by felipecrs** [comment]
Sure, I will have that in mind. Thanks a million and have a great week!

**Comment by felipecrs** [comment]
And for completeness, I didn't find a way to force a container to start without `CMD` once `CMD` is set in the `Dockerfile`.

The following:

```console
docker run --rm --privileged ghcr.io/felipecrs/jenkins-agent-dind ""
```

Will build a `CMD` of `[""]`, which is different from `CMD []`.

What this means effectively is that there is no point in creating such an `entrypoint.sh` if your `Dockerfile` sets `CMD`.

Instead, the following is enough:

```dockerfile
ENTRYPOINT [ "/init",\
        # write jenkins-agent logs to /dev/termination-log so that Kubernets can use
        # it as the termination message. See:
        # https://github.com/just-containers/s6-overlay/issues/425
        # redirect stdout of CMD to /dev/termination-log
        "pipeline", "-w", "tee", "/dev/termination-log", "", \
        # redirect stderr of CMD to stdout so that both goes to /dev/termination-log
        "fdmove", "-c", "2", "1", \
        # drop privileges for CMD (run as jenkins user)
        "s6-setuidgid", "jenkins"]
CMD [ "jenkins-agent" ]
```

But again, only because `CMD` is set. Otherwise, do not mess with `ENTRYPOINT` as @skarnet [said](https://github.com/just-containers/s6-overlay/issues/425#issuecomment-1067078629).
