### ISSUE TITLE
zombie process with s6-rc

### ISSUE THREAD

**Issue by adripo** [just-containers/s6-overlay#429]
Hi, I created a project using s6-overlay and s6-rc services and I am having a problem with zombie processes.
I saw a similar issue here #350, but it was with v2.

I am using latest v3.1.0.1 and starting from alpine:3.15
The structure I created is something similar to this example:

### Structure
```
/
| - Dockerfile
| - root/etc/s6-overlay/
                       | - scripts/
                                  | - main
                       | - s6-rc.d/
                                  | - main/
                                          | - run
                                          | - type
                                  | - user/contents.d/main
```

### Files
`s6-rc.d/main/type`:
```
longrun

```

`s6-rc.d/main/run`:
```sh
#!/command/execlineb -P
s6-setuidgid abc /etc/s6-overlay/scripts/main
```

`scripts/main`:
```sh
#!/command/with-contenv sh


mkfifo /app/in

(
  cat
) < <(tail -f /app/in) &

CMD_PID=$!

wait "${CMD_PID}"
```

### Problem

This script will create a fifo pipe in `/app/in` that will be read continuously with `tail -f` and redirect its output to the STDIN of `cat`.

![image](https://user-images.githubusercontent.com/26493496/160291764-916e2114-1de8-48b6-9e6d-5a7f329f4b10.png)

The problem appears when the `cat` process is killed/dies and the managed service is restarted.
In the example above I did `kill -9 91`, the service restarted (it is also traced in the logs), but the `tail` process wasn't killed.
You can see that it got PPID=1 instead of the 91 that it had before.

![image](https://user-images.githubusercontent.com/26493496/160292113-ca39c6ed-2fe4-4250-b384-76fbc4b19ee7.png)

I also tried to kill it manually with `s6-svscanctl -z` but nothing changed.

How can I solve the issue?

> Note: Same script in ubuntu works as expected, tail dies when service is restarted.

**Comment by skarnet** [comment]
This has nothing to do with s6-overlay - it's a question of shell features and implementation.
`<(command)` is a bash extension.
The `alpine` image uses busybox ash as its shell, which implements some bash extensions, but not all of them, and not always perfectly. The `ubuntu` image uses bash.

My advice would be to avoid using bash extensions and sticking to POSIX constructs, so your shell scripts would be portable everywhere without trouble.
If you absolutely need the `<(command)` extension, you can `apk add bash` in your Dockerfile. Then `/bin/sh` will be bash, which should give you the same behaviour as on Ubuntu.

**Comment by adripo** [comment]
Thank you for the suggestions! I will try and let you know if I have any other issue. 
About using process substitution <() I couldn't find a better way to redirect input from a pipe to a script that only accepts commands through STDIN (where I used `cat` as an example). I also tried to redirect container STDIN to my script but didn't work with s6-rc. [This](https://github.com/adripo/minecraft-server-forge/blob/main/root/etc/s6-overlay/scripts/minecraft-server) is the script if you can have a look.
I will close the issue in the meantime.

**Comment by skarnet** [comment]
Try this:
```sh
mkfifo fifo
redirfd -rnb 0 fifo redirfd -w 3 fifo ./run.sh nogui &
CMD_PID=$!
...
```
You definitely don't need an intermediary `tail -f` process. You can read directly from the pipe. (The `redirfd` command allows you to open the pipe in a non-blocking way so your script can continue, unlike the shell's `<` construct. Then the second `redirfd` command opens the writing end of the pipe, so it doesn't return EOF immediately.)

But really, can your minecraft server _only_ stop when it reads `/stop` on stdin? can't you just send it a signal to kill it, doesn't it react well to SIGTERM? Because if it did, you could do away with your start script entirely, and run the server as a regular longrun service instead, which would be a lot cleaner.

**Comment by skarnet** [comment]
You don't need to convert shell scripts, you can keep using shell scripts everywhere - execline is a nice optimization for very short scripts, and one of its main advantages is that it's easy to autogenerate, but it's not worth converting anything more complex than a few lines of shell.
Join the [skarnet.org mailing-lists](https://skarnet.org/lists/), and above all, the IRC #s6 channel on OFTC, we have a nice community there that's been through all that you're experiencing right now, and that will be happy to answer your questions!
