### ISSUE TITLE
s6-mkfifo: fatal: unable to mkfifo /var/run/s6/uncaught-logs-fifo: File exists

### ISSUE THREAD

**Issue by dreamcat4** [just-containers/s6-overlay#43]
Hi again,
I have the following in my dockerfile:

```sh
# Install s6-overlay
ADD https://github.com/just-containers/s6-overlay-builder/releases/download/v1.9.1.1/s6-overlay-linux-amd64.tar.gz /tmp/
RUN tar zxf /tmp/s6-overlay-linux-amd64.tar.gz -C / && $_clean
ENV S6_LOGGING="1"
# ENV S6_KILL_GRACETIME="3000"
```

However now when i try to start my container, it exits, saying:

```sh
s6-mkfifo: fatal: unable to mkfifo /var/run/s6/uncaught-logs-fifo: File exists
```

Things seemed to have worked the first 1-2 time around. After the container was initially created. But not subsequent times after that.

@glerchundi  Please let me know if any specific test(s) you want me to do. Or tell me there is nothing we can check up on and is OK to delete this container and start over again. Many thanks.

**Comment by dreamcat4** [comment]
@glerchundi Could it be because I am creating the container just once, with `docker create`. And then just restarting the same container? e.g. `docker start <container>` each time?

It seems that docker (v1.6) remembers the container's filesystem state. In-between runs. Including the file mentioned etc.

**Comment by glerchundi** [comment]
@dreamcat4 are you using persistent volumes for `/var/run/...`?

**Comment by dreamcat4** [comment]
@glerchundi No. But like I said ^^ the containers seems to remember between runs.

Also: in the base image `ubuntu-debootstrap:14.04`. `/var/run` is actually a symlink pointing to `/run` (where `/run` is the real folder.

Some more infos coming...

**Comment by glerchundi** [comment]
ok, anyway, i'm going to fix it and always delete it before proceeding, as always thanks for pointing that out its a bug in our side :-)

**Comment by dreamcat4** [comment]
@glerchundi Here is my container's metadata infos.

We can see from that, docker is remembering in a layer the state in-between runs.

**Comment by dreamcat4** [comment]
@glerchundi  Thanks for working on a fix. v. appreciate it. Please check for any other temporary files which were created by s6 in the gist above ^^.

FYI
(and this extra infos does not affect your fixing)

If you have AUFS storage backend (not devicemapper). Then the container's runtime FS state is stored as a diff layer at `/var/lib/docker/aufs/diff/<container_id>`

For example in my container:

```
ls -lsa /var/lib/docker/aufs/diff/f38209adb00c92fc1970e696367852cefe470be8f0528ab743e9a35278d0f71f/run/s6/
total 16
4 drwxr-xr-x 4 root root 4096 Apr 20 22:56 .
4 drwxr-xr-x 3 root root 4096 Apr 20 22:56 ..
4 drwxr-xr-x 2 root root 4096 Apr 23 09:33 container_environment
4 drwxrwxr-x 5 root root 4096 Apr 20 22:56 services
0 prw------- 1 root root    0 Apr 21 13:15 uncaught-logs-fifo
root@emachines-e520:~# 
```

It seems like the same AUFS folder layer is re-used every subsequent container start-stop. So the files added are not checkpointed / checksummed (as that would mean having a different container ID). Hence it may be not-managed. This is actually somewhat of a surprise to me too!

I guess it can be a bit confusing the `docker run` and the `docker start`. Kind rergards.

**Comment by glerchundi** [comment]
`1.9.1.2` is already available, can you test it for me? I did it locally but I prefer to have your feedback before closing it!

**Comment by dreamcat4** [comment]
@glerchundi Sure! 

Will rebuild and confirm.

**Comment by dreamcat4** [comment]
@glerchundi it seems OK now.

**Comment by glerchundi** [comment]
:+1:
