### ISSUE TITLE
s6-overlay-suexec not build with PIE

### ISSUE THREAD

**Issue by eburghar** [just-containers/s6-overlay#430]
Hi,

I rely on abuild tool to make packages that I can install simply in Dockerfile. So instead of copying some tarball I made a s6-overlay alpine package. The [postcheck()](https://github.com/alpinelinux/abuild/blob/master/abuild.in#L827-L835) function fails because s6-overlay-suexec is not build with PIE :

```
>>> ERROR: s6-overlay*: Found non-PIE files that has SUID:
        /package/admin/s6-overlay-helpers-0.1.0.0/command/s6-overlay-suexec 
```

I'm not sure it is even possible (static build ?). I tried `CFLAGS="-pie"` `LDFLAGS="-fpie"` without success.

For now I just remove the SUID flags and add it back in post-install. I just wanted your input to know if it is normal.

**Comment by skarnet** [comment]
Your APKBUILD file needs `options=suid`.
But you should know that there is already an s6-overlay package for Alpine, in the `community` repository, so `apk add s6-overlay` should work.

**Comment by eburghar** [comment]
I have the `options=suid` present which is for packaging and suid exec but the PIE test on suid exec is not avoidable with an option. I checked the community package (no suid option which is strange). I use the tarball and make subpackages whereas they use output directories directly without separating arch and noarch packages.

**Comment by eburghar** [comment]
I checked and I think that's because (correct me if I'm wrong) by default s6-overlay makefile compile static whereas the community package compile with dyn linking. In the case of static compilation pie has no effect.

**Comment by eburghar** [comment]
Ok thanks for the explanations. The base image is slightly bigger but I also remember you wrote somewhere that in complex script scenarios it should be faster. I'll stick with the static linking which is only for the golden image.
