### ISSUE TITLE
s6-sudoc: fatal: unable to get exit status from server: Operation timed out

### ISSUE THREAD

**Issue by jsloan117** [just-containers/s6-overlay#433]
Hello,

I was wondering if I could get assistance or be pointed towards some docs/links/info (or how to debug further) that may help resolve this issue. 

This issue is not occurring all of the time, so even harder for me to try and debug. The issue appears to only be present in v3, since v2 worked fine. I am currently using v3.1.0.1.

```bash
s6-rc: fatal: timed out
s6-sudoc: fatal: unable to get exit status from server: Operation timed out
```

My s6-rc services hierarchy is shown [here](https://github.com/jsloan117/docker-openvpn-client/tree/main/etc/s6-overlay/s6-rc.d). Fairly simple setup running `OpenVPN` as a service and calling a single `one-shot` script called `setup-openvpn` to well setup the container for `OpenVPN` to run.

I have read the docs on s6-sudoc, s6-sudod, as  well as the s6-rc-compile programs (how I found the timeout-up file, but not sure if it'd make a difference or not), but feel like I'm falling down a rabbit hole and not sure what to look at to get my answer or fix.

Any help would be greatly appreciated!

Sloan

**Comment by skarnet** [comment]
I can't see your `/etc/scripts/setup.sh` script, but chances are it takes a long time to initialize, and gets killed by s6-rc.

s6-rc uses two timeouts: a per-service one, which is the `timeout-up` file you read about, and a global one, which is set to 5000 (five seconds) by default.
From the [MOVING-TO-V3](https://github.com/just-containers/s6-overlay/blob/master/MOVING-TO-V3.md) file:
> There is a global timeout for all the services, adjustable via the S6_CMD_WAIT_FOR_SERVICES_MAXTIME variable. You can disable it via setting this variable to 0.

Try setting the variable to 0, or to something large like 60000 (one minute timeout), and see if it fixes your issue.

**Comment by jsloan117** [comment]
Thanks really appreciate the help! That was the fix, I should have re-read that doc 😄.
