### ISSUE TITLE
Support for Apple M1 (linux/arm64/v8) architecture?

### ISSUE THREAD

**Issue by IvoNet** [just-containers/s6-overlay#434]
Will there be support for the Apple M1 processor?
Thank you

**Comment by skarnet** [comment]
There already is! Try the `aarch64` binaries.

**Comment by IvoNet** [comment]
Thank you! It is not reflected in the documentation though.
Another question. Docker works with the terms like amd64 or arm64. These names are actually retrievable when building a multi-platform build from one Dockerfile. Now I can't use that for a build (substitution) because the naming used in this project is different like aarch64. Is it possible to have the release reflect the names used during a docker build?

**Comment by skarnet** [comment]
The naming is the standard used by C compilers. It is unfortunate that Docker chose to use gratuitously different names. We will add something to the documentation to help people figure out what architecture is what.

**Comment by IvoNet** [comment]
Now that I have a multi node build with native amd64 and arch64 it works like a charm. thx
