### ISSUE TITLE
ENV for oneshot scripts

### ISSUE THREAD

**Issue by michaelaguiar** [just-containers/s6-overlay#437]
I am setting up a one shot script in s6-rc.d to run any DB migrations before my long run scripts start. in my `up` file, I am simply calling another script that contains the db migration command. i.e. 

`ash /etc/s6-overlay/scripts/migrate-db`.

In my long run scripts, I use `#!/command/with-contenv sh` and all of the ENV vars I pass to my container, like DB connection details, are available and work great. I can't seem to get any environment variables to load for my oneshot script via `up` file, so it can't connect to the DB to run the migrations.

I can  inject the environment variables via `export DB_SOCKET=$(cat /var/run/s6/container_environment/DB_SOCKET)` in the script file that `up` runs, but wondering if there is a better way?

**Comment by saibotk** [comment]
You can prepend `with-contenv`.

So your up file should look like this:
```
with-contenv
/etc/s6-overlay/scripts/migrate-db
```

Hope that helps :)

**Comment by michaelaguiar** [comment]
Brilliant! I must of tried everything else... Appreciate it!
