### ISSUE TITLE
Trying to update s6 on my ubuntu machine

### ISSUE THREAD

**Issue by Falenone** [just-containers/s6-overlay#439]
Hello

Trying to get my containers to work but getting 
s6-svc: fatal: unable to control /var/run/s6/services/lighttpd-error-log: supervisor not listening

When trying to install I only see some old version. 
 Installed: (none)
  Candidate: 2.9.0.1-2
  Version table:
     2.9.0.1-2 500
        500 http://ee.archive.ubuntu.com/ubuntu focal/universe amd64 Packages

How do I go about getting the latest?

**Comment by skarnet** [comment]
- Ubuntu has s6-2.11 packaged, I don't know why you can't update it; ask a Ubuntu support channel.
- Your problem isn't related to s6, but to s6-overlay.
- In order to get help, you'll need to provide more information. How are you starting your containers? What version of s6-overlay are you using? At what point are you getting the error message? etc.

My wild guess is that you're using s6-overlay v3 with scripts that were made adhoc for s6-overlay v2, expecting service directories in `/var/run/services`, and that you need to [adapt your scripts to v3](https://github.com/just-containers/s6-overlay/blob/master/MOVING-TO-V3.md), but I can't be certain that's a correct diagnosis with how little information you have provided.

**Comment by Falenone** [comment]
> * Ubuntu has s6-2.11 packaged, I don't know why you can't update it; ask a Ubuntu support channel.
> * Your problem isn't related to s6, but to s6-overlay.
> * In order to get help, you'll need to provide more information. How are you starting your containers? What version of s6-overlay are you using? At what point are you getting the error message? etc.
> 
> My wild guess is that you're using s6-overlay v3 with scripts that were made adhoc for s6-overlay v2, expecting service directories in `/var/run/services`, and that you need to [adapt your scripts to v3](https://github.com/just-containers/s6-overlay/blob/master/MOVING-TO-V3.md), but I can't be certain that's a correct diagnosis with how little information you have provided.

* Right, Ubuntu has version 2.9 that it shows me but not the latest 3.x? Can I feed it the latest? 

* I tried also pihole containers that specifically say s6 v3 in their description but they all fail. Initially I tried the official thing.

* I don't even make it to starting the container. I wanted to install pihole and during the install it throws out the error at the end. I tried multiple different containers and tutorials and they all fail with the same error. How can I check it's version? 

>   [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
>   [i] Installing /etc/dnsmasq.d/01-pihole.conf...
>   [✓] Installed /etc/dnsmasq.d/01-pihole.conf
>   [i] Installing /etc/.pihole/advanced/06-rfc6761.conf...
>   [✓] Installed /etc/dnsmasq.d/06-rfc6761.conf
> Creating empty /etc/pihole/setupVars.conf file.
> Configuring default DNS servers: 8.8.8.8, 8.8.4.4
>   [✓] New password set
> DNSMasq binding to default interface: eth0
> Added ENV to php:
> 			"TZ" => "Europe/Tallinn",
> 			"PIHOLE_DOCKER_TAG" => "2022.04.2",
> 			"PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
> 			"ServerIP" => "0.0.0.0",
> 			"CORS_HOSTS" => "",
> 			"VIRTUAL_HOST" => "0.0.0.0",
> Using IPv4 and IPv6
> ::: setup_blocklists now setting default blocklists up: 
> ::: TIP: Use a docker volume for /etc/pihole/adlists.list if you want to customize for first boot
> ::: Blocklists (/etc/pihole/adlists.list) now set to:
> https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
> ::: Testing lighttpd config: Syntax OK
> ::: All config checks passed, cleared for startup ...
> ::: Enabling Query Logging
>   [i] Enabling logging...
> 
>   [✓] Logging has been enabled!
>  ::: Docker start setup complete
>   Checking if custom gravity.db is set in /etc/pihole/pihole-FTL.conf
>   Pi-hole version is v5.9.1 (Latest: v5.9.1)
>   AdminLTE version is v5.11 (Latest: v5.10.1)
>   FTL version is v5.14 (Latest: v5.14)
>   Container tag is: 2022.04.2
> [cont-init.d] 20-start.sh: exited 0.
> [cont-init.d] done.
> [services.d] starting services
> Starting lighttpd
> Starting crond
> Starting pihole-FTL (no-daemon) as pihole
> [services.d] done.
> [2022-04-18 02:43:52.690 535M] Using log file /var/log/pihole-FTL.log
> [2022-04-18 02:43:52.690 535M] ########## FTL started on 66881c9cf9c0! ##########
> [2022-04-18 02:43:52.691 535M] FTL branch: master
> [2022-04-18 02:43:52.691 535M] FTL version: v5.14
> [2022-04-18 02:43:52.691 535M] FTL commit: 52e6b95
> [2022-04-18 02:43:52.691 535M] FTL date: 2022-02-12 19:58:34 +0000
> [2022-04-18 02:43:52.691 535M] FTL user: pihole
> [2022-04-18 02:43:52.691 535M] Compiled for x86_64 (compiled on CI) using gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
> [2022-04-18 02:43:52.692 535M] Creating mutex
> [2022-04-18 02:43:52.692 535M] Creating mutex
> [2022-04-18 02:43:52.700 535M] Starting config file parsing (/etc/pihole/pihole-FTL.conf)
> [2022-04-18 02:43:52.700 535M]    SOCKET_LISTENING: only local
> [2022-04-18 02:43:52.700 535M]    AAAA_QUERY_ANALYSIS: Show AAAA queries
> [2022-04-18 02:43:52.701 535M]    MAXDBDAYS: max age for stored queries is 365 days
> [2022-04-18 02:43:52.701 535M]    RESOLVE_IPV6: Resolve IPv6 addresses
> [2022-04-18 02:43:52.701 535M]    RESOLVE_IPV4: Resolve IPv4 addresses
> [2022-04-18 02:43:52.701 535M]    DBINTERVAL: saving to DB file every minute
> [2022-04-18 02:43:52.701 535M]    DBFILE: Using /etc/pihole/pihole-FTL.db
> [2022-04-18 02:43:52.701 535M]    MAXLOGAGE: Importing up to 24.0 hours of log data
> [2022-04-18 02:43:52.701 535M]    PRIVACYLEVEL: Set to 0
> [2022-04-18 02:43:52.701 535M]    IGNORE_LOCALHOST: Show queries from localhost
> [2022-04-18 02:43:52.702 535M]    BLOCKINGMODE: Null IPs for blocked domains
> [2022-04-18 02:43:52.702 535M]    ANALYZE_ONLY_A_AND_AAAA: Disabled. Analyzing all queries
> [2022-04-18 02:43:52.702 535M]    DBIMPORT: Importing history from database
> [2022-04-18 02:43:52.702 535M]    PIDFILE: Using /run/pihole-FTL.pid
> [2022-04-18 02:43:52.702 535M]    PORTFILE: Using /run/pihole-FTL.port
> [2022-04-18 02:43:52.702 535M]    SOCKETFILE: Using /run/pihole/FTL.sock
> [2022-04-18 02:43:52.703 535M]    SETUPVARSFILE: Using /etc/pihole/setupVars.conf
> [2022-04-18 02:43:52.703 535M]    MACVENDORDB: Using /etc/pihole/macvendor.db
> [2022-04-18 02:43:52.703 535M]    GRAVITYDB: Using /etc/pihole/gravity.db
> [2022-04-18 02:43:52.703 535M]    PARSE_ARP_CACHE: Active
> [2022-04-18 02:43:52.703 535M]    CNAME_DEEP_INSPECT: Active
> [2022-04-18 02:43:52.703 535M]    DELAY_STARTUP: No delay requested.
> [2022-04-18 02:43:52.703 535M]    BLOCK_ESNI: Enabled, blocking _esni.{blocked domain}
> [2022-04-18 02:43:52.703 535M]    NICE: Cannot change niceness to -10 (permission denied)
> [2022-04-18 02:43:52.703 535M]    MAXNETAGE: Removing IP addresses and host names from network table after 365 days
> [2022-04-18 02:43:52.704 535M]    NAMES_FROM_NETDB: Enabled, trying to get names from network database
> [2022-04-18 02:43:52.704 535M]    EDNS0_ECS: Overwrite client from ECS information
> [2022-04-18 02:43:52.704 535M]    REFRESH_HOSTNAMES: Periodically refreshing IPv4 names
> [2022-04-18 02:43:52.704 535M]    RATE_LIMIT: Rate-limiting client making more than 1000 queries in 60 seconds
> [2022-04-18 02:43:52.705 535M]    LOCAL_IPV4: Automatic interface-dependent detection of address
> [2022-04-18 02:43:52.706 535M]    LOCAL_IPV6: Automatic interface-dependent detection of address
> [2022-04-18 02:43:52.707 535M]    BLOCK_IPV4: Automatic interface-dependent detection of address
> [2022-04-18 02:43:52.708 535M]    BLOCK_IPV6: Automatic interface-dependent detection of address
> [2022-04-18 02:43:52.708 535M]    REPLY_ADDR4: Using IPv4 address 0.0.0.0 instead of automatically determined IP address
> [2022-04-18 02:43:52.708 535M]    SHOW_DNSSEC: Enabled, showing automatically generated DNSSEC queries
> [2022-04-18 02:43:52.708 535M]    MOZILLA_CANARY: Enabled
> [2022-04-18 02:43:52.708 535M]    PIHOLE_PTR: internal PTR generation enabled (pi.hole)
> [2022-04-18 02:43:52.708 535M]    ADDR2LINE: Enabled
> [2022-04-18 02:43:52.709 535M]    REPLY_WHEN_BUSY: Permit queries when the database is busy
> [2022-04-18 02:43:52.709 535M]    BLOCK_TTL: 2 seconds
> [2022-04-18 02:43:52.709 535M]    BLOCK_ICLOUD_PR: Enabled
> [2022-04-18 02:43:52.709 535M]    CHECK_LOAD: Enabled
> [2022-04-18 02:4Stopping cron
> Stopping lighttpd
> Stopping pihole-FTL
> [cont-finish.d] executing container finish scripts...
> [cont-finish.d] done.
> s6-svc: fatal: unable to control /var/run/s6/services/lighttpd-access-log: supervisor not listening
> [s6-finish] waiting for services.
> s6-svc: fatal: unable to control /var/run/s6/services/lighttpd-error-log: supervisor not listening
> [s6-finish] sending all processes the TERM signal.
> [s6-finish] sending all processes the KILL signal and exiting.

**Comment by skarnet** [comment]
Thank you. So:
- s6 is not s6-overlay. s6 is a tool that s6-overlay is using. The latest version of s6 is [2.11.1.0](https://skarnet.org/software/s6/).
- s6-overlay v2 is the old version; s6-overlay v3 is the new one. We only provide support for v3, because it solves a lot of problems that v2 had.
- I don't know where you're getting your container images from, but these images are using s6-overlay v2.
- The `s6-svc` error messages you have are an artefact caused by the way s6-overlay v2 works; these messages will sometimes be printed when a container stop. They are harmless, but their existence is due to a bug that is not fixable in v2 and that has been fixed in v3.
- Your problem is that the container stops instantly after starting FTL. (See the "Stopping cron" line.) I am not sure what causes it; it would be difficult to diagnose in v2. v3 would have much more explicit error messages.
- The solution to your problem is to ask the people who maintain your container image to update it to s6-overlay v3.

**Comment by Falenone** [comment]
Tried ubuntu server, latest at this time and during install chose to install brand new docker and all that. Same thing so yep seems to be the issue of the container
