### ISSUE TITLE
How to log oneshot services using logutil-service?

### ISSUE THREAD

**Issue by brunomacf** [just-containers/s6-overlay#442]
I have an oneshot service defined like this in `/etc/s6-overlay/s6-rc.d/hello-svc/run`:

```bash
#!/command/with-contenv bash

for idx in 1 2 3 4 5; do
	echo "hello $idx"
  sleep 3
done
```

How can i log this using `logutil-service`? All the examples in the docs mention loggers as long running processes but if it try to create a `/etc/s6-overlay/s6-rc.d/hello-log/run` with type `longrun` (and with a pipeline-name of `hello`) i get an error saying we can't create a long running pipe with oneshot.

**Comment by skarnet** [comment]
Indeed you cannot define a logger for a oneshot service. Logging services only make sense for longruns.

stdout and stderr for oneshot services naturally go to the container's catch-all logger (or the container's stdout if you have disabled the catch-all logger). If you want to log the output of a oneshot service into a different place, you can call the logger yourself.

For instance, if your `/etc/s6-overlay/s6-rc.d/hello-svc/up` file contains `/etc/s6-overlay/s6-rc.d/hello-svc/run`, try writing this in the `up` file instead:
```
pipeline -w { logutil-service your_logging_directory }
fdmove -c 2 1
/etc/s6-overlay/s6-rc.d/hello-svc/run
```
That should do what you want: log everything that `/etc/s6-overlay/s6-rc.d/hello-svc/run` writes to its stdout or stderr into `your_logging_directory`.

**Comment by skarnet** [comment]
Closing this.
