### ISSUE TITLE
clarification: CMD vs services

### ISSUE THREAD

**Issue by drjasonharrison** [just-containers/s6-overlay#445]
Is there a clear definition of what we should run in a docker container using S6-overlay with the docker CMD vs services defined under /etc/services.d?

I have a dockerized process run on EC2 instances, which I run multiple copies of the same process on the instance. It's a case were I can't scale down the EC2 instance (due to GPU resources) but have extra CPU cycles.

My first approach was to define multiple services, one for each copy of the process I wanted to run. But since each of these are essentially the same, it feels wrong. In the simplest case I could have two services, but I imagine that as we go to more copies of the process I'd have to define more and more services, each a copy. Definitely feels like the wrong path.

So I thought about using a script specified in the CMD. It would start multiple copies of the process in the background and then do a `wait -n`. I could use an environment variable to specify how many copies of the process to run.  Is this compatible with the S6-overlay architecture?

**Comment by skarnet** [comment]
- Services are supervised, which - among other things - means that they will be restarted if they die.
- CMD is not supervised: when the process running as CMD dies, the container will stop.

In the general case, "auxiliary" stuff that supports your main application is run as supervised services, and your main application is run as CMD. But another common setup is that you run _everything_ as a service, with no CMD, and your container runs forever, until you manually stop it via `docker stop` or similar external command.

How you want to run your main application is mostly a question of what you want the container to do when your application exits, if it's stable enough to run forever without dying, etc.

Running several copies of a process is perfectly fine with s6, if your concurrent copies do not lock resources. If it is a supported use case of your application that you can have several instances of the same process running in parallel, then it's definitely not wrong to define a service for each instance.

s6 only supports static instantiation, which means that yes, you would have to define a service for every copy. (Dynamic instantiation is much, much harder to implement and outside the scope of s6-overlay.) But if you know in advance how many instances you want to run, that should not be an issue.

I would recommend against running several copies of a process in CMD, even when headed by a `wait` command. That would cause you significant difficulties when you want to stop the container - you'd need to transmit the signal to all copies, etc. and eventually you'd have to reimplement some of the features that s6 provides. If your application is supposed to run forever and only stop when the administrator tells it to, then running several instances of your application as a set of supervised services is the best solution for you.

**Comment by skarnet** [comment]
Closing this.
