### ISSUE TITLE
using an image with s6 with a docker-compose.yaml and a `COMMAND` will shutdown

### ISSUE THREAD

**Issue by BananaAcid** [just-containers/s6-overlay#448]
Problem: `COMMAND` in a `docker-compose.yaml` will crash / shutdown forcefully any s6-overlay based container.

**dockerfile:**
Just any dockerfile, for this example I tested it locally with: https://github.com/just-containers/s6-overlay#quickstart

**compose file**
For quick testing, the `p3terx/s6-alpine` image was used, but any s6-overlay container shuts down when using command, same for the quickstart example.

docker-compose.yaml
```yaml
version: "3"

services:
  server:
    image: p3terx/s6-alpine
    
    command: >
      sh -c
        "echo \"hi!\" "
```

**RESULT:**

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.

hi!
[cmd] sh exited 0

[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by skarnet** [comment]
Sorry, we don't provide support for s6-overlay v2 anymore, in part due to these kinds of recurring issues. Your image provider should update to s6-overlay v3, which should solve your problem (and if it doesn't we'll be able to fix it quickly enough).

**Comment by BananaAcid** [comment]
temporary fix:
within the command part, appended `sleep 100000000000000` and it works so far.

**Comment by skarnet** [comment]
Closing this.
