### ISSUE TITLE
Alpine 3.16: s6-supervise (child): fatal: unable to exec run: No such file or directory

### ISSUE THREAD

**Issue by GreyXor** [just-containers/s6-overlay#449]
Hello,
I want to use the s6-overlay package integrated in alpine 3.16
<details>
  <summary>Files</summary>

**Dockerfile**
```Dockerfile
FROM alpine

RUN apk add --no-cache redis s6-overlay

# Contains s6-overlay config
COPY /rootfs /

ENTRYPOINT ["/init"]
```

**/etc/s6-overlay/s6-rc.d/redis-server/run** (inside container)
```
#!/command/execlineb -P

s6-setuidgid redis

redis-server
```

**/etc/s6-overlay/s6-rc.d/redis-server/type** (inside container)
```
longrun
```

/etc/s6-overlay/s6-rc.d/user/contents.d/redis-server exists
</details>

**Log**
```sh
s6-rc: info: service redis-server: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-supervise redis-server (child): fatal: unable to exec run: No such file or directory
s6-supervise redis-server: warning: unable to spawn ./run - waiting 10 seconds
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: fatal: timed out
s6-svlisten1: fatal: timed out
s6-supervise redis-server (child): fatal: unable to exec run: No such file or directory
s6-supervise redis-server: warning: unable to spawn ./run - waiting 10 seconds
```

my use seems to be correct and standard. do you have any idea why I have this error? thanks

**Comment by skarnet** [comment]
Yeah, that's a specificity of the Alpine package for s6-overlay:  it reuses the existing skaware packages, which install binaries under `/bin` and `/usr/bin` instead of using slashpackage. So the `#!/command/execlineb -P` shebang won't work with it; try `#!/bin/execlineb -P` or `#!/usr/bin/execlineb -P` instead.

Yes, it sucks, but until distributions realize that it's okay to install symlinks in `/command`, there's unfortunately nothing else I can do.

**Comment by GreyXor** [comment]
Yes I understand the situation here.
Thanks tho!

**Comment by cyqsimon** [comment]
I just ran into the opposite problem: the template files I sourced had `#!/usr/bin/execlineb -P`, but I am installing the overlay using the official tarball, which only provides `/command/execlineb`. FYI for any future readers.

**Comment by skarnet** [comment]
@cyqsimon That's what the symlink tarballs are for - they will provide compatibility links in `/usr/bin` for systems that have hardcoded paths.
