### ISSUE TITLE
fix-attr broken with space

### ISSUE THREAD

**Issue by neclimdul** [just-containers/s6-overlay#453]
I see its deprecated so I guess the long term fix is to move away from this feature but reporting since its supported and likely something someone else will run into. 

Currently when run on a location that has files containing spaces it fails complaining about a missing file. For example applying to `/app` something like `/app/files/foo bar` triggers an error  about `/app/files/foo` not existing.

Looking at applyrec it makes sense that this would fail because unless I'm missing something this loop would split on spaces.

https://github.com/just-containers/s6-overlay/blob/3d4469f9ab235fc9602b8b30feeada71e784cb2d/layout/rootfs-overlay/package/admin/s6-overlay-%40VERSION%40/libexec/fix-attrs#L14

**Comment by skarnet** [comment]
Ah, good catch, will fix, thanks.

**Comment by skarnet** [comment]
It should be long fixed now.
