### ISSUE TITLE
Longrun dependency with oneshot

### ISSUE THREAD

**Issue by ksurl** [just-containers/s6-overlay#454]
Is writing 3 to notification-fd in definition folder of the oneshot the correct way to make sure a longrun service does not start until the oneshot exits? Assuming the oneshot is listed as a dependency of the longrun.

**Comment by skarnet** [comment]
No, `notification-fd` is only useful for longruns. Oneshots notify readiness when the script exits. Normally, if your oneshot is listed as a dependency of your longrun, the longrun should *already* wait until your oneshot's `up` script exits before starting.

**Comment by skarnet** [comment]
Closing this.
