### ISSUE TITLE
Issues at v3.1.1.0

### ISSUE THREAD

**Issue by pvizeli** [just-containers/s6-overlay#456]
It seems that on some hosts and also on AWS ECS, the new overlay version makes the container freeze with around 100% CPU and no output at all. https://github.com/home-assistant/addons/issues/2540 -> https://github.com/home-assistant/addons/issues/2540#issuecomment-1162260272

I can not reproduce it directly local. I saw the issue with our ECS services. But others have also the issue with the add-ons. Revert back to the 3.1.0 all work fine.

It looks also a bit like if you try to run 3.x with multiarch (Qemu) on an amd64. No output and nothing is working. That worked just fine with the 2.x before

**Comment by skarnet** [comment]
We have _just_ identified the issue today.
This is most likely your hosts running an older kernel than the binaries were built with. In particular, the GRND_INSECURE option to the `getrandom()` system call may not be supported by your kernels.

We are working on a fix and will publish a new s6-overlay releaser as soon as it is ready.

**Comment by joergmschulz** [comment]
I'm seeing it on 
`Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal`

**Comment by bfren** [comment]
I am seeing this issue on aarch64 but not amd64 (both Ubuntu 20.04).  Is there anything I can run to get a debug log to help track down / confirm what the issue is?  All I can see via `top` is `s6-ftrigrd` is running at 100% cpu.

**Comment by skarnet** [comment]
You can add the `strace` package to your container, start the container with the `CAP_SYS_PTRACE` capability added (`docker run --cap-add sys_ptrace ...`) then when `s6-ftrigrd` is looping, get a shell in the container and strace the `s6-ftrigrd` process, likely pid 27.

No matter the architecture, chances are you will see a `getrandom()` system call looping with a -1 EINVAL result.

I'm about to push a fix right now, and the new release will be available as soon as github builds it. People following this issue, please test the new release when it's available and report if it's working for you or not.

**Comment by pvizeli** [comment]
@skarnet I would like to sponsor you at GitHub

**Comment by skarnet** [comment]
@pvizeli Thank you! But please read [this Twitter thread](https://twitter.com/laurentbercot/status/1209247040657674240) where I talk about FOSS funding and individual donations.

 I have found a corporate sponsor since, and now the time I spend on s6-overlay (and other projects) is adequately compensated. :-)

**Comment by bfren** [comment]
All sorted for me too, many thanks.
