### ISSUE TITLE
ServiceA never receives any TERM signal when "on-demand" ServiceB has never started at least once

### ISSUE THREAD

**Issue by lmagyar** [just-containers/s6-overlay#458]
S6-overlay: v3.1.1.0, 3.1.0.1, Alpine v3.15

related: #337 #179 #356

see: #457 because in current issue S6_SERVICES_GRACETIME works! maybe it helps to locate the bug in that issue!

repo to reproduce: https://github.com/lmagyar/homeassistant-addon-mariadb-inmemory-beta/tree/BUG2/mariadb

config: 2 etc/services.d services
  - serviceA runs continuously in a `wait "${...}"`, and has `trap ... SIGTERM SIGHUP`
  - serviceB has a `down` file, started on demand with `/command/s6-svc -wR -o /run/service/serviceB/` and it notifies and stops normally a few seconds later (it has `notification_fd` file and `echo "" >&3`)

BUG:
  - when serviceB never started, serviceA never receives any TERM signal when the container stops
  - when serviceB started at least once, serviceA receives TERM signal and s6 waits S6_SERVICES_GRACETIME time to let it finish it's job in it's TERM trap

**Comment by skarnet** [comment]
Duplicate issue with the other one you just opened. The fundamental problem is that your mariadb run script is way too complex and does not fit the specifications of a supervised service.
