### ISSUE TITLE
Accessing environment variables from within scripts

### ISSUE THREAD

**Issue by smebberson** [just-containers/s6-overlay#46]
I'm having a hard time access environment variables within various scripts that I'm running inside the container.

I've read through the source of s6-overlay and found things like `with-contenv` and `import-from-envdir`, but I just can't get these to function.

I noted all of the scripts are in the execline language, using `#!/usr/bin/execlineb -S0`. Do we have to use that to use `with-contenv` and access the environment variables? We're currently using `#!/bin/sh` because that is what we're familiar with but can't access any of the environment variables.

There are two scenarios, we want to access environment variables for use within scripts, such as:

```
if [ -z ${TUTUM_SERVICE_HOSTNAME+x} ]; then
  BIND=`getent hosts ${HOSTNAME} | awk '{print $1}'`
else
  BIND=`getent hosts ${TUTUM_SERVICE_HOSTNAME} | awk '{print $1}'`
fi
```

And we also want to start things such as Node.js applications with the container environment, maybe something like:

```
#!/bin/sh

# cd into our directory
cd /app

# start our node.js application
exec with-contenv node server.js;

```

**Comment by smebberson** [comment]
Just wanted to add that when I run a script through `docker exec` everything works fine, the environment variables exist. But when the script is run through s6, they don't.

**Comment by glerchundi** [comment]
`with-contenv` is the way to go. It was coded with `execline` in mind (chaining processes) but it can be used with other kind of scripting languages of course!

Try this:

```
#!/usr/bin/with-contenv sh

# cd into our directory
cd /app

# start our node.js application
exec node server.js;
```

**Comment by smebberson** [comment]
Awesome, that works perfectly :)

Do you think this is worth adding to the documentation, the README? I'd be happy to submit a PR with this....

**Comment by glerchundi** [comment]
PR are always welcome, and if they are to document, even better!

**Comment by smebberson** [comment]
@glerchundi, also, am I correct in thinking that in your example, node would also have the same environment variables despite the fact it was `exec`'d?

Alright, I'll get to work!

**Comment by glerchundi** [comment]
> @glerchundi, also, am I correct in thinking that in your example, node would also have the same environment variables despite the fact it was exec'd?

yeah, i think so: http://ss64.com/bash/exec.html

**Comment by jprjr** [comment]
@smebberson That should work - exec only clears the environment when you use the `-c` switch.

**Comment by smebberson** [comment]
@glerchundi, just to be clear, for documentation purposes.

From reading the code, if I have a script that sets environment variables using `setenv` or `export` this won't make it's way into the `/var/run/s6/container_environment` directory... I could be wrong?

If they don't, that means running a script with `#!/usr/bin/with-contenv sh` won't pick up the new environment variables... how should one go about doing this kind of thing with s6-overlay?

**Comment by glerchundi** [comment]
You're correct. In runtime you can make it available if you create a file (naming it with your desired env name) and fill it with your custom value. Something like this: `printf "YOURVALUE" > /var/run/s6/container_environment/YOURENV`.

That should do the trick.

**Comment by apratina** [comment]
@glerchundi @jprjr @smebberson @skarnet : using `with-contenv bash` we are unable to use any environment variable of length greater than 4096 char. Is this a known issue?
I have created a very simple way to repro it. Check [here](https://github.com/apratina/with-contenv-repro-env-length-issue#build-image).

**Comment by skarnet** [comment]
Yes, there's a 4096 byte limit for variables loaded via `s6-envdir`. This is intentional: most legitimate uses of the environment never transmit large quantities of data. You can put the data in a temporary file, put the name of the file in an environment variable, and make your application get its data from the file.

Alternatively, you could recompile skalibs, then s6 after increasing the limit here: [http://git.skarnet.org/cgi-bin/cgit.cgi/skalibs/tree/src/libstddjb/envdir.c#n12] but it will not be standard and you will need to maintain the patch.

**Comment by VINAYJAGANNATH** [comment]
Can the limit of 4096 bytes made configurable ? 
If yes this would give us great flexibility to inject environment variables which have higher than 4096 bytes.

**Comment by skarnet** [comment]
My previous post suggests two ways of achieving what you want.
