### ISSUE TITLE
s6-notifyoncheck: fatal: unable to sanity-check current service directory: Permission denied

### ISSUE THREAD

**Issue by kishore25kumar** [just-containers/s6-overlay#462]
I am trying to setup dependency using s6-notifyoncheck. Everything worked as expected but when I try to drop down root privileges I am getting below error

```
s6-notifyoncheck: fatal: unable to sanity-check current service directory: Permission denied
```

I tried strace to figure out what is the actual issue and found below response
```
arch_prctl(ARCH_SET_FS, 0x60c9f8)       = 0
set_tid_address(0x60cb90)               = 390
open("./supervise/lock", O_RDONLY|O_NONBLOCK|O_LARGEFILE) = -1 EACCES (Permission denied)
writev(2, [{iov_base="s6-notifyoncheck: fatal: unable "..., iov_len=93}, {iov_base=NULL, iov_len=0}], 2s6-notifyoncheck: fatal: unable to sanity-check current service directory: Permission denied
) = 93
exit_group(111)                         = ?
+++ exited with 111 +++
```
Any idea on how to fix this?

**Comment by skarnet** [comment]
Yes, `s6-notifyoncheck` needs to run as the same user as the supervisor, i.e. likely root.

Call `s6-notifyoncheck` before dropping privileges: instead of running `exec s6-setuidgid my_daemon_user s6-notifyoncheck my_daemon`, run `exec s6-notifyoncheck s6-setuidgid my_daemon_user my_daemon`.

**Comment by kishore25kumar** [comment]
Thank you @skarnet it worked.
