### ISSUE TITLE
Question: About bundles and order of execution

### ISSUE THREAD

**Issue by roussidis** [just-containers/s6-overlay#463]
Hello and thank you for your project.

Lately I am trying to migrate into the latest v3 s6-overlay from v2. While testing and checking out its functionalities some questions came up that I was not able solve from the documentation. 

Out of my findings and my understanding (of course correct me where I am wrong) there is the top bundle that is the first one which is called from s6-init.

From the top bundle there are dependencies resolved and the first bundle bundle which is called is the base. Base starts with fix-attrs and then the legacy-cont-init script (they have a dependency on the fix-attrs).

Later on while resolving the dependencies it's called the user bundle (because legacy-services have a dependency on it). Followed by legacy-services and finally from the information gathered the user2 bundle is running last. 

I haven't found a dependency regarding user2 bundle. How are we sure that user2 is always last even after the legacy-services ?

My approach would be to create some other bundles and add them to the top bundle. ( I wouldn't want to use the user and user2 bundles).

A setup would be a base image and then a child image 1
```
FROM base image
```

and even another child image 2 with some more nesting 
```
FROM child image1
```

How could it be possible the longrun services from every image (base, child image 1, child image 2) to start always last at the end. I would want somehow to re-create the functionality of user2 bundle which as you say always start last.
How would that be possible?

I would not want to explicitly set a dependency for my longrun services on a specific oneshot service. 
I would like something more dynamically set. How easy it is to create a bundle that starts always last ?

Is there any specific dependency that I can set on my longrun services that would make them run last every time (reminder I don't want to use the user2 bundle) ?

Thank you in advance

**Comment by roussidis** [comment]
So another question that arises. You have said that you intend to support legacy cont-init and legacy services.d scripts.

Does this support will end eventually? 
This is my "fear" and that's why I am intending to migrate to the new scheme. I am very happy with the legacy format but I am afraid that this support might end some time. So since I am updating to v3 i though to migrate the scheme as well

**Comment by skarnet** [comment]
We're not planning on ending the support for `/etc/cont-init.d` and `/etc/services.d`, because it's well integrated in the new scheme and doesn't require much maintenance. You can count on it being supported forever.

We *will* encourage migrating to the new service scheme whenever it solves a problem that cannot be solved with the old scheme. For instance, if you have a oneshot that depends on a longrun, you *need* to use the new scheme. We will not add new developments or anything on the old scheme. But it will stay right where it is.
