### ISSUE TITLE
Question : alternate location for uncaught-logs

### ISSUE THREAD

**Issue by jake-scott** [just-containers/s6-overlay#464]
In the previous version of s6-overlay, we were able to replace `/etc/s6/services/s6-svscan-log` with a new version during container build, that logged to an alternate location.  The newer version of s6-overlay seems to create this service at container start time by way of s6-linux-init-maker.  What is the recommended way to modify the run script for the s6-svscan-log service now?

**Comment by jake-scott** [comment]
Thanks this makes sense.. I did end up making this work by patching `/package/admin/s6-overlay-${S6_OVERLAY_VERSION}/libexec/stage0` in the Dockerfile with:

```
--- libexec/stage0.orig	2022-07-07 12:03:31.774083096 -0400
+++ libexec/stage0	2022-07-07 11:57:13.519909304 -0400
@@ -66,6 +66,13 @@
 
 s6-linux-init-maker -NC -D top -c "$basedir" -p "$PATH" -f /package/admin/s6-overlay-3.1.1.2/etc/s6-linux-init/skel $stampopt $dumpopt $logopt $loguseropt $graceopt $syncopt -- "$basedir"
 
+mkdir -p -m 0755 /squid/logs/container
+
+if test -n "$loguseropt"; then
+    chown -R nobody /squid/logs/container
+fi
+sed -i 's;/run/uncaught-logs;/squid/logs/container;' ${basedir}/run-image/service/s6-svscan-log/run
+
 if test -z "$dumpopt" ; then
   s6-rename "$basedir/env" "$basedir/env.orig"
   s6-dumpenv -N "$basedir/env"
```

It feels dirty but it works in our specific case where we bomb out at initialization if someone forgot to bind mount the logs directory anyway.  The main reason for wanting this was to catch the s6-overlay messages themselves somewhere - point taken about logging by the container manager - perhaps that might be the better solution for these specific messages.

Thanks for taking the time to reply, much appreciated.

**Comment by skarnet** [comment]
Yes, your patch only works if you have a pre-mounted read-write `/squid` hierarchy. Some containers don't pre-mount a read-write filesystem at all, which is why we're hardcoding the directory under `/run` because it's the only filesystem we can guarantee exists and is writable.

It sounds like no catch-all logger at all, letting the default logs fall through to the host is the real solution to what you want. :-)
