### ISSUE TITLE
CMD no longer inheriting environment variables after upgrading from v2

### ISSUE THREAD

**Issue by tedtramonte** [just-containers/s6-overlay#465]
I can see in our safely running production container on v2.2.0.3 that our `php-fpm` process is including `with-contenv` at some point during the init process.

In the broken container I'm testing in on v3.1.1.2 `ps auxf` doesn't clearly show `with-contenv` being part of the init process.

Did I maybe miss a step in the upgrade notes? In our working container, both the shell user and `phpinfo()` sees all the variables we want. In the busted container, the environment has only
```
PWD=/var/www
SHLVL=1
PATH=/command:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
OLDPWD=/
_=/usr/bin/env
~``

**Comment by tedtramonte** [comment]
Adjusting the CMD to:
```
CMD ["with-contenv", "php-fpm","-F", "-O"]
```
seems to restore the behavior I was expecting. Is this just new default behavior and we should be using `with-contenv` as part of our CMD from now on, if wee need that functionality?

**Comment by skarnet** [comment]
If the container environment was available by default in the CMD in v2, that's one of the numerous misdesigns that v3 aims to fix, so the answer to your question is yes, if you want the whole environment in your CMD, you should use `with-contenv`.

That said, I wasn't even aware this was the case, total oversight on my part, my bad; I will add a line to the [upgrade notes](https://github.com/just-containers/s6-overlay/blob/master/MOVING-TO-V3.md) that documents this. Thanks for the report.

**Comment by tedtramonte** [comment]
Interesting. I see why you would make the change, so that every script run by s6 is consistent in how it needs to be manipulated. Plus it's easier to add environment variables for a process than remove them. Glad I wasn't going crazy, and happy to help.
