### ISSUE TITLE
s6-sudoc: fatal: unable to get exit status from server: Operation timed out

### ISSUE THREAD

**Issue by nocive** [just-containers/s6-overlay#467]
In one of our applications which is using the new rc.d layer we sometimes observe the following error during the startup sequence of the container:

```
+ dockerize -template /etc/templates/nginx/includes:/etc/nginx/includes -template /etc/templates/nginx/nginx.conf.tpl:/etc/nginx/nginx.conf -template /etc/templates/nginx/nginx-proxy.conf.tpl:/etc/nginx/sites-enabled/proxy.conf
s6-rc: info: service configure-services successfully started
s6-rc: fatal: timed out
s6-sudoc: fatal: unable to get exit status from server: Operation timed out
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.
```

We already set `S6_CMD_WAIT_FOR_SERVICES_MAXTIME` to 30s on this specific container, but it seems there's another timeout at play here? Please advise :)

```
S6_CMD_WAIT_FOR_SERVICES=1
S6_CMD_WAIT_FOR_SERVICES_MAXTIME=30000
S6_BEHAVIOUR_IF_STAGE2_FAILS=2
S6_LOGGING=0
```

```
s6 version v3.1.1.2
```

Please note that this only happens sometimes, so there doesn't seem to be anything fundamentally wrong in the startup sequence other than this time out being reached under some circumstances (higher load on the machine?).

I don't have a minimum repro scenario that I can provide at this point, sorry.

**Comment by skarnet** [comment]
In your s6-rc database, there is a _oneshot_ service that is timing out. You can check by looking at the logs in `/run/uncaught-logs/current`: you will have a service `foo` that has a `s6-rc: info: service foo: starting` line, but no `s6-rc: info: service foo sucessfully started` line. That's the culprit.

Then you should check the corresponding definition in `/etc/s6-overlay/s6-rc.d/foo`. In particular, if there is a `timeout-up` file, you should increase the value it contains. If there is no such file, chances are your `foo` service is timing out after the whole 30s and you need to keep increasing the global timeout.

**Comment by nocive** [comment]
We do not have specific timeouts on any of the rc.d services.
`configure-app` and `configure-services` are one-shot services which are dependencies of other non one-shot services:
Here's how tree:

```
├── etc
│   ├── s6-overlay
│   │   └── s6-rc.d
│   │       ├── configure-app
│   │       │   ├── type
│   │       │   └── up
│   │       ├── configure-services
│   │       │   ├── type
│   │       │   └── up
│   │       ├── nginx
│   │       │   ├── dependencies.d
│   │       │   │   ├── configure-app
│   │       │   │   └── configure-services
│   │       │   ├── finish
│   │       │   ├── run
│   │       │   └── type
│   │       ├── php-fpm
│   │       │   ├── dependencies.d
│   │       │   │   ├── configure-app
│   │       │   │   └── configure-services
│   │       │   ├── finish
│   │       │   ├── run
│   │       │   └── type
│   │       └── user
│   │           └── contents.d
│   │               ├── configure-app
│   │               ├── configure-services
│   │               ├── nginx
│   │               └── php-fpm
```

We have bumped `S6_CMD_WAIT_FOR_SERVICES_MAXTIME` to 60s and will be checking if this helps/fixes the issue.

**Comment by skarnet** [comment]
Since your `configure-services` was successfully started, the one that's timing out is `configure-app`. You could check why it's taking so much time.

**Comment by nocive** [comment]
Bumping `S6_CMD_WAIT_FOR_SERVICES_MAXTIME` solved the issue.
`configure-app` can slug under heavy load conditions.

Closing, thanks for your quick and very helpful support, once again! :+1:
