### ISSUE TITLE
with-contenv not working with oneshot type

### ISSUE THREAD

**Issue by Sander0542** [just-containers/s6-overlay#468]
When I am using the `#!/command/with-contenv sh` she-bang in an oneshot up script the env is only filled with the path.

`myapp/up`
```
#!/command/with-contenv sh
env
```

`myapp/type`
```
oneshot
```

**Comment by skarnet** [comment]
`up` files are not executables and do not take a shebang.

Search for `weird syntax` in the [README.md](https://github.com/just-containers/s6-overlay/blob/master/README.md) file and click on the arrow for the detailed explanation.
