### ISSUE TITLE
`with-contenv` executes the shebang as a single argument

### ISSUE THREAD

**Issue by jprjr** [just-containers/s6-overlay#47]
Hey guys, just noticed this:

If I make a runscript like:

```
#!/usr/bin/with-contenv /usr/bin/env perl
```

It's a contrived example, but it looks like `with-contenv` treats `/usr/bin/env perl` as a single argument, then dies (since `/usr/bin/env perl` isn't a valid program).

I'm not super-hot as execline, what's the right way to make sure the rest of the shebang is split up into arguments?

**Comment by glerchundi** [comment]
hei john, i think this is not related to execline, probably this won't work too (although i didn't try it): `#!/usr/bin/env /bin/bash perl`.

**Comment by glerchundi** [comment]
john, can we close this?

**Comment by skarnet** [comment]
Yup, it's not an execline problem, it's the kernel's interpretation of the shebang line that is very limited. It can only read one single argument after the first space on the line.
If the shebang line was powerful enough to correctly parse a command line, there would be no need for the `execlineb` parser ! :-)

... which gives the answer to @jprjr 's question: that kind of simple command line is exactly what `execlineb` was made for.
```
#!/usr/bin/execlineb -S0
/usr/bin/with-contenv /usr/bin/env perl $@
```

**Comment by jprjr** [comment]
Sweet, thanks guys - I'll go ahead and close this.
