### ISSUE TITLE
One shot scripts don't appear to be running on container start

### ISSUE THREAD

**Issue by ambled** [just-containers/s6-overlay#470]
I'm having an issue setting up a new s6-overlay environment. I initially used an entrypoint script in /etc/cont-init.d however with the latest version of s6, the script doesn't get attempted (from reading the docker logs). 

I had initially setup using /etc/cont-init.d/00-entrypoint, then when that didn't seem to work, I attempted to use the s6-rc method (shown below).  Am I missing something?

# Please provide a small Dockerfile that demonstrates your issue.
```
FROM alpine:3.16 AS base
ARG S6_OVERLAY_VERSION=v3.1.1.2
# Adding S6-overlay to manage container services
RUN wget https://github.com/just-containers/s6-overlay/releases/download/${S6_OVERLAY_VERSION}/s6-overlay-x86_64.tar.xz --no-check-certificate -O /tmp/s6-overlay-x86_64.tar.xz \
    && wget https://github.com/just-containers/s6-overlay/releases/download/${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz --no-check-certificate -O /tmp/s6-overlay-noarch.tar.xz \
    && tar xpJf /tmp/s6-overlay-noarch.tar.xz -C / \
    && tar xpJf /tmp/s6-overlay-x86_64.tar.xz -C / \
    && rm -f /tmp/s6-overlay-x86_64.tar.xz  \
             /tmp/s6-overlay-noarch.tar.xz

COPY docker/00-entrypoint /etc/s6-overlay/scripts/00-entrypoint
COPY docker/00-entrypoint.up /etc/s6-overlay/s6-rc.d/00-entrypoint/up
COPY docker/00-entrypoint.type /etc/s6-overlay/s6-rc.d/00-entrypoint/type
COPY docker/01-echo /etc/s6-overlay/scripts/01-echo
COPY docker/01-echo.up /etc/s6-overlay/s6-rc.d/01-echo/up
COPY docker/01-echo.type /etc/s6-overlay/s6-rc.d/01-echo/type
RUN chmod +x /etc/s6-overlay/scripts/00-entrypoint \
             /etc/s6-overlay/scripts/01-echo
ENTRYPOINT ["/init"]
```

00-entrypoint.up
```
/etc/s6-overlay/scripts/00-entrypoint
```

00-entrypoint
```
#!/usr/bin/with-contenv bash

FILE=/var/www/html/.env
if [ -f "$FILE" ]; then
    echo "$FILE already exists."
else
    echo "$FILE does not exist. Creating..."
...
```

Startup logs
```
orion  | s6-rc: info: service s6rc-oneshot-runner: starting
orion  | s6-rc: info: service s6rc-oneshot-runner successfully started
orion  | s6-rc: info: service fix-attrs: starting
orion  | s6-rc: info: service fix-attrs successfully started
orion  | s6-rc: info: service legacy-cont-init: starting
orion  | s6-rc: info: service legacy-cont-init successfully started
orion  | s6-rc: info: service legacy-services: starting
orion  | s6-rc: info: service legacy-services successfully started
````

**Comment by ambled** [comment]
Hmm, I registered the s6-rc.d/user/contents.d and I get:

s6-rc-oneshot-run: fatal: unable to exec /etc/s6-overlay/scripts/01-echo: No such file or directory

however

```
orion:local:/var/www/html $ ls -al /etc/s6-overlay/scripts/01-echo
-rwxrwxr-x    1 root     root            39 Aug 22 22:54 /etc/s6-overlay/scripts/01-echo
```

**Comment by ambled** [comment]
aha, I figured out the /usr/bin/with-cont was what was failing for the s6-rc scripts, using /command/with-cont fixed that, trying to convert back to /etc/cont-init.d since it's less overhead for my one-shots. Good to know about the s6-rc issue for my longrun's that come next.

Thank you!

**Comment by skarnet** [comment]
Yes, unfortunately shebangs are places where we have to use absolute paths instead of relying on PATH, and `with-contenv` (as well as other helpers) is only accessible via `/command` now, unless you install the `symlinks-noarch` tarball.

Good luck!

**Comment by ambled** [comment]
ok, fixing the shebang made the oneshot script work correctly in /etc/cron-init.d location, which suits my needs. Thank you!
