### ISSUE TITLE
service scripts starting before /etc/cont-init.d scripts are finished

### ISSUE THREAD

**Issue by ambled** [just-containers/s6-overlay#471]
Now that I have one-shot script successfully setup (currently using /etc/cont-init.d location), I'm finding that services in bundle 'user' are started immediately on boot instead of waiting for the dependency of the one-shot finishing and I'm not sure how to accomplish this.

Do I need to move my one-shot back into an s6-rc.d mess before it can become a dependency? My understanding was that the one-shots finish before services were being started.

**Comment by skarnet** [comment]
If you want a service to wait until the `/etc/cont-init.d` scripts are all done before starting, you need to make it depend on `base`.

`cd /etc/s6-overlay/s6-rc.d/yourservice && mkdir -p dependencies.d && touch dependencies.d/base`

**Comment by ambled** [comment]
That worked perfectly! Thank you, did I miss this someplace in the documentation?

**Comment by skarnet** [comment]
Not explicitly. I should probably make it more obvious but I didn't want to duplicate the s6-rc documentation. The [README](https://github.com/just-containers/s6-overlay/blob/master/README.md) hints at a dependency system, gives a few examples, and points to the [source format documentation](https://skarnet.org/software/s6-rc/s6-rc-compile.html#source), but it's easy to miss it.
