### ISSUE TITLE
Assigning the variable "S6_VERBOSITY" leads to error

### ISSUE THREAD

**Issue by lapicidae** [just-containers/s6-overlay#472]
Assigning the variable "S6_VERBOSITY" leads to an error and prevents the container from starting.

[Dockerfile](https://github.com/just-containers/s6-overlay/files/9433414/Dockerfile.txt)
```
ERROR:
sh: out of range
s6-rc-compile: usage: s6-rc-compile [ -v verbosity ] [ -h fdholder_user ] [ -b ] destdir sources...
```

**Comment by skarnet** [comment]
Indeed. Ouch, sorry about that.
Working on a fix and a new release.

**Comment by skarnet** [comment]
Should be fixed in 3.1.2.0, available now.

**Comment by lapicidae** [comment]
Now works as intended, thank you.

**Comment by elcajon** [comment]
I stumbled across this issue today and wanted to ask if it is intentional that the ENV variable only works for v3 services while legacy v2 services.d and cont-init.d scripts still produce output in the log? 

S6_VERBOSITY set to 1
```
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/02-set-timezone.sh
```

**Comment by skarnet** [comment]
It's normal, as in there's no explicit S6_VERBOSITY support in legacy services, but you're right that it probably doesn't meet user expectations. I'll change this in a future patch.

**Comment by elcajon** [comment]
All right, thanks for the clarification. It's certainly not an urgent problem. 👍
