### ISSUE TITLE
Container exiting straight away

### ISSUE THREAD

**Issue by bfren** [just-containers/s6-overlay#473]
Release of 3.1.2.0 has changed run behaviour.

```Dockerfile
FROM ubuntu
ARG S6_OVERLAY_VERSION=3.1.1.2

RUN apt-get update && apt-get install -y xz-utils

ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.x>RUN tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-x86_64.tar.x>RUN tar -C / -Jxpf /tmp/s6-overlay-x86_64.tar.xz
ENTRYPOINT ["/init"]
```

```bash
docker build -t demo3.1.1 . && docker run -it demo3.1.1 sh
```

Container builds, runs, and a shell prompt opens.

```Dockerfile
FROM ubuntu
ARG S6_OVERLAY_VERSION=3.1.2.0

RUN apt-get update && apt-get install -y xz-utils

ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.x>RUN tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-x86_64.tar.x>RUN tar -C / -Jxpf /tmp/s6-overlay-x86_64.tar.xz
ENTRYPOINT ["/init"]
```

```bash
docker build -t demo3.1.2 . && docker run -it demo3.1.2 sh
```

Container builds, runs, but exits instantly.

I can't see anything in the release notes / docs that suggests why this might be happening, so I'm not sure if this is a bug or new (i.e. expected) behaviour.

**Comment by skarnet** [comment]
*grumbles*
It's a regression, sorry about that. It's a side effect of something I changed to address a user request.
I'm fixing it, 3.1.2.1 coming out soon.

**Comment by bfren** [comment]
No worries, thanks for the speedy response.

**Comment by skarnet** [comment]
There, 3.1.2.1 is out, and your interactive shells should run properly. Please note, however, that running an interactive CMD is incompatible with using the new `S6_CMD_RECEIVE_SIGNALS` variable.

**Comment by bfren** [comment]
Great thanks, all working as expected.
