### ISSUE TITLE
Win11 S6 overlay 3.1.0.1 fatal no longrun or oneshot or bundle, despite being longrun

### ISSUE THREAD

**Issue by WiebedeBoer** [just-containers/s6-overlay#474]
# Please provide a small Dockerfile that demonstrates your issue.

FROM novoserve/php7.4-fpm-alpine

ENV LC_ALL "C"
ENV ABUSEIO_PATH /var/www/html
ENV S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0
ARG S6_OVERLAY_VERSION=3.1.0.1
ARG ARCH=x86_64

ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz /tmp
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-${ARCH}.tar.xz /tmp
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-symlinks-noarch.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz && \
    tar -C / -Jxpf /tmp/s6-overlay-${ARCH}.tar.xz && \
    tar -C / -Jxpf /tmp/s6-overlay-symlinks-noarch.tar.xz

RUN apk add --no-cache --virtual .build-deps \
    make \
    gcc \
    g++ \
    autoconf \
    re2c \
    oniguruma-dev \
    libpq-dev \
    curl-dev \
    libzip-dev \
    icu-dev \
    libmcrypt-dev \
    wget \
    && docker-php-ext-install -j$(nproc) \
    mbstring \
    pdo \
    pdo_pgsql \
    pdo_mysql \
    curl \
    zip \
    intl \
    bcmath \
    && pecl install \
    mailparse \
    mcrypt \
    && docker-php-ext-enable \
    mailparse \
    mcrypt \
    && pear install \
    Mail_mimeDecode \
    && apk del .build-deps && \
    apk add --no-cache \
    oniguruma \
    libpq \
    curl \
    libzip \
    icu \
    libmcrypt \
    nginx \
    gettext \
    mariadb-client \
    fetchmail

RUN addgroup -S abuseio -g 1000 && \
    adduser -S abuseio -G abuseio -u 1000 && \
    addgroup www-data abuseio

COPY --from=composer:2 /usr/bin/composer /usr/local/bin/composer
ENV PATH :/composer/vendor/bin:/root/.composer/vendor/bin:/usr/local/bin:$PATH

WORKDIR ${ABUSEIO_PATH}
COPY docker/php/php.ini ${PHP_INI_DIR}/conf.d/
COPY --chown=abuseio:abuseio --chmod=0775 . .
COPY --chmod=0755 docker/rootfs/ /
RUN composer install --working-dir=${ABUSEIO_PATH} --no-dev --no-scripts

HEALTHCHECK --interval=5m --timeout=5s CMD ["curl", "-f", "-k", "https://localhost/"]
ENTRYPOINT ["/init"]

#provides the following error on windows 11 with docker desktop:
#s6-rc-compile: fatal: invalid /etc/s6-overlay/s6-rc.d/crond/type: must be oneshot, longrun, or bundle
#yet when I look in the image it gives type longrun
#the image was previously made on a mac

**Comment by skarnet** [comment]
Chances are your end-of-lines are `\r\n` instead of `\n`. You can fix that by treating all your files with `dos2unix`.

**Comment by WiebedeBoer** [comment]
tried that, didn't work on the windows. I'm gonna try a VM instead

**Comment by skarnet** [comment]
Have you solved the issue? Can I close this?
