### ISSUE TITLE
unable to start container process: exec: "/init": stat /init: no such file or directory

### ISSUE THREAD

**Issue by schleyk** [just-containers/s6-overlay#475]
Hello together,

```
FROM php:7.4.30-apache-bullseye

ENV TZ "Europe/Berlin"
ARG DEBIAN_FRONTEND=noninteractive
ARG S6=v3.1.2.1

ADD https://github.com/just-containers/s6-overlay/releases/download/v$S6/s6-overlay-x86_64.tar.xz /tmp/
RUN tar xvJf /tmp/s6-overlay-x86_64.tar.xz -C / && rm /tmp/s6-overlay-x86_64.tar.xz

COPY rootfs/ /
ENTRYPOINT ["/init"]
```
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/init": stat /init: no such file or directory: unknown

Does "s6-overlay-x86_64.tar.xz" no longer contain [/init](https://github.com/just-containers/s6-overlay/blob/master/layout/rootfs-overlay/init)?

```
root@build:/srv/docker/web# docker run -it --entrypoint /bin/bash test
root@32ddebdb18a6:/var/www/html# ls /
bin  boot  command  dev  etc  home  lib  lib64  media  mnt  opt  package  proc  root  run  sbin  srv  sys  tmp  usr  var
```
best regards

**Comment by skarnet** [comment]
Please read the [upgrade guide](https://github.com/just-containers/s6-overlay/blob/master/MOVING-TO-V3.md).
