### ISSUE TITLE
Order of services is not correct

### ISSUE THREAD

**Issue by mikedep333** [just-containers/s6-overlay#476]
According to README.md, the order of services begins with:

- (deprecated) Attribute fixing is performed according to files in `/etc/fix-attrs.d`.
- (legacy) One-shot initialization scripts in `/etc/cont-init.d` are run sequentially.
- Services in the `user` bundle are started by s6-rc, in an order defined by
dependencies. Services can be oneshots (initialization
tasks) or longruns (daemons that will run throughout the container's lifetime).

However, here's what I see in container log. All the s6-rc services are part of the `user` bundle:

```
s6-rc: info: service redis: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service redis successfully started
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service postgres-init: starting
s6-rc: info: service db-fields-key-create: starting
fix-attrs: info: applying /etc/fix-attrs.d/postgres
s6-rc: info: service db-fields-key-create successfully started
s6-rc: info: service certs: starting
s6-chown: fatal: unable to chown /var/lib/pgsql/backups
data: No such file or directory
fix-attrs: warning: fix-attrs is deprecated, please fix volume permissions in your container manager instead
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service postgres-init successfully started
s6-rc: info: service postgresql: starting
s6-rc: info: service postgresql successfully started
s6-rc: info: service postgres-prepare: starting
cont-init: info: running /etc/cont-init.d/000-a-src-install
```

**Comment by skarnet** [comment]
You need to make all the services in the `user` bundle depend on `base`. This is not clear enough in the documentation, I'll make this more explicit when I'm back from vacation.

**Comment by skarnet** [comment]
Documentation updated, closing this.
