### ISSUE TITLE
Command is nor working in script but in command shell

### ISSUE THREAD

**Issue by Sveeeeeen** [just-containers/s6-overlay#480]
Hello,

I do have a oneshot service which runs another scipt. It looks like this:
`
#!/command/execlineb
foreground { bash -ex /usr/local/bin/test }
`

The "test" script is just a small command to change some permissions on a remote server at start.

`
#!/bin/bash -ex
cd "/test"
ls -D "/test" | xargs -n 1 -P 8 chown -R user.user
`

For some reasonst the command is not working in this script at boot. But the command is working if I copy it into my shell.
I see the following. What looks strange to me is why I have the command in 2 lines? What happened to the pipe?

```
+ ls -D /test
+ xargs -n 1 -P 8 chown -R user.user
```
The error message is the following:

`chown: missing operand after 'user.user'`

I do not understand what's going on here. Someone has an Idea?

**Comment by skarnet** [comment]
You're seeing the shell's trace. (The `-x` option.)

The error message seems to say that there's nothing to chown. Is `/test` empty at boot time? In any case that doesn't sound related to execline or s6-overlay.

**Comment by Sveeeeeen** [comment]
The directory is empty at boot. That's correct.
But the script above is running after the longrun process is started.

I get more error messages:

`
++ ls -d 'subfolder/*'
ls: cannot access 'subfolder/*': No such file or directory
`

`
cd "/test" 
ls -D "/test" | xargs -n 1 -P 8 chown -R user.user
`
Is the cd not working here?
The "ls" found directorys. But chown not anymore?

**Comment by skarnet** [comment]
If you want help, please give a link to the exact scripts you're running. It's hard to determine what's happening with only snippets when you're constantly changing the context.

**Comment by skarnet** [comment]
If you're not going to provide more context, I'll assume you've solved your issue.
