### ISSUE TITLE
Process start/restart policy

### ISSUE THREAD

**Issue by geeky-akshay** [just-containers/s6-overlay#487]
Is there any control parameter or setting available in s6, where we can control the rate at which processes are started/restarted, for example, 10 processes/second?
What happens when there are 200 processes to start/restart?

**Comment by skarnet** [comment]
Are you intending to deploy immediately-crashing processes in production?

In any case, there's always a 1-second delay between two restarts of the same service, so your CPU won't be hogged.

**Comment by geeky-akshay** [comment]
yes, after evaluating all init systems, we are considering s6-overlay as an init system for our containers and going to use it in production.

**Comment by geeky-akshay** [comment]
@skarnet can we change the 1-second delay using an environment variable or configuration file?

**Comment by geeky-akshay** [comment]
Thanks for pointing this out in that thread. I have got the answer now.
