### ISSUE TITLE
Stop service with s6-rc but service keeps running

### ISSUE THREAD

**Issue by mission-lblaney** [just-containers/s6-overlay#488]
I'm using nginx very similar to the example in the README. 

`nginx/run`
```sh
#!/command/with-contenv bash
# shellcheck shell=bash

SSL_DIR=/etc/nginx/ssl
DH_FILE="${SSL_DIR}/dhparam.pem"

mkdir -p "${SSL_DIR}"

if [ ! -f "${DH_FILE}" ]; then
    openssl dhparam -out "${DH_FILE}" 2048
fi

nginx -g "daemon off;"
```

This brings up nginx and it runs as expected. The problem is when I shut it off.

```sh
root@333ac281638b:/farnsworth# s6-rc -v 2 -u change nginx
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
root@333ac281638b:/farnsworth# s6-rc -v 2 -d change nginx
s6-rc: info: service nginx: stopping
s6-rc: info: service nginx successfully stopped
```
It says it has stopped...

```
root      676  -      S     12:02:35  nginx: master process nginx -g daemon off;
www-data  677  -      S     12:02:35  nginx: worker process
www-data  678  -      S     12:02:35  nginx: worker process
www-data  679  -      S     12:02:35  nginx: worker process
www-data  680  -      S     12:02:35  nginx: worker process
www-data  681  -      S     12:02:35  nginx: worker process
www-data  682  -      S     12:02:35  nginx: worker process
www-data  683  -      S     12:02:35  nginx: worker process
www-data  684  -      S     12:02:35  nginx: worker process
www-data  685  -      S     12:02:35  nginx: worker process
www-data  686  -      S     12:02:35  nginx: worker process
www-data  687  -      S     12:02:35  nginx: worker process
www-data  688  -      S     12:02:35  nginx: worker process
```
But it has not stopped =/ 

I have to run `nginx -s quit` to make it stop. I know I can just use `finish` file or something like that to run `nginx -s quit` but I was really surprised by this behavior.

For example if I run `nginx -g "daemon off;"` manually inside the container.
```console
root@333ac281638b:/farnsworth# nginx -g "daemon off;" 
... (wait some time) ctrl+c
^Croot@333ac281638b:/farnsworth# 
```
This works correctly ^, which is what I expected when bringing down the service with `s6-rc`.

**Comment by snc** [comment]
Aren't you missing `exec` here? Please try `exec nginx -g "daemon off;"`.

**Comment by mission-lblaney** [comment]
@snc  Add exec fixed the issue I was having. I'm not sure I understand why `exec` is needed? The only rime I have ever used it was to reload my bash_profile in the current shell by doing `exec bash`. Do you happen to have a link handy that explains why `exec` is needed in this situation so I have a better understanding? Thanks

**Comment by snc** [comment]
When your run script uses a shell like bash, s6 communicates with the created shell process and not with the commands you are running inside the script. The exec command replaces the shell with the given command so that s6 then can communicate with nginx. You can have a look at https://www.baeldung.com/linux/exec-command-in-shell-script for example.

**Comment by mission-lblaney** [comment]
@snc Thanks =), Its actually obvious now. I kinda knew exec replaced the current shell with the command, that is why I sometimes `exec bash` but I was not thinking about how s6 would send kill signals to the service. I will take a look at the link you shared as well. I only vaugley understand these different signals like `sigterm` etc. So it would be nice to brush up on it and process forking. 

I see s6 speak alot about "execline` or what ever its own scripting language is. I will have to check up on it as well and see what kinda advantages it has.

**Comment by skarnet** [comment]
You don't have to worry about execline as long as you don't forget to use `exec` when you use a shell. ;-)
