### ISSUE TITLE
Question: What is the difference between s6-setuidgid, setuidgid and su.

### ISSUE THREAD

**Issue by shadycuz** [just-containers/s6-overlay#491]
I have a service that I start like this:

```bash
#!/command/with-contenv bash

exec s6-setuidgid jenkins /usr/local/bin/jenkins.sh
```

This seemed to work but later I has problems when I needed this server to install a bash script. 

When I "login" to the container and do this:

```console
root@57cde2517121:/var/jenkins_home/pipeline-library# /command/s6-setuidgid jenkins /var/jenkins_home/workspace/devcontainer-example/.tools/nodenv/null/nodenv_installer
Installing nodenv with git...
mkdir: cannot create directory ‘/root’: Permission denied
```

I get this weird error. I mean it makes sense that the jenkins user can't touch the `/root` directory. I was actually very shocked that the script was even trying that. But then I was like, maybe that's how they are checking if they are running as root? I don't think its relevant but here is the [bash script](https://github.com/nodenv/nodenv-installer/blob/master/bin/nodenv-installer) that is failing.

Anyways here is the weird part, if I do `su jenkins` and then I call the script... it works fine. And it worked fine before switching to `s6`. The only thing that I changed was running `s6-setuidgid` before starting the jenkins daemon. I'm thinking about just doing a `su jenkins` instead but I'm trying to understand why this is happening. 

Thanks =)

EDIT: 

I can confirm that using:
```bash
#!/command/with-contenv bash

exec su jenkins -c "bash /usr/local/bin/jenkins.sh"
```
Does make everything work as expected. Just not sure this is the "s6" way of running this service.

**Comment by nekopsykose** [comment]
> mkdir: cannot create directory ‘/root’: Permission denied  

it tries to make something in $HOME, but s6-setuidgid doesn't change that. see https://github.com/just-containers/s6-overlay/issues/165 for more details of the same thing

**Comment by shadycuz** [comment]
@nekopsykose Thanks, this is exactly the issue I'm having and now explains why it was was trying to access root. I don't have control of my daemon so I will stick with `su -c`.

**Comment by skarnet** [comment]
Indeed, `su` changes some environment variables, including HOME; it changes even more if you use `su -l`, which basically logs you in as the new user. Whereas `s6-setuidgid` only drops root privileges and changes your uid/gid to a normal user's, without modifying the environment.
