### ISSUE TITLE
Just wanted to stop by and say thanks! 🙌

### ISSUE THREAD

**Issue by jaydrogers** [just-containers/s6-overlay#492]
Hey guys,

Sorry this is an "issue" but it's the only way I know how to reach out and say "Thanks!".

I've been using S6 Overlay for 2+ years and I recently did the V2 → V3 migration.

I _**really**_ enjoyed the enhancements with the new version and I'm very grateful for all the work and help that you provided me.

S6 Overlay is the _perfect_ solution for managing something as goofy as PHP. I recently released updates to my PHP Docker images and received a ton of praise from the community: https://github.com/serversideup/docker-php

My containers feel so intelligent after all the health check optimizations. I even received some praise on how performant they are (thanks to S6 Overlay): https://twitter.com/jaydrogers/status/1587838520735027207

Unfortunately I'm more of a server admin than I am of a programmer, but if there is anything I can do to help contribute to S6 Overlay, let me know!

Thanks again for all your hard work 🙌 

(feel free to close this issue once you had a chance to read it 😃)

**Comment by skarnet** [comment]
Thanks a lot!

@jprjr, you should see this, too 😃

**Comment by jprjr** [comment]
Just got this notification, thank you so much! ♥️

**Comment by johanjanssens** [comment]
@skarnet @jprjr @jaydrogers Gave a talk about Multiprocess containers with PHP and S6 Overlay today at ConFoo 2023 (https://confoo.ca/en/2023). 

Used the excellent Docker-PHP images from @jaydrogers. Added in some multiprocess fun with https://openswoole.com/ running multiple OpenSwoole servers all managed by S6 Overlay. Demo'ed how to handle  10k async HTTP requests in 3secs.. all using nothing else then PHP using OpenSwoole and supervised to perfection with S6. The look on people's face ... priceless! 

Slides are here: https://speakerdeck.com/johanjanssens/multiprocess-php-containers-with-s6-overlay-confoo-2023-fff7f58f-9471-459c-a0f6-edcd6fc05736

Thanks again guys, it's very satisfying to be able to build on the shoulders of giants!

**Comment by jaydrogers** [comment]
We just launched a new Documentation Site for our PHP Docker Images that are based on S6 Overlay: https://serversideup.net/open-source/docker-php/

I spent some time really discussing the differences between Supervisor & S6 Overlay (hopefully my points are all accurate 😆) https://serversideup.net/open-source/docker-php/docs/getting-started/these-images-vs-others

If the S6 overlay project is interested in something like this for a documentation site, let us know. We'd love to contribute to help get people using S6 Overlay.

We used [Nuxt Content V2](https://content.nuxtjs.org/blog/announcing-v2/) and Tailwind UI.

You can see everything is 100% open source and in the same repo (look in the `/docs` directory): https://github.com/serversideup/docker-php/

The process worked out well and it automatically deploys to CloudFlare Pages. We even have automated preview builds with GitHub Actions + CloudFlare pages on PRs (great for ensuring the documentation is up to date when releasing a feature).

If anyone of the S6 Overlay team is interested in any help on this, just let us know!

Thanks again for all your hard work ❤️
