### ISSUE TITLE
Grabbing the container env with an RC oneshot & with-contenv

### ISSUE THREAD

**Issue by LiamKearn** [just-containers/s6-overlay#494]
```Dockerfile
# syntax=docker/dockerfile:1

FROM ubuntu:jammy

ENV DEBIAN_FRONTEND=noninteractive
ENV S6_OVERLAY_VERSION=3.1.2.1

RUN apt-get update && \
    apt-get full-upgrade -y && \
    apt-get -y --no-install-recommends install \
        xz-utils

ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz /tmp
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-x86_64.tar.xz /tmp
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-symlinks-noarch.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz
RUN tar -C / -Jxpf /tmp/s6-overlay-x86_64.tar.xz
RUN tar -C / -Jxpf /tmp/s6-overlay-symlinks-noarch.tar.xz

# Legacy

COPY <<EOF /etc/cont-init.d/01-contenv
#!/command/with-contenv sh
env
EOF

RUN chmod +x /etc/cont-init.d/01-contenv

# RC

RUN touch /etc/s6-overlay/s6-rc.d/user/contents.d/conf

COPY <<EOF /etc/s6-overlay/s6-rc.d/conf/type
oneshot
EOF

COPY <<EOF /etc/s6-overlay/s6-rc.d/conf/up
#!/command/with-contenv sh
env
EOF

ENTRYPOINT ["/init"]
```

Hi, sorry for the bothersome question.

I can't seem to get a rc-based oneshot working with the env from my container.

I've tried running an `ls` of `/run/s6/container_environment` from the new rc oneshot instead of `env` and it shows the environment variables present as files.

I haven't got my head around understanding `/command/with-contenv` enough to workout the problem myself.

If it helps `S6_KEEP_ENV` is unset.

The above outputs:
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service conf: starting
PATH=/command:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
s6-rc: info: service conf successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/01-contenv
HOSTNAME=cf7e50da8397
HOME=/root
PATH=/command:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
S6_OVERLAY_VERSION=3.1.2.1
DEBIAN_FRONTEND=noninteractive
MYENV=ENV
PWD=/run/s6-rc:s6-rc-init:AfgKMK/servicedirs/s6rc-oneshot-runner
cont-init: info: /etc/cont-init.d/01-contenv exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
```
When run with `docker build -t repro . && docker run --rm -e MYENV=ENV repro`

I can't help but think I'm not understanding the documentation correctly. Would you kindly point me where I need to read :-)

Many thanks.

**Comment by LiamKearn** [comment]
Hmm, I can see quite a few people using `#!/command/with-contenv sh` in public source code but most of them have `S6_KEEP_ENV` set.

- https://github.com/oznu/docker-homebridge
  - [`S6_KEEP_ENV=1`](https://github.com/oznu/docker-homebridge/blob/032a67bb0be5191122bc1745cc3de6874d229208/Dockerfile#L11)
  - [Oneshot](https://github.com/oznu/docker-homebridge/blob/de9770473ed9c749eb3e6e7cce0cd97925bde6a2/rootfs/etc/s6-overlay/s6-rc.d/credits/up) using [container ENV](https://github.com/oznu/docker-homebridge/blob/de9770473ed9c749eb3e6e7cce0cd97925bde6a2/rootfs/etc/s6-overlay/scripts/credits.sh#L3)
- [This up script](https://github.com/elabftw/elabimg/blob/fbb336eed18e3ab592360b6370740ca0acfb2541/src/init/up)

Reading [here](https://github.com/just-containers/s6-overlay#:~:text=one%20you%20provide.-,S6_KEEP_ENV,-(default%20%3D%200)%3A%20if)(chromium link format) I don't think this is what I want to do.

Following this pattern with the .real script **seems to work for me**: https://github.com/rustdesk/rustdesk-server/tree/master/docker/rootfs/etc/s6-overlay/s6-rc.d/key-secret.

I'm newer to this stuff. Is this because only `sh` in going to be invoked by `with-contenv` and not `env`? Something like this also does the trick but seems weird:
```
#!/command/with-contenv sh
/command/with-contenv env
```


I'd love an explanation if you have time, happy to close this issue otherwise :)

**Comment by skarnet** [comment]
`up` files **are not shell scripts** and ignore the shebang, because lines starting with `#` are parsed as comments.

It's explained in the [README](https://github.com/just-containers/s6-overlay/blob/master/README.md), but not visibly enough. I'll edit the doc to make it more visible.

`with-contenv env` in your `up` file will work. So will `/bin/toto`, if you have a `/bin/toto` file containing your script with the `#!/command/with-content sh` shebang.

_Don't write shell scripts in `up` files._

**Comment by LiamKearn** [comment]
Awesome, that makes me feel much better about using the `up.real` (shell script) solution I ended up using to actually store the shell script.

Thanks for pointing out those docs, I'll give them another read and check if I can get them through my thick skull.

Many thanks for both the software and the pointers, hope you have a nice day!
