### ISSUE TITLE
How to make `docker run` wait until stage 2 is finished? 

### ISSUE THREAD

**Issue by lmagyar** [just-containers/s6-overlay#495]
My s6-rc.d service (basically a database) takes more then a minute to start up (this is normal after eg. a power outage, as part of the recovery it imports some external data and it takes time).

I would like to make `docker run` to wait until everything is started up by the s6 supervisor.

Currently `docker run` returns quite fast, but the container is not usable at this time, other docker containers are started immediately after this, they start to use this container, and they fail.

**Comment by skarnet** [comment]
I don't know, and that's more a question for the Docker developers 😁

You could write a service that runs last (i.e. that depends on all the other ones) and that prints an identifiable message to the log, and have your `docker run` command be piped into something that parses the output and waits until it gets the proper message. That's generally how notifications are done.

**Comment by lmagyar** [comment]
Thank you, I will try the HEALTHCHECK (https://docs.docker.com/engine/reference/builder/#healthcheck), I can't modify the docker run commands (they are in a different project).

If I succeed I will report, maybe somebody else can use it also.

**Comment by lmagyar** [comment]
Closing, as this is really nothing to do with S6. :)

At the end of stage 2:
```
touch /tmp/started
```
And dockerfile:
```
HEALTHCHECK --interval=5s --timeout=3s --start-period=5m --retries=1 \
  CMD test -f /tmp/started || exit 1
```
Gives me nice `starting` and `healthy` status in `.State.Health.Status`, but `docker run` doesn't care about this also. :/
