### ISSUE TITLE
myapp-log - dependencies

### ISSUE THREAD

**Issue by rbro** [just-containers/s6-overlay#498]
In README.md, in the section for Logging, there's a line:

`/etc/s6-overlay/s6-rc.d/myapp-log/dependencies.d/myapp-log`: empty file

Is that correct that myapp-log should be a dependency to itself, or should it be a dependency on base?  Or should it have a dependency of both base and myapp-log-prepare?

Thanks for your help.

**Comment by skarnet** [comment]
Oh, sorry, typo. The dependency is on `myapp-log-prepare`, of course, not `myapp-log`. README fixed in the latest commit. Thanks!
