### ISSUE TITLE
S6_BEHAVIOUR_IF_STAGE2_FAILS doesn't work when Ctrl-C is pressed while s6-rc is running

### ISSUE THREAD

**Issue by mouchar** [just-containers/s6-overlay#499]
# Explanation
When I set `S6_BEHAVIOUR_IF_STAGE2_FAILS=2`, I expect the container fails when stage 2 can not start all services.

The problem is that if the container gets SIGINT while services are starting (`s6-rc` runs from `rc.init`), this signal is NOT handled by the rc.init script. Both rc.init and s6-rc terminate (that's default action for SIGINT) and processing of exit status "1" is not processed by rc.init. Therefore the `/run/s6/basedir/bin/halt` is not called and the container remains in undefined state, because longrun transitions were aborted by s6-rc.

The correct behaviour should be to terminate the container.

# Dockerfile that demonstrates your issue.
Self-contained Dockerfile (BuildKit required) with one long-starting longrun service.
```
# syntax=docker/dockerfile:1.3-labs
FROM debian:11-slim
# FROM alpine:latest
ARG S6_OVERLAY_VERSION=3.1.2.1

RUN apt-get update && apt-get install -y procps xz-utils
# RUN apk update && apk add procps xz

ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-x86_64.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-x86_64.tar.xz
ENTRYPOINT ["/init"]

ENV S6_BEHAVIOUR_IF_STAGE2_FAILS=2
# Disable default start timeout
ENV S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0

COPY <<run <<notification-fd <<type /etc/s6-overlay/s6-rc.d/example/
#!/command/with-contenv sh
echo slow starting... Press Ctrl-C within 10s.
sleep 10
echo finally started... Notifying supervisor
echo "Notified about the start" >&3
sleep infinity
run
3
notification-fd
longrun
type

COPY <<EOF /etc/s6-overlay/s6-rc.d/example/dependencies.d/base
whatever
EOF

COPY <<EOF /etc/s6-overlay/s6-rc.d/user/contents.d/example
whatever
EOF
```

# Example session
```
$ docker run -it --rm --name s6 s6test
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service example: starting
slow starting... Press Ctrl-C within 10s.      <<<=== Here I press Ctrl-C before the service comes up.
^Cs6-rc: warning: received INT, aborting longrun transitions and exiting asap
s6-rc: warning: unable to start service example: command crashed with signal 2


<<<=== The container remains running and needs to be stopped manually.
```
# Expected behavior (with patched rc.init)
```
$ docker run -it --rm --name s6  -v $PWD/rc.init:/package/admin/s6-overlay-3.1.2.1/etc/s6-linux-init/skel/rc.init  s6test
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service example: starting
slow starting... Press Ctrl-c within 10s.                   <<<=== Here I press Ctrl-C before the service comes up.
^Cs6-rc: warning: received INT, aborting longrun transitions and exiting asap
s6-rc: warning: unable to start service example: command crashed with signal 2
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

# Solution
Trap SIGINT early in `rc.init` to suppress script termination before s6-rc exit code is processed.
 
I will send a PR.

**Comment by skarnet** [comment]
I don't understand and will never understand why people insist on running containers in an interactive terminal and think that ^C is an acceptable way of stopping a container.

It is not how containers should be run, it is not how they should be stopped, and it will never be possible to support this case in a 100% failsafe way.

Running the container in a terminal and pressing ^C while it is still booting is firmly in the realm of "Don't do that".

Even if I apply your proposed fix, there will still be a race condition. There will always be a window where `rc.init` is starting and it hasn't trapped SIGINT yet, and if you ^C at that moment, it will die and the container will keep running.

But somehow interactive containers are popular, and we already have numerous kludges in place to support that use case, so, what's one more, I guess? I will add something akin to your proposed fix that minimizes the race condition. Thanks for the report (and the typo fix).

**Comment by skarnet** [comment]
I looked in depth, and just trapping SIGINT in the `rc.init` script is indeed the best we can do. Done in git master, thanks.

**Comment by mouchar** [comment]
@skarnet

Yeah, I understand your standpoint, but honestly - I can't convince all users not to use ^C while running the docker container. They are used to it (especially developers) as they use it in the terminal all the time - running their app in the foreground and pressing ^C to terminate it. Nobody goes to another terminal window to find their app PID and send `kill -TERM <pid>` just to terminate their app "in POSIX-ly correct way" :wink: 

These days, running containers is so popular it is actually replacing installing and running local commands, so it will be more and more common for people would expect the container will behave the same as local commands, including reactions to signals.

I'm aware of the race condition, but its time window is so short that nobody will notice. And if they do: bad luck, try again. Let's be pragmatic.

Anyway, thanks for applying my proposal to the repository.
