### ISSUE TITLE
[Question] Run job at specific time

### ISSUE THREAD

**Issue by PAXANDDOS** [just-containers/s6-overlay#502]
Hey! I might have had a bad look through the docs, or it's not possible. 
Is there any way to schedule a long-term job to run at a specific time (e.g. start at 6am, stop at 9am)? Would be extremely useful for queue workers, that's my case.

**Comment by skarnet** [comment]
That's not the job of the init system. If you want to do that, you can always install a package that provides such a functionality, such as `cron` or `snooze`.
