### ISSUE TITLE
s6 exited after excute /init

### ISSUE THREAD

**Issue by situjianxiong** [just-containers/s6-overlay#504]
# Please provide a small Dockerfile that demonstrates your issue.
Here is the Dockerfile I using:
```
FROM docker.easyops.local/library/nginx:ubuntu-1.21 AS nginx

FROM docker.easyops.local/library/base:ubuntu-4-php74-fpm

COPY /apt-sources.list /etc/apt/sources.list

# install s6 config
COPY base/4/buster/php74/nginx/etc /etc/

RUN set -eux; \
    apt-get update; \
    apt-get install --assume-yes --no-install-recommends \
        libgeoip1 \
        libpcre3 \
        xz-utils \
        zlib1g \
        execline \
        vim \
        ; \
    rm -rf /var/lib/apt/lists/*; \
    chmod -R 755 /etc/services.d/;


# install s6-overlay
ADD https://github.com/just-containers/s6-overlay/releases/download/v2.2.0.1/s6-overlay-amd64-installer /tmp/
RUN chmod +x /tmp/s6-overlay-amd64-installer && /tmp/s6-overlay-amd64-installer /

# install nginx
COPY --from=nginx /usr/local/easyops/nginx /usr/local/easyops/nginx

ENTRYPOINT ["/init"]


LABEL org.opencontainers.image.url=https://git.easyops.local/osLibs/base-image
```

and you can use this command to debug
```
docker run -it --entrypoint=bash jianxiong10000/base:ubuntu-4-php74-nginx-test
```

LABEL org.opencontainers.image.url=https://git.easyops.local/osLibs/base-image
Being able to reproduce your issue helps greatly in troubleshooting, the
best way to do that is to create a small Dockerfile that we can
use to recreate the issue.
I had confirmed the supervise already created but the process exited directly
![image](https://user-images.githubusercontent.com/50319990/207276231-dd90432e-aa8f-47e7-80d3-967f100593c9.png)
![image](https://user-images.githubusercontent.com/50319990/207282839-4e29f472-b037-4578-bb4e-314fd8db22e2.png)

# If you've identified a fix, please open a pull request.

If you've found an issue and know the fix, please open a pull request with your fix.

**Comment by skarnet** [comment]
Sorry, we do not provide support for s6-overlay v2 anymore. Please migrate to v3 if you want support.

That said, `--entrypoint=bash` is *not* a good way to debug s6-overlay. The ENTRYPOINT *needs* to be `/init`, else s6-overlay will not work at all.

Good luck.
