### ISSUE TITLE
GCSFuse Mount endlessly starting

### ISSUE THREAD

**Issue by Stoyvo** [just-containers/s6-overlay#506]
Hi there! I'm transitioning over to S6-Overlay from Tini.

I'm attempting to use 1 docker container to utilize PHP-FPM-NGINX, and a file mount to a storage bucket (GCSFuse, GCP Bucket).

### Configuration
I'm sharing my /etc/s6-overlay directory below:
**GCSFuse:**
/etc/s6-overlay/s6-rc.d/gcsfuse/dependencies (empty)
/etc/s6-overlay/s6-rc.d/gcsfuse/notification-fd
```
3
```
/etc/s6-overlay/s6-rc.d/gcsfuse/run
```
#!/command/execlineb -P
gcsfuse -o allow_other --implicit-dirs --uid 33 --gid 33 --only-dir media/ gcp-bucket-id /var/www/html/pub/media
```
/etc/s6-overlay/s6-rc.d/gcsfuse/type
```
longrun
```

**NGINX:**
/etc/s6-overlay/s6-rc.d/nginx/dependencies
```
gcsfuse
php-fpm
```
/etc/s6-overlay/s6-rc.d/nginx/notification-fd
```
3
```
/etc/s6-overlay/s6-rc.d/nginx/run
```
#!/command/execlineb -P
nginx -g "daemon off;"
```
/etc/s6-overlay/s6-rc.d/nginx/type
```
longrun
```

**PHP-FPM:**
/etc/s6-overlay/s6-rc.d/php-fpm/dependencies
```
gcsfuse
```
/etc/s6-overlay/s6-rc.d/php-fpm/notification-fd
```
3
```
/etc/s6-overlay/s6-rc.d/php-fpm/run
```
#!/command/execlineb -P
with-contenv
/usr/local/sbin/php-fpm --nodaemonize
```
/etc/s6-overlay/s6-rc.d/php-fpm/type
```
longrun
```

**USER:**
/etc/s6-overlay/s6-rc.d/user/contents.d/base (empty)
/etc/s6-overlay/s6-rc.d/user/contents.d/gcsfuse (empty)
/etc/s6-overlay/s6-rc.d/user/contents.d/nginx (empty)
/etc/s6-overlay/s6-rc.d/user/contents.d/php-fpm (empty)

### Issue Seen:
GCSFuse is mounting endlessly, until container eventually crashes or shuts down.
![image](https://user-images.githubusercontent.com/6148099/210950209-f5c8f313-3946-4cbf-9646-4b17ea00c616.png)

Thank you for making something so beautiful <3

**Comment by Stoyvo** [comment]
I discovered that GCSFuse can accept a --foreground parameter, this seems to stop endless mount loop but now seeing another failure "s6-rc: fatal: timed out".

Reflecting on previous image provided, there is a fatal: timed out, similar to the output attached below when using --foreground on GCSFuse.
How can I identify what timed out?
/etc/s6-overlay/s6-rc.d/gcsfuse/run
```
#!/command/execlineb -P
gcsfuse -o allow_other --foreground --implicit-dirs --uid 33 --gid 33 --only-dir media/ gcp-bucket-id /var/www/html/pub/media

```

![image](https://user-images.githubusercontent.com/6148099/210960065-ad02a085-6dff-40d6-816e-a6b67a4e32bc.png)

**Comment by skarnet** [comment]
You are using a `notification-fd` of 3 for your gcsfuse service, but nothing in the command line indicates that the gcsfuse process is writing anything to fd 3 when it's ready.

If there is a way for gcsfuse to signal readiness, use that option to write a line to fd 3 when it's  ready. Otherwise, just delete the `/etc/s6-overlay/s6-rc.d/gcsfuse/notification-fd` file; then you should be good.

**Comment by Stoyvo** [comment]
@skarnet Thank you for the notification-fd file suggestion.

I still have some time out events happening, how can I trace what is timing out?
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service php-fpm: starting
s6-rc: info: service gcsfuse: starting
s6-rc: info: service gcsfuse successfully started
2023/01/07 03:33:46.501703 Opening GCS connection...
2023/01/07 03:33:46.950275 Mounting file system "my-storage-bucket"...
2023/01/07 03:33:46.953367 File system has been successfully mounted.
s6-rc: fatal: timed out
s6-svlisten1: fatal: timed out
2023/01/07 03:33:46.500536 Start gcsfuse/0.41.10 (Go version go1.18.4) for app "" using mount point: /var/www/html/pub/media
2023/01/07 03:33:46.506938 Creating a mount at "/var/www/html/pub/media"
2023/01/07 03:33:46.516191 Creating a new server...
2023/01/07 03:33:46.516442 Set up root directory for bucket my-storage-bucket
2023/01/07 03:33:46.516518 OpenBucket("my-storage-bucket", "")
```
