### ISSUE TITLE
Kubernetes API Server not accessible from within con-init-d script (kubectl)

### ISSUE THREAD

**Issue by ameya-parab** [just-containers/s6-overlay#518]
When spawning Kubeflow notebooks using the approach described [here](https://github.com/kubeflow/kubeflow/tree/master/components/example-notebook-servers#custom-images--s6--scripts), we are currently using S6-overlays to perform some bootstrapping. We want to use 'kubectl' to invoke the Kubernetes API server as part of the bootstrapping process to set up a few properties / environments for the Kubeflow notebooks.

Cont-init-d Script:

```sh
#!/usr/bin/with-contenv bash

CURRENT_IMAGE=$(/usr/local/bin/kubectl get pods ${HOSTNAME} --namespace ${KUBERNETES_NAMESPACE} -o jsonpath="{.spec.containers[].image}")

echo "Configuring the Runtime Image (${CURRENT_IMAGE}) for the Notebook"
```
Here, the `HOSTNAME` is the Kubernetes Pod name and the `KUBERNETES_NAMESPACE` is the namespace of the Pod.

But still, the script fails to access/authorize against the Kubernetes API Server and throws the below error -

```sh
The connection to the server <host>:<port> was refused - did you specify the right host or port?
```

I have confirmed that all of the `Kubernetes` related environment variables such as `KUBERNETES_SERVICE_HOST` and `KUBERNETES_SERVICE_PORT`, which are required to connect to the Kubernetes API server are available during script runtime using `printenv`. Furthermore, the Kubernetes `token` and `certificate` is also accessible from within the `cont-init.d` script.

Note: The same script executes without error from the Kubeflow Notebook's terminal.

I've also tried directly invoking the Kubernetes Server through CuRL, which produces the same error as before.

```sh
/usr/bin/curl -s -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT/api/v1/namespaces/${KUBERNETES_NAMESPACE}/pods/${HOSTNAME} | jq -r .spec.containers[0].image
```

Is this something we've seen before, or am I missing something?

**Comment by skarnet** [comment]
There doesn't seem to be anything s6-overlay-specific here; it doesn't look related.
The only thing I can think of is that your Kubernetes environment may rely on PATH to invoke internal commands, and your `kubectl` command is installed in `/usr/local/bin`, which is not in s6-overlay's default PATH. So, try adding `/usr/local/bin` to PATH in your Dockerfile? It's either that or something similar.

**Comment by ameya-parab** [comment]
Ack, the issue was related to the 'kubectl' command itself. The script in 'cont-init.d' was not able to connect to the Kubernetes API server, but adding a few 'delay' seconds when booting up seem to have resolved the issue.
