### ISSUE TITLE
how to stop the program

### ISSUE THREAD

**Issue by HzaZoro** [just-containers/s6-overlay#519]
my program to be supervised by s6, this program is not my main service,it is a helper process,and type is longrun.
After running it many times,but error occurred. so i want to stop the program
so what should i do

**Comment by skarnet** [comment]
[s6-svc -d](https://skarnet.org/software/s6/s6-svc.html) /run/service/yourprogram ?

**Comment by hmoffatt** [comment]
I've got a related question: I'm running 3 services, using /etc/services.d, with no CMD defined; this means that hitting control-C when running the container from the terminal doesn't do anything. Is there a way to make control-C work?

**Comment by skarnet** [comment]
Running your container in a terminal, i.e. `docker run -it`, should do it, but you *definitely* should not run your container in a terminal in production, and rely on ^C to stop it, if you don't have a CMD that needs a terminal...

**Comment by hmoffatt** [comment]
@skarnet I'm running in `docker run -it` (or more specifically `podman run -it`), but nothing happens when I ^C. If I have a `CMD` defined then it works, but not without.

**Comment by skarnet** [comment]
Sigh. Sorry. I knew there is a case where it doesn't work, but I didn't remember which one. It is, unfortunately, impossible to make it work in all cases, because using ^C with Docker is a hack no matter what.

But indeed, no CMD with `-it` is the case where it does *not* work. When you have no CMD, you need to run the container *without* a terminal, so try running it *without* `-it`.

**Comment by hmoffatt** [comment]
Yes, that works. Useful to be able to ^C it during development, unimportant later once deployed. Thanks for your help!

**Comment by HzaZoro** [comment]
> 
thank you very much,i adopted `s6-svc -d`.
i have another request. i use `#!/usr/bin/with-contenv` to Container environment,but i want to change the environment variable,i use `export`and `source /etc/profile` ,but it doesn't work

**Comment by skarnet** [comment]
Use `#!/command/with-contenv sh` in order to interpret a shell script.

- Without the `sh`, `with-contenv` will interpret an execline script, which is probably not what you want.
- Changing `/usr/bin` to `/command` will ensure you don't need the symbolic links tarball.

**Comment by skarnet** [comment]
Closing this.
