### ISSUE TITLE
Rebuild of release v3.1.4.1 - checksums of artifacts changed

### ISSUE THREAD

**Issue by neovatar** [just-containers/s6-overlay#521]
I just noticed that existing release v3.1.4.1 has been rebuild because the checksums of the release artifacts changed (existing release files have been replaced).

![image](https://user-images.githubusercontent.com/550533/225968829-61e2a5da-8f23-4a7d-ab34-b0ddfc1497e2.png)

![image](https://user-images.githubusercontent.com/550533/225968939-dd705d14-f846-4224-a95f-b2ed6655170f.png)

This was done intentional? Are there any changes?

Thanks!

**Comment by skarnet** [comment]
It was intentional, on a suspicion that one of the tarballs had been incorrectly built (which was later proven wrong).

There should be no change at all in the artifacts.

**Comment by neovatar** [comment]
Thanks for the info!
