### ISSUE TITLE
Environment variables missing from CMD

### ISSUE THREAD

**Issue by Impakt** [just-containers/s6-overlay#523]
Hi all,
I have a plain s6-overlay based container that has fluentd as a service, which works fine. I _used_ to be able to set the CMD to something like `java -cp MyClass` and the environment variables would be passed over. Now, i've started over from scratch and trying to use the latest recommended steps (using `/etc/s6-overlay/sr-rc.d/fluentd`) for the service (which gets the variables fine with `#!/command/with-contenv sh`) but i can't get the CMD to see the variables. Do i now need to wrap the call to java with `wont-contenv` or is there a more elegant solution?

Edit: I prefixed the CMD with `/command/with-contenv` and it's working now. However i have a lot of existing projects that refers to using plain Java, do all of those need to be updated or can i configure s6-overlay to pass the env vars across all the time?

**Comment by skarnet** [comment]
From the [v3 porting guide](https://github.com/just-containers/s6-overlay/blob/master/MOVING-TO-V3.md):

> The CMD, if any, always used to run under the container environment. This is not the case anymore: just like supervised services, the CMD is now run with a minimal environment by default, and you need to prepend it with with-contenv if you want to provide it with the full container environment.

**Comment by Impakt** [comment]
@skarnet thank you! and sorry for wasting your time
