### ISSUE TITLE
Feature request: additional release archives using docker architecture names

### ISSUE THREAD

**Issue by nocive** [just-containers/s6-overlay#525]
Hi :wave: 

I have a somewhat simple feature request.

I'm using docker buildx/buildkit and multi platform/architecture docker builds.
Currently, for such cases, in order to install s6 I need a snippet along these lines:

```Dockerfile
FROM alpine:3.17
ARG TARGETARCH
ARG S6_VERSION

RUN \
  arch=$([ "$TARGETARCH" == "arm64" ] && echo aarch64 || echo x86_64) \
  && curl -fsSL https://github.com/just-containers/s6-overlay/releases/download/v${S6_VERSION}/s6-overlay-noarch.tar.xz | tar xvJf - -C / \
  && curl -fsSL https://github.com/just-containers/s6-overlay/releases/download/v${S6_VERSION}/s6-overlay-${arch}.tar.xz | tar xvJf - -C /
```

This is because the docker architecture codenames do not match the codenames that s6 uses:
- `arm64` vs `aarch64`
- `amd64` vs `x86_64`

This also prevents me from using the `ADD` command (which has layer caching benefits) because I need to set the `arch` variable, which can only be done using `RUN`.

I'm wondering if you would consider the possibility to create additional release archives aliases for the aforementioned architecture names, as that would simplify life a little bit for some of us :)

References:
- https://github.com/docker-library/official-images#architectures-other-than-amd64

**Comment by skarnet** [comment]
This has come up several times, and has been discussed in [this issue](https://github.com/just-containers/s6-overlay/issues/512).

The short answer is: it would be difficult to do in a non-wasteful, non-confusing way, given how GitHub publishes artifacts. But I understand there's some demand there. So, this will not happen tomorrow, but I'm going to explore alternative hosting solutions that could make it easier.

**Comment by nocive** [comment]
@skarnet thanks for the context, I wasn't aware this had been amply discussed before.
I understand now this is not as simple as I initially thought.

Thanks for considering it :+1:

**Comment by davidkaufman** [comment]
Maybe GitLab?

**Comment by skarnet** [comment]
GitLab doesn't allow multiple names for artifacts either.

Since I definitely do not want this issue to become a "my forge is better than yours" discussion, I'm closing this.
