### ISSUE TITLE
Base dependency clarification

### ISSUE THREAD

**Issue by alexyao2015** [just-containers/s6-overlay#527]
I had a question about the documentation. It seems like there are conflicting pieces of information regarding the use of the `base` dependency.

- [In `MOVING-TO-V3`, it states that it should be located in `foo/contents.d/base`](https://github.com/just-containers/s6-overlay/blob/03c2fa8b911e73e63449869570ab28226d91ee4a/MOVING-TO-V3.md?plain=1#L101)
- [In `README`, it states it should be located in `foo/dependencies.d/base`](https://github.com/just-containers/s6-overlay/blob/03c2fa8b911e73e63449869570ab28226d91ee4a/README.md?plain=1#L357)

To clarify should it be in `contents.d` or `dependencies.d`? I've seen the usage of `dependencies.d`, but have not seen `contents.d` within a service directory. Does this do anything?

**Comment by skarnet** [comment]
`contents.d` is when you define a *bundle*: it lists what services (or bundles) are part of this bundle.

`dependencies.d` is when you define a *service*, i.e. a oneshot or a longrun. It lists what services (or bundles) need to be up in order for this service to be started.

**Comment by alexyao2015** [comment]
Thank you. So to be clear, either is okay to use?

**Comment by nekopsykose** [comment]
it depends on if `foo` is a bundle or a service

**Comment by alexyao2015** [comment]
I'm still confused here because of the discrepancy between the two files listed in the original message.

**Comment by skarnet** [comment]
Yeah, you're right, it was not clear in the MOVING-TO-V3 guide, and since we use the term *service*, it's better to mention `dependencies.d` instead. Fixed now.

**Comment by skarnet** [comment]
No, `dependencies.d` only works for atomic services (longruns or oneshots) while `contents.d` only works for bundles.

**Comment by alexyao2015** [comment]
Thanks for the clarification!
