### ISSUE TITLE
Clarification about CMD & STDOUT

### ISSUE THREAD

**Issue by asquel** [just-containers/s6-overlay#528]
Hi, 

I have a quite standard php-fpm container, it was always running with s6, but I now upgraded it to the s6.rc model. 
My problem is that now, when I do run an interactive "shell", I can see all the logs from the docker-healtcheck. 
 
My docker-healthcheck is doing : 
`
if ! cgi-fcgi -bind -connect /tmp/php-fpm.sock; then
	exit 1
fi
`

My run file from php-fpm is: 
`exec docker-php-entrypoint php-fpm`

And the problem is visible as soon as I do for example: 
`❯ docker run -it base-php:8.1 sh
`

Then I got something like : 
![image](https://user-images.githubusercontent.com/1662212/234787112-1b670521-b9d6-4dae-8cce-48abd4b39f13.png)

When I was not using the s6.rc model I had an entrypoint that looked like : 
```
if [ "$1" = 'php-fpm' ]; then
  exec /init
fi

if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

if [ "$(whoami)" = 'root' ]; then
  su-exec $PUID:$PGID "$@"
else
  exec "$@"
fi
```

Do you think I need to re-add an entrypoint, or is there a way through only the "/init" one ?

Thanks a lot for helping me

**Comment by asquel** [comment]
As soon as I change the S6_LOGGING to anything, I get that error: 

s6-linux-init: warning: unable to relinquish control terminal: Not a tty
![image](https://user-images.githubusercontent.com/1662212/234810268-cac4f41e-89c9-482a-98be-4115ecc96c66.png)

**Comment by skarnet** [comment]
There's something going on with your image and/or the way you're running it, because by definition, `docker run -it` gives you a terminal. Also, that warning should not change the fact that your logs go to `/run/uncaught-logs` instead of the container's stdout; if they don't, there's definitely a bigger issue at play. Please post your Dockerfile.

**Comment by asquel** [comment]
OK
````
# syntax=docker/dockerfile:1
ARG PHP_VERSION=8.1
ARG ALPINE_VERSION=3.16

FROM php:${PHP_VERSION}-fpm-alpine${ALPINE_VERSION} AS system

ADD --chown=root:root --chmod=700 ./scripts/basefs/ /

RUN apk add
    bash \
    shadow \
    tzdata \
    openssh-client \
    fcgi \
    su-exec

RUN install-s6

ENV S6_BEHAVIOUR_IF_STAGE2_FAILS=2
ENV S6_CMD_WAIT_FOR_SERVICES_MAXTIME=60000
ENV S6_KEEP_ENV=1
ENV S6_LOGGING=0

ENTRYPOINT ["/init"]
#########################################################################
# PHP DEPS
FROM system AS php-deps

ENV GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no"
ENV MEMORY_LIMIT=512M
ENV COMPOSER_MEMORY_LIMIT=-1
ENV MAX_EXECUTION_TIME=600
ENV COMPOSER_ALLOW_SUPERUSER=1
ENV PATH="${PATH}:/root/.composer/vendor/bin"

COPY php/basefs/ /
RUN chmod -R +x /usr/local/bin;  \
    chmod -R +x /etc/s6-overlay/s6-rc.d/

RUN mkdir -p /app

HEALTHCHECK --interval=10s --timeout=3s --retries=3 CMD ["docker-healthcheck"]
````
The script install-s6 just do: 
````
#!/bin/sh

set -o errexit

if [ -z "${S6_OVERLAY_VERSION}" ]; then
  S6_OVERLAY_VERSION="3.1.4.1"
fi

## TODO: Platform condition

S6_DOWNLOAD_URL="https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}"

echo "Downloading from ${S6_DOWNLOAD_URL}"

curl -sSLf -o /tmp/s6-overlay-noarch.tar.xz "${S6_DOWNLOAD_URL}/s6-overlay-noarch.tar.xz"
tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz

curl -sSLf -o /tmp/s6-overlay-x86_64.tar.xz "${S6_DOWNLOAD_URL}/s6-overlay-x86_64.tar.xz"
tar -C / -Jxpf /tmp/s6-overlay-x86_64.tar.xz

mkdir -p /etc/s6-overlay/s6-rc.d
mkdir -p /etc/s6-overlay/s6-rc.d/user/contents.d
````

**Comment by skarnet** [comment]
I ran some tests, and indeed I understand what's going on.
The messages are nothing to worry about; it's just a cosmetic thing that I will fix in the next version.

With `S6_LOGGING=2`, you should not have anything interfere with your interactive shell, except that warning message that will be removed. Sorry for the inconvenience!

**Comment by asquel** [comment]
The problem is when I do any other level than 0 in S6_LOGGING, I loose the interactive. 
![image](https://user-images.githubusercontent.com/1662212/235592010-c26ca505-efda-4e9e-b592-aa0e5abeb36d.png)
Cannot do anything anymore

**Comment by skarnet** [comment]
... oh. Then it's not only cosmetic. Okay, thanks for the report, I'll be working on it.

**Comment by skarnet** [comment]
The latest version of s6-overlay, `v3.1.5.0`, should fix your issue. Set the `S6_CMD_USE_TERMINAL` variable to **1** and your CMD will have its terminal even with a nonzero `S6_LOGGING`; however, your CMD's output will not be logged.

**Comment by asquel** [comment]
Ok, that works ! 
Thx for working on it (It brings me to another question, I'll open another issue)
