### ISSUE TITLE
/etc/s6-overlay/s6-rc.d executing before /etc/cont-init.d scripts complete.

### ISSUE THREAD

**Issue by crkinard** [just-containers/s6-overlay#531]
I am not sure if this is working as it should or not.

According to the documents:
```
stage 2: This is where most of the end-user provided files are meant to be executed:
1 Execute legacy oneshot user scripts contained in /etc/cont-init.d.
2 Run user s6-rc services declared in /etc/s6-overlay/s6-rc.d, following dependencies
3 Copy legacy longrun user services (/etc/services.d) to a temporary directory and have s6 start (and supervise) them.
```
I am running into issues where scripts in /etc/cont-init.d are not completing before /etc/s6-overlay/s6-rc.d starts running.
This is causing some issues in my docker images launching properly. 

Is step 1 in stage 2 really supposed to completely finish before step 2 starts? Or are 1, 2, and 3 just fired off at the same time when the booting reaches stage 2?

**Comment by skarnet** [comment]
Have you solved your issue? Can I close this?
