### ISSUE TITLE
container doesn't exit on `sigint` (ctrl+c) in interactive mode running php-fpm with `CMD`

### ISSUE THREAD

**Issue by arendhummeling** [just-containers/s6-overlay#532]
Hi there, before dropping my wall of text with an issue here, I'd like to say thanks for this software. The documentation helped shape our view on the appropriate way to handle multiple processes with in a single docker container.

A very short concise summary could be given as follows:
> if I execute the folllowing script in a terminal application a normal linux or macos user would do, I would expect the process started by the script (docker run) to quit on hitting `ctrl+c`. But it does not. So I've either misunderstood [the documentation](https://github.com/just-containers/s6-overlay/tree/v3.1.5.0#using-cmd), or there's a bug here.

_Note that this script is how I am testing this on my M1 Apple machine, you'd replace the `aarch64` with the arch for your machine (probably `x86_64`)_
```bash
#!/bin/bash
docker build -t repro -<<EOF
FROM php:8.1-fpm-bullseye
RUN curl -LSso /tmp/s6-overlay-aarch64.tar.xz https://github.com/just-containers/s6-overlay/releases/download/v3.1.5.0/s6-overlay-aarch64.tar.xz
RUN tar -C / -Jxpf /tmp/s6-overlay-aarch64.tar.xz
RUN curl -LSso /tmp/s6-overlay-noarch.tar.xz https://github.com/just-containers/s6-overlay/releases/download/v3.1.5.0/s6-overlay-noarch.tar.xz
RUN tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz
ENTRYPOINT ["/init"]
CMD ["php-fpm", "-FR"]
EOF

docker run -it repro
```

# Problem description
Running the following commands with the `Dockerfile` provided below:
`docker build -t repro .`
`docker run -it repro`

At this point the `php-fpm` process is running as expected.

### The problem
Issueing a `sigint` in the terminal through `ctrl+c` does not stop the process.

### Additional interesting observations
 - Opening a different shell with `docker kill $(docker ps -lq)` (so `sigterm`) will end the process just fine.
 - Removing the `ENTRYPOINT` directive will result in php-fpm exiting gracefully on receiving a `sigint` through `ctrl-c`
 - Problem is definitely present on an M1 Apple machine (`uname -a` yields: `Darwin arend-hummeling.local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 arm64`)
 - The output of `docker system info` is included at the bottom of the issue.

I will try to reproduce this on my `amd64` linux machine later and if desired, I can also test this in an `arm` linux vm.

# Please provide a small Dockerfile that demonstrates your issue.
```Dockerfile
FROM php:8.1-fpm-bullseye

RUN curl -LSso /tmp/s6-overlay-aarch64.tar.xz https://github.com/just-containers/s6-overlay/releases/download/v3.1.5.0/s6-overlay-aarch64.tar.xz
RUN tar -C / -Jxpf /tmp/s6-overlay-aarch64.tar.xz
RUN curl -LSso /tmp/s6-overlay-noarch.tar.xz https://github.com/just-containers/s6-overlay/releases/download/v3.1.5.0/s6-overlay-noarch.tar.xz
RUN tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz

ENTRYPOINT ["/init"]

CMD ["php-fpm", "-FR"]
```
# If you've identified a fix, please open a pull request.

I'll dive in the code while waiting for confirmation that this is actually an issue and not a misunderstanding of the documentation. In either case I'll happily provide a PR. (So either for fixing the bug, or improving the documentation)

 ## Dockerinfo
Running `docker system info` gives the following information.
```
Client:
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /Users/arend/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.3
    Path:     /Users/arend/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/arend/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.19
    Path:     /Users/arend/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.4
    Path:     /Users/arend/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/arend/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/arend/.docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  v0.10.0
    Path:     /Users/arend/.docker/cli-plugins/docker-scout

Server:
 Containers: 94
  Running: 2
  Paused: 0
  Stopped: 92
 Images: 219
 Server Version: 23.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: v1.1.5-0-gf19387a
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.49-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 8
 Total Memory: 23.45GiB
 Name: docker-desktop
 ID: aa4cded4-21dc-4481-9393-6b0962877db6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

```

**Comment by skarnet** [comment]
Due to the way Unix and docker work, it is unfortunately impossible to make signals and terminals work properly in all cases under s6-overlay. However, there should always be a setting that works for you.

First, please try running `docker run` *without* `-it`. php-fpm is not an interactive program, it doesn't need a terminal; but you should still be able to interrupt your command with ^C, and that will send a SIGTERM to php-fpm. If that doesn't solve your issue, we can look deeper.

**Comment by arendhummeling** [comment]
Thanks for the quick reply!

`docker run` without passing `-it` does indeed result in the desired behaviour, awesome.
