### ISSUE TITLE
Documentation / missing s6-test from v3.1.3.0

### ISSUE THREAD

**Issue by mistraloz** [just-containers/s6-overlay#536]
s6-test is not more provided from v3.1.3.0 but still in the documentation (README.md). 
In v3.1.3.0, s6-test said : `s6-test: warning: this program is now deprecated. Please use execline's eltest instead.`

So i trust we can use eltest instead with same parameters (but i'm not sure).

**Comment by skarnet** [comment]
That's right, you can use `eltest` the exact same way. Thanks for the report, I'll fix the documentation.

**Comment by skarnet** [comment]
Fix pushed.

**Comment by NTA-MAX** [comment]
Great
