### ISSUE TITLE
Best practice for readiness notification based on stdout?

### ISSUE THREAD

**Issue by Jonax** [just-containers/s6-overlay#538]
I'm trying to dockerise a third-party server binary for automated testing purposes. To populate it, a second client binary is used. Trying to manage both steps in the Dockerfile is where s6-overlay has helped a lot. 

The Dockerfile is set up to configure two services: `server` (longrun service, dependant on `base`) and `setup` (oneshot service, dependent on `server`). `server` starts up the server binary, `setup` uses the client binary to populate the server with necessary data via command-line, and the container starts ready for further use/customisation. 

However, there's a problem - `setup` will execute before `server` finishes, so the client tries interacting with a server still initialising. The cause is fairly simple: `server` doesn't know to hold on and it likely needs to [manually signal to s6 when it's ready](https://skarnet.org/software/s6/notifywhenup.html). 

The server binary isn't exactly friendly in regards to readiness - The binary will exit with a non-zero code upon failure, but continues running as a background process if launched successfully. No files are written to be readable as a 'ready' flag. Because time to initialise can vary, a hardcoded timeout/wait seems unwise as it can either be insufficient or wasteful depending on timeout value. The only reliable signal provided by the server binary is a hardcoded `"Server starting..."` message sent to stdout once the server binary is ready to receive commands. 

What I'm wondering is: What would be the recommended/intended way to hold a service from marking itself as "ready", until stdout receives a specific message? 

Apologies if this is an obvious problem to solve. I feel like there's a few ways of doing it (e.g. modify `server`'s `run` to pipe local stdout to a file and use `tail` & `grep` to search for the message, use [s6-notifyoncheck](https://skarnet.org/software/s6/s6-notifyoncheck.html) in a similar but different way, another s6 program etc), but it feels like there's a more direct/simpler approach available that's not immediately obvious.

**Comment by NTA-MAX** [comment]
Ok I will first thing tomorrow

**Comment by skarnet** [comment]
One preliminary thing: you say that `server` will keep running *in the background* when it succeeds. Does that mean that it forks and the parent exits and it causes trouble for supervision? or does it keep running without forking and it's easily supervised?

Then, an important question: is the `Server starting...` line part of regular server logs that you want to keep, or is it just written when `server` is ready as the only line printed to stdout? This makes a crucial difference.

**Comment by Jonax** [comment]
It's probably simpler for everyone if I elaborated that the server in question is Perforce: `server` running the [`p4d`](https://www.perforce.com/manuals/p4sag/Content/P4SAG/appendix.p4d.html) Linux binary that forms a Perforce Helix server, and `setup` running the `p4` binary as a client to customise what's stored in `server`'s SVC depot. 

The relevant bit from [P4D's docs](https://www.perforce.com/manuals/p4sag/Content/P4SAG/appendix.p4d.html):
> After successful startup, p4d does not normally exit. It merely outputs the following startup message:
> `Perforce server starting...`
> and runs in the background.
>
> On failed startup, p4d returns a nonzero error code.

It doesn't explicitly say that it forks, but given it later mentions that [Perforce needs to be able to fork for certain features](https://www.perforce.com/manuals/p4sag/Content/P4SAG/appendix.p4d.html#Usage_Notes) - It looks like `p4d` will fork its own background processes, but p4d itself runs as a blocking process by default. There's flags available to run it as a daemon (`-d`), as a single-threaded non-forking process (`-f`), or as a daemon while also closing stdout/stderr (`--daemonsafe`). 

The interesting thing is that in personal experiments, p4d seems to run best without the flags mentioned above. Using `-d` or `--daemonsafe` leads to an endless loop of trying to relaunch the service and finding the port still bound from the first time in the container. So it looks like it gets supervised normally (in default/non-forking modes), and causes trouble when attempting to daemonise it directly. 
```
[...]
2023-07-06 13:25:35 s6-rc: info: service legacy-cont-init successfully started
2023-07-06 13:25:35 s6-rc: info: service server: starting
2023-07-06 13:25:35 s6-rc: info: service server successfully started
2023-07-06 13:25:35 s6-rc: info: service legacy-services: starting
2023-07-06 13:25:35 s6-rc: info: service legacy-services successfully started
2023-07-06 13:25:35 Perforce db files in '/home/user/' will be created if missing...
2023-07-06 13:25:36 Perforce Server starting...
2023-07-06 13:25:36 Perforce server warning:
2023-07-06 13:25:36 Pid 69
2023-07-06 13:25:36 Operation: topologyRegistration
2023-07-06 13:25:36 No entries made in db.topology for server address: '1666', dest address: '' and serverID: ''.
2023-07-06 13:25:37 Perforce server error:
2023-07-06 13:25:37 Listen 1666 failed.
2023-07-06 13:25:37 TCP listen on 1666 failed.
2023-07-06 13:25:37 bind: 0.0.0.0:1666: Address in use
2023-07-06 13:25:38 Perforce server error:
2023-07-06 13:25:38 Listen 1666 failed.
2023-07-06 13:25:38 TCP listen on 1666 failed.
2023-07-06 13:25:38 bind: 0.0.0.0:1666: Address in use
[...]
```

As for the `Perforce server starting...` line: p4d will print it when it's ready, as well as any errors/warnings (one such warning is in the log above). For this particular scenario, logging p4d output to persistent logs isn't necessary - I know I should likely be setting up logging properly as a good practice (and likely will in the near future), but for this particular use case containers would only last a few minutes. If a container starts failing, odds are that any automated tests configured to use it will all fail, and would warrant manual investigation of the container via terminal. 

Hoping this helps a little.

**Comment by skarnet** [comment]
- As long as the main process stays alive, it can be supervised. So, as long as you *don't* use the `-d` or `--daemonsafe` options to `p4d` (which are meant for when there is *no* supervisor), you're good.
- `p4d` doesn't seem to be open source, so unfortunately it's not possible to check how the options work exactly, but there is a chance that `--pid-file` does the right thing, i.e. only writes the pid after the server is ready. To test this, and make use of it if it works:
  * Write `3` to the `notification-fd` file in your p4d service definition directory
  * Use `--pid-file=/proc/self/fd/3` as a command-line option to p4d.

What this does is that s6 won't consider p4d ready before it has written its pid (we're using the pid line as a notification line written directly to the supervisor; we don't care about the pid per se). If p4d only writes it after it has opened its socket, then it's enough, and your setup oneshot will succeed. If p4d writes it too early, then it's not a viable solution and we'll have to find something else, but please try this first.

**Comment by Jonax** [comment]
Good to know on s6's supervision of non-daemon processes. Cheers for the info, that'll be useful to know for future uses. 😄 

Switched over to using `notification-fd` and using the `--pid-file` option. Some change to behaviour observed, but sadly it spawns a new error and ends in a restart loop (similar to when `-d`/`--daemonsafe` were used). 
```
2023-07-07 07:24:38 s6-rc: info: service s6rc-oneshot-runner: starting
2023-07-07 07:24:38 s6-rc: info: service s6rc-oneshot-runner successfully started
2023-07-07 07:24:38 s6-rc: info: service fix-attrs: starting
2023-07-07 07:24:38 s6-rc: info: service fix-attrs successfully started
2023-07-07 07:24:38 s6-rc: info: service legacy-cont-init: starting
2023-07-07 07:24:38 s6-rc: info: service legacy-cont-init successfully started
2023-07-07 07:24:38 s6-rc: info: service server: starting
2023-07-07 07:24:38 Perforce db files in '/home/user/' will be created if missing...
2023-07-07 07:24:38 Perforce server error:
2023-07-07 07:24:38     unlink: /proc/self/fd/3: Operation not permitted
2023-07-07 07:24:38 Perforce Server starting...
2023-07-07 07:24:39 Perforce server error:
2023-07-07 07:24:39     unlink: /proc/self/fd/3: Operation not permitted
2023-07-07 07:24:39 Perforce Server starting...
2023-07-07 07:24:40 Perforce server error:
2023-07-07 07:24:40     unlink: /proc/self/fd/3: Operation not permitted
2023-07-07 07:24:40 Perforce Server starting...
2023-07-07 07:24:41 Perforce server error:
2023-07-07 07:24:41     unlink: /proc/self/fd/3: Operation not permitted
2023-07-07 07:24:41 Perforce Server starting...
2023-07-07 07:24:42 Perforce server error:
2023-07-07 07:24:42     unlink: /proc/self/fd/3: Operation not permitted
2023-07-07 07:24:42 Perforce Server starting...
2023-07-07 07:24:43 s6-svlisten1: fatal: timed out
2023-07-07 07:24:43 s6-rc: warning: unable to start service server: command exited 99
```

I don't have that much experience with file descriptors (so not sure if it's an obvious fix) but on face value it looked like a potential permissions issue, so focused on getting more (hopefully) useful info. Problem persisted when using other numbers (3 or greater) for the FD. Also decided to test whether p4d would launch successfully if `--pid-file` was instead pointing to a new file in a home directory, to get a better idea of what p4d does with the PID file. p4d launched fine, and the PID file generated was as expected: ownership was `root:root`, chmod set to 444, file contents set to the supervised process's PID. 

Not sure if relevant, but Perforce's own recommendations do mention that [p4d shouldn't be run as `root`](https://www.perforce.com/manuals/p4sag/Content/P4SAG/install-linux-non-package-unprivileged-user.html). However, that comes across as guidance rather than necessity (i.e. security best practices rather than "this won't work well under root"), but seems worth mentioning in case of a conflict given [s6-overlay prefers things running as root](https://github.com/just-containers/s6-overlay#user-directive). 

In case it's of use, Perforce also has a [p4 info](https://www.perforce.com/manuals/cmdref/Content/CmdRef/p4_info.html) command for basic info on server & client. When configured to only run `server` and using p4 on the container's terminal, the following output is provided:
```
User name: root
Client name: 4790d3a31ba4
Client host: 4790d3a31ba4
Client unknown.
Current directory: /
Peer address: 127.0.0.1:43694
Client address: 127.0.0.1
Server address: localhost:1666
Server root: /home/user/
Server date: 2023/07/07 08:28:53 +0000 UTC
Server uptime: 00:00:10
Server version: P4D/LINUX26X86_64/2023.1/2442900 (2023/05/15)
ServerID: ephemeral
Server services: standard
Server license: none
Case Handling: sensitive
```

**Comment by skarnet** [comment]
- Okay, so `--pid-file` does not work because p4d is being a controlling jerk about the pid file name. Annoying, but unfortunately that's to be expected.
- s6-overlay doesn't prefer running things as root. It prefers running as root *itself*, i.e. the container should start as root, but services inside the container can drop privileges. If you want to run `p4d` as user `foo`, it's very possible:
  * Make sure your `/etc/passwd` has a correct definition for `foo`
  * Make sure all the writing places that `p4d` needs to access belong to `foo`
  * Instead of `p4d options...`, run `s6-setuidgid foo options...`
- Does `p4 info` exit 0 on success and nonzero when it fails to contact the server? In this case, you can poll for when the server comes up - it's not as satisfying as true notification, but it's easier to set up. In the p4d service definition directory:
  * Write `3` to the `notification-fd` file
  * Create a `data` subdirectory
  * Create an executable `data/check` shell script (`#!/bin/sh`) with just the following line: `exec p4 info >/dev/null`
  * In the `run` file, instead of calling `p4d options...`, call `s6-notifyoncheck -d p4d options...`
  * This will automatically make it so `p4 info` is run every second after p4d is launched, until `p4 info` succeeds, at which point the supervisor is told that p4d is ready. You can read the [s6-notifyoncheck documentation](https://skarnet.org/software/s6/s6-notifyoncheck.html) for various tuning options, but the defaults should be fine.

 I hope this will work for you.

**Comment by skarnet** [comment]
- You do need to have a preexisting `notification-fd` file. This file is not for you to use, but for the *supervisor* to use.
- When your service is ready, *do not* write to the `notification-fd` file. Instead, write to the *file descriptor* that is listed in that file. The supervisor will have opened it for you.
  + For instance, if `notification-fd` contains `3`, you should write a newline to descriptor 3.
- If you can spawn arbitrary programs, you can indeed achieve notification by having the child write to the descriptor: here you would spawn `fdmove 1 3 s6-echo` to write a newline to fd 3. However, this will not close fd 3 in your main process, so your service will keep running with one useless open fd afterwards. If you can, it's better to do the equivalent of `write(3, "\n", 1); close(3);` in your main process.

**Comment by rauanmayemir** [comment]
Thank you, it is much clearer now.

My main process can only execute arbitrary commands, I’m essentially executing a shell script. Is there a useful s6- util that I can use to write to a descriptor and then close it? (I guess I could just do bash)

**Comment by skarnet** [comment]
`fdmove 1 3 s6-echo` is the command you want. Closing fd 3 afterwards will accomplish nothing, because it will close it in the *child*, it won't change anything in the *parent*. If you can't make your main process close a file descriptor, then it doesn't matter, but it's a bit of a waste.

**Comment by rauanmayemir** [comment]
Thanks a lot, I can use this and then research further now.
