### ISSUE TITLE
/init file missing in releases aarch64 and x86_64 v3.1.5.0 causing the container to fail

### ISSUE THREAD

**Issue by bsobbe** [just-containers/s6-overlay#539]
I have the following Dockerfile, and the `Entrypoint` is towards /init as described in the docs. but it seems like this file is missing in the release download files, causing the container to be unable to find the file and fail with no such file or directory error.
I have also realized that the file does exist in the source code layout/rootfs-overlay/init. I tried copying this file and mounting it to `/` but had no luck.

```
FROM docker.io/library/debian:bullseye-slim

ARG TARGETPLATFORM
ENV S6_BEHAVIOUR_IF_STAGE2_FAILS=2
RELEASE=stable

COPY rootfs /

RUN case ${TARGETPLATFORM} in \
         "linux/amd64")  TPL_ARCH=amd64  ;; \
         "linux/arm64")  TPL_ARCH=arm64  ;; \
    esac && \
    case ${TARGETPLATFORM} in \
         "linux/amd64")  S6_ARCH=x86_64  ;; \
         "linux/arm64")  S6_ARCH=aarch64  ;; \
    esac && \
    apt-dpkg-wrap apt-get update && \
    apt-dpkg-wrap apt-get install -y apt-transport-https apt-utils ca-certificates gnupg wget xz-utils && \
    wget -qO - https://github.com/just-containers/s6-overlay/releases/download/v3.1.5.0/s6-overlay-${S6_ARCH}.tar.xz | tar -xJ -C / && \
    apt-dpkg-wrap apt-get update && \
    apt-dpkg-wrap apt-get dist-upgrade -y && \
    apt-cleanup && \    

RUN [ "$RELEASE" = "unstable" ] && \
    apt-dpkg-wrap apt-get update && \
    apt-dpkg-wrap apt-get install -y jq procps curl vim iputils-ping net-tools && \
    apt-cleanup || \
    true

ENTRYPOINT [ "/init" ]
```

Is there a particular reason for init file not existing in the release download files anymore at v3.1.5.0 or am I missing something?

**Comment by skarnet** [comment]
You need *both* the binaries tarball (which contains the arch-specific binaries for your architecture) *and* the noarch tarball (which contains the s6-overlay scripts, and is valid for all architectures).

**Comment by bsobbe** [comment]
@skarnet that makes a lot of sense. thanks for your help. I made the Dockerfile in a way that it chooses the right binaries based on the system's architecture, and regardless of the chosen architecture `noarch` tarball will always be installed and present. That got rid of the error. I am however getting permission denied on executing anything from /package/admin/s6-overlay-3.1.5.0/etc/s6-rc/scripts/cont-init now; but I don't expect it to be related to any missing tarballs anymore.
thanks again for your help!

**Comment by skarnet** [comment]
I just checked and the scripts in `/package/admin/s6-overlay-3.1.5.0/etc/s6-rc/scripts` do have the executable bit in the tarball. Make sure you extract the tarballs with the `-p` option to preserve file permissions, if you don't extract them as root.

**Comment by NTA-MAX** [comment]
Could it be CAUSE ITS TWO DIFFERENT COMPUTERS

NTASHI MATTHEWS

**Comment by bsobbe** [comment]
@skarnet  Thanks for all your help. seems like the migration from v2 to v3.1.5.0 is finally successful. all the services seem to be running without any warning or error related to the upgrade. and all the base images are now using the latest s6-overlay.
if you think it's helpful, I can add the common issues I faced during migration and their solution at the end of the #[migration document](https://github.com/just-containers/s6-overlay/blob/master/MOVING-TO-V3.md).
Feel free to let me know if that's the case.

**Comment by skarnet** [comment]
- The fact that you need two tarballs is already documented in the README.
- I will make a mention of preserving permissions when extracting the tarballs in the README as well.

Glad it's working for you!
