### ISSUE TITLE
how to determine oneshot process is successful or not ?

### ISSUE THREAD

**Issue by geeky-akshay** [just-containers/s6-overlay#540]
s6-svstat provides a summary of the state of a long-run process. That does not work for a one-shot process. Is there a way to know whether the one-shot process was successful or not? Or get an exit code for a one-shot process?

**Comment by skarnet** [comment]
Yes, success of a oneshot is determined by its exit code. 0 means success, nonzero means failure.

**Comment by geeky-akshay** [comment]
Correct, but how to check the exit code of oneshot? Is there any command available similar to s6-svstat ?

**Comment by skarnet** [comment]
This is a standard Unix thing. In your shell, use `$?` to get the exit code of the last command you ran.
