### ISSUE TITLE
Best way to restart the container if oneshot fails ?

### ISSUE THREAD

**Issue by geeky-akshay** [just-containers/s6-overlay#541]
I've a oneshot process and several longruns. My all longruns are dependent upon the oneshot.
If the oneshot fails, it is not restarted as there is no s6-supervise running for that oneshot. And because it fails, longruns are not started.

I need a way to restart the container when my oneshot fails, so that it will run again. Or, if there is a way to restart the oneshot then that would also help.

**Comment by skarnet** [comment]
Setting `S6_BEHAVIOUR_IF_STAGE2_FAILS` to `2` should solve your issue?

**Comment by geeky-akshay** [comment]
yes, working. thanks.
