### ISSUE TITLE
Is there a way prevent unlimited service restarts

### ISSUE THREAD

**Issue by flylan** [just-containers/s6-overlay#544]
When a certain service cannot be started, such as due to a configuration error, s6-overlay will continuously start the service, and then the service will start and exit infinitely. Is there a mechanism in s6-overlay that can configure a threshold so that the specified service start time is less than a specific time, such as 3 seconds, retry the specified number of times, such as stopping the service after 3 times?

My current implementation method is to record the startup time in the run script, calculate the service runtime in the finish script, and then stop s6 to start the service if the conditions are met. I don't know if there is a better solution?

**Comment by skarnet** [comment]
There is a generic mechanism to do what you want: if the `finish` script for your service (not the `run` script!) exits 125, then the service will be marked as permanently failed and won't be restarted.

The [s6-permafailon](https://skarnet.org/software/s6/s6-permafailon.html) program can be used in your `finish` script, to mark the service as permanently failed on some exit conditions. It can test conditions such as "the service exited nonzero 3 times in the past 5 seconds". It is probably the best suited tool for your use case.

Note that if a service is marked as permanently failed, then s6-rc will be unable to start anything that depends on it (unless you re-run it manually). The best way to treat configuration errors is to debug them before you put the service in production. :-)

**Comment by flylan** [comment]
> There is a generic mechanism to do what you want: if the `finish` script for your service (not the `run` script!) exits 125, then the service will be marked as permanently failed and won't be restarted.
> 
> The [s6-permafailon](https://skarnet.org/software/s6/s6-permafailon.html) program can be used in your `finish` script, to mark the service as permanently failed on some exit conditions. It can test conditions such as "the service exited nonzero 3 times in the past 5 seconds". It is probably the best suited tool for your use case.
> 
> Note that if a service is marked as permanently failed, then s6-rc will be unable to start anything that depends on it (unless you re-run it manually). The best way to treat configuration errors is to debug them before you put the service in production. :-)

Very good, very suitable
`
#/bin/bash
set -Eeuo pipefail

exit_code=${1:-0}
signal=${2:-0}

check=0
s6-permafailon 60 3 1-255 > /dev/null 2>&1 || check=$?

if test $check -eq 125; then
  //exit container
fi
`
