### ISSUE TITLE
Is there a way to delay service shutdown?

### ISSUE THREAD

**Issue by flylan** [just-containers/s6-overlay#545]
Due to the issue of distributed component message synchronization delay in k8s, in most scenarios, in order to achieve smooth container exit as much as possible, the pre stop hook is used to sleep for a certain time, such as 10 seconds. Refer to this document: https://engineering.rakuten.today/post/graceful-k8s-delpoyments/

But I hope to push out the delay service logic and trigger the execution of the specified service exit when s6 receives the SIGTERM signal, rather than using a clever method to implement it in the pre stop hook of k8s. Therefore, I would like to know if there is a similar way for s6 to delay closing the service when s6 receives the exit signal

My current implementation method is to start the service through a bash script

```shell
#!/bin/bash

nginx -g "daemon off;" &
pid=$!

graceful_stop() {
   sleep 10
   kill -QUIT $pid
}

trap "graceful_stop; exit" SIGTERM SIGQUIT

wait $pid
```

Although the above script can achieve delayed exit, there will be an additional bash script resident. I would like to know if there is a better solution?

**Comment by skarnet** [comment]
It is unclear to me why you want to handle the delay at the service level rather than at the container level. Wouldn't the pod termination process imply stopping the whole container rather than a single service? Wouldn't you want to delay the management of a SIGTERM to the container's pid 1 rather than have the container immediately start its shutdown procedure but stall on terminating one service for 10 seconds?

**Comment by flylan** [comment]
> It is unclear to me why you want to handle the delay at the service level rather than at the container level. Wouldn't the pod termination process imply stopping the whole container rather than a single service? Wouldn't you want to delay the management of a SIGTERM to the container's pid 1 rather than have the container immediately start its shutdown procedure but stall on terminating one service for 10 seconds?

Indeed, you are right. This delayed exit should not be coupled to the container level, but should be done at the service orchestration software level such as K8S or Docker Compose
