### ISSUE TITLE
`S6_CMD_WAIT_FOR_SERVICES=1` makes no diference

### ISSUE THREAD

**Issue by felipecrs** [just-containers/s6-overlay#546]
I pushed a reproduction repo: https://github.com/felipecrs/test-s6-overlay

```console
$ git clone https://github.com/felipecrs/test-s6-overlay
$ cd test-s6-overlay
$ docker build . -t test
$ docker run --rm test true
```

1. s6-overlay doesn't wait for myservice to be ready before executing CMD
2. executes CMD even if myservice never gets ready
3. exits with a 0 code (probably because CMD got executed)

Is my expectation wrong?

**Comment by felipecrs** [comment]
I edited the issue with more clear reproduction steps.

**Comment by skarnet** [comment]
Does it wait for 5 seconds before executing your CMD? If so, that's expected: that's the default maximum waiting time. If you want s6-overlay to wait *forever* until your `/etc/services.d` services are ready, you should also set the `S6_CMD_WAIT_FOR_SERVICES_MAXTIME` variable to 0.

**Comment by felipecrs** [comment]
No, it doesn't make any difference:


https://github.com/just-containers/s6-overlay/assets/29582865/b3610e84-4c5d-4f53-97d6-7e5733066896

**Comment by skarnet** [comment]
Indeed it was a bug, thanks for the report! It should be fixed now in the latest git head.

New compiled versions will come out as soon as possible, probably some time in September.

**Comment by felipecrs** [comment]
Awesome, thanks a lot.

**Comment by felipecrs** [comment]
Another thing, after exceeding the `S6_CMD_WAIT_FOR_SERVICES_MAXTIME`, will `CMD` still be executed as you mentioned above?

I wonder if the most desired behavior would not be to exit early the container with a non zero status code.

**Comment by skarnet** [comment]
You can already customize that via `S6_BEHAVIOUR_IF_STAGE2_FAILS`.

**Comment by felipecrs** [comment]
Oh, that's perfect then.

PS: documentation only mentions that `S6_BEHAVIOUR_IF_STAGE2_FAILS` is valid for `cont-init` and `fix-attrs`, but not for `services.d` readiness.

**Comment by skarnet** [comment]
Documentation updated, thanks.

**Comment by felipecrs** [comment]
> New compiled versions will come out as soon as possible, probably some time in September.

@skarnet, I don't want to be inconvenient, but is this something you are still planning?

**Comment by skarnet** [comment]
Yes. I'm behind on schedule (when am I not?) but working to make the release as fast as possible without sacrificing quality.

(The reason for the delay is that the new skarnet.org release includes a web server, which is a significant piece of software; it's not in beta and being debugged and polished to make it ready for release. And in the process there was an important amount of changes done to the skarnet.org stack, so getting everything in a row takes time.)

Sorry for the delays.

**Comment by felipecrs** [comment]
Got it. Makes sense. Thanks for the detailed response.

**Comment by skarnet** [comment]
The new release is finally out! Please test and report if it fixes (or does not fix) the issue.

**Comment by felipecrs** [comment]
All seems to be working fine now. Thanks a lot!
