### ISSUE TITLE
Issue with s6-overlay in Cattr project when deployed on Kubernetes

### ISSUE THREAD

**Issue by khalid244** [just-containers/s6-overlay#551]
Hello,

I am currently using an open-source project named “Cattr” which utilizes s6-overlay. When I run the Cattr project using Docker Compose, it operates as expected. However, I encounter an issue when attempting to do the same with Kubernetes.

The error message I receive is as follows:

```
/package/admin/s6-overlay/libexec/preinit: notice: /var/run is not a symlink to /run, fixing it
s6-rmrf: fatal: unable to remove /var/run: Read-only file system
s6-overlay-suexec: fatal: child failed with exit code 111
```

I have been troubleshooting this problem for over two weeks without success. Any assistance or guidance you could provide would be greatly appreciated.

For reference, here is the Cattr project I am working with.
https://github.com/cattr-app/server-application/releases/tag/v4.0.0-RC43

Thank you in advance for your help.

**Comment by khalid244** [comment]
@skarnet

**Comment by skarnet** [comment]
This sounds related to the way your container manager mounts the filesystems. I don't know Kubernetes at all, but `/var/run` being on a read-only filesystem is wrong. By definition, `/var` has to be read-write. Check your container configuration.

**Comment by khalid244** [comment]
When I start to debug more /var/run used by Kubernetes I think that what make the conflict


```

/ $ ls -l /
total 84
drwxrwx---    1 www      www           4096 Oct 17 07:37 app
drwxr-xr-x    2 root     root          4096 Jan  1  1970 bin
drwxr-xr-x    2 root     root         12288 Jan  1  1970 command
-rw-rw-r--    1 root     root            40 Sep 25 09:10 crontab
drwxr-xr-x    5 root     root           360 Oct 17 07:37 dev
drwxrwxr-x    1 root     root          4096 Oct 17 07:37 etc
drwxr-xr-x    1 root     root          4096 Jan  1  1970 home
drwxr-xr-x    3 root     root          4096 Jan  1  1970 include
-rwxr-xr-x    1 root     root           907 Jan  1  1970 init
drwxr-xr-x    4 root     root          4096 Jan  1  1970 lib
lrwxrwxrwx    1 root     root             3 Jan  1  1970 lib64 -> lib
drwxr-xr-x    2 root     root          4096 Jan  1  1970 opt
drwxr-xr-x    6 root     root          4096 Jan  1  1970 package
drwxrwxr-x    1 root     root          4096 Sep 25 09:10 php
dr-xr-xr-x  442 root     root             0 Oct 17 07:37 proc
drwx------    2 root     root          4096 Jan  1  1970 root
drwxr-xr-x    3 root     root          4096 Jan  1  1970 run
drwxr-xr-x    2 root     root          4096 Jan  1  1970 sbin
dr-xr-xr-x   13 root     root             0 Oct 17 07:37 sys
drwxrwxrwt    1 root     root          4096 Oct 17 07:37 tmp
drwxr-xr-x    8 root     root          4096 Jan  1  1970 usr
drwxr-xr-x    9 root     root          4096 Jan  1  1970 var

/ $ ls -l /var
total 28
drwx------    2 adm      adm           4096 Jan  1  1970 adm
drwxr-xr-x    4 root     root          4096 Jan  1  1970 cache
drwxr-xr-x    5 root     root          4096 Jan  1  1970 lib
drwxr-xr-x    2 root     root          4096 Jan  1  1970 log
drwx------    2 mail     mail          4096 Jan  1  1970 mail
drwxrwxrwx    3 root     root          4096 Oct 17 07:37 run
drwxr-xr-x    5 root     root          4096 Jan  1  1970 spool
```

**Comment by skarnet** [comment]
`ls` won't tell you anything (except that your original image's `/var/run` has incorrect permissions, it should definitely not be writable by everyone).

What you should look at is `mount`, to see where and how the filesystems are mounted; then you need to find the place in your container manager that mounts these filesystems, and fix the settings.

s6-overlay only reported the problem; fixing this isn't s6-overlay related.

**Comment by khalid244** [comment]
Unfortunately, changing the Kubernetes mount path has caused a lot of problems in the past, so I don’t prefer that solution. Is there any way to change the s6-overlay mount path?

**Comment by skarnet** [comment]
There's no such thing as "the s6-overlay mount path".

All s6-overlay is saying is that the way you are currently attempting to use it with Kubernetes cannot work. You don't have an s6-overlay problem. You have a filesystem problem that cannot be solved at the s6-overlay level.

You don't need to change the "Kubernetes mount path". You just need to make the mount *read-write*. Your system cannot work when `/var` is read-only.

I cannot provide Kubernetes support, sorry, so I'm closing this.
