### ISSUE TITLE
`UID not set` error

### ISSUE THREAD

**Issue by romangershgorin** [just-containers/s6-overlay#552]
Hello, I am trying y to use s6-overlay to start couple of services in my docker image, this is part of my Dockerfile.

```
FROM <spark image>

USER root

# some code

ARG S6_OVERLAY_VERSION=3.1.5.0
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-x86_64.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-x86_64.tar.xz

# some code

COPY --chown=spark:root services.d/ /etc/services.d/

USER spark

# some code

USER spark
ENTRYPOINT /init

EXPOSE 4040/tcp 8080/tcp
```

During deployment I get this error:
```
s6-overlay-suexec: warning: unable to gain root privileges (is the suid bit set?)
s6-chown: fatal: **UID not set**
s6-overlay-suexec: fatal: child failed with exit code 100
```
I logged into the container, `echo $UID` works and returns uid successfully. 
What can be the problem here, what permissions do I need to fix this issue? I thought USER instruction inside docker should set up all uid/gid vars inside container, but probably that's not enough? 

When I tried to add UID and GID variables manually, which apparently is not a proper way to fix, got another error:
```
s6-overlay-suexec: warning: unable to gain root privileges (is the suid bit set?)
s6-chown: fatal: unable to chown /run: Operation not permitted
s6-overlay-suexec: fatal: child failed with exit code 111
```

any help is greatly appreciated.

**Comment by skarnet** [comment]
The part that's failing is [this one](https://github.com/just-containers/s6-overlay/blob/master/layout/rootfs-overlay/package/admin/s6-overlay-%40VERSION%40/libexec/preinit#L76), or a similar one earlier in the file.

Normally, in your case - running a container as USER - since `UID` is not set, `"$0UID"` resolves to `0`, the test is false, and the `s6-chown` instruction is never run.

Here, for some reason, the test succeeds. Likely, either the `/bin/sh` or the `test` program provided by your image is nonconformant.

**Comment by skarnet** [comment]
Well there are two possible cases:

- The container is run entirely as a normal user with no root privileges at all. All the binaries, all the files, everything, belongs to that user. In which case `UID` is not set.
- The container is run as a normal user but some files still belong to root. In which case `s6-overlay-suexec` should belong to root and be suid; `UID` will be set, `preinit` will do its initial setup as root, ensuring the user has access to the necessary files, then everything after that will run as the user.

In your case, the warning says `s6-overlay-suexec` does not have the suid bit, so you must be in the first category and `UID` is not set.

Either that, or something else is happening: your `tar`, or the way your guest filesystems are mounted, prevent the suid bit from being properly set on `s6-overlay-suexec`.

In any case there's something wrong with the way your container is set up. I have no further insights, sorry.

**Comment by romangershgorin** [comment]
@skarnet found s6-overlay-seuxec, checked it's permissions, looks like **s** is set. Is it what you meant, or something else? 
-rw**s**r-xr-x 1 root root 37968 May  5  2023 s6-overlay-suexec

**Comment by skarnet** [comment]
Yeah, it's set. But you still get a warning message that it's unable to gain privileges.

Is your container manager mounting the rootfs with the nosuid option? That would explain it.

**Comment by felipecrs** [comment]
> Is your container manager mounting the rootfs with the nosuid option? That would explain it.

BTW this has happened to me in an IT managed environment from my company, and it led to similar results. You can probably find it out by checking `/etc/fstab`.

**Comment by romangershgorin** [comment]
@felipecrs just tried to check this file, but it's not present in my instance.. did you manage to fix the issue in your case?

**Comment by romangershgorin** [comment]
Checked `cat /proc/mounts` instead, almost everywhere is nosuid:
```
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev tmpfs rw,nosuid,size=65536k,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666 0 0
sysfs /sys sysfs ro,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup cgroup2 ro,nosuid,nodev,noexec,relatime 0 0
mqueue /dev/mqueue mqueue rw,nosuid,nodev,noexec,relatime 0 0
shm /dev/shm tmpfs rw,nosuid,nodev,noexec,relatime,size=65536k 0 0
/dev/vda1 /etc/resolv.conf ext4 rw,relatime 0 0
/dev/vda1 /etc/hostname ext4 rw,relatime 0 0
/dev/vda1 /etc/hosts ext4 rw,relatime 0 0
proc /proc/bus proc ro,nosuid,nodev,noexec,relatime 0 0
proc /proc/fs proc ro,nosuid,nodev,noexec,relatime 0 0
proc /proc/irq proc ro,nosuid,nodev,noexec,relatime 0 0
proc /proc/sys proc ro,nosuid,nodev,noexec,relatime 0 0
proc /proc/sysrq-trigger proc ro,nosuid,nodev,noexec,relatime 0 0
tmpfs /proc/kcore tmpfs rw,nosuid,size=65536k,mode=755 0 0
tmpfs /proc/keys tmpfs rw,nosuid,size=65536k,mode=755 0 0
tmpfs /proc/timer_list tmpfs rw,nosuid,size=65536k,mode=755 0 0
tmpfs /proc/sched_debug tmpfs rw,nosuid,size=65536k,mode=755 0 0
tmpfs /sys/firmware tmpfs ro,relatime 0 0
```
@skarnet is that what you suspected?

**Comment by skarnet** [comment]
Well nosuid makes sense for all of these, but `/` is not listed, which would be the interesting mount, and the one where nosuid is a problem...

**Comment by skarnet** [comment]
Did you manage to find the root of the issue? Can I close this?

**Comment by romangershgorin** [comment]
I did not find the root of the issue, please feel free to close it

**Comment by ZEALi** [comment]
docker run --security-opt=no-new-privileges 
WILL break preinit

**Comment by skarnet** [comment]
Break in what way? can you please give the warning and error messages preinit prints out?
