### ISSUE TITLE
s6-overlay v3 only sends SIGTERM to `/etc/services.d` after `S6_SERVICES_GRACETIME`

### ISSUE THREAD

**Issue by felipecrs** [just-containers/s6-overlay#554]
Still at my journey to upgrade from s6-overlay v2 to v3 (https://github.com/felipecrs/jenkins-agent-dind/pull/78).

Now I am facing the following issue:

s6-overlay is only sending SIGTERM to my services at `/etc/services.d` after `S6_SERVICES_GRACETIME` expires.

I suppose this is wrong because:

> S6_SERVICES_GRACETIME (default = 3000): How long (in milliseconds) s6 should wait, at shutdown time, for services declared in /etc/services.d to die before proceeding with the rest of the shutdown.

In s6-overlay v2, as soon as CMD finished, it would send a SIGTERM signal to my processes.

But maybe I am wrong and I should instead be relying on `S6_KILL_GRACETIME`? I guess not because s6-overlay even raises an error _s6-svwait: fatal: timed out_ when `S6_SERVICES_GRACETIME` times up and services are still running.

**Comment by felipecrs** [comment]
Reproduction instructions:

```
$ git clone https://github.com/felipecrs/test-s6-overlay
$ cd test-s6-overlay
$ docker build . -t test
$ docker run --rm test true
```

![image](https://github.com/just-containers/s6-overlay/assets/29582865/08fbce92-b0a1-4a84-925e-838b6f41361d)

**Comment by skarnet** [comment]
I can reproduce the problem. It is a bug, I'll work on it.

**Comment by felipecrs** [comment]
Alright. Thanks a lot.

**Comment by skarnet** [comment]
New release is out, if all goes well it fixes this. Please reopen if you still have the issue.

**Comment by felipecrs** [comment]
Awesome, thanks a lot!

**Comment by felipecrs** [comment]
@skarnet I'm not sure this issue is fixed. Would you mind trying it yourself again?

```console
$ git clone https://github.com/felipecrs/test-s6-overlay
$ cd test-s6-overlay
$ docker build . -t test
$ docker run --rm -e S6_SERVICES_GRACETIME=10000 test false
```

https://github.com/just-containers/s6-overlay/assets/29582865/c4ff6b1c-4186-4269-b6d5-689136e587d9

I'm also observing that the new version is taking a much longer time to actually finish after CMD exits:

```console
$ time docker run --rm -e S6_SERVICES_GRACETIME=10000 test false
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun myservice
s6-rc: info: service legacy-services successfully started
s6-rc: info: service legacy-services: stopping
s6-svwait: fatal: timed out
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
Terminated
Caught SIGTERM
docker run --rm -e S6_SERVICES_GRACETIME=10000 test false  0.03s user 0.01s system 0% cpu 2:00.08 total
```

2 minutes in the example above.

**Comment by skarnet** [comment]
- The initial issue is fixed. If you "exec sleep infinity" in your `service.sh` file, it won't hang; your run script is just incorrect.
- The fact that the shutdown hangs at the end is a different issue. It does not occur with `ENV S6_LOGGING=1`, and it is very weird. I will work on it this week.

**Comment by felipecrs** [comment]
> * The initial issue is fixed. If you "exec sleep infinity" in your `service.sh` file, it won't hang; your run script is just incorrect.

You are right, sorry about it. Apparently bash won't handle the signal until the command being executed finishes. Changing `sleep infinity` to `while sleep 1s; do true; done` seems to make my test valid again:

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun myservice
s6-rc: info: service legacy-services successfully started
s6-rc: info: service legacy-services: stopping
Caught SIGTERM
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

As per the other problem, I will open a separate issue to help you track it better.
