### ISSUE TITLE
How to create something similar like cont-init if this one is deprecated ?

### ISSUE THREAD

**Issue by asquel** [just-containers/s6-overlay#560]
Hi, 

Before the new version of s6 and the bundles it was possible to have a "fix" script that would run at the beginning no matter what.
Now, is it possible to add script into the base bundle ? (Cannot find doc about that anywhere sorry). 
(I have a docker base image for multiple teams and I this script would be in the docker base image, so they would not see it, but they need to depend on it)

Thx in advance for your help !

**Comment by skarnet** [comment]
Maybe you could have looked just a bit harder?

- `/etc/cont-init.d` has not gone away, it's still supported.
- If that still isn't enough for you, you can set the `S6_STAGE2_HOOK` variable to the path of a script that will run even earlier.

**Comment by asquel** [comment]
It was not meant as an offense, I took the time to read the entire manual of the s6-rc, so I looked hard :) 
(I changed the title, maybe my translation was wrong)
In french i would have written you "Pas vraiment de remplacement pour cont-init ?" 
maybe it's less offending. 
I saw the cont-init is deprecated and this is why I didn't want to use it, because it would disapear one day ... 
And in the S6_STAGE2_HOOk, you said "use only if you understand really what is happening". 

Thx for the answer.

**Comment by skarnet** [comment]
`cont-init` is deprecated in that it's not the recommended way of doing things anymore and we're not going to expand on it, but it's not going anywhere, we're not going to delete it. If it's what you need, use it to your heart's content. 😉
