### ISSUE TITLE
Best practice for redirecting output from app1 to app2

### ISSUE THREAD

**Issue by utdrmac** [just-containers/s6-overlay#562]
(Apologies if this is not the best place for community support. I didn't see anything in the README regarding help.)

I'm writing my own docker container, and attempting to use s6. The following is what I have, which works as a bash script. But I'd like to write it properly with s6. What's the best way to have this redirect pipe work and the environment variables?

```
$ ls water_gas_meter_reader/s6-rc.d/
rtlamr-collect/ rtl_tcp/        user/
$ ls water_gas_meter_reader/s6-rc.d/rtlamr-collect/
dependencies.d/ run             type
$ cat water_gas_meter_reader/s6-rc.d/rtlamr-collect/run
#!/bin/bash

export RTLAMR_FORMAT=json
export RTLAMR_MSGTYPE=scm
export RTLAMR_FILTERID="3232323,8282828"

export COLLECT_LOGLEVEL="Trace"
export COLLECT_INFLUXDB_HOSTNAME="http://1.2.3.4:8086/"
export COLLECT_INFLUXDB_TOKEN="mytoken=="
export COLLECT_INFLUXDB_ORG="metrics"
export COLLECT_INFLUXDB_BUCKET="metrics"
export COLLECT_INFLUXDB_MEASUREMENT="meters"

echo "Launching rtlamr piped to rtlamr-collect"

/usr/src/app/rtlamr | /usr/src/app/rtlamr-collect
```

For completness, here's the run for the dependency on the above. This works fine as does the healthcheck.

```
$ cat water_gas_meter_reader/s6-rc.d/rtl_tcp/run
#!/command/execlineb -P

foreground { echo "Starting rtl_tcp..." }
fdmove -c 2 1

# Will execute rtl_tcp/data/check script every 2s, waiting 10s before first check
exec s6-notifyoncheck -d -s 10000 -w 2000 rtl_tcp
```

Thanks for the help.

**Comment by skarnet** [comment]
So, what you want is *two* services: `rtlamr` and `rtlamr-collect`.
In `rtlamr` you would just run the `rtlamr` process with the RTLAMR_* environment variables, and in `rtlamr-collect you would just run `rtlamr-collect` with the COLLECT_* environment variables:

```
$ cat water_gas_meter_reader/s6-rc.d/rtlamr/run
#!/command/execlineb -S1
envfile env/env
/usr/src/app/rtlamr
$ cat water_gas_meter_reader/s6-rc.d/rtlamr/env/env
RTLAMR_FORMAT=json
RTLAMR_MSGTYPE=scm
RTLAMR_FILTERID=3232323,8282828
$ cat water_gas_meter_reader/s6-rc.d/rtlamr-collect/run
#!/command/execlineb -S1
envfile env/env
/usr/src/app/rtlamr-collect
$ cat water_gas_meter_reader/s6-rc.d/rtlamr/env/env
COLLECT_LOGLEVEL=Trace
COLLECT_INFLUXDB_HOSTNAME=http://1.2.3.4:8086/
COLLECT_INFLUXDB_TOKEN=mytoken==
COLLECT_INFLUXDB_ORG=metrics
COLLECT_INFLUXDB_BUCKET=metrics
COLLECT_INFLUXDB_MEASUREMENT=meters
```
(you don't have to use execline and envfile, I just used them here to show how they can simplify your scripts, but you can stick with bash if you're more comfortable with it!)

Now the question is, how do I pipe `rtlamr`'s stdout into `rtlamr-collect`'s stdin? The answer is an s6-rc feature named... a pipeline. You need to declare `rtlamr` as a *producer* for `rtlamr-collect`, and `rtlamr-collect` as the *consumer* for `rtlamr`.
```
$ cat water_gas_meter_reader/s6-rc.d/rtlamr/producer-for
rtlamr-collect
$ cat water_gas_meter_reader/s6-rc.d/rtlamr-collect/consumer-for
rtlamr
$ cat water_gas_meter_reader/s6-rc.d/rtlamr-collect/pipeline-name
rtlamr-pipeline
```
The last file, `pipeline-name` (always in the directory of the *consumer*), is optional. It lets you give an alias to the whole pipeline, here the set of two services, `rtlamr` *and* `rtlamr-collect`, so you can for instance add `rtlamr-pipeline` to the `user` bundle and both services will be started at container boot time.
That's all there is to it!

**Comment by utdrmac** [comment]
Ok. I attempted what you recommended and things aren't working still. Here's my full tree:

```
$ find s6-rc.d/
s6-rc.d/
s6-rc.d/rtlamr
s6-rc.d/rtlamr/type
s6-rc.d/rtlamr/producer-for
s6-rc.d/rtlamr/env
s6-rc.d/rtlamr/env/env
s6-rc.d/rtlamr/run
s6-rc.d/rtlamr/dependencies.d
s6-rc.d/rtlamr/dependencies.d/base
s6-rc.d/rtlamr/dependencies.d/rtl_tcp
s6-rc.d/user
s6-rc.d/user/contents.d
s6-rc.d/user/contents.d/rtl_tcp
s6-rc.d/user/contents.d/rtlamr-pipeline
s6-rc.d/rtl_tcp
s6-rc.d/rtl_tcp/type
s6-rc.d/rtl_tcp/data
s6-rc.d/rtl_tcp/data/check
s6-rc.d/rtl_tcp/run
s6-rc.d/rtl_tcp/dependencies.d
s6-rc.d/rtl_tcp/dependencies.d/base
s6-rc.d/rtl_tcp/notification-fd
s6-rc.d/rtlamr-collect
s6-rc.d/rtlamr-collect/type
s6-rc.d/rtlamr-collect/pipeline-name
s6-rc.d/rtlamr-collect/env
s6-rc.d/rtlamr-collect/env/env
s6-rc.d/rtlamr-collect/run
s6-rc.d/rtlamr-collect/consumer-for
s6-rc.d/rtlamr-collect/dependencies.d
s6-rc.d/rtlamr-collect/dependencies.d/base
```

rtl_tcp must launch first. I created a check script to wait 10s then poll every 2s. You can see "rtl_tcp is ready" below, which is output from the data/check script. (Side note, I would expect to see this line output every 2s but I only ever see it once).

Then, rtlamr starts, or it should. I believe the s6 fatal timeout message below is rtlamr failing to start for some reason. Why does it start even before rtl_tcp has completed its first data/check?

Same thing with rtlamr-collect. I can see the INFO line is a log output from this prog, and it too started before rtl_tcp finished. It also appears that -collect is starting _before_ rtlamr, despite having the producer-for/consumer-for pipe configured. I expected the pipeline to be a sort of dependency.

```
 ✔ Container metrics_metersradio  Recreated                                                                                                                0.6s
Attaching to metrics_metersradio
metrics_metersradio  | s6-rc: info: service s6rc-fdholder: starting
metrics_metersradio  | s6-rc: info: service s6rc-oneshot-runner: starting
metrics_metersradio  | s6-rc: info: service s6rc-oneshot-runner successfully started
metrics_metersradio  | s6-rc: info: service fix-attrs: starting
metrics_metersradio  | s6-rc: info: service s6rc-fdholder successfully started
metrics_metersradio  | s6-rc: info: service fix-attrs successfully started
metrics_metersradio  | s6-rc: info: service legacy-cont-init: starting
metrics_metersradio  | s6-rc: info: service legacy-cont-init successfully started
metrics_metersradio  | s6-rc: info: service rtlamr-collect: starting
metrics_metersradio  | s6-rc: info: service rtl_tcp: starting
metrics_metersradio  | s6-rc: info: service rtlamr-collect successfully started
metrics_metersradio  | Starting rtl_tcp...
metrics_metersradio  | Found 1 device(s):
metrics_metersradio  |   0:  Realtek, RTL2838UHIDIR, SN: 00000001
metrics_metersradio  |
metrics_metersradio  | Using device 0: Generic RTL2832U OEM
metrics_metersradio  | INFO[2024-01-23 01:27:35.339]/go/pkg/mod/github.com/bemasher/rtlamr-collect@v1.0.3/main.go:406 main.main connecting to "http://10.10.10.203:8086/"
metrics_metersradio  | Found Rafael Micro R820T tuner
metrics_metersradio  | [R82XX] PLL not locked!
metrics_metersradio  | Tuned to 100000000 Hz.
metrics_metersradio  | s6-rc: fatal: timed out
metrics_metersradio  | s6-svlisten1: fatal: timed out
metrics_metersradio  | rtl_tcp is ready
```

Files contents:
```
$ cat s6-rc.d/rtl_tcp/data/check
#!/bin/bash

# Look for rtl_tcp listening socket
# 04D2 = port 1234 of rtl_tcp

num=$(cat /proc/net/tcp | grep 04D2 | wc -l)
if [ $num -gt 0 ]; then
  echo "rtl_tcp is ready"
  exit 0
else
  echo "rtl_tcp not ready"
  exit 1
fi

$ cat s6-rc.d/rtl_tcp/run
#!/command/execlineb -P

foreground { echo "Starting rtl_tcp..." }
fdmove -c 2 1

# Will execute rtl_tcp/data/check script every 2s, waiting 10s before first check
s6-notifyoncheck -s 10000 -w 2000 rtl_tcp

$ cat s6-rc.d/rtlamr/run
#!/command/execlineb -S1
envfile env/env
/usr/src/app/rtlamr

$ cat s6-rc.d/rtlamr/producer-for
rtlamr-collect

$ cat s6-rc.d/rtlamr-collect/run
#!/command/execlineb -S1
envfile env/env
/usr/src/app/rtlamr-collect

$ cat s6-rc.d/rtlamr-collect/consumer-for
rtlamr

$ cat s6-rc.d/rtlamr-collect/pipeline-name
rtlamr-pipeline

**Comment by utdrmac** [comment]
I bash'd into the container and ran this
`root@metersradio:/usr/src/app# /package/admin/s6/command/s6-svc -u /run/service/rtlamr`
and that started up. Somewhere in my setup, rtlamr isn't waiting for rtl_tcp to finish starting and pass a check script run.

**Comment by skarnet** [comment]
Everything appears to be working as intended.

- There *is* a dependency between producer and consumer: the consumer is started *first*, always. Because you don't want the producer to start writing into a pipe that will never get read: that would cause data loss. So the producer only starts after the consumer is ready. It is expected that `rtlamr-collect` starts first, and since it doesn't have a dependency on `rtl_tcp`, it doesn't have to wait for it.
- So `rtlamr-collect` starts, but does nothing: it just waits from data from `rtlamr`. Which needs `rtl_tcp` first, so `rtl_tcp` gets started.
- The `data/check` program is only run until it passes: it is not an ongoing health check, it's only at the start of the service, to determine when the service is ready and its dependents can start. Here, `rtl_tcp` is ready at the time of the first check, so, everything's okay.
- At this point, `rtlamr` would be started.

What is happening is that you're hitting the global s6-rc timeout by the time `rtl_tcp` gets ready, so s6-rc gives up entirely and never tries to start `rtlamr`. By default in s6-overlay, this timeout is 5000 (5 seconds); you should increase its value in the S6_CMD_WAIT_FOR_SERVICES_MAXTIME environment variable in your Dockerfile, or set it to 0 in order to disable the timeout entirely.

Although documented in the README, this default timeout is tripping up way more people than it is helping. It will be made infinite by default in a future version of s6-overlay.

**Comment by utdrmac** [comment]
`S6_CMD_WAIT_FOR_SERVICES_MAXTIME` Yes! That was it. Thank you for the assistance.

> and since it doesn't have a dependency on rtl_tcp, it doesn't have to wait for it.

I first tried putting a dependency on rtlamr, but that gave me some circular dependency error on container start so I removed that.
