### ISSUE TITLE
How to read ENV variables from a file for the main process (defined in CMD)

### ISSUE THREAD

**Issue by komapa** [just-containers/s6-overlay#565]
Hello, I am investigating using s6-overlay to replace our custom `entrypoint.sh` and I cannot figure out one use case we have. We use Vault sidecars to inject secrets into `/vault/secrets` and inside there are files that I can just `source 10-kvv2.env`. We currently do that in the `entrypoint.sh` which is spawned with `tini`. I can see there is the `s6-envdir` but that assumes I will run the main process supervised but what I would like to do is run one or 1-2 `oneshot` scripts and then one `long` script which will monitor the files created by Vault and signal the container to exit when they change so that the main process can re-read them.

My question is, what control do we have over `CMD` process in `/etc/s6-overlay`? Can I inject ENV variables to it, or otherwise control it with configs? I want to make the replacement for `entrypoint.sh` seamless so I do not want to ask developers (users of the base image) to have to know about s6 and create config files.

Sorry if this is not very organized ask but I can provide more code tomorrow if this is not obvious to you right away.

Thank you!

**Comment by skarnet** [comment]
I'm not sure I fully understand what you mean, but isn't `with-contenv` what you're looking for? `with-contenv prog` will run `prog` with all the ENV variables defined in your Dockerfile.

**Comment by komapa** [comment]
```
#!/bin/bash
set -e

# By default we are going to exec into "$@"
exec="exec"

# Logic only for when running in Kubernetes
if [[ -n "$KUBERNETES_SERVICE_HOST" ]]; then
  # In Kubernetes, we want to let "tini -g" send signals to the process group
  # (instead of using `exec` and replacing the bash script process with "$@")
  exec=""

  shutdown_consul_dataplane() {
    # Try stopping gracefully the Consul sidecar proxy on shutdown
    # see: https://github.com/solusipse/fiche#useful-aliases
    # see: https://developer.hashicorp.com/consul/docs/k8s/connect#kubernetes-jobs
    # shellcheck disable=SC2028
    NEXT_WAIT_TIME=0;
    until \
      [ $NEXT_WAIT_TIME -eq 3 ] || \
      printf "POST /graceful_shutdown HTTP/1.1\r\nHost: 127.0.0.1\r\nConnection: close\r\n\r\n" | \
        (exec 3<>/dev/tcp/127.0.0.1/20600 && cat >&3 && exec 3<&-) &>/dev/null;
    do
      sleep $(( NEXT_WAIT_TIME++ ));
    done
  }

  shutdown_vault_agent() {
    # Try stopping gracefully the Vault sidecar agent on shutdown
    # see: https://github.com/solusipse/fiche#useful-aliases
    # see: https://developer.hashicorp.com/vault/docs/agent-and-proxy/agent#quit
    # shellcheck disable=SC2028
    NEXT_WAIT_TIME=0;
    until \
      [ $NEXT_WAIT_TIME -eq 3 ] || \
      printf "POST /agent/v1/quit HTTP/1.1\r\nHost: 127.0.0.1\r\nConnection: close\r\n\r\n" | \
        (exec 3<>/dev/tcp/127.0.0.1/20200 && cat >&3 && exec 3<&-) &>/dev/null;
    do
      sleep $(( NEXT_WAIT_TIME++ ));
    done
  }

  shutdown() {
    # shellcheck disable=SC2155
    local COMPONENT=$(printenv "KUBERNETES_LABEL_app.kubernetes.io_component" || echo -n "")
    # shellcheck disable=SC2155
    local CONSUL_CONNECT_INJECT_STATUS=$(printenv "KUBERNETES_ANNOTATION_consul.hashicorp.com_connect_inject_status" || echo -n "")
    # shellcheck disable=SC2155
    local VAULT_AGENT_INJECT_STATUS=$(printenv "KUBERNETES_ANNOTATION_vault.hashicorp.com_agent_inject_status" || echo -n "")

    case "${COMPONENT}:${CONSUL_CONNECT_INJECT_STATUS}" in
      "cronjob:injected" | "batchjob:injected")
        shutdown_consul_dataplane
        ;;
    esac

    case "${COMPONENT}:${VAULT_AGENT_INJECT_STATUS}" in
      "cronjob:injected" | "batchjob:injected")
        shutdown_vault_agent
        ;;
    esac
  }

  trap shutdown EXIT
fi

if [[ -d /vault/secrets ]]; then
  shopt -s nullglob;
  # shellcheck disable=SC1090
  for env in /vault/secrets/*.env; do source "${env}"; done;
  shopt -u nullglob;

  # if inotifywait is available, use it to watch for changes in the environment files
  if [[ $(type -P "inotifywait") != "" ]]; then
    {
      # setup a watch on /vault/secrets and restart on changes for all non "*-noop.env" environment files
      # shellcheck disable=SC2034
      inotifywait --quiet --monitor /vault/secrets --event modify --exclude '.*-noop\.env$' |
        while read -r directory action file; do
          if [[ "${file}" == *.env ]]; then
            # allow for the user to overwrite the kill signal by defining "STOPSIGNAL" environment variable
            # see: https://docs.docker.com/engine/reference/builder/#stopsignal
            kill -s "${STOPSIGNAL:-SIGTERM}" 1;
            exit 0;
          fi;
        done
    } >/dev/null 2>&1 <&1 & disown
  fi
fi

# check if startup-check exists and is executable
if [[ -f /bin/startup-check && -x /bin/startup-check ]]; then
  /bin/startup-check
fi

# shellcheck disable=SC2154
CRONITOR_ID=$(printenv "NOMAD_META_cronitor.${NOMAD_META_environment}.id" || echo -n "")
NUM_PROCESSES=$(printenv "NOMAD_META_entrypoint.${NOMAD_META_environment}.num_processes" || echo -n "1")

# if a cronitor id is set for our job, use cronitor exec
if [[ -n "${CRONITOR_ID}" ]]; then
  echo "detected cronitor job with id $CRONITOR_ID"
  $exec cronitor exec --no-stdout "${CRONITOR_ID}" "$@"
elif [[ "${NUM_PROCESSES}" -gt 1 ]]; then
  # See: https://github.com/Yelp/dumb-init#session-behavior
  # Here we use `dumb-init` to start a subshell which will run all
  # the processes and wait for them to exit/finish.
  # `dumb-init` will forward all signals to these processes and
  # `wait -n` will make sure to exit if at least one process exits prematurely.
  # We also set ENTRYPOINT_PROCESS_OFFSET to allow the spawned process to vary the execution
  # depending on which process number it is (for example, the port it will listen on)
  $exec /usr/bin/dumb-init -- /bin/bash -c "
    for i in {0..$((NUM_PROCESSES - 1))}; do
      export ENTRYPOINT_PROCESS_OFFSET=\$i
      $* &
    done
    trap 'wait' SIGINT SIGTERM
    wait -n
  "
else
  $exec "$@"
fi
```

This is the entrypoint.sh we are trying to recreate into s6-rc scripts. Our entrypoint in Dockerfile looks like this `ENTRYPOINT ["/usr/bin/tini", "-g", "--", "/entrypoint.sh"]`

I guess I can replace the ENTRYPOINT with `ENTRYPOINT ["/init", "/entrypoint.sh"]` and then move things little by little away from `/entrypoint.sh` but I was hoping that there is way to completely reimplement `/entrypoint.sh` away into s6-rc script so that we can make do `ENTRYPOINT ["/init"]` which seems to me cleaner and less chaining of scripts.

Let me know if I am overthinking the important of NOT having `/entrypoint.sh` as part of the ENTRYPOINT.

**Comment by skarnet** [comment]
The ENTRYPOINT and CMD have a lot of overlap, as long as `/init` is the first program in your ENTRYPOINT then it doesn't really matter how you organize things. `ENTRYPOINT['/init', 'foo']` followed by `CMD ['bar']` is exactly equivalent to `ENTRYPOINT ['/init']` followed by `CMD ['foo', 'bar']`. So, indeed, don't overthink things.

I would indeed advise you to incrementally dissect your `entrypoint.sh` script and slowly move things to individual services. Currently, your script is mixing things that impact the whole container with things that should only impact a few services, and your setup would benefit from cleaning that up.

**Comment by komapa** [comment]
Appreciate the confirmation. The "complexity" of the entrypoint.sh is what is pushing us to use proper init system as a lot of the things we are hacking away in bash are first class features in s6-rc. Thank you for your time!
