### ISSUE TITLE
Shutdown container during s6-rc startup leads to deadlock

### ISSUE THREAD

**Issue by agners** [just-containers/s6-overlay#566]
We are using s6-overlays for the [OTBR Home Assistant add-on](https://github.com/home-assistant/addons/tree/master/openthread_border_router). The add-on starts several processes/daemons, the main daemon being `otbr-agent`. The finish script of that service tries to shutdown the container in case the service exited with an error, using `/run/s6/basedir/bin/halt`.

However, what I am noticing currently is that the init system ends up in some kind of deadlock. From what I understand the `s6-rc` of the shutdown deadlocks with the `s6-rc` of startup. The ps tree inside the container in the deadlock situation looks as follows:

```
      1 ?        Ss     0:00 /package/admin/s6/command/s6-svscan -d4 -- /run/service
     15 ?        Ss     0:00 /bin/sh -e /run/s6/basedir/scripts/rc.init top
     56 ?        S      0:00  \_ s6-rc -v5 -u -t 0 -- change top
    180 ?        S      0:00      \_ /package/admin/s6-2.12.0.2/command/s6-svlisten1 -U -- /run/s6-rc/servicedirs/otbr-agent /package/admin/s6-2.12.0.2/command/s6-svc -u -- /run/s6-rc/servicedirs/otbr-agent
    181 ?        S      0:00          \_ /package/admin/s6/command/s6-ftrigrd
     16 ?        S      0:00 s6-supervise s6-linux-init-shutdownd
     18 ?        Ss     0:00  \_ /package/admin/s6-linux-init/command/s6-linux-init-shutdownd -d3 -c /run/s6/basedir -g 3000 -C -B
    264 ?        S      0:00      \_ s6-rc -v5 -bda change
     48 ?        S      0:00 s6-supervise otbr-web
     49 ?        S      0:00 s6-supervise s6rc-oneshot-runner
     64 ?        Ss     0:00  \_ /package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --
     50 ?        S      0:00 s6-supervise mdns
     63 ?        Ss     0:08  \_ /usr/sbin/mdnsd -debug
     51 ?        S      0:00 s6-supervise otbr-agent
     52 ?        S      0:00 s6-supervise s6rc-fdholder
```

In this situation, killing 181 or 264 ultimately shuts down the container.

I was considering using `CMD` instead of a service since that seems to be preferred for such a main service. However, it is unclear to me how I can order CMD relative to other s6 services. Some of them need to be started before `CMD`, some after.

There are one-shot services depending on `otbr-agent`, so I am guessing that is why the s6 startup process didn't really conclude at this point.

As a crude work around I currently kill the `s6-rc` process in the `otbr-agent` service finish script (in the error case). This is rather crude but seems to work.

```
otbr-agent[183]: [ERR ]-REST----: InitializeListenFd error bind : Address already in use
otbr-agent[183]: [EMERG]-REST----: FAILED ../../src/rest/rest_web_server.cpp:174 - otbr rest server init error
[11:58:07] WARNING: otbr-agent exited with code 255 (by signal 0).
[11:58:07] INFO: OTBR firewall teardown completed.
s6-rc: warning: received TERM, aborting longrun transitions and exiting asap
s6-rc: warning: unable to start service otbr-agent: command crashed with signal 15
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: bringing selected services down
...
```

Any help or further advice how-to debug/implement this properly is appreciated.

**Comment by skarnet** [comment]
That's right, you cannot call s6-rc from inside s6-rc, else it will deadlock. The boot procedure needs to have completed before you can shutdown.

This is usually solved via readiness notification. Have a way to make sure that s6-rc does not report success for otbr-agent until it is really running successfully. That way, if it fails during the boot phase, s6-rc stops there, and you can make the container automatically shutdown via `ENV S6_BEHAVIOUR_IF_STAGE2_FAILS=2`. If otbr-agent does not support readiness notification, you can use [s6-notifyoncheck](https://skarnet.org/software/s6/s6-notifyoncheck.html) in the otbr-agent run script, with a `data/check` program that polls the service.

Once s6-rc has completed successfully, you can trigger `halt` from otbr-agent's finish script if that's what you want your workflow to be. For safety, you could check that there's no other s6-rc process running: if there's one, if means that the boot procedure hasn't completed yet, and you can simply report permanent failure (have the finish script exit 125), and let the container automatically shut down once its boot procedure ends in failure.

**Comment by agners** [comment]
> This is usually solved via readiness notification. Have a way to make sure that s6-rc does not report success for otbr-agent until it is really running successfully. That way, if it fails during the boot phase, s6-rc stops there, and you can make the container automatically shutdown via `ENV S6_BEHAVIOUR_IF_STAGE2_FAILS=2`. If otbr-agent does not support readiness notification, you can use [s6-notifyoncheck](https://skarnet.org/software/s6/s6-notifyoncheck.html) in the otbr-agent run script, with a `data/check` program that polls the service.

That is actually exactly what we are using here: `ENV S6_BEHAVIOUR_IF_STAGE2_FAILS=2` is set in the base docker file (https://github.com/home-assistant/docker-base/blob/master/debian/Dockerfile#L15) and the `otbr-agent` `run` script uses `s6-notifyoncheck` (see https://github.com/home-assistant/addons/blob/master/openthread_border_router/rootfs/etc/s6-overlay/s6-rc.d/otbr-agent/run#L114). Now in that particular case the otbr-agent presumably errors very early and calls it's finish script, so this is not a notification failure, just the process exiting immediately.

> Once s6-rc has completed successfully, you can trigger halt from otbr-agent's finish script if that's what you want your workflow to be. For safety, you could check that there's no other s6-rc process running: if there's one, if means that the boot procedure hasn't completed yet, and you can simply report permanent failure (have the finish script exit 125), and let the container automatically shut down once its boot procedure ends in failure.

Oh I wasn't aware of finish script exit code 125, that seems what I need here. I'll give this a try!

**Comment by agners** [comment]
Using exit code 125 works perfectly!

```
[23:17:37] WARNING: otbr-agent exited with code 6 (by signal 0).
[23:17:37] INFO: OTBR firewall teardown completed.
s6-svlisten1: fatal: /run/s6-rc/servicedirs/otbr-agent failed permanently or its supervisor died
s6-rc: warning: unable to start service otbr-agent: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: bringing selected services down
```

Thanks for the help. I guess this isn't really a valid issue then.
