### ISSUE TITLE
finish script does not receive system.exit code but 0 

### ISSUE THREAD

**Issue by rschaffa** [just-containers/s6-overlay#567]
Hello 

I have a problem receiving the main application exit code when sending docker stop to my container 

I am using  s6 version v3.1.5.0 

I have replaced the ENTRY_POINT s6 /init script with an exact copy of /init (I need to write the docker run $1 parameter to disk before startup)  

ENTRYPOINT ["/tmp/Myrun"]

the Myrun script looks like this (note that "$@" is missing at the end as it was causing problems

```
#!/bin/sh -e

# This is the first program launched at container start.
# We don't know where our binaries are and we cannot guarantee
# that the default PATH can access them.
# So this script needs to be entirely self-contained until it has
# at least /command, /usr/bin and /bin in its PATH.

echo $1 > /tmp/1.parm.txt

addpath () {
  x="$1"
  IFS=:
  set -- $PATH
  IFS=
  while test "$#" -gt 0 ; do
    if test "$1" = "$x" ; then
      return
    fi
    shift
  done
  PATH="${x}:$PATH"
}

if test -z "$PATH" ; then
  PATH=/bin
fi

addpath /bin
addpath /usr/bin
addpath /command
export PATH

# Now we're good: s6-overlay-suexec is accessible via PATH, as are
# all our binaries.
# Run preinit as root, then run stage0 as the container's user (can be
# root, can be a normal user).

# TODO: Needs to be synchronized with the s6 installation.
exec s6-overlay-suexec \
  ' /package/admin/s6-overlay-3.1.5.0/libexec/preinit' \
  '' \
  /package/admin/s6-overlay-3.1.5.0/libexec/stage0
```
I have implemented a SIGTERM handler in service "mainService" 
"mainService" is declared in s6-overlay/s6-rc.d/user/contents.d/mainService
I have created a finish script in s6-overlay/s6-rc.d/mainService/finish which looks as follows

```
#!/bin/sh

if test "$1" -eq 256 ; then
  e=$((128 + $2))
else
  e="$1"
fi

s6-echo "Application exited with exitcode: $e"

echo "$e" > /run/s6-linux-init-container-results/exitcode
```
when calling docker stop the signal handler gets triggered and exits with system.exit(application_error)

 the finishgh script of mainService gets correctly called but the application_error code is not passed to it - but instead 0
 
 the line s6-echo "Application exited with exitcode: $e" prints as "Application exited with exitcode: 0"

I also noted that there is  an exception in the sigterm_handler of my mainService happening maybe it is the cause that the error is not returned to s6 ? 

```
Exception ignored in: <module 'threading' from '/usr/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
  File "mainService.py", line 48, in sigterm_handler
    sys.exit(system_return_code)

``` 
 When I do not replace /init I am getting the error code returned. 

 
Do you see what could cause the error code not to be returned ?  

Thanks !

**Comment by skarnet** [comment]
We provide no support for modified versions of s6-overlay.

> he Myrun script looks like this (note that "$@" is missing at the end as it was causing problems

I wonder what might be causing your *current* problems. 🤔

**Comment by skarnet** [comment]
The arguments to the ENTRYPOINT are how Docker passes the CMD. The initial command line that is run in the container is the concatenation of ENTRYPOINT and CMD. If you omit the `"$@"`, then it's as if you never used a CMD.

The first parameter of `/init`, that you feel the need to write to the disk, normally is the program that will run as CMD.

To answer your question: the culprit is very probably the run script for your mainService. Could you show it?

**Comment by rschaffa** [comment]
```
#!/command/execlineb -P
with-contenv
python3 /appdir/myService.py 2>&1 | ts '[%Y-%m-%d %H:%M:%.S]

```

**Comment by skarnet** [comment]
- the argument to `docker run` cannot be data, it will be a *command executed by the container*, same as when you specify a CMD in your Dockerfile.
- If you want to pass an argument to the container, put it in an environment variable: `ENV MYPATH=/some/thing` in your Dockerfile. It will be available to services via `with-contenv`.
- Your run script is invalid: it uses shell constructs in an execline script. This is probably why your service crashes. A valid script that does what you want is the following:
```
#!/command/execlineb -S1
fdmove -c 2 1
pipeline -w { ts "[%Y-%m-%d %H:%M:%.S]" }
with-contenv
python3 /appdir/myService.py
```

**Comment by rschaffa** [comment]
the run script works okay - but above script fails maybe I have made a typo ?

pipeline: fatal: unable to spawn ts: No such file or director
Application exited with exitcode: 111

re. "pass an argument to the container, " unfortunately ENV MYPATH=/some/thing changes on every docker run invocation

**Comment by skarnet** [comment]
- Your `ts` program, whatever it is, needs to be in the service's PATH, i.e. `/usr/bin` or `/bin`. If not, write the whole path to it.
- Ah, so you're trying to pass variable data to `docker run` without changing the Dockerfile. I see. That's interesting, and probably doable, but I'll have to think a bit more about it to find a clean solution.

**Comment by rschaffa** [comment]
I have some update - I was able to go back to ENTRYPOINT ["/init"] - so it is default - I am able to pass the parameter to docker run --e  MYPATH=/some/thing

but the behaviour is the same - the finish script does not catch the system.exit(120)  - its 0 instead of 120 
it writes Application exited with exitcode: 0

there is though this exception thrown in the signal handler

```
Exception ignored in: <module 'threading' from '/usr/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
  File "mainService.py", line 48, in sigterm_handler
    sys.exit(system_return_code)

```

**Comment by rschaffa** [comment]
this is the exact code of the run script

`#!/command/execlineb -P
with-contenv
python3 /appdir/myService.py 2>&1 | ts '[%Y-%m-%d %H:%M:%.S]
`

**Comment by skarnet** [comment]
As I mentioned earlier, this run script is *not* working. It will run `python3` on `/appdir/myService.py`, yes, but with unwanted additional arguments, and it will not do what you expect it to do.

Change it to the run script I posted earlier, with a correct path to your `ts` utility, whatever it is.

**Comment by rschaffa** [comment]
I have changed the script according to your recommendation but still am not able to receive the return code from system.exit in the service's finish script - $1 is 0 and $2 is  0 

below is my finish script

`#!/bin/sh

s6-echo "A - dollar 1: $1"
s6-echo "A - dollar 2: $2"

if test "$1" -eq 256 ; then
  s6-echo "B - dollar 1: $1"
  s6-echo "B - dollar 2: $2"
  e=$((128 + $2))
else
  e="$1"
fi

s6-echo "C - dollar 1: $1"
s6-echo "Application exited with exitcode: $e"

echo "$e" > /run/s6-linux-init-container-results/exitcode`

**Comment by skarnet** [comment]
> The container is stopped right now by calling in the service a 'kill 1' at the end when the container should be stopped.

Where are you doing this? Since you refuse to post your run script, there's not much I can do to help.

> It would also be acceptable if my service would shutdown the container when it finished and returns any "application return code" or 0

You could run your service as a CMD. That's what it's for.

**Comment by rschaffa** [comment]
do you mean what is inside the run folder ? or the service (myService.py) ?

**Comment by skarnet** [comment]
I mean the script that is named `run`.

Note that `kill 1` is not a supported way of stopping the container. It is likely that the best way of accomplishing what you want is running your service as the CMD.

**Comment by skarnet** [comment]
- Okay, so there *is* an issue with the exit code of your run script, but the run script is correct. It appears that `python3` is exiting 0 despite you instructing it to exit with another code. Can you instrument python to see what's happening?
- Try running `/run/s6/basedir/bin/halt` instead of `kill 1`.

**Comment by rschaffa** [comment]
sigterm handler: 

```
def sigterm_handler(signal, frame):
    try:
        global system_return_code
        os.system('echo %r /tmp/system_return_code.txt' % str (system_return_code))
        # context.launch_cmd('echo {system_return_code} > /tmp/return_code.txt', check_return_code=False)
        # save the state here or do whatever you want
        print('received SIGTERM now exiting with system_return_code = ' + str(system_return_code))
        sys.exit(system_return_code)
        # sys.exit(system_return_code)
    except Exception as e:
        print('Exception occurred in sigterm_handler', e)    
```

finish script of myService

```
#!/bin/sh

s6-echo "A - dollar 1: $1"
s6-echo "A - dollar 2: $2"

if test "$1" -eq 256 ; then
  s6-echo "B - dollar 1: $1"
  s6-echo "B - dollar 2: $2"
  e=$((128 + $2))
else
  e="$1"
fi

s6-echo "C - dollar 1: $1"
s6-echo "Application exited with exitcode: $e"

echo "$e" > /run/s6-linux-init-container-results/exitcode

```

log file of container 

```
s6-rc: info: service myService: stopping
[2024-02-26 17:51:33.392317] 160 /tmp/system_return_code.txt
Exception ignored in: <module 'threading' from '/usr/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
  File "/appdir/myService.py", line 21, in sigterm_handler
    sys.exit(system_return_code)
SystemExit: 160
[2024-02-26 17:51:33.392903] received SIGTERM now exiting with system_return_code = 160
[2024-02-26 17:51:33.392930] My application is ending!
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
A - dollar 1: 0
A - dollar 2: 0
C - dollar 1: 0
Application exited with exitcode: 0
s6-rc: info: service myService successfully stopped

```

**Comment by skarnet** [comment]
Got it.

What is happening is that your finish script triggers a shutdown, but by the time the shutdown procedure comes to your service, the supervisor has already restarted it, and the shutdown procedure just sends a SIGTERM to your service, which makes it exit 0, overwriting your previous `exitcode` file.

The best solution would be to run your service as CMD, but if you cannot do that, then the solution is
to prevent it from restarting after you've modified `exitcode`.
At the end of your finish script, add: `s6-svc -O .` and that should solve your problem.

**Comment by rschaffa** [comment]
Thanks. Unfortunately after adding s6-svc -O . I still get the same results :(

```
#!/bin/sh

s6-echo "A - dollar 1: $1"
s6-echo "A - dollar 2: $2"

if test "$1" -eq 256 ; then
  s6-echo "B - dollar 1: $1"
  s6-echo "B - dollar 2: $2"
  e=$((128 + $2))
else
  e="$1"
fi

s6-echo "C - dollar 1: $1"
s6-echo "Application exited with exitcode: $e"

echo "$e" > /run/s6-linux-init-container-results/exitcode

s6-svc -0 .
```

when I try to run s6-svc -O . inside the finish scripts folder I get 

s6-svc: fatal: unable to control .: supervisor not listening

**Comment by skarnet** [comment]
What do you mean, "inside the finish script's folder"? The command should run in the service directory, just like the service. If it runs in the service directory, it will work.

**Comment by rschaffa** [comment]
correction :
running "s6-svc -O ." inside /run/service/myService folder works

but there is no change to the behaviour the exit code is still not correct (still 0)

**Comment by skarnet** [comment]
Are you running a CMD? Because if you do, the exit code of the CMD will overwrite what's stored in `/run/s6-linux-init-container-results/exitcode`.

If you're not running a CMD, please post your newest logs, so I can see what exactly is happening when the container shuts down.

**Comment by rschaffa** [comment]
I am not running a CMD. 

```
s6-rc: info: service myService: stopping
[2024-02-27 09:23:10.981835] 160 /tmp/system_return_code.txt
Exception ignored in: <module 'threading' from '/usr/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
  File "/appdir/myService.py", line 51, in sigterm_handler
    sys.exit(system_return_code)
SystemExit: 160
[2024-02-27 09:23:10.982440] received SIGTERM now exiting with system_return_code = 160
[2024-02-27 09:23:10.982471] My application is ending!
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
A - dollar 1: 0
A - dollar 2: 0
C - dollar 1: 0
Application exited with exitcode: 0
s6-rc: info: service myService successfully stopped

```

**Comment by rschaffa** [comment]
replacing sys.exit(system_return_code) with os._exit(system_return_code) solved our problem!

**Comment by skarnet** [comment]
Yes, I would still recommend to use `/run/s6/basedir/bin/halt` instead of `kill 1` wherever you would use it.

What's happening is that, for some reason, with `sys.exit` your python process does not exit until the whole shutdown procedure is done, so your finish script runs very late and the `exitcode` file has been overwritten. `os.system` apparently does the right thing and exits right away, so the finish script runs *before* the shutdown procedure. I don't know python, this looks very weird, and I'm glad you found a solution that works for you. :-)

**Comment by rschaffa** [comment]
I am very grateful for your help!! thanks for spending your time!

**Comment by rschaffa** [comment]
I am sorry to be picking up this conversation again. I have been experiencing a new behaviour and I dont know where to start...


the finish script is being called with 

1. parameter 256

2. parameter 15

the docker then ends with error code 143 (128+15) which seems to be a GOOD code 

for some reason the sigterm handler of the service with the finish script is not being invoked which is odd 

from what I have researched 143 seems to be SIGTERM (docker stop) 

the code for finish and signal handlers (which is part of this discussion) has not changed 


we are stopping s6 by issuing os.system('/run/s6/basedir/bin/halt')

I have no implemented running "s6-svc -O ." as the last command inside the finish script - could this make a difference ?

**Comment by skarnet** [comment]
Your problem sounds python-related, honestly. Are you sure you're *actually* trapping SIGTERM?

If the finish script is run with 256 15, it means that the run script, i.e. your Python application, has been killed by SIGTERM. That normally would not happen if you have a SIGTERM handler that ends with a call to `os._exit()`. And the fact that your SIGTERM handler appears to not be called makes me think that you are *declaring* a signal handling function, but not *setting* it as an actual handler for SIGTERM.

**Comment by rschaffa** [comment]
Interestingly this situation only happens when the application did not finish with an application exit code

**Comment by skarnet** [comment]
Yes, because you're running `docker stop`, which sends a SIGTERM to your application, but apparently your application is *not* trapping it.

Sorry, but this is out of scope for s6-overlay.

**Comment by skarnet** [comment]
As I previously said: this is something that happens in your Python code, in your service, and is out of scope for s6-overlay. We cannot provide free support for application-specific issues.
