### ISSUE TITLE
Cannot make Log to stdout work with s6-overlay 3.1.6.2 (no bug, just looking for some guidance/help).

### ISSUE THREAD

**Issue by xirixiz** [just-containers/s6-overlay#568]
Hi! First of all, thanks for this nice solution. I've been using v2 happily for years already!

This brings me directly to the second part, switching to s6-overlay v3.x.x.x. 
Recently I've tried to make a conversion from v2 to v3. Everything seems to workout nicely, but I see absolutely 0 stdout when using ```docker logs -f` <container>``. 

What I'd like to accomplish to have the output of the echo's etc, visible in stdout when starting the image as a container.

Link to project with Dockerfile: 
https://github.com/xirixiz/dsmr-reader-docker/tree/pre_release

Linkt to one of the things I'd like to see the output from:
https://github.com/xirixiz/dsmr-reader-docker/tree/pre_release/rootfs/etc/s6-overlay/s6-rc.d/init-docker-entrypoint

I've tried the following:
https://github.com/just-containers/s6-overlay/issues/479
https://github.com/just-containers/s6-overlay/issues/442

And I've followed the instructions regarding logging (relates to issue 479), 
Also played arround with ```exec 2>&1``` but unfortunatly also without any result.

I hope someone can point me in the right direction, I'm sure that I'm overseeing something easy.

Output example currently:
```
exec docker run --rm --network host dsmr_test_image
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
```

Inside the container the services are started as expected, so it does seem to run properly.

Thanks!

**Comment by skarnet** [comment]
Logs that you catch and log to the container, by definition, will not fall through to the container's stdout.

If you want the logs to exit the container, you'll have to *not* log them in the container.

Remove the loggers you installed, and use `ENV S6_LOGGING=0`. Your logs will go to the container's stdout.

**Comment by xirixiz** [comment]
Thanks for the info. The logs of the running services saving to a logfile I understand that they do not log to stdout.

That is why I use this for nginx for example in the Dockerfile:
```
ln -sf /dev/stdout /var/log/nginx/access.log
ln -sf /dev/stderr /var/log/nginx/error.log
  ```

I`m mainly interested in the output like in this script for example: https://github.com/xirixiz/dsmr-reader-docker/blob/pre_release/rootfs/etc/s6-overlay/s6-rc.d/svc-dsmr-datalogger/run#L5-L7

I've tried ```ENV S6_LOGGING=0``` but I cannot make it work somehow.
Really appreciate your help. I`ll also dive into the docs a bit more to (hopefully) get a better understanding and make it work.

**Comment by xirixiz** [comment]
Started from scratch with a clean structure, and now it seems to work.
It seems something was wrong with the structure of ```/etc/s6-overlay/s6-rc/d```
My asusmption is that the ```user/contens.d ``` was misplaced.

Closing the issue, nothing fancy was required for ```ENV S6_LOGGING=0``` etc.
