### ISSUE TITLE
unable to restart services that use bash for run script (unless using exec)

### ISSUE THREAD

**Issue by fredlllll** [just-containers/s6-overlay#572]
i use bash for my run files instead of execlineb cause im more familiar with it

i noticed that this made it impossible for me to restart services. what happened instead was that the bash process got killed, but not the child python process running my service. so the service was now running twice.

adding an exec before python fixes this, but it is not documented anywhere that child processes dont get killed on a restart or stop request for any service. i had to search quite a while till i found that out.

minimal example here (you can change base image to something smaller, i just used what we used for the image this was happening on)
[s6example.zip](https://github.com/just-containers/s6-overlay/files/14609016/s6example.zip)

and what happens if you just try to restart the service
![s6 restart broken](https://github.com/just-containers/s6-overlay/assets/13737455/cb47c66f-54c6-4b30-aef1-eb3d396a5a55)

as you see there are now 2 instances printing their pid after entering the restart command. with exec it works as expected. would be nice if this was documented more clearly, or configurable if child processes should be receiving a sigterm/sigkill too, like in systemd (killmode)

**Comment by skarnet** [comment]
Yes, the supervisor only controls its direct child, so if your run script is a shell, it needs to exec into the program you want to send signals to.

This is well-known by people who use supervision suites, but you're right that it's probably not explicit enough. I will add a note about it in the documentation, thanks for the report.
