### ISSUE TITLE
"not found" when converting from v2 to v3

### ISSUE THREAD

**Issue by MrTyton** [just-containers/s6-overlay#575]
[Link to Repo](https://github.com/MrTyton/AutomatedFanfic)
[Dockerfile](https://github.com/MrTyton/AutomatedFanfic/blob/master/Dockerfile)
[/etc](https://github.com/MrTyton/AutomatedFanfic/tree/master/root/etc)

Hi -

So my dockerfile broke because the V2 packages had vanished, which was fine because after looking I went to update to v3. After getting the dockerfile to actually build and run, it doesn't actually work anymore. I'm currently getting the errors

```bash
04/01/2024 07:28:52 PM s6-rc: info: service s6rc-oneshot-runner: starting
04/01/2024 07:28:52 PM s6-rc: info: service s6rc-oneshot-runner successfully started
04/01/2024 07:28:52 PM s6-rc: info: service fix-attrs: starting
04/01/2024 07:28:52 PM s6-rc: info: service fix-attrs successfully started
04/01/2024 07:28:52 PM s6-rc: info: service legacy-cont-init: starting
04/01/2024 07:28:52 PM cont-init: info: running /etc/cont-init.d/05-default-confs
04/01/2024 07:28:52 PM /package/admin/s6-overlay-3.1.6.2/etc/s6-rc/scripts/cont-init: 20: /etc/cont-init.d/05-default-confs: not found
04/01/2024 07:28:52 PM cont-init: info: /etc/cont-init.d/05-default-confs exited 127
04/01/2024 07:28:52 PM cont-init: info: running /etc/cont-init.d/90-user-permissions
04/01/2024 07:28:52 PM /package/admin/s6-overlay-3.1.6.2/etc/s6-rc/scripts/cont-init: 20: /etc/cont-init.d/90-user-permissions: not found
04/01/2024 07:28:52 PM cont-init: info: /etc/cont-init.d/90-user-permissions exited 127
04/01/2024 07:28:52 PM cont-init: info: running /etc/cont-init.d/99-init.d-finish
04/01/2024 07:28:52 PM /package/admin/s6-overlay-3.1.6.2/etc/s6-rc/scripts/cont-init: 20: /etc/cont-init.d/99-init.d-finish: not found
04/01/2024 07:28:52 PM cont-init: info: /etc/cont-init.d/99-init.d-finish exited 127
04/01/2024 07:28:52 PM s6-rc: info: service legacy-cont-init successfully started
04/01/2024 07:28:52 PM s6-rc: info: service legacy-services: starting
04/01/2024 07:28:52 PM services-up: info: copying legacy longrun ffdl (no readiness notification)
04/01/2024 07:28:52 PM s6-supervise ffdl: warning: unable to spawn ./run (waiting 60 seconds): No such file or directory
04/01/2024 07:28:52 PM s6-rc: info: service legacy-services successfully started
04/01/2024 07:29:52 PM s6-supervise ffdl: warning: unable to spawn ./run (waiting 60 seconds): No such file or directory
```

This is after I had to set /etc/... to chmod +777 otherwise it apparently didn't have permission to run.

I'm just kind of very confused, because if I open a docker terminal, the files are all there... and I haven't been able to find out what is going on. Any help would be appreciated.

Thanks.

**Comment by skarnet** [comment]
Additionally to the two main tarballs, you need to install the `s6-overlay-symlinks-noarch.tar.xz` one if you have scripts with a `#!/usr/bin/with-contenv` shebang, and the `s6-overlay-symlinks-arch.tar.xz` one if you have old scripts with a `#!/usr/bin/execlineb` shebang.

Convert these shebangs to `#!/command/with-contenv` and `#!/command/execlineb` respectively, and then you can do away with the symlinks tarballs.

**Comment by MrTyton** [comment]
Cool. Thanks!!
