### ISSUE TITLE
operation timed out

### ISSUE THREAD

**Issue by jurgenweber** [just-containers/s6-overlay#577]
# Please provide a small Dockerfile that demonstrates your issue.

Using this image https://github.com/blakeblackshear/frigate/tree/dev/docker I added a cont-init to do some additional things in the pod. When I do this, I get the following error:

```
frigate-7856dbc88-glfrn frigate s6-rc: fatal: timed out
frigate-7856dbc88-glfrn frigate s6-sudoc: fatal: unable to get exit status from server: Operation timed out
```

From what I have read, it should just wait. I have tried things like

S6_CMD_WAIT_FOR_SERVICES_MAXTIME

without help, any ideas?

note, the additional things which seem to work find when done manually are:

```
     apt-get update
     apt-get install -y apt-utils
     apt-get install -y usbip

     usbip list -r 192.168.1.95
     usbip attach -r 192.168.1.95 -b 1-2.3
     usbip port
  ```

**Comment by skarnet** [comment]
This is definitely a `S6_CMD_WAIT_FOR_SERVICES_MAXTIME` issue. Try setting it to 0 to disable it.

The next version of s6-overlay with disable this timeout by default, because it causes more issues than it solves.

**Comment by jurgenweber** [comment]
just whack that in the env of the container?

**Comment by jurgenweber** [comment]
Yep, that worked a treat. Thank you so much!
