### ISSUE TITLE
[howto] pass envs vars to service process

### ISSUE THREAD

**Issue by mcgr0g** [just-containers/s6-overlay#588]
For [build](https://gitlab.com/mcgr0g/mopidy-ams/-/blob/43ed1e01a5b3dcb7a6ec9d803beb97d0192e69c8/Dockerfile) one python app I used linuxserver alpine image.
The [init script](https://gitlab.com/mcgr0g/mopidy-ams/-/blob/43ed1e01a5b3dcb7a6ec9d803beb97d0192e69c8/root/etc/s6-overlay/s6-rc.d/init-mopidy-config/run) contains custom env for one package.
```
echo "/config/mopidy/mopidy.conf" > /var/run/s6/container_environment/IRIS_CONFIG_LOCATION
```
The [service script](https://gitlab.com/mcgr0g/mopidy-ams/-/blob/43ed1e01a5b3dcb7a6ec9d803beb97d0192e69c8/root/etc/s6-overlay/s6-rc.d/svc-mopidy/run) has `#!/usr/bin/with-contenv bash` for access to envs. But it works strange.
When container run, there is expected echo:
```
[custom-init] No custom files found, skipping...
IRIS_CONFIG_LOCATION=/config/mopidy/mopidy.conf
XDG_CONFIG_DIR=/config
crond[159]: crond (busybox 1.36.1) started, log level 5
INFO     2024-07-24 16:22:09,090 [158:MainThread] mopidy.__main__
  Starting Mopidy 3.4.2
```
But app (started by `exec s6-setuidgid abc /usr/bin/mopidy`) not see this env. If attach to container shell there is filled file `/var/run/s6/container_environment/IRIS_CONFIG_LOCATION`, but env `IRIS_CONFIG_LOCATION` is not setted and app can't use it. Full list of environments:
```
root@e8581a38e5e4:/# echo IRIS_CONFIG_LOCATION=$IRIS_CONFIG_LOCATION
IRIS_CONFIG_LOCATION=
root@e8581a38e5e4:/# printenv
PUID=1002
HOSTNAME=e8581a38e5e4
S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0
PWD=/
APP_DATA=/app_data
HOME=/root
PGID=1002
VIRTUAL_ENV=/lsiopy
S6_VERBOSITY=1
S6_STAGE2_HOOK=/docker-mods
TERM=xterm
SHLVL=1
PS1=$(whoami)@$(hostname):$(pwd)\$ 
PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
USR_DATA=/data
CONFIG=/config
_=/bin/printenv
```
In service script I tried to use in `exec line `s6-env XDG_CONFIG_DIR=$XDG_CONFIG_DIR`, but without success.

As workaround I can set ENV in dockerfile, but I think this is a compromise solution. Setting such variables relative to the initialization stage of the container, most of lsio images wreitten in this strategy.
Also, for building .aarch64, you often need to copy the entire .x64 dockerfile. And the less copy-paste, the less likely to be an wrong.

**Comment by skarnet** [comment]
The container environment holds the variables that are inherited from the container manager, essentially the ones you define in your Dockerfile. It is *not* meant to hold your own variables. Do not tamper with it.

If you want to define some environment in a oneshot script, then source it from your services or your CMD, then you can make your own place to store the variables:

```sh
mkdir /run/myenv
echo /config/mopidy/mopidy.conf > /run/myenv/IRIS_CONFIG_LOCATION
```

And instead of running `s6-setuidgid abc /usr/bin/mopidy`, run `s6-setuidgid abc s6-envdir /run/myenv /usr/bin/mopidy`. That should work.

**Comment by mcgr0g** [comment]
> It is not meant to hold your own variables. Do not tamper with it.

Hm, I used [recommendation from old issue](https://github.com/just-containers/s6-overlay/issues/46#issuecomment-97708601). Should it only be used to pass variables between s6-rc.d scripts? 

> run s6-setuidgid abc s6-envdir /run/myenv /usr/bin/mopidy. That should work.

Unfortunately recommend [init](https://gitlab.com/mcgr0g/mopidy-ams/-/blob/6378e9075d8aa295a4c1e9e848aededd067190be/root/etc/s6-overlay/s6-rc.d/init-mopidy-config/run#L7) and [service](https://gitlab.com/mcgr0g/mopidy-ams/-/blob/43ed1e01a5b3dcb7a6ec9d803beb97d0192e69c8/root/etc/s6-overlay/s6-rc.d/svc-mopidy/run) script not worked: there is nothing about IRIS_CONFIG_LOCATION in printenv. And app logs contains:
```
INFO     2024-07-25 20:51:39,943 [159:Thread-18] mopidy_iris.system
  Running system action 'local_scan'
INFO     2024-07-25 20:51:40,575 [542:MainThread] mopidy.__main__
  Starting Mopidy 3.4.2
INFO     2024-07-25 20:51:40,942 [542:MainThread] mopidy.config
  Loading config from builtin defaults
INFO     2024-07-25 20:51:40,943 [542:MainThread] mopidy.config
  Loading config from command line options
INFO     2024-07-25 20:51:40,946 [542:MainThread] mopidy.config
  Loading config from builtin defaults
INFO     2024-07-25 20:51:40,947 [542:MainThread] mopidy.config
  Loading config from command line options
INFO     2024-07-25 20:51:40,950 [542:MainThread] mopidy.internal.path
  Creating file file:///config/mopidy.conf
INFO     2024-07-25 20:51:40,950 [542:MainThread] mopidy.__main__
  Initialized file:///config/mopidy.conf with default config
```
It's means that variable was not set. 
Any Ideas?

**Comment by skarnet** [comment]
> Hm, I used [recommendation from old issue](https://github.com/just-containers/s6-overlay/issues/46#issuecomment-97708601). Should it only be used to pass variables between s6-rc.d scripts?

 No, this was for a very old version of s6-overlay, do not do the same for the current version.

> Unfortunately recommend [init](https://gitlab.com/mcgr0g/mopidy-ams/-/blob/6378e9075d8aa295a4c1e9e848aededd067190be/root/etc/s6-overlay/s6-rc.d/init-mopidy-config/run#L44) and [service](https://gitlab.com/mcgr0g/mopidy-ams/-/blob/43ed1e01a5b3dcb7a6ec9d803beb97d0192e69c8/root/etc/s6-overlay/s6-rc.d/svc-mopidy/run) script not worked: there is nothing about IRIS_CONFIG_LOCATION in printenv.

You are not reading the environment in `/run/myenv`. Your svc-mopidy/run script needs to have `s6-envdir /run/myenv` in the command line leading to the execution of `/usr/bin/mopidy`.

Also, there is no binary called `s6-env`, so I have no idea how your service is working in the first place.

**Comment by mcgr0g** [comment]
> You are not reading the environment in /run/myenv

My bad. In previous post was incorrect link. It was too long day. Now link fixed.
Also In documentation was flag `-i : strict. If dir does not exist, exit 111 with an error message. This is the default.`.
And running with
```
exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 6680" \
    s6-setuidgid abc \
    s6-envdir -i /run/myenv \
    /usr/bin/mopidy --config /config/mopidy/mopidy.conf 2>&1
```
produces no errors. There was usual work yesterday, but without propagated envs.

**Comment by skarnet** [comment]
So... is your setup working now, or is there still something going wrong?

**Comment by mcgr0g** [comment]
There is no custom envs, such as IRIS_CONFIG_LOCATION.

By the way I found similar problem at https://serverfault.com/questions/801658/s6-supervisor-variable-set-with-s6-envdir-cant-be-used. But start a subshell in this way
```
exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 6680" \
    s6-setuidgid abc \
    s6-envdir /run/myenv \
    sh -c '/usr/bin/mopidy --config /config/mopidy/mopidy.conf'
```
still not propagate custom envs.

**Comment by skarnet** [comment]
The longrun service that starts mopidy needs to have a dependency to the service that sets the IRIS_CONFIG_LOCATION variable, to make sure it starts *after* the variable has been written in the environment.

Also, why are you invoking a second shell to start mopidy? You don't need the `sh -c` stuff, that will only muddy things up.

**Comment by mcgr0g** [comment]
> The longrun service that starts mopidy needs to have a dependency to the service that sets the IRIS_CONFIG_LOCATION variable

Yes, this is achieved using the configuration tree with specifying dependencies
```
.
├── init-config-end
│   └── dependencies.d
│       └── init-mopidy-config
├── init-mopidy-config
│   ├── dependencies.d
│   │   └── init-config
│   ├── run
│   ├── type
│   └── up
├── svc-mopidy
│   ├── dependencies.d
│   │   └── init-services
│   ├── notification-fd
│   ├── run
│   └── type
└── user
    └── contents.d
        ├── init-mopidy-config
        └── svc-mopidy
```
In addition, environment variables from init-mopidy-config/run worked in svc-mopidy/run.
For some unknown reason, svc-mopidy/run does not pass through to exec.

> Also, why are you invoking a second shell to start mopidy?

This was just an attempt to test other people's workarounds. I myself find such nesting of calls - strange.

**Comment by skarnet** [comment]
Your svc-mopidy depends on something called `init-services`, not `init-mopidy-config`. What is `init-services` and where is it defined? I'm done playing guessing games: you are not giving full information, only bits and pieces, and it makes it difficult to help you, especially if the links you post have inaccurate data.

Is your real, full setup available somewhere so I can have a look?
If not, that's it for me.

**Comment by mcgr0g** [comment]
> What is init-services and where is it defined?

As I said before, I used linuxserver alpine image. The guys made a lot of modifications to the alpine image for different options. For example, [linuxserver/docker-mod](https://github.com/linuxserver/docker-mods?tab=readme-ov-file#using-a-docker-mod) 
By this reason they implemented a lot of init scripts and service scripts into their base image. And here is the one you asked 
https://github.com/linuxserver/docker-baseimage-alpine/blob/master/root/etc/s6-overlay/s6-rc.d/init-services
Yes, they are inherited implicitly and are not visible in the repo for building app.

> Is your real, full setup available somewhere so I can have a look?

Of course, I use a repository for docker build. Similar to how linuxserver do this.
There is branch https://gitlab.com/mcgr0g/mopidy-ams/-/tree/s6-overlay.

> I'm done playing guessing games: you are not giving full information, only bits and pieces, and it makes it difficult to help you

I agree, it must not be easy. That's why I used the "s6-overlay" git branch at the beginning.
Thanks for your time and comments about the envdir utility and outdated practices.
If you don't have more time, I'll try my 2 another ideas and close the issue.

At the moment it seems to me that the problem is not in the run script, but in the complex chain of calls:
execline → mopidy (main py process) → py sub process → [bash](https://github.com/jaedb/Iris/blob/master/mopidy_iris/system.sh#L34) → another modipy process → another py sub process.

It might be better to change the location of the configs than to figure out if the environment variables are available "another py sub process"

**Comment by skarnet** [comment]
From what I understand, linuxserver's `init-services` only initializes their custom stuff, not the services you add to s6-rc yourself. So `svc-mopidy` would *still* need to depend on `init-mopidy-config` in addition to `init-services`. Please try it with the added dependency.

**Comment by mcgr0g** [comment]
Works the same way with `svc-mopidy/dependencies.d/init-mopidy-config` and without it. There are built dependencies through configs in the linuxserver's stuff, so an explicit dependency was not needed in this particular case.

By the way using "ENV IRIS_CONFIG_LOCATION=/config/mopidy/mopidy.conf" in the Dockerfile also did not help. Despite the fact that the variable is visible in "printenv", apparently it is not available in the final sub-process.
It is unlikely that anything else can be done here. I am inclined to close this issue.
Do you have any more ideas?

**Comment by skarnet** [comment]
Since you converted the `svc-mopidy` to execline, try `foreground { s6-printenv }` right before the `/usr/bin/mopidy` invocation. You'll see if the variable is defined at the time of the invocation.

Don't use `-fn` as options to s6-envdir. I omitted it above for a reason.

Apart from that, I have no more ideas.

**Comment by mcgr0g** [comment]
Yes, the environment variables are set and output to the console.
But the final subprocess still doesn't see them. I'll adapt to the default configs of the iris package.

Thanks for the recommendations, @skarnet . This was very helpful.

For googles found this tread: I'm going to keep the git branch we discussed here for a half year. If it's gone, here are some details.

last tested service script
```
#!/command/execlineb -P

# with-contenv
s6-envdir /run/myenv

# Redirect stderr to stdout.
fdmove -c 2 1

# Notify service manager when app is up
s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 6680"

# Set environment
s6-setuidgid abc

# show env env variables
foreground { s6-printenv }

# run app
/usr/bin/mopidy --config /config/mopidy/mopidy.conf
```
and last tested config script (not full)
```
#!/usr/bin/with-contenv bash
# shellcheck shell=bash

## main envs
mkdir -p /run/myenv
echo "/config"                    > /run/myenv/XDG_CONFIG_DIR
echo "/config/mopidy/mopidy.conf" > /run/myenv/IRIS_CONFIG_LOCATION
echo "false"                      > /run/myenv/IRIS_USE_SUDO
## make our default folder
mkdir -p /config/mopidy
# IRIS has another default config location.
# copy default config
if [[ ! -f /config/mopidy/mopidy.conf ]]; then
  cp /defaults/mopidy.conf /config/mopidy/mopidy.conf
fi
lsiown -R abc:abc /config
```

Good luck.
