### ISSUE TITLE
Services don't wait until cont-init.d scripts is finished

### ISSUE THREAD

**Issue by altvnk** [just-containers/s6-overlay#59]
I run into issue when services falling into errors because of empty env variables, supervisor try's to restart them, but no success, env is not loading during attempts.
Env is exporting into  `/var/run/s6/container_environment/` via `cont-init.d` script. Shell started via `CMD` is getting all variables loaded. 
So how can i ensure to not start services until cont-init.d script is done his work?

**Comment by glerchundi** [comment]
hi @altvnk, if every script you're running is executed in the foreground, no service will be started until those have been completed (succeded or failed). Can you provide us a non-working example?

These are the steps followed:
* fix attributes (permissions and ownerships)
* execute cont-init.d
* start services

Take a look to the [stage2](https://github.com/just-containers/s6-overlay/blob/master/builder/overlay-rootfs/etc/s6/init/init-stage2) which implements the sequential behaviour of this stage, it's written in execline but it's fairly easy to read.

**Comment by altvnk** [comment]
Thank you for clarification about startup sequence.
Anyway the most problem is that PATH variable does not contain file system path to my binary.
For a first i'm exporting env vars via cont-init.d script like this:
```
#!/bin/sh
set -e
BINDIR=/opt/mybin
VAR1=bla
VAR2=bla
PATH=$PATH:${BINDIR}
printf ${PATH} > /var/run/s6/container_environment/PATH
```
Service script is:
```
#!/usr/bin/with-contenv sh
exec 2>&1
mybinname --option1 ${VAR1} --option1 ${VAR2}
```
As result service run fails with `mybinname: command non found`. But when i run container interactively with shell, PATH is set correctly and binary is reachable by name.

**Comment by altvnk** [comment]
Real example you can see in my repo [link](https://github.com/altvnk/kubernetes-mesos-docker). There is heavy WIP, but now i'm stuck with service execution. The next step is service dependencies.

**Comment by glerchundi** [comment]
@altvnk,

1. Use our latest overlay, a lot of bugfixes were solved since 1.9.0.0, also remove -builder and -portable: https://github.com/just-containers/s6-overlay/releases/download/v1.10.0.3/s6-overlay-amd64.tar.gz
2. I think the problem is that your script is not finishing correctly (exited 1?), because you're using `set -e` at the very beginning and probably `if [ ! -f ..]` is stopping your script execution.
3. Although it is perfectly possible, I would not recommend to create cont-envs in runtime, probably I would create those env's inside your `Dockerfile` and then using another init script create your required config file dynamically. But of course, that's up to you :-)

**Comment by altvnk** [comment]
Thanks for pointing in the right direction, i will investigate the script.
About 3 - i need to set variables inside container just to be able modify them on container run.
Well, anyway many thanks!

**Comment by glerchundi** [comment]
You're welcome,

Just to clarify my comments, you can do this:

`Dockerfile`:
```
FROM busybox
ENV K8M_BIN /opt/k8s
ENV ETCD_URL etcd.service.consul
...
```

With this you're not modifying `/var/run/s6/container_environments` directly, and you're also able to modify them in runtime through `docker run -ti -e ETCD_URL="whatever"`

**Comment by altvnk** [comment]
That's the good point! I just was thinking how to hide all of default inside keep things clean, but run into other problems, so yes it's probably the best way to solve my issue ))

**Comment by altvnk** [comment]
One more question - i have simple script in cont-init.d
```
#!/bin/sh
cat > ${K8SM_HOME}/mesos-cloud.conf <<EOL
[mesos-cloud]
    mesos-master        = ${MESOS_HOST}:${MESOS_PORT}
    http-client-timeout = 5s
    state-cache-ttl     = 20s
EOL
```
But it not produces output file. When i run it under shell in interactive mode - it does. Does it possible that cont-intit.d scripts cannot see environment variables? Or maybe `#!/usr/bin/with-contenv sh` must be used here?

**Comment by glerchundi** [comment]
You've already answered yourself. Overlay doesn't make cont. envs in the scripts by default, as you pointed, you must use `#!/usr/bin/with-contenv sh` in order to make them available.

**Comment by altvnk** [comment]
Many thank again! You make my day! ;)
