### ISSUE TITLE
How to skip startup of a specific service for s6-rc.d?

### ISSUE THREAD

**Issue by rophy** [just-containers/s6-overlay#590]
Same question as #267, but the previous issue seems to be using old `cont-init.d` structure.

Version: 3.2.0.0

I've tried these:

(a) a starter script in `/etc/cont-init.d` conditionally touches `/etc/s6-overlay/s6-rc.d/user/contents.d/my-conditional-service`

(b) a starter script in `/etc/s6-overlay/s6-rc.d/init` touches `/etc/s6-overlay/s6-rc.d/user/contents.d/my-conditional-service`, which `my-conditional-service` depends on.

(c) a starter script in `/etc/s6-overlay/s6-rc.d/init` touches `/etc/s6-overlay/s6-rc.d/user2/contents.d/my-conditional-service`.

All these did not work. It seems the check of `contents.d/my-conditional-service` existence is done before all these stages.

**Comment by skarnet** [comment]
That's on purpose. The s6-rc set of services is static - the point is that once you boot on a configuration, you can always boot on the same configuration again. Conditional services introduce external factors and can lead your container to fail.

If you want to change the service set at container run-time, you'll need to do it in a `S6_STAGE2_HOOK` script. That will run earlier than `/etc/cont-init.d`.

**Comment by rophy** [comment]
That's reasonable. Let me try and feedback here for those that searched for the same.

**Comment by rophy** [comment]
works good, thanks!

https://github.com/rophy/git-cache-server/commit/deb9db02ceb9d962006e4497c3edbc97f3369ecd

**Comment by skarnet** [comment]
Glad you made it work!
