### ISSUE TITLE
Question about s6-log utility

### ISSUE THREAD

**Issue by shieldz80** [just-containers/s6-overlay#594]
Hi,

I have a logger script like the one below

```
#!/command/with-contenv sh

s6-log -bp \
  f 1 - \
  n20 s5000 S50000000 !"gzip -nq9" \
  +"general.(DEBUG|INFO|NOTICE|WARNING|ERROR|CRITICAL|ALERT|EMERGENCY): " /var/log/${APP_NAME}/general - \
  +"audit.(DEBUG|INFO|NOTICE|WARNING|ERROR|CRITICAL|ALERT|EMERGENCY): " /var/log/${APP_NAME}/audit
```

So first of all let me say that this seems to work as expected. But I have a couple of questions:

1. What exactly is the purpose of the dash in the logging script? For example: `s6-log -bp f 1 - n20 ...`. I am talking about the dash after `f 1`. The documentation page does have an example with using this dash but does not explain it. So I am curious to know. It seems like some sort of a reset point.
2. What is the purpose of this `=statusfile: status` ? When would this be helpful?
3. `Stotalsize: next logdirs will contain up to totalsize bytes of archived (and maybe processed) log files.` . It's not clear for me, next logdirs will contain up to totalsize bytes combined? Or separately? In my example script, I am not sure if the size of 50MB applies to both logdirs combined or to each one (there are 2 in my example) separately?

Thanks in advance for any clarifications.

**Comment by skarnet** [comment]
1. It is indeed a reset, in a way: it clears the line selection. When you say `+general.something`, it _adds_ lines that match the regex to the line selection, and then when you say `/var/log/something`, it logs the selected lines to the logdir you specified. If you don't specify `-`, your new regex will add lines to the selection, but previously selected lines will leak into your new logdir.
  + Initially, all the lines are selected, so your initial `f` is superfluous. To log everything to stdout, you can just start with `1`. Then if you want to filter by regex, you'd do `- +regex1 /var/log/logdir1 - +regex2 /var/log/logdir2 ...`
2. It's when you want to update a file with a line that reflects the current state of the service. You could then watch the file with `inotify` and read it when it changes, for instance, or publish it somewhere for other services to access. It is an old mechanism that predates readiness notification by s6 and modern services that have ways to publish their state, so nowadays `=statusfile` isn't very useful. But the functionality is cheap, so there's no reason to remove it.
3. `Stotalsize` applies to only one logdir. 50MB would be the total size limit for the `current` file and all the archive files in each logdir you specify after that. If you declared 4 logdirs, you could have up to 200MB of stored data.

**Comment by shieldz80** [comment]
Thanks @skarnet
