### ISSUE TITLE
Question: How to add a longrun with state `down`

### ISSUE THREAD

**Issue by dazz** [just-containers/s6-overlay#595]
> An optional, empty, regular file named down. If such a file exists, the default state of the service is considered down, not up: s6-supervise will not automatically start it until it receives a s6-svc -u command. If no down file exists, the default state of the service is up.
https://skarnet.org/software/s6/servicedir.html

I want a longrun only to be started if an env variable is set so with each start I can decide if the service should be started or not.

It is only mentioned in the documentation how a `down` file in the service directory is handled, but it does not state how it gets there and if the existence can be changed from a `oneshot` or somehow else.

One way we have solved it is to call `sleep 86400 && exit 0` if the env is set to disable the service, but I think there should be a better way.

I found I can `/command/s6-svc -D /run/service/svc-scheduler` then the `down` file existed, but it did not work when calling it from a `oneshot`.

Can you show a better way please and maybe point to the right part of documentation.

Cheers,
dazz

PS: The documentation for oneshots defines a `down` file as well, but it has a completely different purpose, which confused me for a while.

**Comment by skarnet** [comment]
That's the neat part, you don't.

`s6-rc` uses `s6`'s `down` file internally. When the supervision tree is created, it contains every service, but they're initially down; then the service manager brings them up in dependency order.

s6-rc wasn't made for dynamic service sets; it was made for reliability and predictability of the machine state, which runtime changes are bad for - and you're going against its design by attempting to conditionally start services.

The way to achieve what you want is by making sure that _only_ the services you want to activate are in s6-rc's `user` bundle, which contains everything that will be started. For that purpose, you have the `S6_STAGE2_HOOK` environment variable: in it, put the path to a script, and that script will be run before s6-rc analyzes its service set. That script should be the one to read your environment variables, and adjust the files of `/etc/s6-overlay/s6-rc.d/user/contents` accordingly.

**Comment by dazz** [comment]
Thank you, this is what I was looking for! :+1:
