### ISSUE TITLE
EXIT / HALT / STAGE2_FAILS are ignored in longrun services for 3.2+ versions

### ISSUE THREAD

**Issue by rundx** [just-containers/s6-overlay#599]
Starting from version 3.2.0.0 I can no longer use 'exit' or '/run/s6/basedir/bin/halt' in a longrun script to kill container on a fatal error check
the service will keep on restarting despite 'S6_BEHAVIOUR_IF_STAGE2_FAILS' being set to '2'

In version 3.1.6.2 I'm able to terminate container with 'exit 1' and 'S6_BEHAVIOUR_IF_STAGE2_FAILS=2'
now even 'exec /run/s6/basedir/bin/halt' will not kill the container

**Comment by skarnet** [comment]
Please give a precise example of what worked previously and doesn't now, with details of your services.

**Comment by rundx** [comment]
Sorry I think I figured it out the default for 'S6_CMD_WAIT_FOR_SERVICES_MAXTIME' was 3 seconds
in 3.1.x and from 3.2.x is 0, infinite

```
FROM alpine

ARG S6_OVERLAY_VERSION=3.1.6.2

ENV S6_VERBOSITY=6
ENV S6_BEHAVIOUR_IF_STAGE2_FAILS=2

RUN apk update && apk add xz bash

ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-x86_64.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-x86_64.tar.xz

RUN mkdir -p \
    /etc/s6-overlay/s6-rc.d/app/ \
    /etc/s6-overlay/s6-rc.d/user/contents.d && \
    touch /etc/s6-overlay/s6-rc.d/user/contents.d/app

RUN echo -e '#!/command/execlineb -S0\nforeground { redirfd -w 1 /run/s6-linux-init-container-results/exitcode echo "$1" }\n/run/s6/basedir/bin/halt\n' > /etc/s6-overlay/s6-rc.d/app/finish

RUN echo -e '#!/command/with-contenv bash\nset -x\nif true; then\n\texit 1\nfi\nexec tail -f /dev/null\n' > /etc/s6-overlay/s6-rc.d/app/run

RUN echo -e 'longrun' > /etc/s6-overlay/s6-rc.d/app/type
RUN echo -e '5' > /etc/s6-overlay/s6-rc.d/app/notification-fd

ENTRYPOINT ["/init"]
```

`docker build --pull --build-arg S6_OVERLAY_VERSION=3.1.6.2 -t s6-test:3.1 .`
`docker build --pull --build-arg S6_OVERLAY_VERSION=3.2.0.0 -t s6-test:3.2 .`

`docker run --rm -it s6-test:3.1`
`docker run --rm -it s6-test:3.2`

`docker run --rm -it -e S6_CMD_WAIT_FOR_SERVICES_MAXTIME=1 s6-test:3.1`
`docker run --rm -it -e S6_CMD_WAIT_FOR_SERVICES_MAXTIME=1 s6-test:3.2`

**Comment by skarnet** [comment]
Indeed 😉 Can I close this?

**Comment by rundx** [comment]
Sure, Thanks
