### ISSUE TITLE
Unable to start service with S6_CMD_WAIT_FOR_SERVICES_MAXTIME != 0

### ISSUE THREAD

**Issue by rundx** [just-containers/s6-overlay#601]
I want to exit container on error check so I'm setting 
S6_BEHAVIOUR_IF_STAGE2_FAILS=2
AND
S6_CMD_WAIT_FOR_SERVICES_MAXTIME to non zero 

but service will fail to start except with S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0 for some reason and then I can't exit the container cause it will keep on retrying to start the service

/etc/s6-overlay/s6-rc.d/svc-php/run
```
#!/usr/bin/with-contenv bash

set -x

FAIL=${FAIL:-"false"}

if [[ ${FAIL} != "false" ]]; then
    exit 1
fi

exec s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 9000" s6-setuidgid abc /usr/local/sbin/php-fpm -F
```

```
ARG PHP_VERSION=8.3
FROM php:${PHP_VERSION}-fpm-alpine

ARG S6_OVERLAY_VERSION=3.2.0.2
ENV S6_VERBOSITY=6
ENV S6_BEHAVIOUR_IF_STAGE2_FAILS=2

RUN apk add --no-cache xz bash shadow
RUN addgroup -g 984 --system abc
RUN adduser -G abc --system -D -s /bin/sh -u 984 abc
RUN usermod -a -G tty abc

ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-x86_64.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-x86_64.tar.xz
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-symlinks-noarch.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-symlinks-noarch.tar.xz
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-symlinks-arch.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-symlinks-arch.tar.xz

RUN mkdir -p \
    /etc/s6-overlay/s6-rc.d/svc-php/ \
    /etc/s6-overlay/s6-rc.d/user/contents.d && \
    touch /etc/s6-overlay/s6-rc.d/user/contents.d/svc-php

RUN echo -e '#!/command/with-contenv bash\nset -x\nif [[ ${FAIL} != "false" ]]; then\n\texit 1\nfi\nexec s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 9000" s6-setuidgid abc /usr/local/sbin/php-fpm -F\n' > /etc/s6-overlay/s6-rc.d/svc-php/run

RUN chmod +x /etc/s6-overlay/s6-rc.d/svc-php/run

RUN echo -e 'longrun' > /etc/s6-overlay/s6-rc.d/svc-php/type
RUN echo -e '3' > /etc/s6-overlay/s6-rc.d/svc-php/notification-fd

ENTRYPOINT ["/init"]
```
Service starts fine with default S6_CMD_* value
`docker run --rm -it -e S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0 -e FAIL=false s6-test:latest`

Should normally start but fails
`docker run --rm -it -e S6_CMD_WAIT_FOR_SERVICES_MAXTIME=100 -e FAIL=false s6-test:latest`

**Comment by skarnet** [comment]
You're using `s6-notifyoncheck`, which will poll every second (starting 10 ms after `php-fpm` is executed) until your `nc` succeeds. The service will not be considered ready until this test passes.

You're giving the service 100 milliseconds to succeed.

See the issue here?

Put a much larger number in `S6_CMD_WAIT_FOR_SERVICES_MAXTIME` if you want a timeout. But note that if you're using `s6-notifyoncheck`, you _already_ have a builtin timeout: here, after 300 unsuccessful `nc` attempts, i.e. 5 minutes, the service will report failure. If you use the default value for the `-n` option, the service will report failure after 7 unsuccessful attempts, i.e. 7 seconds.

**Comment by rundx** [comment]
Sorry again, I get it now I forgot about it's in milliseconds
I removed the -n option and set S6_CMD_WAIT_FOR_SERVICES_MAXTIME to 5000  so I can still fail the container if ${FAIL} is true, everything works fine now I think
thank you
