### ISSUE TITLE
How do I set my environment variables to be available to all run scripts

### ISSUE THREAD

**Issue by chenxudong2020** [just-containers/s6-overlay#605]
1.I am in /etc/s6-overlay/s6-rc.d/frp/env/a
The content ：
a="b"
In the /etc/s6-overlay/s6-rc.d/frp/run script, ${a} is output, but it is prompted that the a variable cannot be found.
2. Then change the method and enter the following content in the /etc/cont-init.d/01-env file:
#!/usr/bin/with-contenv bash
a="b"
Similarly, when running ${a} in the run script, the variable cannot be found.

**Comment by skarnet** [comment]
It is unclear what you're trying to do, but cargo culting other services and fiddling with `env/` subdirectories is certainly not going to achieve anything; the fact that a service's environment is local to the service is *on purpose*. You don't want to leak service-specific variables to another service.

If you want environment variables that are valid for *all* your services, that's what `with-contenv` is for: it imports the environment you define for your container.

If `with-contenv` isn't working for you, please describe accurately what you want.

**Comment by chenxudong2020** [comment]
> It is unclear what you're trying to do, but cargo culting other services and fiddling with `env/` subdirectories is certainly not going to achieve anything; the fact that a service's environment is local to the service is _on purpose_. You don't want to leak service-specific variables to another service.
> 
> If you want environment variables that are valid for _all_ your services, that's what `with-contenv` is for: it imports the environment you define for your container.
> 
> If `with-contenv` isn't working for you, please describe accurately what you want.

When building a docker container, I need to pass the variables defined by ARG in the Dockerfile to all running programs.

**Comment by skarnet** [comment]
It doesn't sound like your problem has anything to do with s6-overlay. Read [this page](https://vsupalov.com/docker-arg-env-variable-guide/) explaining how to pass your ARG variables as ENV variables, do that, and `with-contenv` will import them.

**Comment by chenxudong2020** [comment]
> It doesn't sound like your problem has anything to do with s6-overlay. Read [this page](https://vsupalov.com/docker-arg-env-variable-guide/) explaining how to pass your ARG variables as ENV variables, do that, and `with-contenv` will import them.

You may not understand what I mean. What I mean is that the variable is used during the docker build, but I want to pass this variable to the running script of all programs.

**Comment by skarnet** [comment]
Then write the variable somewhere in the filesystem and source the file in every run script?

```
ARG a=1
RUN echo ${a} > /etc/private-environment/a
```

and in your run scripts,

```sh
#!/bin/sh
a=`cat /etc/private-environment/a`
...
```

something like that?

The overlay provides you with programs like [envfile](https://skarnet.org/software/execline/envfile.html) or [s6-envdir](https://skarnet.org/software/s6/s6-envdir.html) if you're trying to read several environment variables at once; you can use them as you please in your run scripts if it helps you, but you don't have to. You're free to script however you want.

**Comment by chenxudong2020** [comment]
Is there a more elegant way




---Original---
From: "Laurent ***@***.***&gt;
Date: Mon, Dec 30, 2024 22:45 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [just-containers/s6-overlay] How do I set my environmentvariables to be available to all run scripts (Issue #605)




 
Then write the variable somewhere in the filesystem and source the file in every run script?
 ARG a=1 RUN echo ${a} &gt; /etc/private-environment/a  
and in your run scripts,
 #!/bin/sh a=`cat /etc/private-environment/a` ...
 
something like that?
 
The overlay provides you with programs like envfile or s6-envdir if you're trying to read several environment variables at once; you can use them as you please in your run scripts if it helps you, but you don't have to. You're free to script however you want.

**Comment by chenxudong2020** [comment]
Give me a specific example，thinks




---Original---
From: "Laurent ***@***.***&gt;
Date: Mon, Dec 30, 2024 22:45 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [just-containers/s6-overlay] How do I set my environmentvariables to be available to all run scripts (Issue #605)




 
Then write the variable somewhere in the filesystem and source the file in every run script?
 ARG a=1 RUN echo ${a} &gt; /etc/private-environment/a  
and in your run scripts,
 #!/bin/sh a=`cat /etc/private-environment/a` ...
 
something like that?
 
The overlay provides you with programs like envfile or s6-envdir if you're trying to read several environment variables at once; you can use them as you please in your run scripts if it helps you, but you don't have to. You're free to script however you want.

**Comment by chenxudong2020** [comment]
Unfortunately, I created an env file whose content is: a="1" through the command
envfile env prompt
/etc/s6-overlay/s6-rc.d/frpc # envfile env
envfile: usage: envfile [ -i | -I ] file prog...

Then I use the command:
envfile env sh
Perform successful discovery
The env command also returns successfully
But when running in the run script, it cannot output
The script is as follows
#!/command/with-contenv sh
    envfile env sh
    echo ${a}
No value of a is output

**Comment by skarnet** [comment]
This has, again, nothing to do with s6-overlay, this is just about reading documentation and understanding what you're doing instead of cargo culting.

Try:
```sh
#!/bin/sh
envfile env sh -c 'echo ${a}'
```

or

```
#!/command/execlineb -S0
envfile env
importas -S a
echo ${a}
```

Note that `a="1"` will not do what you want. You need `a=1` in the file.

Also note that you don't *have to* use envfile. For your use case, you might be better off doing:

```sh
#!/bin/sh
. env
echo "${a}"
```

Closing this.
