### ISSUE TITLE
question about logging 2 services to stdout

### ISSUE THREAD

**Issue by dreamcat4** [just-containers/s6-overlay#70]
Hi Gorka,
Sorry to be a nuicance, but i've got a question about logging 2 services to stdout. Is this possible?

I am looking at the documentation here:

https://github.com/just-containers/s6-overlay#writing-a-service-script

But there is no mention of it.

**Comment by glerchundi** [comment]
Don't worry :-)

It's not documented because it's the default behaviour, if you set `S6_LOGGING` to 0 (which is the default), everything printed to stdout will be outputted.

Make sure stderr is redirected to stdout, and no `log/run` script is eating your messages:

`execline`:
```
#!/usr/bin/execlineb -P
fdmove -c 2 1
nginx -g "daemon off;"
```

`bash`:
```
#!/bin/sh
exec 2>&1
exec nginx -g "daemon off;" 
```

**Comment by dreamcat4** [comment]
ok. Thanks Gorka! Was hoping this was the situation. Appreciate it.

**Comment by janeczku** [comment]
@glerchundi 
> It's not documented because it's the default behavior

I guess than it should be documented that `this is the default behavior`
Since it certainly hasn't been the default behavior in any multi-process docker images i have dealt with in the past.
Just saying, cause i had to search through issues in order to confirm this.
I dig the s6 overlay by the way :wink:

**Comment by glerchundi** [comment]
Although it is documented: https://github.com/just-containers/s6-overlay/blob/master/README.md#logging (default = 0) , i'm going to try to clarify a little bit more. Because if two people ask the same thing it's, of course, a documentation bug.

**Comment by shinebayar-g** [comment]
@glerchundi  thanks for the answer and sorry for the ping outta nowhere.

Is it possible to add prefix to service scripts? For example, let's say I've nginx running as `CMD` and some other process in a s6 service. For now all of the logs are looks kinda same. It would be super helpful to add prefix to logs like s6 itself like example below.

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] cron-logfolder: executing... 
[cont-init.d] cron-logfolder: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```
