### ISSUE TITLE
init causes erroneous symlinks to be created

### ISSUE THREAD

**Issue by inklesspen** [just-containers/s6-overlay#83]
I started writing an app container using v1.13.0.0. Yesterday I upgraded the container to use v1.14.0.3, which I see introduced profiles in #81. Since then, I'm experiencing an interesting problem. The first time I start a specific container, everything is fine. But on subsequent starts, each of the /etc/ directories has had a recursive symlink added to it. This appears to be added during /init on the second time the container is started. These symlinks cause the init scripts to not work properly.

You can see this in action with my [base image](https://github.com/inklesspen/s6-py3-node):

```
docker run --name=testing -it inklesspen/s6-py3-node:latest /init
# ctrl-c to stop it
docker start -ai testing
```

Of course, if I remove the container after stopping it, the next run works perfectly.

**Comment by glerchundi** [comment]
@inklesspen I've limited internet access right now, I pushed a small change that I think it should solve this issue. If it doesn't you have to wait until next week.

Tell me if #84 fixed this or not.

Thanks for reporting.

**Comment by glerchundi** [comment]
Ups :-)

**Comment by inklesspen** [comment]
Seems to be a fix! Thanks.

**Comment by glerchundi** [comment]
Closing this then.
