### ISSUE TITLE
Version strategy

### ISSUE THREAD

**Issue by smebberson** [just-containers/s6-overlay#88]
What is your version strategy. It has 4 numbers, so I wanted to clarify exactly what it is...

Thanks!

**Comment by glerchundi** [comment]
hi @smebberson, take a look to this issue in skaware: just-containers/skaware#13. We try to follow that strategy...

**Comment by glerchundi** [comment]
@smebberson can we close this?

**Comment by smebberson** [comment]
Oh yes! Thanks for your response :)
