### ISSUE TITLE
Fixing and creating directories

### ISSUE THREAD

**Issue by analogic** [just-containers/s6-overlay#90]
I have two suggestions for init system
1. overlay should be able to create directories (recursive) if dont exist when fixing perms
2. and there should be step before fixing perms 

My usecase - i have project which heavily uses caches that needs to be cleaned every start (&perms fixed) - the only way to do that is in cont-init.d, leaving native way of fixing perms behind

**Comment by glerchundi** [comment]
Can you explain a little bit more? Or give a full example in order to assess if it's worth it or not?

**Comment by analogic** [comment]
Better example: service wont run without log directory - for ex. nginx. I mount volume /var/log - for first time its completely empty and directory /var/log/nginx is missing, nginx wont run until i create it with proper rights.

1. it would be nice to have some flag in fix-attrs, which will automaticaly run mkdir -p /var/log/nginx if directory not exists
2. or/and have ability to run a script BEFORE fix-attrs which will run mkdir -p /var/log/nginx

**Comment by analogic** [comment]
I would post a patch but execlineb is not my favorite language yet :)

**Comment by glerchundi** [comment]
@analogic sorry for the delay, right now, i don't have much time to invest on the overlay. Have you thought on making them in your container before building it up?

Something like this (take a look to `/var/log/{nginx-access-logs,nginx-error-logs}`): https://github.com/just-containers/nginx-loadbalancer

WDYT?

**Comment by glerchundi** [comment]
@analogic any news on this?

**Comment by analogic** [comment]
Sorry for delay - nginx was only for example - there are other services which needs precreate directories with proper rights. I am author of https://hub.docker.com/r/analogic/poste.io/ and handling directories which are exposed to users is kind of complex task. :) I will write patch when i will have some time...

**Comment by glerchundi** [comment]
My nginx references were an example too. I pre-create folders within the rootfs before building the image itself, it's more declarative and seems cleaner, at least for me. Give it a try and tell me what you think and if this doesn't fit explain your use-case a little bit more. Image source would help of course.

**Comment by analogic** [comment]
Technicaly my image is blackbox with only datadir/logs exposed via volumes - rootfs is not problem at all.   Mainly i am solving first container run (precreating needed directories), fixing user errors (deletion some of a logs dir) or updates in datadir structure... its no big deal, but it would be nice to switch all this handling from custom script to simple fix-attrs

**Comment by glerchundi** [comment]
What about something like this (this is the way it was done in nginx-loadbalancer):

`mysql-data-image/Dockerfile:`
```
FROM busybox
VOLUME /var/lib/mysql
COPY rootfs /
CMD ["true"]
```

`mysql-data-image/rootfs/var/lib/mysql/test-file:`
```
buh from a data container
```

Then:
1. `docker build -t mysql-data-image .`
2. `docker run --name mysql-data mysql-data-image`
3. `docker run --rm --volumes-from mysql-data  quay.io/justcontainers/mariadb:v0.4.0 cat /var/lib/mysql/test-file`

Among other things this is printed to the stdout:
```
[...]
buh from a data container
cat exited 0
[...]
```

**Comment by glerchundi** [comment]
@analogic please close this whenever you can.

**Comment by analogic** [comment]
sorry, i am bit busy right now... ill do patch later
