### ISSUE TITLE
Question: The Docker Way

### ISSUE THREAD

**Issue by gzoller** [just-containers/s6-overlay#94]
The README text describes The Docker Way, where if "the thing" fails the container stops.  I'm not clear how to configure/differentiate "the thing" process(es) from stuff like cron that should clearly be restarted.  How is this done?

Thanks!

**Comment by jprjr** [comment]
By default, everything will restart automatically. What differentiates a particular service is how what you write in the `finish` script.

If you check out Issue #87, particularly [this comment](https://github.com/just-containers/s6-overlay/issues/87#issuecomment-142456561), there's an example `finish` script that will bring the whole container down.

I'll get this added to the README

**Comment by jprjr** [comment]
Hi @gzoller - I've added some details to the README, let me know if that clears everything up!

**Comment by gzoller** [comment]
Much better, thanks!  And this feature is very useful.  I plugged this overlay into Alpine Linux even tho it ships with another supervisor because I wanted this ability to differentiate those services that should be restarted vs those that should terminate the container.

**Comment by glerchundi** [comment]
@gzoller can we close this?

thanks.
