### ISSUE TITLE
consider providing gpg signed releases

### ISSUE THREAD

**Issue by robwdux** [just-containers/s6-overlay#98]
provide key for gpg verify and file with hash(es)

many thanks for making it easy to use s6 in Docker!

**Comment by glerchundi** [comment]
@robwdux thanks for pointing that out, if i can find a free slot during this month i'll do. although PR's are always welcome ;)

**Comment by jprjr** [comment]
Hi there @robwdux - I added a signing key into travis, and updated the README with information on importing our public key and verifying the downloaded file: https://github.com/just-containers/s6-overlay/blob/master/README.md#verifying-downloads

Let me know if that works, and I'll close out this issue.

**Comment by robwdux** [comment]
fantastic! confirmed working. Thank you
