### ISSUE TITLE
Why would my service script not run under /init but run fine manually?

### ISSUE THREAD

**Issue by gzoller** [just-containers/s6-overlay#99]
I have a service script (bash) that sets 2 env vars then runs a small compiled Go program.  The script is installed in /etc/services.d/portster/run.  (If curious the code for portster is here: https://github.com/gzoller/portster/blob/master/portster.go)

Steps to reproduce my problem:

1) I run the image -it and get into /bin/sh (no S6 running yet)
2) I can execute the run script manually with no problem
3) Kill that, then start /init

This will produce a failure on line 26 of my program:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xc8 pc=0x4011ed]

goroutine 1 [running]:
main.main()
	/go/src/github.com/gzoller/portster/portster.go:26 +0x1ed

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
```
Can you think of any reason why the same program, launched from the same run script would not run under /init?  My program is using a library to read the Docker API tcp port 2376.

Contents of /etc/services.d/portster/run here:
```
#!/bin/sh
export DOCKER_CERT_PATH=/mnt/certs
export DOCKER_HOST=tcp://$HOST_IP:2376
/usr/local/bin/portster
```

**Comment by glerchundi** [comment]
Probably because env's required by your docker client needs more parameters than the ones provided. First, don't avoid checking for errors here, probably it'll tell you why is this happening: `https://github.com/gzoller/portster/blob/master/portster.go#L25`. And then, try to propate every env in your container to you process with this:
```
#!/usr/bin/with-contenv sh
export DOCKER_CERT_PATH=/mnt/certs
export DOCKER_HOST=tcp://$HOST_IP:2376
/usr/local/bin/portster
```

**Comment by glerchundi** [comment]
Probably because `HOME` is not set: `https://github.com/fsouza/go-dockerclient/blob/master/external/github.com/docker/docker/pkg/homedir/homedir.go#L10-L30`

**Comment by gzoller** [comment]
Yep, the with-contenv did the trick.  Thanks!
